### PR TITLE
pack: enable kafka on windows

### PR DESCRIPTION
**Pull request by prince-chrismc**
This PR enables Kafka in/out by default for fluentbit. The research I found the original reason was the CI/CD pipeline was not about to [support it](https://github.com/fluent/fluent-bit/pull/5204#issuecomment-1086263992) but in the years since it has been greatly improved and I was able to get it to build https://github.com/prince-chrismc/fluent-bit/pull/2. I used these binaries to deploy to 75 devs across several locations.

~~I tried to join the slack channel, but I never got the invite and slack says there was a problem. Please let me know if there's more information I can provide~~ I was able to attend the community meeting and share this! ❤️ 

Related issues/pr

#8662 
#7010
#5204

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

```
 [SERVICE]
     flush           0.5
     grace           5
     log_Level       debug
     log_file        .fluentbit.log.txt
     Mem_Buf_Limit   100MB
 
     http_server     on
 
 [INPUT]
     Name tail 
     Path .buildscript.log.txt
     Path_Key file_name
     Read_from_head true
 
 # [INPUT]
 #     Name tail 
 #     Path .fluentbit.log.txt
 #     Path_Key file_name
 # #     Read_from_head   true
 
 [OUTPUT]
     Name        kafka
     Match       *
     Brokers     kafka01:9092,kafka02:9092,kafka03:9092
     Topics      build_logs
     timestamp_key nanoseconds
     rdkafka.log.connection.close false
     rdkafka.request.required.acks 1
     # rdkafka.linger.ms 2500
     rdkafka.linger.ms 500
     # rdkafka.debug broker,topic,msg
     rdkafka.message.max.bytes 2147483647
     rdkafka.batch.size 2147483647
     rdkafka.batch.num.messages 2500000
     rdkafka.queue.buffering.max.messages 250000
     rdkafka.queue.buffering.max.kbytes 2147483647
 
 [FILTER]
     Name record_modifier
     Match *
     Record build_number ${BUILD_ID}
     Record hostname ${HOSTNAME}
     Record username ${USERNAME}
     Record version_id ${VERSION_ID}
 
 [FILTER]
     Name          lua
     Match         *
     script        add_timestamp.lua
     call          add_timestamp
```

- [x] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

_I was not able to run the tests local but I did run the maintainers ones in my fork to ensure it works._

- [x] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by cosmo0920** [comment]
Duplicated https://github.com/fluent/fluent-bit/pull/8662.

**Comment by prince-chrismc** [comment]
Seems like we needed the same feature at the same time 😂 let's hope we can get more traction!

**Comment by yangliuqing5470** [comment]
great job

**Comment by prince-chrismc** [comment]
Found more related issues of others asking for this feature

https://github.com/fluent/fluent-bit/issues/7010
https://laurierhodes.info/node/156 Published by Laurie Rhodes - Sun, 04/07/2024 - 10:58

**Comment by patrick-stephens** [comment]
Do we need dependency updates for the various builds?
https://github.com/fluent/fluent-bit/tree/master/packaging/distros
https://github.com/fluent/fluent-bit/tree/master/dockerfiles

**Comment by prince-chrismc** [comment]
I am sorry Patrick but I don't understand your question. Could you try rephrasing it differently?

This is windows only, so none of the distro packages are affected. For the windows docker, the source code for Kafka is the same that's already checked into the repo.

There are no changes to any dependencies or versionnin this pr.

**Comment by patrick-stephens** [comment]
> I am sorry Patrick but I don't understand your question. Could you try rephrasing it differently?
> 
> This is windows only, so none of the distro packages are affected. For the windows docker, the source code for Kafka is the same that's already checked into the repo.
> 
> There are no changes to any dependencies or versionnin this pr.

Ah my bad, just windows - I saw the cmake change and thought it was global.

**Comment by prince-chrismc** [comment]
Phew! got scared I missed something important 🙈 Windows setting in CMake so it should not be global

**Comment by cosmo0920** [comment]
However, AppVeyor complains that missing libcrypto.lib error:
> LINK : warning LNK4044: unrecognized option '/lpthread'; ignored
LINK : fatal error LNK1104: cannot open file 'libcrypto.lib'
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
Test project C:/projects/fluent-bit-2e87g/build
      Start  1: flb-it-pipe

**Comment by prince-chrismc** [comment]
I am not sure how to move this forward, https://github.com/fluent/fluent-bit/issues/5690 it seems that you already plan to remove Appveyor. I can't help but notice you duplicated this PR and did in fact disable appveyor in https://github.com/fluent/fluent-bit/pull/8662 since it's not setup to handle windows.

It's missing OpenSSL from being installed in the pipeline https://github.com/fluent/fluent-bit/blob/a6aac459d5ec1d1d591986f4e130cc7b69ffe56f/appveyor.yml#L35 and this was addressed on GitHub Actions by adding VCPKG to handle the dependencies. This was support in the Windows Dockerfile, https://github.com/fluent/fluent-bit/blob/a6aac459d5ec1d1d591986f4e130cc7b69ffe56f/dockerfiles/Dockerfile.windows#L65. Is that what it would take? Appveyor is less accessible which makes it more difficult to work with.

As someone relying on the GitHub packages produced for Windows I would like to give my vote of confidence for making the switch.

**Comment by cosmo0920** [comment]
> It's missing OpenSSL from being installed in the pipeline

 No. AppVeyor's Windows workers are already installed OpenSSL libraries.

ref: https://www.appveyor.com/docs/windows-images-software/

> . Is that what it would take? Appveyor is less accessible which makes it more difficult to work with.

> As someone relying on the GitHub packages produced for Windows I would like to give my vote of confidence for making the switch.

We didn't tried this. Because We had already used GitHub Actions to publish Windows packages. AppVeyor is no longer needed to create them.

**Comment by cosmo0920** [comment]
Superserded by https://github.com/fluent/fluent-bit/pull/8662.

**Comment by cosmo0920** [comment]
And thanks for your vcpkg advice here. I applied your advice in #8692. Anyway thank you for your suggestions.

**Comment by prince-chrismc** [comment]
Wonderful! I apologize I was not clear but I am glad this made it into the next release.
Looking forward to upgrading more regularly! 

Thanks!

**Pull request closed without merging**
