### PR TITLE
Add  --with-jemalloc-prefix=je_ so it compiles on musl

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
Fixes errors like

| /mnt/a/oe/build/tmp/work/cortexa7t2hf-neon-vfpv4-bec-linux-musleabi/fluentbit/0.11.11-r0/build/include/jemalloc/jemalloc.h:250:28: error: exception specification in declaration does not match previous declaration
|     void JEMALLOC_NOTHROW       *je_valloc(size_t size) JEMALLOC_CXX_THROW
|                                  ^
| /mnt/a/oe/build/tmp/work/cortexa7t2hf-neon-vfpv4-bec-linux-musleabi/fluentbit/0.11.11-r0/build/include/jemalloc/jemalloc.h:80:21: note: expanded from macro 'je_valloc'
| #  define je_valloc valloc
|                     ^

**Comment by edsiper** [comment]
thanks for the PR.

we cannot add the prefix since all build-in libraries like co, jsmn, mbedtls, etc can take advantage of jemalloc, otherwise it adds more complexity since some mem will be handled by jemalloc vs others by the default memory allocator.

Closing this PR.

**Comment by kraj** [comment]
Pull has two patches you can still apply the other patch related to thread library

**Comment by edsiper** [comment]
oh thanks for catching that. 

I did a cherry-pick of that patch, it's here now:

https://github.com/fluent/fluent-bit/commit/d2dcb773395b150ddf2b7c338e1aa48c602d40f6

**Pull request closed without merging**
