### PR TITLE
engine: Add infrastructure to run input plugin in separate thread

### PR DESCRIPTION
**Pull request by tarruda**
This PR adds the necessary infrastructure to simplify creation of input plugins that run in a separate thread. The current use case will be the implementation of kafka input plugin which will use libkafka (which can't integrate with our event loop, so it must run in a separate thread).

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by tarruda** [comment]
Example of how to test the thread_dummy plugin with valgrind output:

```
$ valgrind --leak-check=full ./build/bin/fluent-bit -i thread_dummy -o stdout
==128916== Memcheck, a memory error detector
==128916== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==128916== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==128916== Command: ./build/bin/fluent-bit -i thread_dummy -o stdout
==128916==
Fluent Bit v1.9.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/01/06 23:16:27] [ info] [engine] started (pid=128916)
[2022/01/06 23:16:27] [ info] [storage] version=1.1.5, initializing...
[2022/01/06 23:16:27] [ info] [storage] in-memory
[2022/01/06 23:16:27] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/01/06 23:16:27] [ info] [cmetrics] version=0.2.2
[2022/01/06 23:16:27] [ info] [sp] stream processor started
[0] thread_dummy.0: [1641521787.150553208, {"message"=>"thread dummy"}]
[1] thread_dummy.0: [1641521788.160779428, {"message"=>"thread dummy"}]
[2] thread_dummy.0: [1641521789.161689356, {"message"=>"thread dummy"}]
[3] thread_dummy.0: [1641521790.161886693, {"message"=>"thread dummy"}]
[4] thread_dummy.0: [1641521791.162525842, {"message"=>"thread dummy"}]
^C[2022/01/06 23:16:33] [engine] caught signal (SIGINT)
[0] thread_dummy.0: [1641521792.162717717, {"message"=>"thread dummy"}]
[2022/01/06 23:16:33] [ warn] [engine] service will shutdown in max 5 seconds
[2022/01/06 23:16:33] [ info] [engine] service has stopped (0 pending tasks)
==128916==
==128916== HEAP SUMMARY:
==128916==     in use at exit: 472 bytes in 1 blocks
==128916==   total heap usage: 1,032 allocs, 1,031 frees, 1,020,270 bytes allocated
==128916==
==128916== LEAK SUMMARY:
==128916==    definitely lost: 0 bytes in 0 blocks
==128916==    indirectly lost: 0 bytes in 0 blocks
==128916==      possibly lost: 0 bytes in 0 blocks
==128916==    still reachable: 472 bytes in 1 blocks
==128916==         suppressed: 0 bytes in 0 blocks
==128916== Reachable blocks (those to which a pointer was found) are not shown.
==128916== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==128916==
==128916== For lists of detected and suppressed errors, rerun with: -s
==128916== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by tarruda** [comment]
I've finished work on the PR, it is ready for review.

**Comment by edsiper** [comment]
@nokute78 can you take a look at this one ?

**Comment by nokute78** [comment]
@tarruda  How about extending in_dummy plugin ? e.g. adding thread_mode property to in_dummy.
I think it is not user friendly to add similar plugin and it will increase maintenance cost .

**Comment by nokute78** [comment]
Just a question, `flb_output_thread` is not for plugin it is used by only engine.
Is `flb_input_thread` for plugin ? If so, should we modify each input plugins ?

**Comment by tarruda** [comment]
hi @nokute78 

> @tarruda How about extending in_dummy plugin ? e.g. adding thread_mode property to in_dummy.
I think it is not user friendly to add similar plugin and it will increase maintenance cost .

It might be possible to modify the existing `in_dummy`, but the purpose of `in_thread_dummy` is to be an example of how to use the `flb_input_thread` module added in this PR. If I simply added a configuration flag to `in_dummy`, it would not have any user-visible effect, from their perspective it makes no difference which thread a plugin code is running on.

To give a bit more context: I'm working on an `in_kafka` plugin (#4641) which requires running the kafka connect loop in a separate thread (polling kafka on the main fluent-bit thread would pause the program too much waiting for kafka messages) and this PR contains  infrastructure code to make it easy running input plugin code loop in a separate thread.

@edsiper Since `in_thread_dummy` is just an example, should I remove it and add the code on the "examples" directory?

> Just a question, flb_output_thread is not for plugin it is used by only engine.
Is flb_input_thread for plugin ? If so, should we modify each input plugins ?

No, we don't need to modify any input plugins. `flb_input_thread` is just a helper module to simplify creating an input plugin that has a separate I/O loop from fluent-bit.

**Review by edsiper — CHANGES_REQUESTED** [review]

**Pull request merged**
