### PR TITLE
Migrate Fluent Bit's C interface to Windows

### PR DESCRIPTION
**Pull request by fujimotos**
This is what we need to port Fluent Bit's C interface to Windows,
and allows users to ingest data through `in_lib`

I tested the C interface using hello_world.c. I could confirm that
it works on Windows.

```
PS> .\bin\Debug\hello_world.exe
[2019/04/05 16:22:20] [ info] [storage] initializing...
[2019/04/05 16:22:20] [ info] [storage] in-memory
[2019/04/05 16:22:20] [ info] [storage] normal synchronization mode, checksum disabled
[2019/04/05 16:22:20] [ info] [engine] started (pid=11032)
[2019/04/05 16:22:20] [ info] [input] pausing lib.0
[0] test: [1554448940.526829004, {"key"=>"val 0"}]
[1] test: [1554448940.526985883, {"key"=>"val 1"}]
[2] test: [1554448940.527056932, {"key"=>"val 2"}]
[3] test: [1554448940.527115106, {"key"=>"val 3"}]
...
[99] test: [1554448940.533000946, {"key"=>"val 99"}]
[2019/04/05 16:22:20] [ warn] [engine] service will stop in 5 seconds
[2019/04/05 16:22:25] [ info] [engine] service stopped
```

As to C++, we need a bit more work to make it usable on Windows.
So I'm planning to work on the C++ support in a subsequent PR.

### CODE REVIEW

**Comment by fujimotos** [comment]
An internal error occurred within Travis CI. 

> W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/xenial/InRelease Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
>
> https://travis-ci.org/fluent/fluent-bit/jobs/516063712

Otherwise tests seem just fine, so rerun Travis CI by pushing the master HEAD again.

**Comment by edsiper** [comment]
ready to merge once https://github.com/fluent/fluent-bit/pull/1251#pullrequestreview-223183783 is added

**Comment by fujimotos** [comment]
@edsiper Reading the manual of WSACleanup(), it seems to me that
we actually do not want to call it.


The major issue is that WSACleanup halts the entire WinSock stack
and kills all the connections for all threads. This includes
connections that users created outside of Fluent Bit.

For an embedding interface, it seems a too dangerous thing to do.

Here is a related comment in librdkafka. It seems librdkafka also
avoid calling it.

https://github.com/fluent/fluent-bit/blob/6125571d47fb00c3ac3ae7c7bdb3319a35cd4ab4/plugins/out_kafka/librdkafka-0.11.6/src/rdkafka_transport.c#L1664

**Comment by fujimotos** [comment]
@edsiper Reading the manual of WSACleanup(), it seems to me that
we actually do not want to call it.

The major issue is that WSACleanup halts the entire WinSock stack
and kills all the connections for all threads. This includes
connections that users created outside of Fluent Bit.

For an embedding interface, it seems a too dangerous thing to do.

Here is a related comment in librdkafka. It seems librdkafka also
avoid calling it.

https://github.com/fluent/fluent-bit/blob/6125571d47fb00c3ac3ae7c7bdb3319a35cd4ab4/plugins/out_kafka/librdkafka-0.11.6/src/rdkafka_transport.c#L1664-L1675

**Comment by edsiper** [comment]
oh, thanks for the clarification, that's super dangerous XD

**Comment by edsiper** [comment]
in order to merge please rename:

hello_world: remove unistd.h for Windows compatibility

to

examples: hello_world: remove unistd.h for Windows compatibility

**Comment by fujimotos** [comment]
@edsiper  Thank you. Just fixed it.

**Comment by edsiper** [comment]
thanks

**Pull request merged**
