### PR TITLE
in_tail: don't pause scan/rotate

### PR DESCRIPTION
**Pull request by jsravn**
Otherwise new files may never get ingested if heavy log volume is
causing frequent pauses.

This should be safe since no ingestion happens during scan and rotate.

Fix https://github.com/fluent/fluent-bit/issues/465

### CODE REVIEW

**Comment by edsiper** [comment]
thinking: what would be the default behavior when:

- output destination is down
- fluent bit cannot flush logs
- input have mem_buf_limit enabled (so cannot consume more logs)
- scan new files, but cannot consume them (because is paused)
- scanned file  (not consumed) is rotated

**Comment by edsiper** [comment]
@jsravn ping

**Comment by jsravn** [comment]
@edsiper Okay I see your point I think. If it rotates during paused ingestion, we could lose some logs (depending on rotate_wait setting). We could address that by pausing the rotation purge callback, or simply pausing rotation as well (with the risk that rotation could be heavily delayed). The main issue is with scanning.

I don't see any problem with scanning for new files while paused - which fixes the main issue.

**Comment by jsravn** [comment]
Actually if we don't detect rotations, won't that mess up when it scans for new files? I think we need to do both. Or we need a better way of not starving rotation/file detection.

@edsiper thoughts?

**Comment by edsiper** [comment]
hmmm, yeah.. so if it's paused I think would be safer to keep scanning files and rotated files, but on both cases log a message "new file scanned but plugin is paused, no data ingestion", same for when a file is rotated. So we advice the user about the situation since he is in charge to solve the problem from a configuration perspective.

what do you think ?

**Comment by jsravn** [comment]
>  "new file scanned but plugin is paused, no data ingestion"

After a flush, it will start ingesting the new file up to the buffer limit, even if it gets paused. So I think this message is misleading. Maybe a message on rotation while paused, in case we purge a file before consuming all of it?

**Comment by jsravn** [comment]
@edsiper I added a warning for the rotation case.

**Comment by edsiper** [comment]
thanks @jsravn !

**Pull request merged**
