### PR TITLE
Dockerfile: use the binary as the entrypoint so we can pass arguments to docker run.

### PR DESCRIPTION
**Pull request by pwhelan**
This is a relatively small change but a huge QoL gain. With this small change it makes several things extremely easy and intuitive:

- run the docker container to see the help
- pass in a volume with a configuration and parse it
- run ephemeral instances quickly to just push metrics from one place to another.

In essence this just removes the requirement to pass the full binary name to docker run if you want to run it with different arguments, ie you could quickly invoke fluent-bit to just log what events docker is generating:

```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock fluent/fluent-bit:master -i docker_events -o stdout -f 1
Fluent Bit v1.9.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/10/22 18:27:35] [ info] [engine] started (pid=1)
[2021/10/22 18:27:35] [ info] [storage] version=1.1.4, initializing...
[2021/10/22 18:27:35] [ info] [storage] in-memory
[2021/10/22 18:27:35] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/10/22 18:27:35] [ info] [cmetrics] version=0.2.2
[2021/10/22 18:27:35] [ info] [input:docker_events:docker_events.0] listening for events on /var/run/docker.sock
[2021/10/22 18:27:35] [ info] [sp] stream processor started
[0] docker_events.0: [1634927255.260770919, {"message"=>"{"status":"start","id":"aedd25fbdcb015e1a2ad322fcadb119fbff0a19c793b1fdbfd83856557c3e589","from":"pwhelan/fluent-bit:master","Type":"container","Action":"start","Actor":{"ID":"aedd25fbdcb015e1a2ad322fcadb119fbff0a19c793b1fdbfd83856557c3e589","Attributes":{"Description":"Fluent Bit docker image","Vendor":"Fluent Organization","Version":"1.1","image":"pwhelan/fluent-bit:master","name":"bold_johnson"}},"scope":"local","time":1634927255,"timeNano":1634927255260648616}
"}]
^C[2021/10/22 18:27:42] [engine] caught signal (SIGINT)
[2021/10/22 18:27:42] [ warn] [engine] service will stop in 5 seconds
[2021/10/22 18:27:46] [ info] [engine] service stopped
```

### CODE REVIEW

**Comment by pwhelan** [comment]
> If people are using it as a base image then they may have their own entrypoint to manage Fluent Bit that just assumes it can then run the CMD parameters including Fluent Bit

With this change the situation should be the same, as far as I can tell.

> as per my Couchbase image just override CMD without doing ENTRYPOINT so the image launches the wrong thing.

This case would most likely break, especially if it overrides CMD to execute something besides fluent-bit. I could argue that that is a very weird use case for a docker container and is actually frowned upon in best practices since you would probably be doing this to add another service or process to the base image.

**Comment by patrick-stephens** [comment]
> > If people are using it as a base image then they may have their own entrypoint to manage Fluent Bit that just assumes it can then run the CMD parameters including Fluent Bit
> 
> With this change the situation should be the same, as far as I can tell.
> 
> > as per my Couchbase image just override CMD without doing ENTRYPOINT so the image launches the wrong thing.
> 
> This case would most likely break, especially if it overrides CMD to execute something besides fluent-bit. I could argue that that is a very weird use case for a docker container and is actually frowned upon in best practices since you would probably be doing this to add another service or process to the base image.

Agreed, I think the improvements on usability are well worth any niggles people might have with any current tooling. I just suspect that there will be some so best to make sure we highlight it just in case.

**Review by patrick-stephens — APPROVED** [review]

**Comment by patrick-stephens** [comment]
@niedbalski I've included these changes in the new multi-arch containers already so be good to get merged for 1.9.

@pwhelan the recommendation is still to include the binary in the `CMD` (it'll be ignored anyway): https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#cmd
`CMD should rarely be used in the manner of CMD ["param", "param"] in conjunction with ENTRYPOINT, unless you and your expected users are already quite familiar with how ENTRYPOINT works.` I would suggest we keep that in.

**Comment by pwhelan** [comment]
This PR has now effectively become redundant because of the updates to the multiarch Dockerfile.

**Pull request closed without merging**
