### PR TITLE
Add filter_geoip2

### PR DESCRIPTION
**Pull request by okkez**
This is a feature request from [an issue](https://github.com/fluent-plugins-nursery/geoip2_c/issues/12).

This is inspired by [fluent-plugin-geoip](https://github.com/y-ken/fluent-plugin-geoip)'s geoip2_c backend. But this plugin implements very simple features from fluent-plugin-geoip.

Sample configuration is here:

```
[FILTER]
  Name geoip2
  Match *
  Database GeoLite2-City.mmdb
  Lookup_key remote_addr
  Record city remote_addr %{city.names.en}
  Record country remote_addr %{country.names.en}
```

Not implemented features:
* configuration
  * multiple values in a string
    `Record location_string remote_addr %{location.latitude},%{location.longitude}`
  * array
  * map
  * nested lookup key
* decode some types (TODO comments in source code)
  * these types are not used in general cases because [geoip2_c](https://github.com/fluent-plugins-nursery/geoip2_c) does not have such features

### CODE REVIEW

**Comment by nigels-com** [comment]
It's a lot of files, are they all necessary?

It would be nice to have the 3rd party stuff as an earlier commit and/or pull request, to ease review.

**Comment by mhf-ir** [comment]
Any update on this useful PR ?

**Comment by edsiper** [comment]
@okkez please resubmit on top of git master, the current PR has modified more than 200 files

**Comment by okkez** [comment]
I've rebased and force-pushed.

**Comment by edsiper** [comment]
@okkez one more change. Since this is the only plugin that will use ibmaxmind, I suggest to movie this dependency "inside" the filter directory, pretty much like we did with out_kafka plugin where we put librdkafka inside it.

**Comment by okkez** [comment]
@edsiper I've done about your comment.

**Comment by edsiper** [comment]
the build fails with:

```
/home/edsiper/coding/fluent-bit/plugins/filter_geoip2/libmaxminddb-1.3.2/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make[3]: *** [Makefile:404: aclocal.m4] Error 127
make[2]: *** [plugins/filter_geoip2/CMakeFiles/maxminddb.dir/build.make:112: plugins/filter_geoip2/maxminddb-prefix/src/maxminddb-stamp/maxminddb-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:5440: plugins/filter_geoip2/CMakeFiles/maxminddb.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

is it possible to add a CMakeLists.txt file that only builds the required libmaxmind source files ?

here are some insights about that:

https://github.com/maxmind/libmaxminddb/issues/182

**Comment by okkez** [comment]
> is it possible to add a CMakeLists.txt file that only builds the required libmaxmind source files ?

I'll try it when I have enough time.

**Comment by newtoncorp** [comment]
I may be doing something wrong, but with the following patch and a rebase it compiles.
see https://github.com/newtoncorp/fluent-bit/tree/geoip

```
diff --git a/plugins/filter_geoip2/CMakeLists.txt b/plugins/filter_geoip2/CMakeLists.txt
index e46680d..8e559ee 100644
--- a/plugins/filter_geoip2/CMakeLists.txt
+++ b/plugins/filter_geoip2/CMakeLists.txt
@@ -3,8 +3,15 @@ include(libmaxminddb.cmake)

 # libmaxminddb headers
 include_directories(${LIBMAXMINDDB_DEST}/include/)
+set(maxmindversion 1.3.2)
+
+add_compile_options(-DPACKAGE_VERSION="${maxmindversion}")
+
+include_directories(libmaxminddb-${maxmindversion}/ libmaxminddb-${maxmindversion}/src libmaxminddb-${maxmindversion}/include)

 set(src
+  libmaxminddb-${maxmindversion}/src/maxminddb.c
+  libmaxminddb-${maxmindversion}/src/data-pool.c
   geoip2.c)

-FLB_PLUGIN(filter_geoip2 "${src}" "libmaxminddb")
+FLB_PLUGIN(filter_geoip2 "${src}" "")
diff --git a/plugins/filter_geoip2/libmaxminddb.cmake b/plugins/filter_geoip2/libmaxminddb.cmake
deleted file mode 100644
index 57318ec..0000000
--- a/plugins/filter_geoip2/libmaxminddb.cmake
+++ /dev/null
@@ -1,32 +0,0 @@
-# This file provides 'libmaxminddb' target for both UNIX and Windows.
-#
-# To enalbe libmaxminddb, include this file:
-#
-#    include(libmaxminddb.cmake)
-
-include(ExternalProject)
-add_library(libmaxminddb STATIC IMPORTED GLOBAL)
-
-# Global Settings
-set(LIBMAXMINDDB_SRC ${CMAKE_CURRENT_SOURCE_DIR}/libmaxminddb-1.3.2)
-set(LIBMAXMINDDB_DEST ${CMAKE_CURRENT_BINARY_DIR}/libmaxminddb-1.3.2)
-
-# libmaxminddb (UNIX)
-ExternalProject_Add(maxminddb
-  BUILD_IN_SOURCE TRUE
-  EXCLUDE_FROM_ALL TRUE
-  SOURCE_DIR ${LIBMAXMINDDB_SRC}
-  INSTALL_DIR ${LIBMAXMINDDB_DEST}
-  CONFIGURE_COMMAND ${LIBMAXMINDDB_SRC}/configure --disable-shared --prefix=${LIBMAXMINDDB_DEST}
-  BUILD_COMMAND $(MAKE)
-  INSTALL_COMMAND $(MAKE) install)
-
-if(MSVC)
-  add_dependencies(libmaxminddb maxminddb)
-  set(LIBMAXMINDDB_STATIC_LIB "${LIBMAXMINDDB_DEST}/lib/libmaxminddb.lib")
-else()
-  add_dependencies(libmaxminddb maxminddb)
-  set(LIBMAXMINDDB_STATIC_LIB "${LIBMAXMINDDB_DEST}/lib/libmaxminddb.a")
-endif()
-
-set_target_properties(libmaxminddb PROPERTIES IMPORTED_LOCATION "${LIBMAXMINDDB_STATIC_LIB}")
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index dea1b8e..8229a82 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -165,13 +165,6 @@ if(FLB_LUAJIT)
     "libluajit")
 endif()

-if(FLB_MAXMINDDB)
-  set(extra_libs
-    ${extra_libs}
-    "libmaxminddb"
-    )
-endif()
-
 if(FLB_SQLDB)
   set(src
     ${src}
```

**Comment by edsiper** [comment]
pls resolve conflicts

**Comment by edsiper** [comment]
assigned to @fujimotos

**Comment by fujimotos** [comment]
This PR has been merged into the mainline via #2888.

`filter_geoip2` will be included in the next v1.7.0 release.

**Pull request closed without merging**
