### PR TITLE
CODEOWNERS: Google owners for out_stackdriver test

### PR DESCRIPTION
**Pull request by braydonk**
In the previous PR I forgot to add Google owners to the `out_stackdriver` tests as well. I also accidentally put the row in the AWS section before so I've fixed that here.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by patrick-stephens** [comment]
We need to make sure everyone listed has write access to this repo as well, probably by adding them to the Fluent Bit Maintainers team.

**Comment by edsiper** [comment]
@patrick-stephens as codeowners I assume they can merge their own PRs, is that a correct statement ?

**Comment by patrick-stephens** [comment]
Codeowners does not affect actual access control in this repo, you have to set them up with that. It is just part of CI to automate the allocation of reviews.

**Comment by braydonk** [comment]
Thanks @patrick-stephens! I'll let Igor know as well

**Pull request merged**
