### PR TITLE
 out_opentelemetry: enhancements for log body and attributes handling (fix #8359)     

### LINKED ISSUE #8359: Fluentbit OpenTelemetry Output Pipeline/Plugin doesnt format fields properly
**Issue:**
When using the OpenTelemetry Output Pipeline/Plugin to send logs to an opentelemetry endpoint, the output json/payload/fields are not formatted correctly. They should be formatted according to the opentelemetry specifications.  As a result, opentelemetry is unable to process the request, from fluentbit, correctly.

**Fluentbit Logs showing logs being sent to opentelemtry endpoint:**

[36] ebiz: [[1704434606.150000000, {}], {"message"=>"This is a test log message for abc application", "loglevel"=>"INFO", "service"=>"helloworld", "clientIp"=>"111.222.888", "timestamp"=>"2024-01-08 18:37:08.150", "testtag"=>"fluentbit", "trace_id"=>"7ada6c95a1bd243fa9013cab515173a9", "span_id"=>"9c1544cc4f7ff369"}]
[2024/01/08 18:37:10] [debug] [upstream] proxy returned 200
[2024/01/08 18:37:10] [debug] [http_client] flb_http_client_proxy_connect connection #32 connected to myproxy.com:8080.
[2024/01/08 18:37:10] [debug] [upstream] proxy returned 200
[2024/01/08 18:37:10] [debug] [http_client] flb_http_client_proxy_connect connection #31 connected to myproxy.com:8080.
[2024/01/08 18:37:10] [debug] [upstream] KA connection #32 to myproxy.com:8080 is connected
[2024/01/08 18:37:10] [debug] [http_client] not using http_proxy for header
[2024/01/08 18:37:10] [debug] [upstream] KA connection #31 to myproxy.com:8080 is connected
[2024/01/08 18:37:10] [debug] [http_client] not using http_proxy for header
[2024/01/08 18:37:10] [ info] [output:opentelemetry:opentelemetry.1] ingest.privateotel.com:443, HTTP status=200

My fluentbit configuration:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit
  namespace: otel
data:
 apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit
  namespace: otel
data:
  custom_parsers.conf: |
        
    [MULTILINE_PARSER]
        Name          multiline-rules
        Type          regex
        Flush_timeout 2000
        rule      "start_state"   "/(\d{4}-\d{1,2}-\d{1,2})(.*)/"  "cont"
        rule      "cont"          "/^\D(.*)/"                     "cont"

    [PARSER]
        Name named-captures
        Format regex
        Regex /(?<timestamp>[^ ]* .*):(?<loglevel>DEBUG|ERROR|INFO)([\s\s]*)-\|(?<id>[\w\-]*)\|(?<clientIp>[0-9\.]*)\|(?<trace_id>[0-9A-Za-z]*)\|(?<span_id>[0-9A-Za-z]*)\|(?<message>.*)/m
        Time_key timestamp
        Time_Format %Y-%m-%d %H:%M:%S.%L
        Time_Offset -0600
        Time_Keep On

  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level debug
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Log_Level error
        multiline.parser multiline-rules
        Path /app/logs/*.log
        Tag logs

    [FILTER]
        Name             parser
        Match            *
        key_name         log
        parser           named-captures

    [FILTER]
        Name             modify
        Match            *
        Add service ${SERVICE_NAME}
        
    [FILTER]
        Name             modify
        Match            *
        Add testtag fluentbit

    [OUTPUT]
        Name stdout
        Log_Level trace
        Match *

    [OUTPUT]
        Name opentelemetry
        Match *
        Log_Level trace
        Host ingest.privateotel.com
        Port 443
        Header token ***************
        Log_response_payload True
        Tls                  On
        Tls.verify           Off
        add_label            app local

  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level debug
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Log_Level error
        multiline.parser multiline-rules
        Path /app/logs/*.log
        Tag logs

    [FILTER]
        Name             parser
        Match            *
        key_name         log
        parser           named-captures

    [FILTER]
        Name             modify
        Match            *
        Add service ${SERVICE_NAME}
        
    [FILTER]
        Name             modify
        Match            *
        Add testtag fluentbit

    [OUTPUT]
        Name stdout
        Log_Level trace
        Match *

    [OUTPUT]
        Name opentelemetry
        Match *
        Log_Level trace
        Host ingest.privateotel.com
        Port 443
        Header token ***************
        Log_response_payload True
        Tls                  On
        Tls.verify           Off
        add_label            app local

```

My opentelemetry endpoint receives the request formatted as such:

```

 {
    "body": {
      "clientIp": "111.222.888",
      "loglevel": "INFO",
      "message": "This is a test log message for abc application",
      "service": "helloworld",
      "span_id": "9c1544cc4f7ff369",
      "testtag": "fluentbit",
      "timestamp": "2024-01-08 18:37:08.150",
      "trace_id": "7ada6c95a1bd243fa9013cab515173a9"
    },
    "instrumentation.name": "",
    "instrumentation.version": "",
    "observed_timestamp": 0,
    "severity_text": "",
    "span_id": "",
    "trace_id": ""
  }
```

As you can see above every named pair gets nested under the body.  The body should simply contain the log message and all the other fields I choose to send should be nested under "fields". The proper format would looks something like what i have below.

**Expected behavior:**
```
 {
    "body": {
      "message": "This is a test log message for abc application",
    },
    "clientIp": "111.222.888",
    "loglevel": "INFO",
    "service": "helloworld",
    "instrumentation.name": "",
    "instrumentation.version": "",
    "observed_timestamp": 0,
    "testtag": "fluentbit",
    "severity_text": "",
    "span_id": "9c1544cc4f7ff369",
    "timestamp": "2024-01-08 18:37:08.150",
    "trace_id": "7ada6c95a1bd243fa9013cab515173a9"
  }
```

**To Reproduce**
Use a configuration similiar to mine. Generate a log line, extract some fields from that log line including traceid, spanid, timestamp, body, etc.  Then use the opentelemetry output and point it to a opentelemetry endpoint.  

**Your Environment**
I am running in a Kubernetes cluster using a daemonset and the configmap above.
The version on fluentbit I am using is 2.1.10. 
The image is fluent/fluent-bit:2.1.10-debug

**Additional context**
Opentelemetry is unable to correctly process all the fields such as traceid and span id since they are not in the proper format schema
For more information on the opentelemetry logging data model and schema, please see below:

[Otel logs data model docs](https://opentelemetry.io/docs/specs/otel/logs/data-model/)

[Otel logs data model github](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md)

[Additional resource](https://opentelemetry.io/docs/specs/otel/compatibility/logging_trace_context/)

Please fix the issue or if there is something I am doing incorrectly in my fluentbit config then please advise. Thank you.

### PR DESCRIPTION
**Pull request by edsiper**
The following patch fix and enhance the OpenTelemetry output connector when handling log records.
    
In Fluent Bit world, we deal with ton of unstructured log records which comes from variety of sources, or just simply raw text files. When converting those lines to structured messages, there was no option to define what will be the log body and log attributes and everything is packaged inside log body by default.
    
This patch enhances the previous behavior by allowing the following:
    
- log body: optionally define multiple record accessor patterns that tries to match a key or sub-key from the record structure. For the first matched key, it's value is used as part of the body content. If no matches exists, the whole record is set inside the body.
    
- log attributes: if the log record contains native metadata, the keys are added as OpenTelemetry Attributes.  if the log body was populated by using a record accessor pattern as described above, the remaining keys that were not used can be optionally added as attributes as well if the new option `logs_body_key_attributes` is set to `true` (default: false).
    
To achieve the desired new behavior, the configuration needs to use the new configuration property called `logs_body_key`, which can be used to define multiple record accessor patterns. e.g:

```yaml
pipeline:
  inputs:
    - name: dummy
      metadata: '{"meta": "data"}'
      dummy: '{"name": "bill", "lastname": "gates", "log": {"abc": {"def":123}, "saveme": true}}'
    
  outputs:
    - name: opentelemetry
      match: '*'
      host: localhost
      port: 4318
      logs_body_key: $name
      logs_body_key: $log['abc']['def']
      logs_body_key_attributes: true
```
    
In the example above, the dummy input plugin will generate a record with metadata, in the output side, the plugin will lookup in order for `$name` and then `$log['abc']['def']`. `$name` will match, so `bill` will become the value of the body and the remaining content as attributes. Here is the output of the vanilla Otel Collector when inspecting the content it receives:
    
```
  Body: Str(bill)
  Attributes:
       -> meta: Str(data)
       -> lastname: Str(gates)
       -> log: Map({"abc":{"def":123},"saveme":true})
```

__updates__

- [02/18/2024] adjusted the description to include the new option `logs_body_key_attributes`.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by nokute78** [comment]
In my understanding, first `logs_body_key` is for log body and second `logs_body_key` is for log attributes, right ?
Why are they not separate names ?

**Comment by edsiper** [comment]
@nokute78 logs_body_key allows to define a list of candidate keys to populate the body, everything else that was not included in the body gets added as attribute. There is more context about this behavior on #8359

**Comment by nokute78** [comment]
@edsiper Thank you.

> everything else that was not included in the body gets added as attribute.

I think it may affect user request https://github.com/fluent/fluent-bit/issues/8205.
It is to forward OTLP using fluent-bit.
```
Expected behavior
The data I passed in with OTLP should, at minimum, be the same when it comes out if there is no processing done.
```

Once `log_body_key` is set, `Attributes` also will be changed.
I think it is better not to touch `Attributes` since other metadata may follow Logs Data structure.
https://github.com/fluent/fluent-bit/issues/8359#issuecomment-1933138383

**Comment by nokute78** [comment]
I tested following configuration and it enrich Attributes field.
User may not want to change.

Following `Metadata` of in_dummy is a pseudo OTEL Logs Data structure.
```
[INPUT]
    name dummy
    Metadata {"ObservedTimestamp":1234, "Timestamp":3456, "SeverityText":"WARN", "SeverityNumber":5, "TraceFlags":13, "Attributes":{"log.file.name":"a.log", "test":"val"}}
    dummy {"name": "bill", "lastname": "gates", "log": {"abc": {"def":123}, "saveme": true}}

[OUTPUT]
    Name   stdout
    Match *

[OUTPUT]
    Name opentelemetry
    Host localhost
    Port 6969
    Match *
    logs_body_key $name
```

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:6969

exporters:
  file:
    path: 2_out.json

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [file]
```

Output of otel-collector
```json
{
  "resourceLogs": [
    {
      "resource": {},
      "scopeLogs": [
        {
          "scope": {},
          "logRecords": [
            {
              "timeUnixNano": "1708134916475903956",
              "body": {
                "stringValue": "bill"
              },
              "attributes": [
                {
                  "key": "ObservedTimestamp",
                  "value": {
                    "intValue": "1234"
                  }
                },
                {
                  "key": "Timestamp",
                  "value": {
                    "intValue": "3456"
                  }
                },
                {
                  "key": "SeverityText",
                  "value": {
                    "stringValue": "WARN"
                  }
                },
                {
                  "key": "SeverityNumber",
                  "value": {
                    "intValue": "5"
                  }
                },
                {
                  "key": "TraceFlags",
                  "value": {
                    "intValue": "13"
                  }
                },
                {
                  "key": "Attributes",
                  "value": {
                    "kvlistValue": {
                      "values": [
                        {
                          "key": "log.file.name",
                          "value": {
                            "stringValue": "a.log"
                          }
                        },
                        {
                          "key": "test",
                          "value": {
                            "stringValue": "val"
                          }
                        }
                      ]
                    }
                  }
                },
                {
                  "key": "lastname",
                  "value": {
                    "stringValue": "gates"
                  }
                },
                {
                  "key": "log",
                  "value": {
                    "kvlistValue": {
                      "values": [
                        {
                          "key": "abc",
                          "value": {
                            "kvlistValue": {
                              "values": [
                                {
                                  "key": "def",
                                  "value": {
                                    "intValue": "123"
                                  }
                                }
                              ]
                            }
                          }
                        },
                        {
                          "key": "saveme",
                          "value": {
                            "boolValue": true
                          }
                        }
                      ]
                    }
                  }
                }
              ],
              "traceId": "",
              "spanId": ""
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by sudomateo** [comment]
Thank you for working on this. I was able to compile this branch locally and test it. Here are my results.

I started OpenTelemetry and Fluent Bit with the following respective configurations.

<details>

<summary>otel-config.yaml</summary>

```yaml
---
receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  file:
    path: otel-output.json

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - file
```

</details>

<details>

<summary>fluent-bit-config.yaml</summary>

```yaml
---
pipeline:
  inputs:
    - name: dummy
      tag: dummy
      metadata: |
        {
          "resource-attr": "resource-attr-val-1"
        }
      # This log record is taken directly from OpenTelemetry's Examples page.
      # https://opentelemetry.io/docs/specs/otel/protocol/file-exporter/#examples
      dummy: |
        {
          "severityNumber": 9,
          "severityText": "Info",
          "name": "logA",
          "message": "This is a log message",
          "app": "server",
          "instance_num": 1,
          "traceId": "08040201000000000000000000000000",
          "spanId": "0102040800000000"
        }

  outputs:
    - name: opentelemetry
      match: "*"
      host: localhost
      port: 4318
      logs_body_key: $message

    # For live debugging on the Fluent Bit side.
    - name: stdout
      match: "*"
      format: json
```

</details>

Here's what I received in OpenTelemetry. This is a _much better_ experience than previous. However, it's still not exactly what I would expect when shipping logs to an OpenTelemetry endpoint.

<details>

<summary>actual-logs.json</summary>

```json
{
  "resourceLogs": [
    {
      "resource": {},
      "scopeLogs": [
        {
          "scope": {},
          "logRecords": [
            {
              "timeUnixNano": "1708201530553920000",
              "body": {
                "stringValue": "This is a log message"
              },
              "attributes": [
                {
                  "key": "resource-attr",
                  "value": {
                    "stringValue": "resource-attr-val-1"
                  }
                },
                {
                  "key": "severityNumber",
                  "value": {
                    "intValue": "9"
                  }
                },
                {
                  "key": "severityText",
                  "value": {
                    "stringValue": "Info"
                  }
                },
                {
                  "key": "name",
                  "value": {
                    "stringValue": "logA"
                  }
                },
                {
                  "key": "app",
                  "value": {
                    "stringValue": "server"
                  }
                },
                {
                  "key": "instance_num",
                  "value": {
                    "intValue": "1"
                  }
                },
                {
                  "key": "traceId",
                  "value": {
                    "stringValue": "08040201000000000000000000000000"
                  }
                },
                {
                  "key": "spanId",
                  "value": {
                    "stringValue": "0102040800000000"
                  }
                }
              ],
              "traceId": "",
              "spanId": ""
            }
          ]
        }
      ]
    }
  ]
}
```

</details>

Instead, I would have expected to receive the following where the `metadata` from Fluent Bit maps to the [Resource](https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-resource) field in OpenTelemetry instead of being bundled with the rest of the attributes under the [Attributes](https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-attributes) field. Also, I would expect to have some mechanism to set the other top-level OpenTelemetry fields (i.e., TraceId, SpanId, SeverityNumber, etc.).

<details>

<summary>expected-logs.json</summary>

```json
{
  "resourceLogs": [
    {
      "resource": {
        "attributes": [
          {
            "key": "resource-attr",
            "value": {
              "stringValue": "resource-attr-val-1"
            }
          }
        ]
      },
      "scopeLogs": [
        {
          "scope": {},
          "logRecords": [
            {
              "timeUnixNano": "1708201530553920000",
              "severityNumber": 9,
              "severityText": "Info",
              "name": "logA",
              "body": {
                "stringValue": "This is a log message"
              },
              "attributes": [
                {
                  "key": "app",
                  "value": {
                    "stringValue": "server"
                  }
                },
                {
                  "key": "instance_num",
                  "value": {
                    "intValue": "1"
                  }
                }
              ],
              "traceId": "08040201000000000000000000000000",
              "spanId": "0102040800000000"
            },
          ]
        }
      ]
    }
  ]
}
```

</details>

I believe we need to answer the following questions before the Fluent Bit `opentelemetry` output will be ready for mass adoption with the greatest compatibility.
- How does Fluent Bit's event metadata relate to OpenTelemetry's [Logs Data Model](https://opentelemetry.io/docs/specs/otel/logs/data-model)?
- How does a Fluent Bit operator populate top-level fields (i.e., TraceId, SpanId, SeverityNumber, etc.) in OpenTelemetry's Logs Data Model? This pull request is focused on solving populating the `Body` and `Attributes` fields, but what about the rest?

**Comment by edsiper** [comment]
@sudomateo thanks for the feedback.

Regarding other Log model fields that are not mapped yet, @nokute78 is working on #8475 to support those dynamically. The concept is as follows, let's use `SeverityNumber` as an example:

- plugin exposes a configuration option called `logs_severity_number_key` that defaults to `$SeverityNumber` (it starts with `$` because it is a record accessor pattern) and tries to find the key inside the record, then it populates the value in the right place. 

Through $8475 the expectation is to do that for all the missing keys that are part of the Log data model. 

Regarding the questions:

__1.__  How does Fluent Bit's event metadata relate to OpenTelemetry's [Logs Data Model](https://opentelemetry.io/docs/specs/otel/logs/data-model)?

Fluent Bit is schema-less, meaning that it can adapt to any type of schema; we provide configurations like the one we are working on to solve specific use cases. In Logging, we have to deal with tons of data that are structured but don't follow a schema, while OTel does it. We just need to finish up these mapping details.

__2.__ How does a Fluent Bit operator populate top-level fields (i.e., TraceId, SpanId, SeverityNumber, etc.) in OpenTelemetry's Logs Data Model? This pull request is focused on solving populating the Body and Attributes fields, but what about the rest?

This PR #8491, only focuses on fixing how to populate body and attributes when the data that comes is not from OTel instrumentation. About the rest will be implemented in #8475; note we have other PRs around to solve OTel in the input side, here we are focusing in the output. 

For this PR, I will do some tweaks to make it optional to set all remaining keys that were not used in the body as part of the attributes, or allow to define specific attributes from the record.

Again, thanks for the feedback on this, to get it right we need this type of testing and interaction :)

**Comment by edsiper** [comment]
@nokute78 I have added a new option called `logs_body_key_attributes` (bool / default: false) which adds the unmatched keys as attributes, so we can keep it clean, thanks for the feedback

**Comment by edsiper** [comment]
To move forward OTel fixes ASAP, I am merging this PR and we will continue iterating in the others to fill the end-user gaps.

**Comment by sudomateo** [comment]
Thank you for working on this @edsiper! I agree with your assessment to merge this and continue iterating in the other pull requests.

**Comment by cb645j** [comment]
@edsiper This is good but still does not address the main concerns of my ticket (https://github.com/fluent/fluent-bit/issues/8359#issuecomment-1965123981).  The traceid and spanid are still not being set.  It seems your saying the rest will be fixed as part of https://github.com/fluent/fluent-bit/pull/8475 ?? However it seems the PR has staled

**Comment by saixiaohui** [comment]
> Thank you for working on this. I was able to compile this branch locally and test it. Here are my results.
> 
> I started OpenTelemetry and Fluent Bit with the following respective configurations.
> 
> otel-config.yaml
> ```yaml
> ---
> receivers:
>   otlp:
>     protocols:
>       grpc:
>       http:
>         endpoint: "0.0.0.0:4318"
> 
> processors:
>   batch:
> 
> exporters:
>   file:
>     path: otel-output.json
> 
> service:
>   telemetry:
>     logs:
>       level: debug
>   pipelines:
>     logs:
>       receivers:
>         - otlp
>       processors:
>         - batch
>       exporters:
>         - file
> ```
> 
> fluent-bit-config.yaml
> ```yaml
> ---
> pipeline:
>   inputs:
>     - name: dummy
>       tag: dummy
>       metadata: |
>         {
>           "resource-attr": "resource-attr-val-1"
>         }
>       # This log record is taken directly from OpenTelemetry's Examples page.
>       # https://opentelemetry.io/docs/specs/otel/protocol/file-exporter/#examples
>       dummy: |
>         {
>           "severityNumber": 9,
>           "severityText": "Info",
>           "name": "logA",
>           "message": "This is a log message",
>           "app": "server",
>           "instance_num": 1,
>           "traceId": "08040201000000000000000000000000",
>           "spanId": "0102040800000000"
>         }
> 
>   outputs:
>     - name: opentelemetry
>       match: "*"
>       host: localhost
>       port: 4318
>       logs_body_key: $message
> 
>     # For live debugging on the Fluent Bit side.
>     - name: stdout
>       match: "*"
>       format: json
> ```
> 
> Here's what I received in OpenTelemetry. This is a _much better_ experience than previous. However, it's still not exactly what I would expect when shipping logs to an OpenTelemetry endpoint.
> 
> actual-logs.json
> Instead, I would have expected to receive the following where the `metadata` from Fluent Bit maps to the [Resource](https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-resource) field in OpenTelemetry instead of being bundled with the rest of the attributes under the [Attributes](https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-attributes) field. Also, I would expect to have some mechanism to set the other top-level OpenTelemetry fields (i.e., TraceId, SpanId, SeverityNumber, etc.).
> 
> expected-logs.json
> I believe we need to answer the following questions before the Fluent Bit `opentelemetry` output will be ready for mass adoption with the greatest compatibility.
> 
> * How does Fluent Bit's event metadata relate to OpenTelemetry's [Logs Data Model](https://opentelemetry.io/docs/specs/otel/logs/data-model)?
> * How does a Fluent Bit operator populate top-level fields (i.e., TraceId, SpanId, SeverityNumber, etc.) in OpenTelemetry's Logs Data Model? This pull request is focused on solving populating the `Body` and `Attributes` fields, but what about the rest?

May I know what your pod yaml looks like? I am always getting permission issue when I try to write to a file from Aks cluster. Thanks!

**Comment by cb645j** [comment]
> > Thank you for working on this. I was able to compile this branch locally and test it. Here are my results.
> > I started OpenTelemetry and Fluent Bit with the following respective configurations.
> > otel-config.yaml
> > ```yaml
> > ---
> > receivers:
> >   otlp:
> >     protocols:
> >       grpc:
> >       http:
> >         endpoint: "0.0.0.0:4318"
> > 
> > processors:
> >   batch:
> > 
> > exporters:
> >   file:
> >     path: otel-output.json
> > 
> > service:
> >   telemetry:
> >     logs:
> >       level: debug
> >   pipelines:
> >     logs:
> >       receivers:
> >         - otlp
> >       processors:
> >         - batch
> >       exporters:
> >         - file
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > fluent-bit-config.yaml
> > ```yaml
> > ---
> > pipeline:
> >   inputs:
> >     - name: dummy
> >       tag: dummy
> >       metadata: |
> >         {
> >           "resource-attr": "resource-attr-val-1"
> >         }
> >       # This log record is taken directly from OpenTelemetry's Examples page.
> >       # https://opentelemetry.io/docs/specs/otel/protocol/file-exporter/#examples
> >       dummy: |
> >         {
> >           "severityNumber": 9,
> >           "severityText": "Info",
> >           "name": "logA",
> >           "message": "This is a log message",
> >           "app": "server",
> >           "instance_num": 1,
> >           "traceId": "08040201000000000000000000000000",
> >           "spanId": "0102040800000000"
> >         }
> > 
> >   outputs:
> >     - name: opentelemetry
> >       match: "*"
> >       host: localhost
> >       port: 4318
> >       logs_body_key: $message
> > 
> >     # For live debugging on the Fluent Bit side.
> >     - name: stdout
> >       match: "*"
> >       format: json
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here's what I received in OpenTelemetry. This is a _much better_ experience than previous. However, it's still not exactly what I would expect when shipping logs to an OpenTelemetry endpoint.
> > actual-logs.json
> > Instead, I would have expected to receive the following where the `metadata` from Fluent Bit maps to the [Resource](https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-resource) field in OpenTelemetry instead of being bundled with the rest of the attributes under the [Attributes](https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-attributes) field. Also, I would expect to have some mechanism to set the other top-level OpenTelemetry fields (i.e., TraceId, SpanId, SeverityNumber, etc.).
> > expected-logs.json
> > I believe we need to answer the following questions before the Fluent Bit `opentelemetry` output will be ready for mass adoption with the greatest compatibility.
> > 
> > * How does Fluent Bit's event metadata relate to OpenTelemetry's [Logs Data Model](https://opentelemetry.io/docs/specs/otel/logs/data-model)?
> > * How does a Fluent Bit operator populate top-level fields (i.e., TraceId, SpanId, SeverityNumber, etc.) in OpenTelemetry's Logs Data Model? This pull request is focused on solving populating the `Body` and `Attributes` fields, but what about the rest?
> 
> May I know what your pod yaml looks like? I am always getting permission issue when I try to write to a file from Aks cluster. Thanks!

If you look at my changes, they address your concerns and the rest of the fields.

https://github.com/fluent/fluent-bit/pull/8644

**Pull request merged**
