### PR TITLE
in_tail: Add missed argument processed_bytes

### PR DESCRIPTION
**Pull request by shadchin**
----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by nokute78** [comment]
Could you check commit log style and DCO ?
- Commit log style
  - https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#commit-changes
- DCO
  - https://probot.github.io/apps/dco/

**Comment by shadchin** [comment]
Ok, I try

**Review by tarruda — APPROVED** [review]
LGTM

**Review by nokute78 — APPROVED** [review]
@shadchin Thank you for updating. LGTM.

**Comment by shadchin** [comment]
ping :)

**Comment by nokute78** [comment]
@edsiper @niedbalski Could you check and merge this ?

**Comment by edsiper** [comment]
cherry-picked cfe9f2748 for backports-1.9.8

**Pull request merged**
