### PR TITLE
build: fix Kafka support needs a toolchain w/ C++

### PR DESCRIPTION
**Pull request by ThomasDevoogdt**
While building fluent-bit on buildroot, I saw some build failures for toolchains that are lacking C++ support.
Kafka needs a C++ compiler to get compiled, but given the C codebase, it should be possible to compile it without.

Issue:
- https://github.com/fluent/fluent-bit/issues/7741

Logs:
- http://autobuild.buildroot.org/?reason=fluent-bit-2.1.7

Upstream:
- https://github.com/confluentinc/librdkafka/pull/4366

Buildroot:
- https://github.com/buildroot/buildroot/commit/a70e226ac1cbfcab3efb16a44d8e5c7bd6a520f1

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [x] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by patrick-stephens** [comment]
It looks like AppVeyor is failing so suggests a Windows build issue.
Triggering a full set of target builds to confirm but it looks like a unit test issue: https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/47658687/job/1w6aewjhg84vkw87

```
Test cache_basic_timeout...                     
------------------------
[ FAILED ]
  log.c:16: Check (*interval >= timeout - 1) && *interval <= timeout... failed
    interval error. got=3 expect=4-5
  log.c:92: Check ret == 0... failed
    update_and_check_interval for TEST_RECORD_01 failed. i=9
  log.c:16: Check (*interval >= timeout - 1) && *interval <= timeout... failed
    interval error. got=3 expect=4-5
  log.c:98: Check ret == 0... failed
    update_and_check_interval for TEST_RECORD_02 failed. i=9
Test cache_one_slot...                          
[ OK ]
FAILED: 1 of 2 unit tests has failed.
      Start 32: flb-it-processor
```

I cannot comment on the specific change itself: I think the typical approach is to fix it in the upstream dependency then update to the fixed version in Fluent Bit. We don't want to keep patching future dependency updates but it sounds like this is what you've done...

**Comment by ThomasDevoogdt** [comment]
Yes, I've pushed a commit upstream, I'm awaiting response on that. I will
definitely ping you if this is the case.
About the build failures, these are not very clean to me. I don't see how
the changes in this PR could cause regression. But never say never indeed.
Please double check.

Op di 1 aug. 2023 21:33 schreef Pat ***@***.***>:

**Comment by patrick-stephens** [comment]
macOS unit tests failures can be ignored.
I've no idea about the appveyor one I'm afraid, that's probably better on @leonardo-albertovich

**Comment by patrick-stephens** [comment]
I'll leave this with @edsiper as not really a CI question for me :)

**Comment by ThomasDevoogdt** [comment]
This PR is overruled by https://github.com/fluent/fluent-bit/pull/9277, so I will close it. (Please have a look at that one!)

**Pull request closed without merging**
