### PR TITLE
Engine: implement cb_exit callback for plugins

### PR DESCRIPTION
**Pull request by pandax381**
Proposal to fix issue #23

Signed-off-by: Masaya YAMAMOTO &lt;pandax381@gmail.com&gt;

### CODE REVIEW

**Comment by edsiper** [comment]
Looks good to me, just a minor suggestion, can we call it "cb_exit" instead of cb_pre_exit ?, the exit point is just one.

**Comment by pandax381** [comment]
Sure! We call it "cb_exit".

**Comment by cosmo0920** [comment]
`cb_exit` is also looks good to me. :+1:

**Comment by edsiper** [comment]
thanks!

**Pull request merged**
