### PR TITLE
1.8: container definition removal

### PR DESCRIPTION
**Pull request by patrick-stephens**
Remove duplication of Dockerfiles from https://github.com/fluent/fluent-bit-docker-image/tree/1.8.

Addresses #4970 and choose this or #4969.

----

**Testing**

- Master definition:
```
$ docker build -t fb-1-8 -f ./dockerfiles/Dockerfile.x86_64-master .
$ docker run --rm -it fb-1-8
Fluent Bit v1.8.13
* Copyright (C) 2015-2021 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/03/03 10:12:27] [ info] [engine] started (pid=1)
[2022/03/03 10:12:27] [ info] [storage] version=1.1.6, initializing...
[2022/03/03 10:12:27] [ info] [storage] in-memory
[2022/03/03 10:12:27] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/03/03 10:12:27] [ info] [cmetrics] version=0.2.2
[2022/03/03 10:12:27] [ info] [sp] stream processor started
[2022/03/03 10:12:27] [ info] [output:stdout:stdout.0] worker #0 started
[0] cpu.local: [1646302348.073016462, {"cpu_p"=>0.312500, "user_p"=>0.187500, "system_p"=>0.125000, "cpu0.p_cpu"=>0.000000, "cpu0.p_user"=>0.000000, "cpu0.p_system"=>0.000000, "cpu1.p_cpu"=>1.000000, "cpu1.p_user"=>0.000000, "cpu1.p_system"=>1.000000, "cpu2.p_cpu"=>0.000000, "cpu2.p_user"=>0.000000, "cpu2.p_system"=>0.000000, "cpu3.p_cpu"=>0.000000, "cpu3.p_user"=>0.000000, "cpu3.p_system"=>0.000000, "cpu4.p_cpu"=>0.000000, "cpu4.p_user"=>0.000000, "cpu4.p_system"=>0.000000, "cpu5.p_cpu"=>0.000000, "cpu5.p_user"=>0.000000, "cpu5.p_system"=>0.000000, "cpu6.p_cpu"=>0.000000, "cpu6.p_user"=>0.000000, "cpu6.p_system"=>0.000000, "cpu7.p_cpu"=>0.000000, "cpu7.p_user"=>0.000000, "cpu7.p_system"=>0.000000, "cpu8.p_cpu"=>1.000000, "cpu8.p_user"=>0.000000, "cpu8.p_system"=>1.000000, "cpu9.p_cpu"=>1.000000, "cpu9.p_user"=>0.000000, "cpu9.p_system"=>1.000000, "cpu10.p_cpu"=>0.000000, "cpu10.p_user"=>0.000000, "cpu10.p_system"=>0.000000, "cpu11.p_cpu"=>0.000000, "cpu11.p_user"=>0.000000, "cpu11.p_system"=>0.000000, "cpu12.p_cpu"=>1.000000, "cpu12.p_user"=>1.000000, "cpu12.p_system"=>0.000000, "cpu13.p_cpu"=>0.000000, "cpu13.p_user"=>0.000000, "cpu13.p_system"=>0.000000, "cpu14.p_cpu"=>0.000000, "cpu14.p_user"=>0.000000, "cpu14.p_system"=>0.000000, "cpu15.p_cpu"=>1.000000, "cpu15.p_user"=>1.000000, "cpu15.p_system"=>0.000000}]
```
- Master-debug
```
$ docker build -t fb-1-8-debug -f ./dockerfiles/Dockerfile.x86_64-master_debug .
$ docker run --rm -it fb-1-8-debug
Fluent Bit v1.8.13
* Copyright (C) 2015-2021 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/03/03 10:14:27] [ info] [engine] started (pid=1)
[2022/03/03 10:14:27] [ info] [storage] version=1.1.6, initializing...
[2022/03/03 10:14:27] [ info] [storage] in-memory
[2022/03/03 10:14:27] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/03/03 10:14:27] [ info] [cmetrics] version=0.2.2
[2022/03/03 10:14:27] [ info] [sp] stream processor started
[2022/03/03 10:14:27] [ info] [output:stdout:stdout.0] worker #0 started
[0] cpu.local: [1646302468.073001043, {"cpu_p"=>0.062500, "user_p"=>0.062500, "system_p"=>0.000000, "cpu0.p_cpu"=>0.000000, "cpu0.p_user"=>0.000000, "cpu0.p_system"=>0.000000, "cpu1.p_cpu"=>0.000000, "cpu1.p_user"=>0.000000, "cpu1.p_system"=>0.000000, "cpu2.p_cpu"=>0.000000, "cpu2.p_user"=>0.000000, "cpu2.p_system"=>0.000000, "cpu3.p_cpu"=>0.000000, "cpu3.p_user"=>0.000000, "cpu3.p_system"=>0.000000, "cpu4.p_cpu"=>0.000000, "cpu4.p_user"=>0.000000, "cpu4.p_system"=>0.000000, "cpu5.p_cpu"=>0.000000, "cpu5.p_user"=>0.000000, "cpu5.p_system"=>0.000000, "cpu6.p_cpu"=>0.000000, "cpu6.p_user"=>0.000000, "cpu6.p_system"=>0.000000, "cpu7.p_cpu"=>0.000000, "cpu7.p_user"=>0.000000, "cpu7.p_system"=>0.000000, "cpu8.p_cpu"=>0.000000, "cpu8.p_user"=>0.000000, "cpu8.p_system"=>0.000000, "cpu9.p_cpu"=>0.000000, "cpu9.p_user"=>0.000000, "cpu9.p_system"=>0.000000, "cpu10.p_cpu"=>0.000000, "cpu10.p_user"=>0.000000, "cpu10.p_system"=>0.000000, "cpu11.p_cpu"=>0.000000, "cpu11.p_user"=>0.000000, "cpu11.p_system"=>0.000000, "cpu12.p_cpu"=>0.000000, "cpu12.p_user"=>0.000000, "cpu12.p_system"=>0.000000, "cpu13.p_cpu"=>0.000000, "cpu13.p_user"=>0.000000, "cpu13.p_system"=>0.000000, "cpu14.p_cpu"=>0.000000, "cpu14.p_user"=>0.000000, "cpu14.p_system"=>0.000000, "cpu15.p_cpu"=>0.000000, "cpu15.p_user"=>0.000000, "cpu15.p_system"=>0.000000}]
```
----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Review by niedbalski — APPROVED** [review]
LGTM

**Comment by ilanitr** [comment]
@patrick-stephens could you please explain the reason to remove windows dockerfiles from 1.8 branch? We are using the windows dockerfile to build our images and currently failing on 1.8.14 and 1.8.15 due to the missing file.

**Comment by patrick-stephens** [comment]
1.8 releases were built from a separate repo and we were seeing both duplication of effort or deviation when making updates. It was decided to make it clearer by only having one source of truth. This actually caused issues as we updated one and not the other so it was a way to improve releases.

Additionally the Windows container definitions were not used for anything so they would not be tested and may end up breaking. I raised a discussion on this here so please add your use case: https://github.com/fluent/fluent-bit/discussions/5007 

The master branch still has them with no change as we build it all from the same repo now. 

Having just the Windows ones, which aren't used for releases or testing, for 1.8 seems incorrect to me. They probably should be added to https://github.com/fluent/fluent-bit-docker-image/tree/1.8 as a PR if you want to raise one?

**Comment by ilanitr** [comment]
Thanks @patrick-stephens! I've added a comment to [#5007](https://github.com/fluent/fluent-bit/discussions/5007) and will raise a PR.

**Pull request merged**
