### PR TITLE
Allow building on FreeBSD

### PR DESCRIPTION
**Pull request by girgen**
A couple of small fixes to allow building on FreeBSD

### CODE REVIEW

**Comment by edsiper** [comment]
@girgen thanks for the contribution, in order to merge the changes would you please do:

- change commit subjects: the endian change commit must start with: "lib: crc32: ..."
- "chunkio" related changes must be sent as a separate PR to repository https://github.com/edsiper/chunkio

**Comment by girgen** [comment]
I've opened a pull request in https://github.com/edsiper/chunkio for both these patches.

**Comment by girgen** [comment]
> * "chunkio" related changes must be sent as a separate PR to repository https://github.com/edsiper/chunkio

and the PR for lib/LuaJIT should perhaps also go to a different project as well?

**Comment by edsiper** [comment]
@girgen for LuaJIT, instead of modify the project code it self, can you try some modifier in our CMake ?, specifically in the BUILD_COMMAND:

https://github.com/fluent/fluent-bit/blob/master/CMakeLists.txt#L506

according to LuaJIT [documentation](http://luajit.org/install.html) the compiler can be modified like:

```
make CC="gcc -m32"
```

of course on that value we should put the CMake variable that holds the compiler used by the system or specified by the user at build time (CMAKE_C_COMPILER maybe ?)

**Comment by edsiper** [comment]
for some reason it works (tested in luajit tree):

```
$ make CC="invalidcompiler"
==== Building LuaJIT 2.0.5 ====
make -C src
make[1]: Entering directory '/home/edsiper/coding/fluent-bit/lib/luajit-2.0.5/src'
make[1]: invalidcompiler: Command not found
make[1]: invalidcompiler: Command not found
make[1]: invalidcompiler: Command not found
make[1]: invalidcompiler: Command not found
make[1]: invalidcompiler: Command not found
make[1]: invalidcompiler: Command not found
Makefile:254: *** Unsupported target architecture.  Stop.
make[1]: Leaving directory '/home/edsiper/coding/fluent-bit/lib/luajit-2.0.5/src'
make: *** [Makefile:110: default] Error 2
```

**Comment by girgen** [comment]
I can't make it work that way:

libtool: install: chmod 644 /wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/lib/libonigmo.a
libtool: install: ranlib /wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/lib/libonigmo.a
gmake[6]: Leaving directory '/wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/onigmo-prefix/src/onigmo-build'
gmake[5]: Leaving directory '/wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/onigmo-prefix/src/onigmo-build'
Making install in sample
gmake[5]: Entering directory '/wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/onigmo-prefix/src/onigmo-build/sample'
gmake[6]: Entering directory '/wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/onigmo-prefix/src/onigmo-build/sample'
gmake[6]: Nothing to be done for 'install-exec-am'.
gmake[6]: Nothing to be done for 'install-data-am'.
gmake[6]: Leaving directory '/wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/onigmo-prefix/src/onigmo-build/sample'
gmake[5]: Leaving directory '/wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/onigmo-prefix/src/onigmo-build/sample'
gmake[4]: Leaving directory '/wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/onigmo-prefix/src/onigmo-build'
cd /wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/onigmo-prefix/src/onigmo-build && /usr/local/bin/cmake -E touch /wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/onigmo-prefix/src/onigmo-stamp/onigmo-install
[ 33%] Completed 'onigmo'
/usr/local/bin/cmake -E make_directory /wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/CMakeFiles
/usr/local/bin/cmake -E touch /wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/CMakeFiles/onigmo-complete
/usr/local/bin/cmake -E touch /wrkdirs/usr/ports/sysutils/fluent-bit/work/.build/onigmo-prefix/src/onigmo-stamp/onigmo-done
gmake[3]: Leaving directory '/wrkdirs/usr/ports/sysutils/fluent-bit/work/.build'
[ 33%] Built target onigmo
gmake[2]: Leaving directory '/wrkdirs/usr/ports/sysutils/fluent-bit/work/.build'
gmake[1]: *** [Makefile:155: all] Error 2
gmake[1]: Leaving directory '/wrkdirs/usr/ports/sysutils/fluent-bit/work/.build'
===> Compilation failed unexpectedly.

**Comment by edsiper** [comment]
I've pushed a small fix in GIT master, would you please give it a try ?

**Comment by edsiper** [comment]
ping

**Comment by edsiper** [comment]
timeout.

**Pull request closed without merging**
