### PR TITLE
hash: Improve flb_hash_add to copy the key up to the passed key_len

### PR DESCRIPTION
**Pull request by vlvasilev**
Make `flb_hash_add` to copy the key up to the passed key_len.

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for your contribution, in order to merge please fix the commit message, prefix it with "hash: ...", ref: 

https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#commit-changes

**Comment by vlvasilev** [comment]
Thanks for the comment. It is done.

**Comment by nigels-com** [comment]
Looks good to me.

**Comment by edsiper** [comment]
thanks

**Pull request merged**
