### PR TITLE
sp: add support for checking the existence of a key or NULL value

### PR DESCRIPTION
**Pull request by koleini**
Signed-off-by: Masoud Koleini <masoud.koleini@arm.com>

### CODE REVIEW

**Comment by koleini** [comment]
The changes addresse the feature request https://github.com/fluent/fluent-bit/issues/1332 and fixes several bugs.

This PR adds`EXISTS <key>`, `<key> IS NULL` and `<key> IS NOT NULL` to the syntax of `WHERE` condition:

`EXISTS <key>` holds when key is present in the record (even if the value is `null`).
`<key> IS NULL` holds when key is present and has `null` value.
`<key> IS NOT NULL` is equivalent to`NOT <key> IS NULL`.

**Comment by koleini** [comment]
closes https://github.com/fluent/fluent-bit/issues/1332

**Comment by edsiper** [comment]
thanks @koleini !

one quick comment, wouldn't the EXISTS be applied after the key ? like: 

```
<key> EXISTS
```

like:

```
bin/fluent-bit -i dummy -p alias=data -p "dummy={\"key1\": null, \"key2\": \"test\"}" -T "SELECT * FROM STREAM:data WHERE key1 IS NULL AND key2 EXISTS;" -o null -f 1
```

comments ?

**Comment by koleini** [comment]
Negating an `EXISTS` expression using `NOT` (prefix) operator looks more idiomatic if we write `NOT EXISTS <key>`. However, `NOT <key> EXISTS` also looks good. Having `IS NOT NULL` required adding a separate rule, but I did that in order to make it similar to SQL. It is semantically the same as `NOT <key> IS NULL`.

Changing the parser is very simple, and I am OK to modify the code if you suggest using `EXISTS` after key.

**Comment by edsiper** [comment]
@xerial what do you think would be the ideal semantic ?, basically we are providing special conditions in the stream processor to check if a key has null value but also testing if a key exists or not in the record, e.g:

__option 1__

- WHERE key IS NULL
- WHERE key IS NOT NULL
- WHERE EXISTS key
- WHERE NOT EXISTS key

__option 2__

- WHERE key IS NULL
- WHERE key IS NOT NULL
- WHERE key EXISTS
- WHERE key NOT EXISTS

based in your SQL experience, what would be preferred ?, or do you recommend a different option ?

**Comment by xerial** [comment]
Some concerns:
- `exists` is used for set-semantics in SQL, so re-using it for column presence check can be confusing for people who are familiar to SQL.
- When compiling an SQL if we don't know whether the key is present or not, it also means we don't know the structure of an intermediate relation (= table attributes). So SQL type analysis can be complicated if we check the presence of key at the expression level like `WHERE (column) exists`. 
- If we have a representation of a record in the table (e.g., `r`), we should be able to write an expression like `r.contains('key')`.
- I guess for most of the cases, we would like to switch the behavior like (e.g., Either, Option, Optional, etc.): 
    - `Option(key).getOrElse('default value')` returns the value if the key is present in the record, or the default value if not.
    - If the proposed syntax is good enough to do such optional value handling?

**Comment by edsiper** [comment]
@xerial thanks for the feedback! very useful.

I like @xerial idea of having a special key name that represents the record in question for the query, should we use something like:

- @record
- @record.contains(key), applicable also for @record.contains(key['sub1']['sub2']...)

note: IS NULL and IS NOT NULL are good to go, comments now are about a record context and further functions available.

at Kubecon we also got the question to have something similar to query the timestamp of the record but in the conditionals, like:

- WHERE @record.timestamp() > num

comments are welcome.

**Pull request merged**
