### PR TITLE
bin: document trace level logging.

### PR DESCRIPTION
**Pull request by attila123**
Signed-off-by: Attila Vangel <vangel.attila@gmail.com>

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for this contribution. I think this change have two parts:

- improve fluent-bit.c help function -> OK, just don't mention a CMake build option since it should go in the official docs, specifically in the [build](https://docs.fluentbit.io/manual/installation/build_install) part.

- Don't touch the README.md since build instructions have a separate repo [here](github.com/fluent/fluent-bit-docs)

**Comment by edsiper** [comment]
ping

**Comment by nigels-com** [comment]
The current `README.md` points to [Build and Install](https://docs.fluentbit.io/manual/installation/build_install) portion of the manual.
There could be a new section added there to draw attention to development-oriented options such as trace.

**Comment by nigels-com** [comment]
I think `fluent-bit.c` could also list the `-vv` flag for trace mode, if support is available.

**Comment by nigels-com** [comment]
I filed two PRs in response to the discussion here.
Perhaps these are a good compromise.

**Comment by edsiper** [comment]
I'd suggest to shrink the explanation of -v, this looks too long:

```
  -v, --verbose		increase logging verbosity: use it once for debug level, twice for trace level (to enable trace level use -DFLB_TRACE=On with cmake, see README.md in the source code)
```

what about something like:

```
  -v, --verbose		increase verbosity: use it once for debug level, twice for trace level
```

but note that message will need to be conditional on trace macro, e.g:

```c
#ifdef FLB_HAVE_TRACE
...  -v, --verbose		increase verbosity: use it once for debug level, twice for trace level..
#else
... -v, --verbose		increase verbosity: use it once for debug level
#endif

```

**Comment by edsiper** [comment]
ping

**Comment by nigels-com** [comment]
I think this was sufficiently addressed via the other PRs.   Time to close this IMHO.

**Pull request closed without merging**
