### PR TITLE
Avro source code on top of the previous jansson PR. [2 of 5]

### PR DESCRIPTION
**Pull request by xmcqueen**
This is the avro code built on top of the jansson code from the previous PR.  

We just want the last commit here:

libavro: avro source code on top of the jansson PR 102da70

### CODE REVIEW

**Comment by xmcqueen** [comment]
PAUSE 

I found a build problem over here, and I've revised how the jansson is used by lib/avro and src/flb-avro.

I've got it working already. I'll send an update soon.

Specifically I found the product was not using a static linkage to jansson, but was linking to a shared jansson.  

I've fixed that with an unambiguous name so it won't happen again.  

I've also improved how jansson is built, by using its cmake, rather than treating it as an externally built library.  Now its built the same way avro is built and is names jansson-static just like how avro is built with avro-static.

**Comment by edsiper** [comment]
thanks for the updates.

would you please squash or normalize the commits with the components name as prefixes ?

**Comment by xmcqueen** [comment]
OK squashed and prefixed.

only one commit:

libavro: avro source code on top of the jansson PR e1035d1

**Comment by edsiper** [comment]
Closing this PR since #2820 re-implemented this.

**Pull request closed without merging**
