### PR TITLE
Plugin: add throttle size filter and it's unit tests

### PR DESCRIPTION
**Pull request by vlvasilev**
The Throttle Size Filter plugin sets the average Rate of messages payload per
Interval per Name_field(if defined), based on a leaky bucket and sliding window algorithm.
In the case of overflood, it will leak within a certain rate. There can be multiple
buckets as each bucket are made for a different value of Name_field.
For example, Name_field could be the source `pod_name`, so for the pods kube-apiserver and alertmanager there will be two different buckets. 

We can monitor only one field of the log message by setting log_field, e.g. "log". 
Thus we will take into account only the size of the "log" field. 

After a time of no encountered new data into a bucket, it will be deleted. The Window_time_duration setting specifies the time required to flag a bucket as unused and therefore deleted.

When we have nested fields in the log data object (as in the input example below) we separate the keys by '|'.
example:
```
[FILTER]
	Name     		throttle_size
	Match	 		*
	Rate     		1M
	Window   		30
	Interval 		3s
	Log_field	 	log
	Name_field		kubernetes|pod_name
	Window_time_duration 	360s
        Hash_table_size         256

```
input:
    [123456, {"log":"20kmessage", "kubernetes":{"pod_name":"kube-apiserver"}}]
    [123490, {"log":"30kmessage", "kubernetes":{"pod_name":"alermanager"}}]

This plugin will make two buckets (one for "kube-apiserver" and one for
"alertmanager) where will take into account only the size of the "log" field.
Log_field can be omitted, thus all of the message will be calculated.
So if the kube-apiserver starts to flood the plugin will drop the messages
only of kube-apiserver pod, not alertmanager's ones.

At the moment fluent bit hashmap does not resize, so to avoid the population of the hashmaps buckets choose proper size by hash_table_size setting.

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for your contribution.

Would you please replace uthash by using own hashing interface: 

https://github.com/fluent/fluent-bit/blob/master/src/flb_hash.c

**Comment by edsiper** [comment]
one minor thing, can you rename from filter_size_throttle to filter_throttle_size ?, so becomes easier to identify throttle's plugins. (rename plugin and functions names)

**Comment by edsiper** [comment]
My apologizes for the very long delay on this.

I am testing the unit test but all tests are failing, any idea about why ?

**Comment by edsiper** [comment]
ping

**Comment by edsiper** [comment]
thanks!

**Comment by AkshayDubey29** [comment]
@vlvasilev Can we put the rate in KBs? like below

Rate     		1K or Rate     		1Kb

**Pull request merged**
