### PR TITLE
lib: mbedtls removal

### PR DESCRIPTION
**Pull request by leonardo-albertovich**
This PR completely removes mbedtls from fluent-bit replacing it with the following abstraction layers : 

1. flb_hash  - This handles hashing
2. flb_hmac - This handles hmac, there's no cmac support at the moment
3. flb_crypto -  This handles asymetric encryption, decryption and signatures

I have added proper testing for the three wrappers and additionally verified that stackdriver properly generates the signature required to obtain a valid JWT token.

All the plugins that used mbedtls have been updated to use these abstraction layers which have been modeled according to the needs of said plugins.

Since this is a substantial change I will send review requests to the maintainers of the output plugins I touched to get their approval.

### CODE REVIEW

**Comment by nokute78** [comment]
@leonardo-albertovich I think this patch breaks master.
Please merge after reviewing and checking CI result...
```
[ 36%] Building C object src/CMakeFiles/fluent-bit-static.dir/flb_hmac.c.o
In file included from /home/taka/git/tmp/fluent-bit/src/flb_hmac.c:18:
/home/taka/git/tmp/fluent-bit/include/fluent-bit/flb_hmac.h:22:10: fatal error: openssl/err.h: No such file or directory
   22 | #include <openssl/err.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/fluent-bit-static.dir/build.make:661: src/CMakeFiles/fluent-bit-static.dir/flb_hmac.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6802: src/CMakeFiles/fluent-bit-static.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by leonardo-albertovich** [comment]
This doesn't break master, it's a defect in CIFuzz for which I already submitted a PR, this was carefully considered when merging this PR and I locally reproduced the oss-fuzz environment to ensure that after they merged my PR master would pass the CIFuzz test (since it only checks out master regardless of the PR that triggers it).

**Comment by nokute78** [comment]
Thank you for updating. 
https://github.com/google/oss-fuzz/pull/8205 fixed CIFuzz error.
https://github.com/fluent/fluent-bit/pull/5878/checks

By the way, it meant that this patch made it depends on openssl header files.
Could you add a documentation about it ?

**Comment by leonardo-albertovich** [comment]
Yes, openssl is no longer optional.

**Comment by nokute78** [comment]
CI failed on macOS and we need to take care it.
https://github.com/fluent/fluent-bit/runs/7798078862?check_suite_focus=true#step:4:1557

By the way, I raised a documentation issue as https://github.com/fluent/fluent-bit/issues/5879

**Comment by leonardo-albertovich** [comment]
It seems like the macos workflow is not installing openssl, maybe @patrick-stephens or @niedbalski can help us with that.

**Comment by nokute78** [comment]
> CI failed on macOS

It was fixed by https://github.com/fluent/fluent-bit/pull/5887 .

**Comment by leonardo-albertovich** [comment]
Thanks a lot @nokute78!

**Pull request merged**
