### PR TITLE
wasm: restore support for some targets

### PR DESCRIPTION
**Pull request by ThomasDevoogdt**
Somehow, support for ARC, MIPS, and XTENSA got dropped by bumping to v1.3.0, so restore it now. Remark that those targets are mentioned in the section above.

See commit fa6a248746f9f481b5f6aef49716141fa0222650.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [N/A] Example configuration file for the change
- [N/A] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Review by cosmo0920 — COMMENTED** [review]
These added lines should be failed due to this line:
> message(SEND_ERROR "Unsupported build target platform!")

Shouldn't we pay attention to the previous lines to detect automatically platforms?

**Comment by ThomasDevoogdt** [comment]
> These added lines should be failed due to this line:

Wrong, that block is guarded with "if (NOT DEFINED WAMR_BUILD_TARGET)", but I do define it.
See: https://github.com/buildroot/buildroot/blob/master/package/fluent-bit/fluent-bit.mk#L25-L39.

**Comment by cosmo0920** [comment]
> > These added lines should be failed due to this line:
> 
> Wrong, that block is guarded with "if (NOT DEFINED WAMR_BUILD_TARGET)", but I do define it. See: https://github.com/buildroot/buildroot/blob/master/package/fluent-bit/fluent-bit.mk#L25-L39.

I mean, this should be completed inside on the CMakeLists.txt not on the additional autoconf mechansim.

**Comment by ThomasDevoogdt** [comment]
> I mean, this should be completed inside on the CMakeLists.txt not on the additional autoconf mechanism.

The problem is that the CMakeLists.txt was not really able to detect the relevant platforms right. Partially since buildroot sometimes uses other names and so on. So for that reason, this translation is done:
```
config BR2_PACKAGE_FLUENT_BIT_WASM_ARCH
	string
	default "AARCH64"    if BR2_aarch64 || BR2_aarch64be
	default "ARC"        if BR2_arcle || BR2_arceb
	default "ARM"        if BR2_arm || BR2_armeb
	default "MIPS"       if BR2_mips || BR2_mipsel || BR2_mips64 || BR2_mips64el
	default "RISCV32"    if BR2_riscv && BR2_RISCV_32
	default "RISCV64"    if BR2_riscv && BR2_RISCV_64
	default "X86_32"     if BR2_i386
	default "X86_64"     if BR2_x86_64
	default "XTENSA"     if BR2_xtensa
...
-DWAMR_BUILD_TARGET=$(FLUENT_BIT_WAMR_ARCH)
```
I now wanted to bump fluent-bit from v2.1.7 to v2.2.2, and saw that some targets were broken.
The main reason seems to be that some of them were dropped from the list.

So there are indeed two things here.
a) the auto detection which is not yet solved by this PR to detect ARC, MIPS, and XTENSA, should be added here:
https://github.com/fluent/fluent-bit/blob/b1b4d5fd2774a4e15e185dea3602e304c972e3ab/src/wasm/CMakeLists.txt#L17-L37
b) the definitions for the build target (this PR), which is part of this block:
https://github.com/fluent/fluent-bit/blob/b1b4d5fd2774a4e15e185dea3602e304c972e3ab/src/wasm/CMakeLists.txt#L41-L64

**Comment by cosmo0920** [comment]
Ah, got it. Thanks for the explanation. Then, it seems great to detect for the latter detectors for architecture. The auto detectors are only good enough to handle well-known architectures, I believe.

**Review by cosmo0920 — APPROVED** [review]

**Comment by edsiper** [comment]
thank you. I will backport this to 2.2

**Pull request merged**
