### PR TITLE
filter_kubernetes: add Keep_Log option (#764)

### PR DESCRIPTION
**Pull request by yann-soubeyrand**
This option allows to choose wether to keep the original log field once it has
been successfully unescaped or parsed.

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for your contribution.

Would you please submit the following:

- new commit for tests/runtime/filter_kubernetes.c adding an option for this test (commit prefix is "tests: runtime: filter_kubernetes: ..."
- Send a PR for the documentation PR: https://github.com/fluent/fluent-bit-docs

**Comment by yann-soubeyrand** [comment]
Here is the documentation PR: https://github.com/fluent/fluent-bit-docs/pull/154.

I'll make a commit for the tests.

**Comment by yann-soubeyrand** [comment]
And here is the commit for tests ;-)

**Comment by edsiper** [comment]
thanks

**Pull request merged**
