### PR TITLE
out_bigquery: support AWS auth via GCP Workload Identity Federation

### PR DESCRIPTION
**Pull request by zhenyami**
Traditionally, applications running outside Google Cloud have used service account keys to access Google Cloud resources. Using identity federation, you can allow an AWS user or role to impersonate a service account. This lets your workload access Google Cloud resources directly, using a short-lived access token, and eliminates the maintenance and security burden associated with service account keys.

Documentation:
https://cloud.google.com/iam/docs/workload-identity-federation
https://cloud.google.com/iam/docs/using-workload-identity-federation

These changes will allow exchanging temporary AWS IMDS credentials for a Google OAuth token, which is required for sending logs to BigQuery. A GCP project with Workload Identity Pool and Providers needs to be set up before using this functionality.

* Added a config parameter `enable_identity_federation`, which disables the traditional OAuth token retrieval using the long-term service account credentials, and instead enables exchanging AWS credentials for the Google OAuth token via GCP Workload Identity Federation.
* Added a config parameter `aws_region`, which is required to construct the correct AWS STS API URL.
* Added config parameters `project_number`, `pool_id`, and `provider_id`. These refer to the GCP project with Workload Identity Pool and AWS Providers.
* Added a config parameter `google_service_account`, used to generate the service account-specific URL in order to call the `generateAccessToken()` method to retrieve OAuth token.
* Updated BigQuery config to set up AWS EC2 credentials provider. IMDS (Instance Metadata Service) is used on EC2. This code was copied from Kinesis and ElasticSearch plugins that use AWS authentication. Also added setup of AWS STS, Google STS, and Google IAM connections.
* Added a function to sign clients with AWS SigV4 signature. We're using it to sign the AWS STS API client to the GetCallerIdentity endpoint. The resulting signature is later sent to Google API for verification.
* Added a copy of a slightly modified function to encode URI that follows RFC 3986 for reserved characters. It is used to encode the AWS GetCallerIdentity token to be included in the Google STS payload.
* Added code to create a request to Google Service Account Credentials API generateAccessToken() method. The request URL includes the service account email or ID in the path, and the federated token is passed as a header. This method returns an OAuth token that can be used in the same way as the existing OAuth token that is generated from the service account credentials file.
* Set the OAuth token refresh period to 50 minutes since its retrieval, same duration as the existing service account credentials OAuth token. The actual token expires in 60 minutes.

Signed-off-by: zhenyami <zhenyamzk+GitHub@gmail.com>

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change
- [x] Debug log output from testing the change

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [x] Documentation required for this feature

Documentation PR: https://github.com/fluent/fluent-bit-docs/pull/666
----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by zhenyami** [comment]
### Testing
Example BigQuery output plugin configuration for the change:
```yaml
[OUTPUT]
    Name                            bigquery
    Match                           *

    # Workload Identity Federation
    enable_identity_federation      On
    aws_region                      us-east-1
    project_number                  012345678901
    pool_id                         my-pool
    provider_id                     987654321098
    google_service_account          my-service-account@my-project.iam.gserviceaccount.com

    project_id                      my-project
    dataset_id                      my-dataset
    table_id                        my_table

```

**Comment by zhenyami** [comment]
### Logs
AWS credentials provider initialization and credentials exchange on Fluent Bit startup:
```
[2021/11/04 09:02:41] [ info] [engine] started (pid=4425)
[2021/11/04 09:02:41] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2021/11/04 09:02:41] [debug] [storage] [cio stream] new stream registered: tail.0
[2021/11/04 09:02:41] [ info] [storage] version=1.1.5, initializing...
[2021/11/04 09:02:41] [ info] [storage] in-memory
[2021/11/04 09:02:41] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/11/04 09:02:41] [ info] [cmetrics] version=0.2.2
[2021/11/04 09:02:41] [debug] [input:tail:tail_service.my_srv.my_pkg] flb_tail_fs_inotify_init() initializing inotify tail input
[2021/11/04 09:02:41] [debug] [input:tail:tail_service.my_srv.my_pkg] inotify watch fd=26
[2021/11/04 09:02:41] [debug] [input:tail:tail_service.my_srv.my_pkg] scanning path /mnt/services/my_pkg/logs/my_pkg-service.log
[2021/11/04 09:02:41] [debug] [input:tail:tail_service.my_srv.my_pkg] inode=134310019 with offset=321090000 appended as /mnt/services/my_pkg/logs/my_pkg-service.log
[2021/11/04 09:02:41] [debug] [input:tail:tail_service.my_srv.my_pkg] scan_glob add(): /mnt/services/my_pkg/logs/my_pkg-service.log, inode 134310019
[2021/11/04 09:02:41] [debug] [input:tail:tail_service.my_srv.my_pkg] 1 new files found on path '/mnt/services/my_pkg/logs/my_pkg-service.log'
[2021/11/04 09:02:41] [debug] [filter:modify:modify_add_host_metadata] Initialized modify filter with 0 conditions and 10 rules
[2021/11/04 09:02:41] [debug] [bigquery:bigquery_service.my_srv.my_pkg] created event channels: read=28 write=29
[2021/11/04 09:02:41] [ info] [output:bigquery:bigquery_service.my_srv.my_pkg] project='qtco-observability-logging' dataset='tables' table='service_my_srv_my_pkg_dev'
[2021/11/04 09:02:41] [debug] [aws_credentials] Initialized Env Provider in standard chain
[2021/11/04 09:02:41] [ warn] [aws_credentials] Failed to initialize profile provider: HOME, AWS_CONFIG_FILE, and AWS_SHARED_CREDENTIALS_FILE not set.
[2021/11/04 09:02:41] [debug] [aws_credentials] Not initializing EKS provider because AWS_ROLE_ARN was not set
[2021/11/04 09:02:41] [debug] [aws_credentials] Not initializing ECS Provider because AWS_CONTAINER_CREDENTIALS_RELATIVE_URI is not set
[2021/11/04 09:02:41] [debug] [aws_credentials] Initialized EC2 Provider in standard chain
[2021/11/04 09:02:41] [debug] [aws_credentials] Sync called on the EC2 provider
[2021/11/04 09:02:41] [debug] [aws_credentials] Init called on the env provider
[2021/11/04 09:02:41] [debug] [aws_credentials] Init called on the EC2 IMDS provider
[2021/11/04 09:02:41] [debug] [aws_credentials] requesting credentials from EC2 IMDS
[2021/11/04 09:02:41] [debug] [http_client] not using http_proxy for header
[2021/11/04 09:02:41] [debug] [http_client] server 169.254.169.254:80 will close connection #30
[2021/11/04 09:02:41] [debug] [aws_client] (null): http_do=0, HTTP Status: 401
[2021/11/04 09:02:41] [debug] [http_client] not using http_proxy for header
[2021/11/04 09:02:41] [debug] [http_client] server 169.254.169.254:80 will close connection #31
[2021/11/04 09:02:41] [debug] [imds] using IMDSv2
[2021/11/04 09:02:41] [debug] [http_client] not using http_proxy for header
[2021/11/04 09:02:41] [debug] [http_client] server 169.254.169.254:80 will close connection #30
[2021/11/04 09:02:41] [debug] [aws_credentials] Requesting credentials for instance role my_srv
[2021/11/04 09:02:41] [debug] [imds] using IMDSv2
[2021/11/04 09:02:41] [debug] [http_client] not using http_proxy for header
[2021/11/04 09:02:41] [debug] [http_client] server 169.254.169.254:80 will close connection #30
[2021/11/04 09:02:41] [debug] [aws_credentials] Async called on the EC2 provider
[2021/11/04 09:02:41] [debug] [aws_credentials] upstream_set called on the EC2 provider
[2021/11/04 09:02:41] [debug] [http_client] not using http_proxy for header
[2021/11/04 09:02:41] [debug] [output:bigquery:bigquery_service.my_srv.my_pkg] Signing the request with AWS SigV4 using IMDS credentials
[2021/11/04 09:02:41] [debug] [aws_credentials] Requesting credentials from the EC2 provider..
[2021/11/04 09:02:41] [debug] [http_client] not using http_proxy for header
[2021/11/04 09:02:41] [debug] [http_client] not using http_proxy for header
[2021/11/04 09:02:41] [debug] [upstream] KA connection #31 to sts.googleapis.com:443 is now available
[2021/11/04 09:02:41] [debug] [upstream] KA connection #32 to iamcredentials.googleapis.com:443 is now available
[2021/11/04 09:02:41] [ info] [output:bigquery:bigquery_service.my_srv.my_pkg] Retrieved Google service account OAuth token via Identity Federation
[2021/11/04 09:02:41] [debug] [router] match rule tail.0:bigquery.0
[2021/11/04 09:02:41] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2021/11/04 09:02:41] [debug] [socket] could not validate socket status for #30 (don't worry)
```

**Comment by zhenyami** [comment]
### Valgrind
```
sudo valgrind --track-origins=yes --leak-check=full /usr/local/bin/fluent-bit -c /etc/fluent-bit/fluent-bit.conf
==28462== Memcheck, a memory error detector
==28462== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==28462== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==28462== Command: /usr/local/bin/fluent-bit -c /etc/fluent-bit/fluent-bit.conf
==28462==
Fluent Bit v1.9.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/01/11 07:40:43] [ info] Configuration:
[2022/01/11 07:40:43] [ info]  flush time     | 5.000000 seconds
[2022/01/11 07:40:43] [ info]  grace          | 5 seconds
[2022/01/11 07:40:43] [ info]  daemon         | 0
[2022/01/11 07:40:43] [ info] ___________
[2022/01/11 07:40:43] [ info]  inputs:
[2022/01/11 07:40:43] [ info]      tail
[2022/01/11 07:40:43] [ info] ___________
[2022/01/11 07:40:43] [ info]  filters:
[2022/01/11 07:40:43] [ info]      grep.0
[2022/01/11 07:40:43] [ info]      modify.1
[2022/01/11 07:40:43] [ info]      lua.2
[2022/01/11 07:40:43] [ info]      lua.3
[2022/01/11 07:40:43] [ info]      lua.4
[2022/01/11 07:40:43] [ info]      lua.5
[2022/01/11 07:40:43] [ info]      lua.6
[2022/01/11 07:40:43] [ info]      lua.7
[2022/01/11 07:40:43] [ info]      lua.8
[2022/01/11 07:40:43] [ info] ___________
[2022/01/11 07:40:43] [ info]  outputs:
[2022/01/11 07:40:43] [ info]      bigquery.0
[2022/01/11 07:40:43] [ info] ___________
[2022/01/11 07:40:43] [ info]  collectors:
==28462== Warning: client switching stacks?  SP change: 0x83e17c8 --> 0xc0e23e0
==28462==          to suppress, use: --max-stackframe=63966232 or greater
==28462== Warning: client switching stacks?  SP change: 0xc0e2388 --> 0x83e17c8
==28462==          to suppress, use: --max-stackframe=63966144 or greater
==28462== Warning: client switching stacks?  SP change: 0x83e17c8 --> 0xc0e2388
==28462==          to suppress, use: --max-stackframe=63966144 or greater
==28462==          further instances of this message will not be shown.
^C[2022/01/11 07:40:55] [engine] caught signal (SIGINT)
[2022/01/11 07:40:55] [ info] [input] pausing tail_app.fluent-bit-load-tests.0
==28462== Thread 2 flb-pipeline:
==28462== Invalid read of size 4
==28462==    at 0x75407E: mk_stop (mk_lib.c:254)
==28462==    by 0x48D747: flb_hs_destroy (flb_hs.c:121)
==28462==    by 0x462AC8: flb_engine_shutdown (flb_engine.c:856)
==28462==    by 0x46287D: flb_engine_start (flb_engine.c:764)
==28462==    by 0x444CC0: flb_lib_worker (flb_lib.c:627)
==28462==    by 0x4E3BE74: start_thread (in /lib64/libpthread-2.17.so)
==28462==    by 0x6142A2C: clone (in /lib64/libc-2.17.so)
==28462==  Address 0x9fcd38c is 396 bytes inside a block of size 720 free'd
==28462==    at 0x4C29CDD: free (vg_replace_malloc.c:530)
==28462==    by 0x75883B: mk_mem_free (mk_memory.h:102)
==28462==    by 0x758BB0: mk_config_free_all (mk_config.c:106)
==28462==    by 0x7673CC: mk_exit_all (monkey.c:218)
==28462==    by 0x753EE9: mk_lib_worker (mk_lib.c:174)
==28462==    by 0x4E3BE74: start_thread (in /lib64/libpthread-2.17.so)
==28462==    by 0x6142A2C: clone (in /lib64/libc-2.17.so)
==28462==  Block was alloc'd at
==28462==    at 0x4C2A975: calloc (vg_replace_malloc.c:711)
==28462==    by 0x766ED6: mk_mem_alloc_z (mk_memory.h:70)
==28462==    by 0x7670C1: mk_server_create (monkey.c:89)
==28462==    by 0x753C21: mk_create (mk_lib.c:61)
==28462==    by 0x48D56A: flb_hs_create (flb_hs.c:73)
==28462==    by 0x462468: flb_engine_start (flb_engine.c:665)
==28462==    by 0x444CC0: flb_lib_worker (flb_lib.c:627)
==28462==    by 0x4E3BE74: start_thread (in /lib64/libpthread-2.17.so)
==28462==    by 0x6142A2C: clone (in /lib64/libc-2.17.so)
==28462==
==28462==
==28462== HEAP SUMMARY:
==28462==     in use at exit: 102,248 bytes in 3,427 blocks
==28462==   total heap usage: 175,869 allocs, 172,442 frees, 19,626,622 bytes allocated
==28462==
==28462== Thread 1:
==28462== 56 bytes in 1 blocks are definitely lost in loss record 621 of 689
==28462==    at 0x4C2A975: calloc (vg_replace_malloc.c:711)
==28462==    by 0x7620A3: mk_mem_alloc_z (mk_memory.h:70)
==28462==    by 0x762214: thread_get_libco_params (mk_http_thread.c:60)
==28462==    by 0x7623EC: thread_params_set (mk_http_thread.c:168)
==28462==    by 0x7625C6: mk_http_thread_create (mk_http_thread.c:226)
==28462==    by 0x75EA18: mk_http_init (mk_http.c:748)
==28462==    by 0x75D8F1: mk_http_request_prepare (mk_http.c:232)
==28462==    by 0x760650: mk_http_sched_read (mk_http.c:1576)
==28462==    by 0x75C546: mk_sched_event_read (mk_scheduler.c:693)
==28462==    by 0x764C89: mk_server_worker_loop (mk_server.c:523)
==28462==    by 0x75BF19: mk_sched_launch_worker_loop (mk_scheduler.c:416)
==28462==    by 0x4E3BE74: start_thread (in /lib64/libpthread-2.17.so)
==28462==
==28462== LEAK SUMMARY:
==28462==    definitely lost: 56 bytes in 1 blocks
==28462==    indirectly lost: 0 bytes in 0 blocks
==28462==      possibly lost: 0 bytes in 0 blocks
==28462==    still reachable: 102,192 bytes in 3,426 blocks
==28462==         suppressed: 0 bytes in 0 blocks
==28462== Reachable blocks (those to which a pointer was found) are not shown.
==28462== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==28462==
==28462== For counts of detected and suppressed errors, rerun with: -v
==28462== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
```

**Comment by edsiper** [comment]
thank you!

**Pull request merged**
