### PR TITLE
plugin: in_proc_metrics

### PR DESCRIPTION
**Pull request by pwhelan**
Add a new plugin which logs the metrics for a single process.

----

**Testing**

- [x] Example configuration file for the change
- [x] Debug log output from testing the change

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [x] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by pwhelan** [comment]
Here is a valgrind log where I opened and closed some instances of htop.

[valgrind.log](https://github.com/fluent/fluent-bit/files/7198876/valgrind.log)

**Comment by pwhelan** [comment]
Here is a simple configuration file that shows statistics from all the htop processes that are running:

```ini
[INPUT]
    Name    proc_metrics
    Tag        metrics
    Process htop

[OUTPUT]
    Name stdout
    Match metrics
```

**Comment by pwhelan** [comment]
Here is a log of fluent-bit running with verbose logging:

[fluent-bit.log](https://github.com/fluent/fluent-bit/files/7203452/fluent-bit.log)

**Comment by edsiper** [comment]
@patrick-stephens are you familiar with any of the projects mentioned above ?

**Comment by patrick-stephens** [comment]
The https://github.com/ncabatoff/process-exporter is the one I've generally seen people use and briefly experimented with but am not an expert in I'm afraid.

I'd also watch out for container/kubernetes issues with trying to mount `/proc` as well if that's the approach you're taking. How is this intended to function in a container world? Are we trying to retrieve metrics about processes on the host, pod or just inside the container here?

The docs I think need to cover what you need to do to get it working in Kubernetes and a standalone container. Particularly with security constraints, how do we enable the capability to do it or at least flag up it may not work without extra effort.

We probably need to follow the approach Kubernetes is taking there as well: https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/
I'm not sure how stable this is but there are various guides on what the `kubelet` offers for metrics as well as the other components.

**Comment by pwhelan** [comment]
this seems to have little to no chance of getting in and already seems to have drifted considerably. closing it for now.

**Pull request closed without merging**
