### PR TITLE
filter_lua: add new option to convert integer

### LINKED ISSUE #641: sometimes filter_lua converts double -> integer
When filter_lua converts Lua table to messagepack, some double values are converted to integer.

nop.lua
```lua
function nop(tag, timestamp, record)
     new_record = record
     return 1, timestamp, new_record
end
```

Configuration file.
Dummy generates 3 double values.
```python
[INPUT]
    Name dummy
    Tag  dummy

    dummy {"double1":0.9, "double2":1.0, "double3":1.1}

[FILTER]
    Name   lua
    Match  *
    script ./nop.lua
    call   nop

[OUTPUT]
    Name  stdout
    Match *
```

Output is 
```
[taka@localhost build]$ bin/fluent-bit -c dummy.conf 
Fluent-Bit v0.14.0
Copyright (C) Treasure Data

[2018/06/15 20:45:21] [ info] [engine] started (pid=15286)
[0] dummy: [1529063122.001215457, {"double2"=>1, "double1"=>0.900000, "double3"=>1.100000}]
[1] dummy: [1529063123.000427484, {"double2"=>1, "double1"=>0.900000, "double3"=>1.100000}]
[2] dummy: [1529063124.000121831, {"double2"=>1, "double1"=>0.900000, "double3"=>1.100000}]
[3] dummy: [1529063125.002114772, {"double2"=>1, "double1"=>0.900000, "double3"=>1.100000}]
```

In this case `double2` is converted integer.

This conversion is here.
https://github.com/fluent/fluent-bit/blob/master/plugins/filter_lua/lua.c#L179

### PR DESCRIPTION
**Pull request by nokute78**
This is an another patch to fix #641 

With this patch
* default : lua_TNUMBER is converted to `double`
* option (c_int_key) : lua_TNUMBER is converted to `int64`

## example 
lua.conf:
```python
[INPUT]
    Name cpu

[FILTER]
    Name lua
    Match *
    call  cb_append
    script append.lua
    c_int_key cpu_p cpu0.p_system lua_int

[OUTPUT]
    Name stdout
```

append.lua:
```lua
function cb_append(tag, timestamp, record)
   new_record = record
   new_record["lua_double"] = 12345
   new_record["lua_int"]    = 12345
   return 1, timestamp, new_record
end
```

`cpu_p` and `cpu0.p_system` and `lua_int` (generated in lua) are converted to integer.
Others are double.
```sh
$ bin/fluent-bit -c lua.conf 
Fluent-Bit v0.14.0
Copyright (C) Treasure Data

[2018/08/26 20:30:27] [ info] [engine] started (pid=22075)
[0] cpu.0: [1535283028.002336740, {"lua_double"=>12345.000000, "system_p"=>1.000000, "cpu0.p_cpu"=>2.000000, "cpu0.p_user"=>1.000000, "cpu_p"=>2, "cpu0.p_system"=>1, "lua_int"=>12345, "user_p"=>1.000000}]
[1] cpu.0: [1535283029.002326011, {"lua_double"=>12345.000000, "system_p"=>1.000000, "cpu0.p_cpu"=>8.000000, "cpu0.p_user"=>7.000000, "cpu_p"=>8, "cpu0.p_system"=>1, "lua_int"=>12345, "user_p"=>7.000000}]
[2] cpu.0: [1535283030.002673387, {"lua_double"=>12345.000000, "system_p"=>2.000000, "cpu0.p_cpu"=>8.000000, "cpu0.p_user"=>6.000000, "cpu_p"=>8, "cpu0.p_system"=>2, "lua_int"=>12345, "user_p"=>6.000000}]
[3] cpu.0: [1535283031.011747121, {"lua_double"=>12345.000000, "system_p"=>1.000000, "cpu0.p_cpu"=>7.000000, "cpu0.p_user"=>6.000000, "cpu_p"=>7, "cpu0.p_system"=>1, "lua_int"=>12345, "user_p"=>6.000000}]
^C[engine] caught signal (SIGINT)
[2018/08/26 20:30:32] [ info] [input] pausing cpu.0

```

### CODE REVIEW

**Comment by nokute78** [comment]
Note: CI failure may be caused by authentication error.

It reported `Fix WWDRCA Certificate`.

**Comment by edsiper** [comment]
@nokute78 

thanks for the contribution.

It looks good. what about also to use the same mechanism you wrote for  Parser types ?, I mean use the same names and nomenclature (and setup) ?

**Comment by nokute78** [comment]
@edsiper Thank you for reviewing.

> to use the same mechanism you wrote for Parser types ?

I tried to do first , but the use case of filter_lua is limited, so I changed the mechanism.

Types of parser supports string(default), integer, bool, float, and hex.
I think it is mostly used to convert string to another types. (e.g. "123" -> 123, "13.5" -> 13.5)

In filter_lua case, we can mostly convert data types using lua function like "tonumber" and "string.format".

However, lua script can't convert LUA_TNUMBER to integer, so I added an option to support this conversion only.

**Comment by edsiper** [comment]
got it, what about to rename c_int_key to type_int ?

**Comment by nokute78** [comment]
@edsiper 
First, I prefer "*_key" to specify key name. (e.g. In fluentd, `auto_increment_key` of in_dummy, `path_key` of in_tail)

Second, We may need to take lua->c type conversion into account.
If so, it is better to include language name explicitly. (e.g. Lua_TYPENAME_key. )
Are there any cases?

In short, I think it is proper to rename "type_int_key" or "c_type_int_key".

**Comment by edsiper** [comment]
I vouch for type_int_key

**Comment by edsiper** [comment]
@nokute78 what are your thoughts on moving to normal Lua (no LuaJIT) ?

**Comment by nokute78** [comment]
> type_int_key

OK. I will rename a few days later.

> Lua vs Luajit

I’m not familiar with these differences.
Luajit is faster, but less compatibility, because jit needs to generate native machine code.
http://luajit.org/install.html

**Comment by nokute78** [comment]
I renamed c_int_key -> type_int_key.

**Comment by edsiper** [comment]
thanks. would you please send a documentation update for filter_lua ?

**Comment by nokute78** [comment]
I updated documentation.

https://github.com/fluent/fluent-bit-docs/pull/94

**Comment by edsiper** [comment]
thanks

**Pull request merged**
