### PR TITLE
in_head: add lines mode like $ head -n

### LINKED ISSUE #294: input "head" fails to upload to elasticsearch due to special characters
For the input type of "head", uploading to the elasticsearch fails because: the corresponding value field (precisely, head_config->buf) contains new line characters which are not accepted as valid json by the elasticsearch server (error: [debug] [out_es] HTTP Status=500). The solution is to escape special characters, e.g. `\x0a` --> `\\x0a`.

### PR DESCRIPTION
**Pull request by nokute78**
I added a new mode "lines" of in_head to fix #294.
It works like "$ head -n"

## Configuration file

The new property "lines" is needed.

```python
[INPUT]
    Name head
    File /proc/meminfo
    Lines 5
    Tag  head.meminfo

[OUTPUT]
    Name stdout
    Match *
```

## output

in_head reads 5 (=property "Lines 5") lines each iteration.

```shell
$ bin/fluent-bit -c head.conf 
Fluent-Bit v0.12.0
Copyright (C) Treasure Data

[2017/06/15 22:54:57] [ info] [engine] started
[0] head.meminfo: [1497534898.001409355, {"head"=>"MemTotal:        3920464 kB"}]
[1] head.meminfo: [1497534898.001422557, {"head"=>"MemFree:          373088 kB"}]
[2] head.meminfo: [1497534898.001423877, {"head"=>"Buffers:          184648 kB"}]
[3] head.meminfo: [1497534898.001425171, {"head"=>"Cached:          2675856 kB"}]
[4] head.meminfo: [1497534898.001426330, {"head"=>"SwapCached:            8 kB"}]
[5] head.meminfo: [1497534899.001334908, {"head"=>"MemTotal:        3920464 kB"}]
[6] head.meminfo: [1497534899.001349907, {"head"=>"MemFree:          373088 kB"}]
[7] head.meminfo: [1497534899.001351191, {"head"=>"Buffers:          184648 kB"}]
[8] head.meminfo: [1497534899.001352470, {"head"=>"Cached:          2675856 kB"}]
[9] head.meminfo: [1497534899.001353554, {"head"=>"SwapCached:            8 kB"}]
[10] head.meminfo: [1497534900.001344325, {"head"=>"MemTotal:        3920464 kB"}]
[11] head.meminfo: [1497534900.001351162, {"head"=>"MemFree:          373088 kB"}]
[12] head.meminfo: [1497534900.001352476, {"head"=>"Buffers:          184648 kB"}]
[13] head.meminfo: [1497534900.001353780, {"head"=>"Cached:          2675856 kB"}]
[14] head.meminfo: [1497534900.001355095, {"head"=>"SwapCached:            8 kB"}]
[15] head.meminfo: [1497534901.001354753, {"head"=>"MemTotal:        3920464 kB"}]
[16] head.meminfo: [1497534901.001361761, {"head"=>"MemFree:          373112 kB"}]
[17] head.meminfo: [1497534901.001363015, {"head"=>"Buffers:          184648 kB"}]
[18] head.meminfo: [1497534901.001364500, {"head"=>"Cached:          2675856 kB"}]
[19] head.meminfo: [1497534901.001365779, {"head"=>"SwapCached:            8 kB"}]
```

### CODE REVIEW

**Comment by edsiper** [comment]
If I am not wrong using this feature creates a behavior change, because it limit the number of lines but also split every line as a separate record, not sure about the last one.

**Comment by nokute78** [comment]
Yes. If user sets "lines", in_head creates records and each record contains one line.
If not set, in_head creates single record in the same manner as before.

Is it convenient to create single record in the case of lines mode ?

**Comment by edsiper** [comment]
what about to collect N lines but without split them ?

**Comment by nokute78** [comment]
like this?

{"line1":"aaa", "line2":"bbb","line3":"ccc", ... "lineN":"end"}

**Comment by edsiper** [comment]
like it works now but setting a number of lines instead of a maximum number of bytes (buf_size=256), including the breaklines, that's fine

**Comment by edsiper** [comment]
Example: real content of /proc/meminfo:

```
$ cat /proc/meminfo 
MemTotal:        8079652 kB
MemFree:          189336 kB
MemAvailable:    1257464 kB
Buffers:          147728 kB
Cached:          2717224 kB
SwapCached:         1224 kB
Active:          5080492 kB
Inactive:        2308712 kB
Active(anon):    4428484 kB
Inactive(anon):  1726020 kB
Active(file):     652008 kB
Inactive(file):   582692 kB
Unevictable:         400 kB
Mlocked:             400 kB
SwapTotal:        130044 kB
SwapFree:          85524 kB
Dirty:               404 kB
Writeback:             0 kB
AnonPages:       4477692 kB
Mapped:          1516492 kB
Shmem:           1630296 kB
Slab:             269692 kB
SReclaimable:     115760 kB
SUnreclaim:       153932 kB
KernelStack:       29180 kB
PageTables:       107180 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     4169868 kB
Committed_AS:   22599304 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:    706560 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      365208 kB
DirectMap2M:     7929856 kB
DirectMap1G:           0 kB
```

Using lines feature:

```
$ fluent-bit -i head -p file=/proc/meminfo -p lines=3 -o stdout
[0] head.0: [1497563040.000210292, {"head"=>"MemTotal:        8079652 kB
MemFree:          145828 kB
MemAvailable:    1211448 kB
"}]
```

**Comment by nokute78** [comment]
Do you mean 
{"lines":"aaa bbb ccc ... end"} at lines mode?

**Comment by edsiper** [comment]
I mean {"lines":"aaa\nbbb\nccc\n ... end"}

**Comment by nokute78** [comment]
I see, I will modify the PR.

and I will send another PR to add a mode to send
 {"line1":"aaa", "line2":"bbb","line3":"ccc", ... "lineN":"end"}

**Comment by nokute78** [comment]
I updated.

## lines mode

The output is {"head"->"aaa\nbbb\nccc\n"}.

### Configuration file and output

```python
[INPUT]
    Name head
    File /proc/meminfo
    Lines 5
    Tag  head.meminfo

[OUTPUT]
    Name stdout
    Match *
```

```shell
$ bin/fluent-bit -c a.conf 
Fluent-Bit v0.12.0
Copyright (C) Treasure Data

[2017/06/16 22:25:14] [ info] [engine] started
[0] head.meminfo: [1497619515.000834236, {"head"=>"MemTotal:        3920464 kB
MemFree:          350012 kB
Buffers:          187168 kB
Cached:          2680392 kB
SwapCached:            8 kB
"}]
```

## split line mode

The output is {"line0"->"aaa", "line1"->"bbb", "line2"->"ccc"}.

### Configuration file and output

```python
[INPUT]
    Name head
    File /proc/meminfo
    Lines 5
    Split_line true
    Tag  head.meminfo


[OUTPUT]
    Name stdout
    Match *
```

```shell
$ bin/fluent-bit -c a.conf 
Fluent-Bit v0.12.0
Copyright (C) Treasure Data

[2017/06/16 22:26:51] [ info] [engine] started
[0] head.meminfo: [1497619612.002340693, {"line0"=>"MemTotal:        3920464 kB", "line1"=>"MemFree:          350824 kB", "line2"=>"Buffers:          187180 kB", "line3"=>"Cached:          2680408 kB", "line4"=>"SwapCached:            8 kB"}]
```

This mode is helpful to watch specific line with record_modifier plugin.
e.g. tracing "SwapCached" line only.
```python
[INPUT]
    Name head
    File /proc/meminfo
    Lines 5
    Split_line true
    Tag  head.meminfo


[OUTPUT]
    Name stdout
    Match *

[FILTER]
    Name record_modifier
    Match *
    Whitelist_key line4
```

```shell
$ bin/fluent-bit -c a.conf 
Fluent-Bit v0.12.0
Copyright (C) Treasure Data

[2017/06/16 22:29:18] [ info] [engine] started
[0] head.meminfo: [1497619759.000680613, {"line4"=>"SwapCached:            8 kB"}]
[1] head.meminfo: [1497619760.001947305, {"line4"=>"SwapCached:            8 kB"}]
[2] head.meminfo: [1497619761.002475753, {"line4"=>"SwapCached:            8 kB"}]
[3] head.meminfo: [1497619762.002155756, {"line4"=>"SwapCached:            8 kB"}]
```

**Comment by edsiper** [comment]
Looks like the last commit does a merge touching other things. Please do a clean pull of latest from git master and apply your commits on top of it.

**Comment by nokute78** [comment]
Oops, it's my mistake.
I tried to fix it. Could you check it again?

**Comment by edsiper** [comment]
it's still there:

https://github.com/fluent/fluent-bit/commit/3c1d3d33e71b36a08ea030c05d4924a0cbc2052c

**Comment by nokute78** [comment]
Hmm, it is to fix conflicting.

github reports conflicting without that commit.
(conflicting is caused another PR #300)
The changed file number is 3, and it doesn't include another files.

well, It may be faster that closing this PR and send another PR.

**Comment by nokute78** [comment]
I rebased. How about this?

**Comment by edsiper** [comment]
now it looks fine, thanks for the changes.

**Pull request merged**
