### PR TITLE
Add new parser: ltsv

### PR DESCRIPTION
**Pull request by manuelluis**

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for this contribution!

would you please attach to this ticket some configuration examples and log files to be parsed ?

**Comment by manuelluis** [comment]
The description of the ltsv format from http://ltsv.org/:

Labeled Tab-separated Values (LTSV) format is a variant of Tab-separated Values (TSV). Each record in a LTSV file is represented as a single line. Each field is separated by TAB and has a label and a value. The label and the value have been separated by ':'. 

A interesting example how to use this format is in the apache accesslog.
  
Config this in httpd.conf

```
LogFormat "host:%h\tident:%l\tuser:%u\ttime:%t\treq:%r\tstatus:%>s\tsize:%b\treferer:%{Referer}i\tua:%{User-Agent}i" combined_ltsv
CustomLog "logs/access_log" combined_ltsv
```

The parser.conf:

```
[PARSER]
    Name        access_log_ltsv
    Format      ltsv
    Time_Key    time
    Time_Format [%d/%b/%Y:%H:%M:%S %z]
    Types       status:integer size:integer
```

the acces_log file:

```
host:127.0.0.1  ident:- user:-  time:[10/Jul/2018:13:27:05 +0200]       req:GET / HTTP/1.1      status:200      size:16218      referer:http://127.0.0.1/       ua:Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
host:127.0.0.1  ident:- user:-  time:[10/Jul/2018:13:27:05 +0200]       req:GET /assets/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1        status:200      size:121200     referer:http://127.0.0.1/       ua:Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
host:127.0.0.1  ident:- user:-  time:[10/Jul/2018:13:27:05 +0200]       req:GET /assets/css/headers/header-v6.css HTTP/1.1      status:200      size:37706      referer:http://127.0.0.1/       ua:Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
host:127.0.0.1  ident:- user:-  time:[10/Jul/2018:13:27:05 +0200]       req:GET /assets/css/style.css HTTP/1.1  status:200      size:1279       referer:http://127.0.0.1/       ua:Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
```

```
$ bin/fluent-bit -R parser.conf -i tail -p path=access_log -p parser=access_log_ltsv -o stdout
Fluent-Bit v0.14.0
Copyright (C) Treasure Data

[2018/07/10 13:37:50] [ info] [engine] started (pid=18028)
[0] tail.0: [1531222025.000000000, {"host"=>"127.0.0.1", "ident"=>"-", "user"=>"-", "req"=>"GET / HTTP/1.1", "status"=>200, "size"=>16218, "referer"=>"http://127.0.0.1/", "ua"=>"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"}]
[1] tail.0: [1531222025.000000000, {"host"=>"127.0.0.1", "ident"=>"-", "user"=>"-", "req"=>"GET /assets/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1", "status"=>200, "size"=>121200, "referer"=>"http://127.0.0.1/", "ua"=>"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"}]
[2] tail.0: [1531222025.000000000, {"host"=>"127.0.0.1", "ident"=>"-", "user"=>"-", "req"=>"GET /assets/css/headers/header-v6.css HTTP/1.1", "status"=>200, "size"=>37706, "referer"=>"http://127.0.0.1/", "ua"=>"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"}]
[3] tail.0: [1531222025.000000000, {"host"=>"127.0.0.1", "ident"=>"-", "user"=>"-", "req"=>"GET /assets/css/style.css HTTP/1.1", "status"=>200, "size"=>1279, "referer"=>"http://127.0.0.1/", "ua"=>"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"}]
```

**Comment by manuelluis** [comment]
Test to see the parser skip malformed kv entries:

```
$ echo -e "key1:value1" >> test.txt 
$ echo -e "key1:value1\tkey2:value2" >> test.txt 
$ echo -e "key1:value1\tkey2:value2\tkey3:value3" >> test.txt 
$ echo -e "key1:value1\tkey2:value2\tkey3:value3\tkey4:" >> test.txt 
$ echo -e "key1:value1\tkey2:value2\tkey3:value3\tkey4:value4\tkey5:  value5  " >> test.txt 
$ echo -e "key1:value1\tkey2:value2\tkey3:value3\tkey4:value4\tkey5:::value5  " >> test.txt 
$ echo -e "key1:value1\tkey2:value2\tkey3:value3\tkey4:value4\t\tkey5:value5" >> test.txt 
$ echo -e "key1:value1\tkey2:value2\tkey3:value3\tkey4:value4\tkey5:\tvalue5" >> test.txt
$ cat test.txt 
key1:value1
key1:value1     key2:value2
key1:value1     key2:value2     key3:value3
key1:value1     key2:value2     key3:value3     key4:
key1:value1     key2:value2     key3:value3     key4:value4     key5:  value5
key1:value1     key2:value2     key3:value3     key4:value4     key5:::value5
key1:value1     key2:value2     key3:value3     key4:value4             key5:value5
key1:value1     key2:value2     key3:value3     key4:value4     key5:   value5
```


The  parser.conf  file:                         
```
[PARSER]
    Name        ltsv
    Format      ltsv
```

```
$ bin/fluent-bit -R parser.conf -i tail -p path=test.txt -p parser=ltsv -o stdout                               
Fluent-Bit v0.14.0
Copyright (C) Treasure Data

[2018/07/10 14:04:35] [ info] [engine] started (pid=19204)
[0] tail.0: [1531224275.000000000, {"key1"=>"value1"}]
[1] tail.0: [1531224275.000000000, {"key1"=>"value1", "key2"=>"value2"}]
[2] tail.0: [1531224275.000000000, {"key1"=>"value1", "key2"=>"value2", "key3"=>"value3"}]
[3] tail.0: [1531224275.000000000, {"key1"=>"value1", "key2"=>"value2", "key3"=>"value3"}]
[4] tail.0: [1531224275.000000000, {"key1"=>"value1", "key2"=>"value2", "key3"=>"value3", "key4"=>"value4", "key5"=>"  value5  "}]
[5] tail.0: [1531224275.000000000, {"key1"=>"value1", "key2"=>"value2", "key3"=>"value3", "key4"=>"value4", "key5"=>"::value5  "}]
[6] tail.0: [1531224275.000000000, {"key1"=>"value1", "key2"=>"value2", "key3"=>"value3", "key4"=>"value4"}]
[7] tail.0: [1531224275.000000000, {"key1"=>"value1", "key2"=>"value2", "key3"=>"value3", "key4"=>"value4"}]
^C[engine] caught signal (SIGINT)
[2018/07/10 14:04:46] [ info] [input] pausing tail.0
```

**Comment by manuelluis** [comment]
With the commit that allow empty values:

```
$ echo -e "key1:value1" >> test.txt 
$ echo -e "key1:value1\tkey2:value2" >> test.txt 
$ echo -e "key1:value1\tkey2:value2\tkey3:value3" >> test.txt 
$ echo -e "key1:value1\tkey2:value2\tkey3:value3\tkey4:" >> test.txt 
$ echo -e "key1:value1\tkey2:value2\tkey3:value3\tkey4:value4\tkey5:  value5  " >> test.txt   
$ echo -e "key1:value1\tkey2:value2\tkey3:value3\tkey4:value4\tkey5:::value5  " >> test.txt 
$ echo -e "key1:value1\tkey2:value2\tkey3:value3\tkey4:value4\t\tkey5:value5" >> test.txt 
$ echo -e "key1:value1\tkey2:value2\tkey3:value3\tkey4:value4\tkey5:\tvalue5" >> test.txt
$ echo -e "key1:value1\tkey2:\tkey3:\tkey4:\tkey5:" >> test.txt
$ cat test.txt
key1:value1
key1:value1     key2:value2
key1:value1     key2:value2     key3:value3
key1:value1     key2:value2     key3:value3     key4:
key1:value1     key2:value2     key3:value3     key4:value4     key5:  value5
key1:value1     key2:value2     key3:value3     key4:value4     key5:::value5
key1:value1     key2:value2     key3:value3     key4:value4             key5:value5
key1:value1     key2:value2     key3:value3     key4:value4     key5:   value5
key1:value1     key2:   key3:   key4:   key5:
```
```
$ bin/fluent-bit -R parser.conf -i tail -p path=test.txt -p parser=ltsv -o stdout
Fluent-Bit v0.14.0
Copyright (C) Treasure Data

[2018/07/11 22:07:12] [ info] [engine] started (pid=1905)
[0] tail.0: [1531339632.000000000, {"key1"=>"value1"}]
[1] tail.0: [1531339632.000000000, {"key1"=>"value1", "key2"=>"value2"}]
[2] tail.0: [1531339632.000000000, {"key1"=>"value1", "key2"=>"value2", "key3"=>"value3"}]
[3] tail.0: [1531339632.000000000, {"key1"=>"value1", "key2"=>"value2", "key3"=>"value3", "key4"=>""}]
[4] tail.0: [1531339632.000000000, {"key1"=>"value1", "key2"=>"value2", "key3"=>"value3", "key4"=>"value4", "key5"=>"  value5  "}]
[5] tail.0: [1531339632.000000000, {"key1"=>"value1", "key2"=>"value2", "key3"=>"value3", "key4"=>"value4", "key5"=>"::value5  "}]
[6] tail.0: [1531339632.000000000, {"key1"=>"value1", "key2"=>"value2", "key3"=>"value3", "key4"=>"value4"}]
[7] tail.0: [1531339632.000000000, {"key1"=>"value1", "key2"=>"value2", "key3"=>"value3", "key4"=>"value4", "key5"=>""}]
[8] tail.0: [1531339632.000000000, {"key1"=>"value1", "key2"=>"", "key3"=>"", "key4"=>"", "key5"=>""}]
```

**Comment by edsiper** [comment]
thanks!

**Pull request merged**
