### PR TITLE
New output plugin syslog

### PR DESCRIPTION
**Pull request by manuelluis**
Syslog output module

| Key | Description | default |
| --- | --- | --- |
| Match | Pattern to match which tags of logs to be outputted by this plugin | |
| Host | IP address or hostname of the target syslog server | 127.0.0.1 |
| Port | The port that your syslog server is listening on | 514 |
| Mode | The protocol to use ( udp, tcp or tls) | udp |
| syslog_format | Syslog format:  rfc3164 or rfc5424 | rfc5424 |
| syslog_maxsize | Max message size  | 2048 for rfc5424 or 1024 for rfc3164 |
| syslog_severity_key | key to use as the syslog severity | 6 (info) |
| syslog_facility_key | key to use as the syslog facility | 1 (user) |
| syslog_hostname_key | key to use as the name of the host | |
| syslog_appname_key | key to use as the application name | |
| syslog_procid_key | key to use as the process identifier | |
| syslog_msgid_key | key to use as message id | |
| syslog_message_key |  key to use as syslog message | |
| syslog_sd_key | key to a syslog structured data, can be set multiple times it must be a map | |

### CODE REVIEW

**Comment by manuelluis** [comment]
Examples:

```
[INPUT]
	Name   dummy
	Tag    log.test
	Dummy  {"log":"test message", "hostname":"localhost", "severity":"info", "facility":"user", "app":"appname", "info=]1": {"key=1":"[1]", "key2":2}, "info2": {"key3":3, "key4":4}}

[OUTPUT]
	Name   syslog
	Match  *

	Host   127.0.0.1
	Port   514
	Mode   tcp

	Syslog_Format        rfc5424
	Syslog_Severity_key  serverity
	Syslog_Facility_key  factility
	Syslog_Hostname_key  hostname
	Syslog_Appname_key   app
	Syslog_Procid_key    pid
	Syslog_Message_key   log
	Syslog_sd_key        info=]1
	Syslog_sd_key        info2
```

Will send:
```
<14>1 2019-09-29T22:43:06.000161Z localhost appname - - [info__1 key_1="[1\]" key2="2"][info2 key3="3" key4="4"] test message
```

For send the journal messages:

```
[INPUT]
	Name   systemd
	Tag    host.*

[OUTPUT]
	Name   syslog
	Match  *

	Host   127.0.0.1
	Port   5140
	Mode   tcp

	Syslog_Format        rfc5424
	Syslog_Severity_key  PRIORITY
	Syslog_Facility_key  SYSLOG_FACILITY
	Syslog_Hostname_key  _HOSTNAME
	Syslog_Appname_key   SYSLOG_IDENTIFIER
	Syslog_Procid_key    _PID
	Syslog_Message_key   MESSAGE
```

**Comment by dtimm** [comment]
This seems like a really nice improvement over the current state of things. The documentation is a little lacking around the various keys, particularly structured data keys. Are you planning to update https://github.com/fluent/fluent-bit-docs/ as well?

**Comment by SuvratAgrawal** [comment]
@manuelluis  @edsiper ,Is out_syslog available with official fluentbit release. I am not able to find any documentation about it.

**Comment by wrenashe** [comment]
Any plan to update the document about the update on syslog output plugin?

**Pull request merged**
