### PR TITLE
in_collectd/out_statsd: set the FLB_INPUT_NET_SERVER flag to fix their schema.

### PR DESCRIPTION
**Pull request by pwhelan**
# Summary

Add the FLB_INPUT_NET_SERVER to the `in_collectd` and `out_statsd` plugins, which do use UDP instead of TCP, so the schema includes the network properties for them. 

The `FLB_IO_TLS` flag should not and is not set which should avoid most special cased code. If not we need another way to express they use network properties so the correct schema and help options can be output for them.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by nicolasparada** [comment]
Typo in PR title and description: collectd.

**Comment by pwhelan** [comment]
> Typo in PR title and description: collectd.

It appears to have been an auto and complete failure.

**Comment by edsiper** [comment]
Please split the commits per plugin/component

**Comment by pwhelan** [comment]
> > Typo in PR title and description: collectd.
> 
> It appears to have been an auto and complete failure.

@edsiper done!

I have rewritten the git history so each modification is it's own commit.

**Comment by edsiper** [comment]
thank you!

**Pull request merged**
