### PR TITLE
Revert: support native cross-compilation for ARM64

### PR DESCRIPTION
**Pull request by cveilleux**
The reverted commit breaks proper cross-compilation.

See https://github.com/fluent/fluent-bit/issues/4204

As per @ptsneves comment:

> The commit should be reverted because it is wrong to add extra flags that should be part of the AUTOCONF_HOST_OPT. Reverting the change will allow for most of the issues to go away 

https://github.com/fluent/fluent-bit/issues/4204#issuecomment-1016642446

It seems that the commit attempts to *enable* cross-compilation for arm64, but took the wrong approach of hard-coding the HOST and path to CMAKE_C_COMPILER.

As demonstrated by a normal bitbake build, this is in no way required to get proper cross-compilation to work.

See also 1f3ccd4334a2f9e9babd53a2715d84b5a8042e06 which initially added support for `AUTOCONF_HOST_OPT` and is the appropriate way to add cross-compilation params.

### CODE REVIEW

**Comment by edsiper** [comment]
Asking original author and reviewers about this first: @sarandia @niedbalski

**Comment by sarandia** [comment]
lgtm

**Comment by ptsneves** [comment]
any chance of merging this?

**Comment by patrick-stephens** [comment]
@niedbalski I think this is ok to merge - do you agree?

**Review by niedbalski — APPROVED** [review]
LGTM

**Comment by patrick-stephens** [comment]
Should we backport this to 1.8?

**Pull request merged**
