### PR TITLE
out_es: add option to generate uuid

### PR DESCRIPTION
**Pull request by jsravn**
So that retries won't cause duplicate records in ES.

Adds option 'Generate_ID' that when set to yes generates a unique ID per record.

For https://github.com/fluent/fluent-bit/issues/423

### CODE REVIEW

**Comment by edsiper** [comment]
thank for the PR.

Reviewing the behavior I see the following error on Elasticsearch:

```json
{"took":6,"errors":true,"items":[{"index":{"_index":"fluent-bit","_type":"flb_type","_id":"AV_wbyo0vPvaWZHE7oaI","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse [rand_value]","caused_by":{"type":"json_parse_exception","reason":"Numeric value (12589956062658480428) out of range of long (-9223372036854775808 - 9223372036854775807)\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@6d52379d; line: 1, column: 74]"}}}}]}
```

the generated number is out of range.

**Comment by jsravn** [comment]
@edsiper Hmm that's strange. It's a string (of 32 hex characters) for `_id` field. Your error is complaining about `rand_value`? Is that something else?

**Comment by jsravn** [comment]
Note I've tested this in my own cluster and it seems to work well. I was a little concerned about murmur3ing every message, but murmur3 throughput is around 5Gi/s so it should be okay.

**Comment by jsravn** [comment]
* Changed it to output a proper uuid  (8-4-4-4-12).

**Comment by edsiper** [comment]
ah you are right, it was my random generated sample.

**Comment by edsiper** [comment]
thanks!

**Pull request merged**
