### PR TITLE
Retrieve Kubernetes pod IP address if it is set in status.podIP

### PR DESCRIPTION
**Pull request by kgtw**
This PR exposes the Kubernetes pod IP address if it has been set.

Fixes: https://github.com/fluent/fluent-bit/issues/2301

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ N/A ] Example configuration file for the change
- [ N/A ] Debug log output from testing the change

- [ N/A ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [ N/A ] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by kgtw** [comment]
@edsiper @fujimotos @koleini any chance of getting a review on this?

**Comment by kgtw** [comment]
@edsiper @fujimotos @koleini ?

**Comment by kgtw** [comment]
@edsiper @fujimotos @koleini any chance of getting a review on this?

**Comment by artemlive** [comment]
@kgtw thanks for such useful improvement, I hope it will be reviewed and merged.

**Comment by syndbg** [comment]
Can we get some response about this PR?  It's something really needed for fluent-bit users.

Promtrail already supports it and it's a shame if we're forced to migrate "just cause" we can't have a pod IP.

**Comment by askuy** [comment]
@kgtw thanks for such useful improvement, I hope it will be reviewed and merged.

**Comment by sevennt** [comment]
@edsiper how about this PR?

**Comment by patrick-stephens** [comment]
Can you rebase to force the various checks to run? I'm guessing it was Github issues at the time.

**Comment by dan-leanix** [comment]
> Can you rebase to force the various checks to run? I'm guessing it was Github issues at the time.

@kgtw FYI.

**Comment by dan-leanix** [comment]
@patrick-stephens I guess someone from the reviewers' list needs to approve the PR first before the various checks can run. At least that is what I read from the Action itself.

-> https://github.com/fluent/fluent-bit/actions/runs/2568072268

image

**Comment by patrick-stephens** [comment]
@dan-leanix yeah it's to help with security and prevent spurious PRs causing issues as they will run on the Fluent resources. Plus quite often an initial review will highlight some issues that need resolving immediately anyway so not worth running until those are done.

**Comment by dan-leanix** [comment]
Thanks, @patrick-stephens for the explanation. It makes total sense. 

@kgtw Seems to be that the issue with the tests is that the expected record does not match the actual record. Hence, the expected record is missing the pod_ip.

```
 filter_kubernetes.c:156: Check comparing expected record with actual record... failed
```

**Comment by raxidex** [comment]
Hi @kgtw, would it be possible to finish this PR? Thanks for the effort

**Comment by mrueg** [comment]
@edsiper I know this PR is quite old, but would this be something you'd be up to adding to fluent-bit? It would help a lot with migrating from fluentd.

**Comment by ziyuen** [comment]
Waiting for this PR. We are migrating to fluent-bit

**Comment by kgtw** [comment]
Hi to all who've commented 👋 

If there is anybody who would like to take over, feel free to. I've since moved on to other engineering domains so am no longer active in this space. 

After this PR had no interest from the maintainers within the first two years of it being opened I gave up any hope of it ever being merged. 

I still believe the intent behind this PR holds merit that many would benefit from and hope that the maintainers see from the continued activity within this PR that people are still looking for a solution.

**Comment by edsiper** [comment]
The code looks ok to me, however the unit test seems not to consider a proper input file and just validate the output, I have my doubts. Unit test is pending.

**Pull request merged**
