### PR TITLE
Make out_stackdriver compilable on Windows

### PR DESCRIPTION
**Pull request by fujimotos**
This is a series of patches that bring the stackdriver output plugin compilable
on Windows.

* Add prefix "FLB_STD" to global variables to avoid naming conflicts.
* Define a macro `S_ISLNK` that is nonexistent in MSVC
* Introduce `flb_utils_read_file()` to bring file data into memory portably.

With this, I can confirm `out_stackdriver` is compilable on MSVC.

### CODE REVIEW

**Comment by fujimotos** [comment]
The original issue is #1603.

**Comment by edsiper** [comment]
why mk_file_to_buffer() is not working properly ?

**Comment by fujimotos** [comment]
@edsiper  It's not always present due to the check in [mk_core/CMakeLists.txt#L34](https://github.com/monkey/monkey/blob/master/mk_core/CMakeLists.txt#L44).
At least we do not have it on Windows, so 5997211 comes in.

**Comment by fujimotos** [comment]
Closing this PR for cleaning up old branches.

**Pull request closed without merging**
