### PR TITLE
out_cloudwatch_logs: handle DataAlreadyAcceptedException response

### PR DESCRIPTION
**Pull request by PettitWesley**
Signed-off-by: Wesley Pettit <wppttt@amazon.com>

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by Jell** [comment]
Hitting this issue regularly on our side, and fluent-bit fails to recover after that, this fix would help us a lot

**Comment by PettitWesley** [comment]
@edsiper Can I get a approval & merge on this?

**Comment by PettitWesley** [comment]
@Jell I'd be happy to build you a custom image using the AWS for Fluent Bit build process off of our current stable version or whichever version you are currently using, if that'd help unblock you.

**Comment by PettitWesley** [comment]
Actually @Jell I already built an image with this:

```
144718711470.dkr.ecr.us-west-2.amazonaws.com/1_8_9_alreadyacceptedissue:latest
```

This image can be pulled by an AWS account.

**Comment by Jell** [comment]
tested your image @PettitWesley it did solve our issues! Would be great to get this merged asap

**Review by Jell — APPROVED** [review]
This patch solved the issues we had in production.

**Comment by PettitWesley** [comment]
@agup006  this is an AWS output fix that I can't merge myself since its my PR

**Review by agup006 — APPROVED** [review]

**Comment by agup006** [comment]
I approved based off the successful tests, @PettitWesley are you able to merge now?

**Comment by PettitWesley** [comment]
@agup006 Thanks!!

**Comment by geekofalltrades** [comment]
Will these changes be ported to https://github.com/aws/aws-for-fluent-bit?

**Comment by PettitWesley** [comment]
@geekofalltrades Yes, once we start releasing 1.9.x series into AWS distro. We will do this soon. We do not like to consume new series immediately, so 1.9.3 will be the first 1.9 series release we uptake probably.

**Pull request merged**
