### PR TITLE
Issue 2868: Add Max_Shutdown_Retries configuration parameter for the fluent-bit service. 

### PR DESCRIPTION
**Pull request by epsteina16**
Added new service configuration option Max_Shutdown_Retries to prevent an infinite loop on shutdown. The default is set to 5.

Stopgap for #2868 

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ x] Example configuration file for the change
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  fluent-bit.conf: |-
    [SERVICE]
      Flush                5
      Daemon               off
      Log_Level            debug
      Max_Shutdown_Retries 2

    [INPUT]
      Name              tail
      Path              /var/log/*.log
      Tag               alllogs
      Refresh_Interval  2
      Read_from_Head    On
      DB                /var/log/logs.db

    [OUTPUT]
      Name              stdout
      Match             *

- [ x] Debug log output from testing the change
Fluent Bit v1.7.0
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/12/21 17:47:51] [ info] Configuration:
[2020/12/21 17:47:51] [ info]  flush time     | 5.000000 seconds
[2020/12/21 17:47:51] [ info]  grace          | 5 seconds
[2020/12/21 17:47:51] [ info]  daemon         | 0
[2020/12/21 17:47:51] [ info] ___________
[2020/12/21 17:47:51] [ info]  inputs:
[2020/12/21 17:47:51] [ info]      tail
[2020/12/21 17:47:51] [ info] ___________
[2020/12/21 17:47:51] [ info]  filters:
[2020/12/21 17:47:51] [ info] ___________
[2020/12/21 17:47:51] [ info]  outputs:
[2020/12/21 17:47:51] [ info]      stdout.0
[2020/12/21 17:47:51] [ info] ___________
[2020/12/21 17:47:51] [ info]  collectors:
[2020/12/21 17:47:51] [ info] [engine] started (pid=1)
[2020/12/21 17:47:51] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2020/12/21 17:47:51] [debug] [storage] [cio stream] new stream registered: tail.0
[2020/12/21 17:47:51] [ info] [storage] version=1.1.0, initializing...
[2020/12/21 17:47:51] [ info] [storage] in-memory
[2020/12/21 17:47:51] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/12/21 17:47:51] [debug] [input:tail:tail.0] inotify watch fd=25
[2020/12/21 17:47:51] [debug] [input:tail:tail.0] scanning path /var/log/*.log
[2020/12/21 17:47:51] [debug] [input:tail:tail.0] inode=333247528 with offset=0 appended as /var/log/mylog.log
[2020/12/21 17:47:51] [debug] [input:tail:tail.0] scan_glob add(): /var/log/mylog.log, inode 333247528
[2020/12/21 17:47:51] [debug] [input:tail:tail.0] 1 new files found on path '/var/log/*.log'
[2020/12/21 17:47:51] [debug] [stdout:stdout.0] created event channels: read=29 write=30
[2020/12/21 17:47:51] [debug] [router] match rule tail.0:stdout.0
[2020/12/21 17:47:51] [ info] [sp] stream processor started
[2020/12/21 17:47:51] [debug] [input:tail:tail.0] inode=333247528 file=/var/log/mylog.log promote to TAIL_EVENT
[2020/12/21 17:47:51] [ info] [input:tail:tail.0] inotify_fs_add(): inode=333247528 watch_fd=1 name=/var/log/mylog.log
[2020/12/21 17:47:52] [debug] [input:tail:tail.0] scanning path /var/log/*.log
[2020/12/21 17:47:52] [debug] [input:tail:tail.0] scan_blog add(): dismissed: /var/log/mylog.log, inode 333247528
[2020/12/21 17:47:52] [debug] [input:tail:tail.0] 0 new files found on path '/var/log/*.log'
[2020/12/21 17:47:54] [debug] [input:tail:tail.0] scanning path /var/log/*.log
[2020/12/21 17:47:54] [debug] [input:tail:tail.0] scan_blog add(): dismissed: /var/log/mylog.log, inode 333247528
[2020/12/21 17:47:54] [debug] [input:tail:tail.0] 0 new files found on path '/var/log/*.log'
[0] alllogs: [1608572871.043392279, {"log"=>"hello world!"}]
[1] alllogs: [1608572871.043401416, {"log"=>"Another log message!"}]
[2020/12/21 17:47:55] [debug] [task] created task=0x7f6958855820 id=0 OK
[2] alllogs: [1608572871.043401547, {"log"=>"Another log message 2!"}]
[3] alllogs: [1608572871.043401641, {"log"=>"Another log message 3!"}]
[4] alllogs: [1608572871.043401705, {"log"=>"Done"}]

**Documentation**

- [x] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by manojna10** [comment]
Hi @epsteina16 , This original issue happens when there is a syslog output plugin (UDP/TCP) as well. Not always but occasionally. I see that you have stopped waiting for the tasks to finish themselves and force delete them. I am just trying to understand: when we do flb_stop(), I see that all the inputs are paused and the code just waits for the tasks to finish once every grace period. I couldn't understand how the retry tasks knows that flb is stopped and needs to be invalidated. it will be helpful if you can point me to that point of the code.

**Comment by manojna10** [comment]
Also when run via valgrind with this fix, it reports mem leak when force stopping after configured number of attempts as shown below.                                                                                                                                                                                                        
==7452== LEAK SUMMARY:
==7452==    definitely lost: 112 bytes in 1 blocks
==7452==    indirectly lost: 25,088 bytes in 1 blocks
==7452==      possibly lost: 0 bytes in 0 blocks
==7452==    still reachable: 0 bytes in 0 blocks
==7452==         suppressed: 0 bytes in 0 blocks                                                                                                                                                                                             
                                                                                                                                                                                             
[2020/12/27 23:04:24] [ warn] [engine] shutdown delayed, grace period has finished but some tasks are still running. num_shutdowns_attempted : 4
[2020/12/27 23:04:24] [ info] [task] lib/lib.0 has 1 pending task(s):
[2020/12/27 23:04:24] [ info] [task]   task_id=0 still running on route(s): syslog/syslog.0
[2020/12/27 23:04:24] [ info] [task] storage_backlog/storage_backlog.1 has 5 pending task(s):
[2020/12/27 23:04:24] [ info] [task]   task_id=1 still running on route(s): syslog/syslog.0
[2020/12/27 23:04:24] [ info] [task]   task_id=2 still running on route(s): syslog/syslog.0
[2020/12/27 23:04:24] [ info] [task]   task_id=3 still running on route(s): syslog/syslog.0
[2020/12/27 23:04:24] [ info] [task]   task_id=4 still running on route(s): syslog/syslog.0
[2020/12/27 23:04:24] [ info] [task]   task_id=5 still running on route(s): syslog/syslog.0
[2020/12/27 23:04:24] [ warn] [engine] failed to flush chunk '20953-1609138957.394157297.flb', retry in 47 seconds: task_id=1, input=storage_backlog.1 > output=syslog.0
[2020/12/27 23:04:24] [ warn] [engine] service will stop in 3 seconds
[2020/12/27 23:04:27] [ info] [engine] service stopped
==7452==
==7452== HEAP SUMMARY:
==7452==     in use at exit: 25,200 bytes in 2 blocks
==7452==   total heap usage: 413 allocs, 411 frees, 988,501 bytes allocated
==7452==
==7452== 25,200 (112 direct, 25,088 indirect) bytes in 1 blocks are definitely lost in loss record 2 of 2
==7452==    at 0x4C2DF9D: malloc (vg_replace_malloc.c:307)
==7452==    by 0x4EBD591: flb_malloc (flb_mem.h:62)
==7452==    by 0x4EBD9AA: flb_thread_new (flb_thread_libco.h:119)
==7452==    by 0x4EBD9AA: flb_output_thread (flb_output.h:488)
==7452==    by 0x4EBD9AA: flb_engine_dispatch_retry (flb_engine_dispatch.c:77)
==7452==    by 0x4EC1020: flb_sched_event_handler (flb_scheduler.c:384)
==7452==    by 0x4EBD11D: flb_engine_start (flb_engine.c:631)
==7452==    by 0x4EA007A: flb_lib_worker (flb_lib.c:489)
==7452==    by 0x5AE16B9: start_thread (pthread_create.c:333)
==7452==    by 0x56134DC: clone (clone.S:109)
==7452==
==7452== LEAK SUMMARY:
==7452==    definitely lost: 112 bytes in 1 blocks
==7452==    indirectly lost: 25,088 bytes in 1 blocks
==7452==      possibly lost: 0 bytes in 0 blocks
==7452==    still reachable: 0 bytes in 0 blocks
==7452==         suppressed: 0 bytes in 0 blocks
==7452==
==7452== For lists of detected and suppressed errors, rerun with: -s
==7452== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

**Comment by epsteina16** [comment]
Thanks for bringing this to my attention. This pull request also needs to include invalidating tasks as you mentioned. I am working on this now.

**Comment by epsteina16** [comment]
@edsiper @manojna10 Is there anything that is needed prior to review?

**Comment by manojna10** [comment]
Hi @epsteina16 Per my understanding this looks good as a solution to solve the issue. But as I am a newbie to this code, I couldn't understand why the issue is happening in the first place. I mean, it happens sometimes and not always. As explained in my first comment here, how does all the tasks knows that they need to get invalidated when flb is stopped and why sometimes it doesn't happen?   My earlier comment in this pull request : https://github.com/fluent/fluent-bit/pull/2885#issuecomment-751391845

**Comment by epsteina16** [comment]
@manojna10 The use case which stemmed this is: 
- Fluent-bit is in a short lived Pod, where it will exit after finishing reading the logs in the pod.
- If a receiver went down (like a TCP connection or syslog server), fluent-bit should still exit in a timely manner

This method is bound to lose some data that hasn't been sent when it has to invalidate tasks.

**Comment by manojna10** [comment]
> * If a receiver went down (like a TCP connection or syslog server), fluent-bit should still exit in a timely manner

@epsteina16, even when the receiver is down, the behavior should be consistent. Either it should exit in a timely manner or not. But I see its not consistent. Even when there are multiple retries(tasks) scheduled, sometimes it does exit in a timely manner and sometimes it don't. So something looks off here. That's the basis of my question. Am I missing something here?

**Comment by epsteina16** [comment]
@manojna10 I don't ever see it exit in a timely manner when the receiver is down. There are retries(tasks) scheduled, as you said, and the engine waits for those to finish before shutting down. If the receiver is down, the attempt to establish a TCP connection fails and the callback function in tcp.c (line 77) returns FLB_RETRY which creates a retry. 

These retries will not succeed, and when the fluent-bit program catches SIGINT it checks how many active "users" (threads) there are on each task (flb_task_running_count in flb_engine.c). If this is >0, which it is when there are task retries or active tasks, then shutdown is delayed by the grace period.

**Comment by f0o** [comment]
I'm also experiencing fluentbit looping through the graceperiod if the receiver (forward protocol to fluentd) is unavailable which prevents it from shutting down until the runtime SIGKILL's it.

Is there any hold up on this PR?

**Comment by epsteina16** [comment]
@edsiper ; @fujimotos ; @koleini Can one of the reviewers take a look at this pull request? This is a nice-to-have feature for fluent bit processes that aren't long lived.

**Comment by fujimotos** [comment]
[ FTR, I received some email from users who stumbled upon "Fluent Bit won't shutdown" issue ]

I set out to review patch today, intending to do testing on master HEAD
applying this patch, but I found that the latest mainline already contains
almost the same fix.

In particular, the commit 3b9a2e73b094f0442fe7c9181e5bd7abc89b591e (authored by @edsiper 2w ago) 
introduced a retry counter, and modified the shutdown logic so that
Fluent Bit always respects the grace period.

So I believe  the next release (v1.8.11) should resolve the issue #2668,
and can close this proposal as resolved.

**Comment by fujimotos** [comment]
[ FTR, I received some email from users who stumbled upon "Fluent Bit won't shutdown" issue ]

I set out to review patch today, intending to do testing on master HEAD
applying this patch, but I found that the latest mainline already contains
almost the same fix.

In particular, the commit 3b9a2e73b094f0442fe7c9181e5bd7abc89b591e (authored by @edsiper 2w ago) 
introduced a retry counter, and modified the shutdown logic so that
Fluent Bit always respects the grace period.

So I believe  the next release (v1.8.11) should resolve #2868,
and we can close this proposal as resolved.

**Pull request closed without merging**
