### PR TITLE
core: add compile flag to disable control chars

### PR DESCRIPTION
**Pull request by patrick-stephens**
Signed-off-by: Patrick Stephens <pat@calyptia.com>

Addresses #5002 by allowing us to compile out the control codes and then use this for containers.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by niedbalski** [comment]
Q: Why not disabling control chars by default? and enable on flags? Is on being assumed/used by scripts or tools?

**Comment by niedbalski** [comment]
@edsiper @patrick-stephens I would suggest switching control chars as disabled by default, unless this can break backwards compatibility with scripts or some other tool.

**Comment by patrick-stephens** [comment]
@edsiper @niedbalski why do we need control characters at all? Most users are running via some init system or as containers so I imagine do not really care. My concern is I've had real world experience of failures due to control chars being in logs and it is frustrating.

**Review by niedbalski — APPROVED** [review]
LGTM

**Comment by patrick-stephens** [comment]
Rebased as #5583 .

**Pull request closed without merging**
