### PR TITLE
in_syslog: Add syslog udp network

### LINKED ISSUE #760: Syslog Input Mode UDP
**Is your feature request related to a problem? Please describe.**
There is a syslog TCP input endpoint, but not a UDP one.

**Describe the solution you'd like**
Just like the syslog input mode `tcp`, I'd love if there was a syslog mode `udp` 

**Additional context**
I have many servers which expect a syslog UDP endpoint for pushing their logs.

### PR DESCRIPTION
**Pull request by newtoncorp**
Patch a bit to add syslog udp network. Tested locally

Should fix #760

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for the contribution, it looks good to me. 

In order to merge the changes, would you please split the changes in two commits, e.g:

- in_syslog: ...
- network: ...

**Comment by newtoncorp** [comment]
Done, but my version of git does not recognize the `--sign-off' option :/

**Comment by newtoncorp** [comment]
Done

**Comment by edsiper** [comment]
thanks

**Comment by anandsinghkunwar** [comment]
Which version can we expect this to be in the release for?

**Comment by flokli** [comment]
This seems to have landed in a release so far, but docs still don't show it ;-)

**Pull request merged**
