### PR TITLE
kubernetes_filter: add support for preload cache dir using pod_id.meta file 

### PR DESCRIPTION
**Pull request by mgeriesa**
kubernetes_filter: Change k8s filter plugin to add support for preload cash directory using:  pod_id.meta file 

New enhancement

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ N/A] Example configuration file for the change - configuration is not changed.
-       [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Annotations         Off
        Merge_Log           Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Kube_meta_preload_cache_dir  ${FLUENT_META_CACHE_DIR}
        Regex_Parser        custom-kube-filter
        Kube_Tag_Prefix     kube.
        tls.verify          Off
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by patrick-stephens** [comment]
I think this needs a docs PR for an example of how to use it: it's not entirely clear to me how this change is used and what files you need to provide in what format.

Currently the docs say:
```
Kube_meta_preload_cache_dir
If set, Kubernetes meta-data can be cached/pre-loaded from files in JSON format in this directory, named as namespace-pod.meta
```
Presumably this change introduces another option so that should be documented as well?

**Comment by mgeriesa** [comment]
Yes ,

I will add :

If set, Kubernetes meta-data can be cached/pre-loaded from files in
JSON format in this directory, named as namespace-pod.meta or
podid.meta

Regards,

Manal

**Comment by mgeriesa** [comment]
Adding document changes to be added to Fluentbit docs:
https://docs.fluentbit.io/manual/pipeline/filters/kubernetes
[Docs_change_K8S_filter.docx](https://github.com/fluent/fluent-bit/files/8817609/Docs_change_K8S_filter.docx)

**Comment by mgeriesa** [comment]
[valgrind.docx](https://github.com/fluent/fluent-bit/files/8818450/valgrind.docx)

**Comment by patrick-stephens** [comment]
Note you need to update your commit messages to be something like: `kubernetes_filter: ...`

**Comment by mgeriesa** [comment]
Done.

Please let me know if all is ok .

**Comment by patrick-stephens** [comment]
Unit tests are all still failing along with the DCO check I'm afraid - you can see this directly in the checks section.

**Comment by mgeriesa** [comment]
I did sync with latest to avoid build failure with MAC OS.

**Comment by pwhelan** [comment]
> Unit tests are all still failing along with the DCO check I'm afraid - you can see this directly in the checks section.

Here is an explanation: https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for.

**Pull request closed without merging**
