### PR TITLE
signv4: fix NULL dereference

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Signed-off-by: David Korczynski <david@adalogics.com>

This PR supersedes https://github.com/fluent/fluent-bit/pull/4052

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A ] Example configuration file for the change
- [N/A ] Debug log output from testing the change

- [N/A ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [N/A ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by edsiper** [comment]
ping @PettitWesley

**Comment by DavidKorczynski** [comment]
@PettitWesley could you take a look at this? it would be nice to get it mergerd

**Comment by edsiper** [comment]
Since CI is passing I am merging this one. @PettitWesley if it generates any issue pls let us know

**Comment by DavidKorczynski** [comment]
Thanks -- this is a much more explicit fix than the other one and will not create any issue. If any of the conditionals added is true then the code would otherwise have segfaulted, and it will not create any new execution pattern for code that would not otherwise trigger a segfault.

**Comment by PettitWesley** [comment]
@DavidKorczynski @edsiper Thanks!

**Pull request merged**
