### PR TITLE
Replace uses of 'temporal' with 'temporary'.

### PR DESCRIPTION
**Pull request by jhuntwork**
Looking at the instances and locations used, it seems very likely that
the meaning of 'temporary' is intended. For native English speakers,
temporary is clear, temporal is somewhat confusing.

This article helps make the distinction clear:
https://english.stackexchange.com/questions/7539/temporal-vs-temporary

### CODE REVIEW

**Comment by nigels-com** [comment]
Agreed.  The word "temporary" is most likely the intended word.

**Comment by edsiper** [comment]
sorry for the late reply.

would you please rebase on top of git master ?

note: changes not applicable for content under lib/ directory

**Comment by edsiper** [comment]
@jhuntwork the PR needs to be rebased on top of master before a review.

**Comment by jhuntwork** [comment]
@edsiper - rebased, thanks.

**Comment by edsiper** [comment]
thanks. PLease note the pending change:

> note: changes not applicable for content under lib/ directory

for short, do not push changes inside lib/ content since they are dependencies

**Comment by jhuntwork** [comment]
@edsiper - updated, without changes to `lib/`

**Comment by nigels-com** [comment]
Looks good to me.

**Comment by edsiper** [comment]
thanks

**Pull request merged**
