### PR TITLE
build: wasm: upgrade wasm-micro-runtime to WAMR-1.3.2

### PR DESCRIPTION
**Pull request by ThomasDevoogdt**
Main reason for the bump:
 - Enhance setting write gs base with cmake variable ([#3066](https://github.com/bytecodealliance/wasm-micro-runtime/pull/3066)) --> fixes cross compilation on buildroot

Other news:
 - https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-1.3.1
 - https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-1.3.2

### CODE REVIEW

**Comment by patrick-stephens** [comment]
HadoLint is failing because this PR is too large...
However it does not touch the container definition so can be safely ignored.

**Review by cosmo0920 — APPROVED** [review]
Looks good to me. No Wasm related test breakages. :+1:

**Comment by ThomasDevoogdt** [comment]
Thx for the review. I also added some small remark about buildroot in another pull request. https://github.com/fluent/fluent-bit-docs/pull/1357

**Comment by cosmo0920** [comment]
Ah, Buildroot is one of the embedded Linux! I actually worked for Yocto Linux which is another Embedded Linux distribution. Thanks for the addition into Fluent Bit documentation.

**Comment by ThomasDevoogdt** [comment]
@edsiper, @cosmo0920, @patrick-stephens, can this be merged? I don't have the rights to do so.

**Comment by ThomasDevoogdt** [comment]
@cosmo0920, @patrick-stephens, @edsiper kind ping

**Comment by patrick-stephens** [comment]
What's up with the test failures?

**Comment by ThomasDevoogdt** [comment]
@edsiper can you consider this PR?
I've rebased the PR to get a CI test update.

**Comment by ThomasDevoogdt** [comment]
@edsiper @cosmo0920 @patrick-stephens @leonardo-albertovich Hi, I rebased this PR to the current master. Is it possible to consider this PR?

**Comment by ThomasDevoogdt** [comment]
Hi @cosmo0920, is it possible to also add a "Fluent Bit v3.2.0" tag for this PR? Or to just merge it?

**Comment by patrick-stephens** [comment]
I think best to leave this with @cosmo0920 for review.

**Comment by edsiper** [comment]
closing in favor of https://github.com/fluent/fluent-bit/pull/9643

**Comment by ThomasDevoogdt** [comment]
> closing in favor of #9643

Thanks!

**Pull request closed without merging**
