### PR TITLE
build: opt-in FLB_SMALL for optimising for binary size (~50% reduction)

### PR DESCRIPTION
**Pull request by nigels-com**
For potential application on small devices, reduce the footprint by around half.

Results for Ubuntu 18.04 64-bit:

```
-rwxrwxr-x 1 nigels nigels 5.3M Jul 24 14:00 bin/fluent-bit
-rwxrwxr-x 1 nigels nigels 2.8M Jul 24 15:37 bin/fluent-bit
```

### CODE REVIEW

**Comment by edsiper** [comment]
this change breaks anything that's not armv7:

https://travis-ci.org/fluent/fluent-bit/jobs/562947622

**Comment by nigels-com** [comment]
Indeed, the armv7 flag was in error.

But aside from that `-Os` appears to be causing problems on Ubuntu, so I'll continue digging into this one.

**Comment by nigels-com** [comment]
For Ubuntu 18.04 (and possibly elsewhere too) it appears necessary to use `-U_FORTIFY_SOURCE` in combination with `-Os`.   Otherwise there are runtime crashes concerning stack-smashing checks that seem to be going wrong.  It seems suprising that `-Os` (optimise for size) might be broadly broken, but I couldn't find any fault with the particular `snprintf` at issue:

```
    /* Retrieve an instance id for the output instance */
    instance->id = instance_id(config);

    /* format name (with instance id) */
    snprintf(instance->name, sizeof(instance->name) - 1,
             "%s.%i", plugin->name, instance->id);
    instance->p = plugin;
```
Our intended use for `FLB_SMALL` is for ARM-based devices, so this is sufficient, although a bit unsettling from a security point of view, to require disabling fortification.

**Comment by edsiper** [comment]
what's the current status against stack errors ?, changing the compiler flags is enough ?

**Comment by nigels-com** [comment]
Yes, it's been running fine for us on a few ARM and Intel systems for tens of hours so far.
I'd like to see this merged into the mainline to reduce our divergence.

**Comment by edsiper** [comment]
thanks

**Pull request merged**
