### PR TITLE
Add new API to generate huge JSON string.

### LINKED ISSUE #195: msgpack to json: incomplete message
Migrating out_es plugin I found that when converting some msgpack messages to JSON are not completed, e.g:

Original msgpack:
```
{"date"=>1487366000, 
 "rand_value"=>14190504959783770716, 
 "rand_valuX"=>{"keyname_00"=>"valu0", 
                "keyname_01"=>{"subkey_a_b_c"=>14190504959783770716, 
                               "array_X"=>[12345]
                              }
               }
}
```

converted (incomplete):

```json
{"date":1487366000, 
  "rand_value":14190504959783770716, 
  "rand_valuX": {"keyname_00": "valu0", 
                 "keyname_01": {"subkey_a_b_c":
```

### PR DESCRIPTION
**Pull request by nokute78**
To fix #195 

I added a new API `flb_msgpack_to_json_str_list` and modified out_file to use new API.

User passes msgpack to API, it will return string list.
User can get huge JSON string with iterating the list.

### CODE REVIEW

**Comment by nokute78** [comment]
@edsiper Could you review this?

**Comment by edsiper** [comment]
why a list ?

**Comment by nokute78** [comment]
It's just easy to implement...

It needs to modify `msgpack2json` drastically to keep token state.

It may be proper `char **` instead of `mk_list`

**Comment by edsiper** [comment]
no need of new api, recent changes fixed the problem: 461319eb and c06d082c

**Pull request closed without merging**
