### PR TITLE
Allow user to decide whether they want to include annotations in Kubernetes filter

### PR DESCRIPTION
**Pull request by mikn**
This addresses my actual concern here in issue #422. I think this is a good starting point in allowing users to decide what metadata to include. What do you guys think?

### CODE REVIEW

**Comment by edsiper** [comment]
thanks @mikn , we need two minor changes please:

- rename configuration variable from include_annotations to annotations
- rework commits and prefix them with the component they are touching, e.g: "filter_kubernetes: fix...."

thanks

**Comment by mikn** [comment]
Sure! Just a quick question. Would you prefer this to be default set to "How it works in fluentd" (ie. annotations off by default) or "How it works now" (ie. annotations on by default).

**Comment by edsiper** [comment]
@mikn thanks. Since this improvement will be merged into 0.12 series, let's keep it ON by default to avoid break current users config.

**Comment by mikn** [comment]
Good! Then I'll keep it as-is. :)

**Pull request merged**
