### PR TITLE
in_gelf: add gelf input plugin (tcp mode only)

### PR DESCRIPTION
**Pull request by phoefflin**
Signed-off-by: Philipp Hoefflin <philipp.hoefflin@haufe-lexware.com>

initial implementation of a gelf input plugin. As discussed in PR #2072 instead of extending in_tcp I created a new input plugin for better maintainability. It is still heavily based on in_tcp in order to not reinvent the wheel. The plugin currently does only support TCP mode, UDP could follow. I think having a TCP mode does already add an extra value, therefore I excluded the UDP part for the first step.

- debug log: [fluent-bit-debug.log](https://github.com/fluent/fluent-bit/files/4673639/fluent-bit-debug.log)
 - valgrind output of a test run consuming the logs of a load tested quarkus/java app: [fluent-bit-valgrind.log](https://github.com/fluent/fluent-bit/files/4673640/fluent-bit-valgrind.log)
 - example config file:
```
[SERVICE]
    Log_Level   debug

[INPUT]
    Name        gelf
    Listen      0.0.0.0
    Port        12201
    Mode        tcp

[OUTPUT]
    Name        stdout
    Match       *
``` 

 - Docs PR will follow

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change
- [x] Debug log output from testing the change: 
- [x] Attached [Valgrind]: 

**Documentation**

- [x] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by merkys7** [comment]
Why this is not being merged for so long? I need this feature

**Comment by merkys7** [comment]
@edsiper @fujimotos @koleini

**Review by merkys7 — APPROVED** [review]

**Comment by konradasb** [comment]
Would be awesome to have this feature, as well, ELF input is highly needed @edsiper @fujimotos @koleini

**Comment by jtheo** [comment]
Hi, I apologise in advance to bother you, and I realise that this is only one of many PR and feature requests that you have, but, would be possible to merge it into the master branch?
Thanks.

**Comment by phoefflin** [comment]
@edsiper @koleini @fujimotos Could you please give a hint if the feature is worth while proceeding? It was built based on your feedback in https://github.com/fluent/fluent-bit/pull/2072 but never commented here. If it is I'll be happy to update the PR and take your input otherwise let's close it. Thx

**Pull request closed without merging**
