### PR TITLE
filter_record_modifier: support uuid_key

### PR DESCRIPTION
**Pull request by nokute78**
This patch is to append UUID to each record.
Requested at #5571 

|Name|Description|
|---|---|
|uuid_key| If set, the plugin generates uuid per record.|

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

## Configuration

```
[INPUT]
    Name dummy

[FILTER]
    Name record_modifier
    Match *
    uuid_key uuid

[OUTPUT]
    Name stdout
```

## Debug/Valgrind output

```
$ valgrind --leak-check=full bin/fluent-bit -c uuid.conf 
==73886== Memcheck, a memory error detector
==73886== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==73886== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==73886== Command: bin/fluent-bit -c uuid.conf
==73886== 
Fluent Bit v2.0.6
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/11/20 09:12:32] [ info] [fluent bit] version=2.0.6, commit=2049e320eb, pid=73886
[2022/11/20 09:12:32] [ info] [storage] ver=1.2.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/11/20 09:12:32] [ info] [cmetrics] version=0.5.7
[2022/11/20 09:12:32] [ info] [ctraces ] version=0.2.5
[2022/11/20 09:12:32] [ info] [input:dummy:dummy.0] initializing
[2022/11/20 09:12:32] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2022/11/20 09:12:32] [ info] [output:stdout:stdout.0] worker #0 started
[2022/11/20 09:12:32] [ info] [sp] stream processor started
==73886== Warning: client switching stacks?  SP change: 0x6ffb6f8 --> 0x55ffa30
==73886==          to suppress, use: --max-stackframe=27245768 or greater
==73886== Warning: client switching stacks?  SP change: 0x55ff988 --> 0x6ffb6f8
==73886==          to suppress, use: --max-stackframe=27245936 or greater
==73886== Warning: client switching stacks?  SP change: 0x6ffb6f8 --> 0x55ff988
==73886==          to suppress, use: --max-stackframe=27245936 or greater
==73886==          further instances of this message will not be shown.
[0] dummy.0: [1668903153.547521855, {"message"=>"dummy", "uuid"=>"441b94a3-ff3b-44b9-9578-10bee7d749d7"}]
[0] dummy.0: [1668903154.546527567, {"message"=>"dummy", "uuid"=>"a8e901b0-236b-4231-8e96-bef6e395d1cc"}]
[0] dummy.0: [1668903155.519441622, {"message"=>"dummy", "uuid"=>"da3197a6-7b30-4ee5-9edc-9ad7b06fe27c"}]
^C[2022/11/20 09:12:36] [engine] caught signal (SIGINT)
[2022/11/20 09:12:36] [ warn] [engine] service will shutdown in max 5 seconds
[0] dummy.0: [1668903156.517244770, {"message"=>"dummy", "uuid"=>"58bb95d2-a666-4e08-8d49-f05864e65d2f"}]
[2022/11/20 09:12:36] [ info] [input] pausing dummy.0
[2022/11/20 09:12:37] [ info] [engine] service has stopped (0 pending tasks)
[2022/11/20 09:12:37] [ info] [input] pausing dummy.0
[2022/11/20 09:12:37] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2022/11/20 09:12:37] [ info] [output:stdout:stdout.0] thread worker #0 stopped
==73886== 
==73886== HEAP SUMMARY:
==73886==     in use at exit: 542,739 bytes in 4,232 blocks
==73886==   total heap usage: 8,297 allocs, 4,065 frees, 2,616,893 bytes allocated
==73886== 
==73886== LEAK SUMMARY:
==73886==    definitely lost: 0 bytes in 0 blocks
==73886==    indirectly lost: 0 bytes in 0 blocks
==73886==      possibly lost: 0 bytes in 0 blocks
==73886==    still reachable: 542,739 bytes in 4,232 blocks
==73886==         suppressed: 0 bytes in 0 blocks
==73886== Reachable blocks (those to which a pointer was found) are not shown.
==73886== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==73886== 
==73886== For lists of detected and suppressed errors, rerun with: -s
==73886== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by nokute78** [comment]
Note: valgrind reports openssl leak.
Once `flb_utils_uuid_v4_gen` is called, openssl allocates memory.

We may need to call some cleanup functions...
https://wiki.openssl.org/index.php/Library_Initialization#Cleanup

```
$ valgrind --leak-check=full --show-leak-kinds=all bin/fluent-bit -c uuid.conf 
==85060== Memcheck, a memory error detector
==85060== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==85060== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==85060== Command: bin/fluent-bit -c uuid.conf
==85060== 
Fluent Bit v2.0.6
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/11/20 09:32:39] [ info] [fluent bit] version=2.0.6, commit=2049e320eb, pid=85060
[2022/11/20 09:32:40] [ info] [storage] ver=1.2.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/11/20 09:32:40] [ info] [cmetrics] version=0.5.7
[2022/11/20 09:32:40] [ info] [ctraces ] version=0.2.5
[2022/11/20 09:32:40] [ info] [input:dummy:dummy.0] initializing
[2022/11/20 09:32:40] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2022/11/20 09:32:40] [ info] [sp] stream processor started
[2022/11/20 09:32:40] [ info] [output:stdout:stdout.0] worker #0 started
==85060== Warning: client switching stacks?  SP change: 0x6ffb6f8 --> 0x55ffa30
==85060==          to suppress, use: --max-stackframe=27245768 or greater
==85060== Warning: client switching stacks?  SP change: 0x55ff988 --> 0x6ffb6f8
==85060==          to suppress, use: --max-stackframe=27245936 or greater
==85060== Warning: client switching stacks?  SP change: 0x6ffb6f8 --> 0x55ff988
==85060==          to suppress, use: --max-stackframe=27245936 or greater
==85060==          further instances of this message will not be shown.
[0] dummy.0: [1668904361.593635513, {"message"=>"dummy", "uuid"=>"cf997667-2707-4ad2-a524-ed8a4c42485b"}]
[0] dummy.0: [1668904362.710553699, {"message"=>"dummy", "uuid"=>"852690f7-9504-4412-a7c1-7611909f899f"}]
^C[2022/11/20 09:32:43] [engine] caught signal (SIGINT)
[0] dummy.0: [1668904363.519067803, {"message"=>"dummy", "uuid"=>"6de9c5b2-98d6-4e97-a831-09d119356e0d"}]
[2022/11/20 09:32:43] [ warn] [engine] service will shutdown in max 5 seconds
[2022/11/20 09:32:43] [ info] [input] pausing dummy.0
[2022/11/20 09:32:44] [ info] [engine] service has stopped (0 pending tasks)
[2022/11/20 09:32:44] [ info] [input] pausing dummy.0
[2022/11/20 09:32:44] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2022/11/20 09:32:44] [ info] [output:stdout:stdout.0] thread worker #0 stopped
==85060== 
==85060== HEAP SUMMARY:
==85060==     in use at exit: 542,739 bytes in 4,232 blocks
==85060==   total heap usage: 8,268 allocs, 4,036 frees, 2,246,904 bytes allocated
==85060== 
==85060== 1 bytes in 1 blocks are still reachable in loss record 1 of 700
==85060==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==85060==    by 0x4C95617: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C8C0BC: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4CAB3FA: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4D73C17: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4D7426D: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C77BC2: EVP_RAND_fetch (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4CC9C2B: RAND_get0_primary (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4CCA177: RAND_get0_public (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4CCA267: RAND_bytes_ex (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x223561: flb_utils_uuid_v4_gen (flb_utils.c:1131)
==85060==    by 0x65F8E4: create_uuid (filter_modifier.c:287)
==85060== 
==85060== 4 bytes in 1 blocks are still reachable in loss record 2 of 700
==85060==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==85060==    by 0x4C980D2: CRYPTO_strndup (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C99E21: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C96727: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C9690A: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C964FC: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4D7419B: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C77BC2: EVP_RAND_fetch (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4CC9C2B: RAND_get0_primary (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4CCA177: RAND_get0_public (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4CCA267: RAND_bytes_ex (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x223561: flb_utils_uuid_v4_gen (flb_utils.c:1131)
==85060== 
==85060== 4 bytes in 1 blocks are still reachable in loss record 3 of 700
==85060==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==85060==    by 0x4C980D2: CRYPTO_strndup (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C99E21: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C96727: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C96550: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4D7419B: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C77BC2: EVP_RAND_fetch (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4CC9C2B: RAND_get0_primary (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4CCA177: RAND_get0_public (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4CCA267: RAND_bytes_ex (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x223561: flb_utils_uuid_v4_gen (flb_utils.c:1131)
==85060==    by 0x65F8E4: create_uuid (filter_modifier.c:287)
==85060== 
==85060== 4 bytes in 1 blocks are still reachable in loss record 4 of 700
==85060==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==85060==    by 0x4C980D2: CRYPTO_strndup (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C99E21: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C96727: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C96809: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C96536: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4D7419B: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4C77BC2: EVP_RAND_fetch (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4CC9C2B: RAND_get0_primary (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4CCA177: RAND_get0_public (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x4CCA267: RAND_bytes_ex (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
==85060==    by 0x223561: flb_utils_uuid_v4_gen (flb_utils.c:1131)
```

**Comment by edsiper** [comment]
cc: @lecaros docs PR

**Comment by nokute78** [comment]
I sent a doc PR https://github.com/fluent/fluent-bit-docs/pull/982

**Comment by Balukn11** [comment]
Will the generated UUID be the same for alike kind of records or different for same type of records?

**Pull request merged**
