### PR TITLE
downstream: PR 6882 rework

### PR DESCRIPTION
**Pull request by leonardo-albertovich**
This pull request addresses the same issues that PR #6882 covered.

### CODE REVIEW

**Comment by edsiper** [comment]
the changes makes sense to me, but we need more testing. @nokute78 can you validate the approach proposed here ?

**Comment by leonardo-albertovich** [comment]
I just realized that the test case I created for this has already been running for 24 hours when I went to switch branches to backport it to 2.0.

The configuration I used was this : 

```
[SERVICE]
    flush 1
    grace 1
    log_level info

[INPUT]
    name forward
    threaded On

[OUTPUT]
    name stdout
    match *
```

The clients were eight shells running this line : 

```
while [ 1 ] ; do  telnet 127.0.0.1 24224 <sample_file >/dev/null 2>&1; sleep 0.1 ; done
```

And the contents of `sample_file` were these : 

```
{"a": "b"}
```

Which obviously is wrong considering this is `in_forward` but what's important in this case is that those 8 clients were constantly establishing new connections, sending a bit of data and closing the connection which combined with the timers and main thread event loop processing caused all "three" issues to trigger originally.

So I am fairly confident that this PR works.

**Comment by nokute78** [comment]
@leonardo-albertovich Thank you for reworking.
I tested using thread sanitizer and the race was not detected (except #6776)

Note: Side effect of thread sanitizer ?
https://github.com/fluent/fluent-bit/pull/6882#issue-1590509147

I tested following configuration and enabled thread sanitizer.
The receiver didn't output and ignored signal (Ctrl+C).

If I disabled thread sanitizer, the receiver worked correctly.

Receiver: 
```
[INPUT]
    Name forward
    Threaded on

[OUTPUT]
    Name stdout
```
Sender: 
```
fluent-bit -i dummy -p rate=100000 -o forward
```

Note: Detail of the PR is 
https://github.com/fluent/fluent-bit/pull/6882#issuecomment-1441555469
https://github.com/fluent/fluent-bit/pull/6882#issuecomment-1442000640

**Comment by leonardo-albertovich** [comment]
I think once we move the atomic operation abstraction layer from cmetrics to cfl we'll be in a much better position to fix that race in a performant way.

I think it's about time we move atomics to cfl, it's not the first time I've been in a situation where I'd like to use them outside of cmetrics and from a purely organizational point of view it would make sense (which I don't think anyone disagrees with).

**Pull request merged**
