### PR TITLE
out_influxdb: add 'Auto_Tags' and 'Tag_Keys' options

### PR DESCRIPTION
**Pull request by zozzz**
These two options works like similar to 'fluent-plugin-influxdb'.
- `Auto_Tags:` On/Off *(default: Off)* Auto-tagging behaviour which makes string values as tags.
- `Tag_Keys:` Space separated list of the key names. Set this keys as tag in InfluxDB.

### CODE REVIEW

**Comment by edsiper** [comment]
@zozzz 

thanks for this contribution.

Doing some tests I found a problem when ingesting parsed Apache logs:

```
[2018/04/02 14:57:28] [error] [out_influxdb] http_do=0 http_status=400
{"error":"unable to parse 'tail.0,_seq=0,host=\"149.56.83.40\",user=\"-\",method=\"POST\",path=\"/administrator/index.php\",code=\"200\",size=\"4498\",referer=\"-\",agent=\"-\"  1486559140000000000': invalid field format\nunable to parse 'tail.0,_seq=1,host=\"149.56.83.40\",user=\"-\",method=\"POST\",path=\"/administrator/index.php\",code=\"200\",size=\"4498\",referer=\"-\",agent=\"-\"  1486559141000000000': invalid field format\nunable to parse 'tail.0,_seq=2,host=\"149.56.83.40\",user=\"-\",method=\"POST\",path=\"/administrator/index.php\",code=\"200\",size=\"4498\",referer=\"-\",agent=\"-\"  1486559141000000000': invalid field format\nunable to parse 'tail.0,_seq=3,host=\"149.56.83.40\",user=\"-\",method=\"POST\",path=\"/administrator/index.php\",code=\"200\",size=\"4498\",referer=\"-\",agent=\"-\"  1486559142000000000': invalid field format\nunable to parse 'tail.0,_seq=4,host=\"149.56.83.40\",user=\
```
> please pull the latest changes in out_influxdb so you get the pending connection fix and the proper HTTP error messages if any.

I've tested using the following command:

```
$ fluent-bit -R ../conf/parsers.conf -i tail -p path=../20.log -p parser=apache -o influxdb  -p tag_keys=host -p auto_tags=on -m '*' -f 1
```

The example log file is attached here: [20.log](https://github.com/fluent/fluent-bit/files/1869331/20.log)

**Comment by zozzz** [comment]
This problem is caused by `auto_tags`. 
InfluxDB Line Protocol:
`<measurement>[,<tag_key>=<tag_value>[,<tag_key>=<tag_value>]] <field_key>=<field_value>[,<field_key>=<field_value>] [<timestamp>]`
- Tag set optional
- Field set NOT optional
- Timestamp optional
So with this option, every key is turn into tags, and missing *Field set* part from data.

I have two ide, how ho handle this:
1. Put sequence key=value in *Field set* (maybe not backward compatible, not soo good)
2. Display a proper error message, why not send data to InfluxDB

What do you think?

**Comment by edsiper** [comment]
how Fluentd influxdb plugin handle this ?

**Comment by zozzz** [comment]
Gives error message: "InfluxDB requires at least one value in raw", so i do the same.

**Comment by edsiper** [comment]
let's follow Fluentd-way

**Comment by edsiper** [comment]
thanks. I've squashed all commits into one here: a7dd2e942d05ece7b45a2192bb17c2579ce322eb

please also update repo https://github.com/fluent/fluent-bit-docs with the options in InfluxDB page:

https://github.com/fluent/fluent-bit-docs/blob/master/output/influxdb.md

Closing as merged.

**Pull request closed without merging**
