### PR TITLE
parser: support "Skip_Empty_Values" (#1486)

### LINKED ISSUE #1486: Regular Expression Parser is skipping empty values
Hi,

If a field in JSON log is empty, the field is not preserved in Elasticsearch result. See example below.

**Note**: Using `fluent/fluent-bit:1.2.2-debug`

# EXAMPLES

**ISSUE**

When `client_ip` field is empty in `log`, the field is not preserved.

```json
{
  ...
  "_source": {
    ...
    "time_local": "2019-07-31T21:17:15",
    "log": "{\"time_local\":\"2019-07-31T21:17:15\",\"client_ip\":\"\"}",
    ...
  },
  ...
}
```

**EXPECTED**

When `client_ip` field is empty in `log`, the field should be preserved with empty value.

```json
{
  ...
  "_source": {
    ...
    "time_local": "2019-07-31T21:17:15",
    "client_ip": "",
    "log": "{\"time_local\":\"2019-07-31T21:17:15\",\"client_ip\":\"\"}",
    ...
  },
  ...
}
```

# MY SETUP

**fluent-bit.conf**
```yaml
[SERVICE]
    Flush                     5
    Daemon                    Off
    Log_Level                 debug
    storage.path              /var/log/flb-storage
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 5M
    Parsers_File              parsers.conf

[INPUT]
    Name         forward
    storage.type filesystem
    Listen       my_fluent_bit_service
    Port         24224

[FILTER]
    Name         parser
    Parser       json_regex
    Match        *
    Key_Name     log
    Reserve_Data On
    Preserve_Key On

[OUTPUT]
    Name            es
    Host            my_elasticsearch_service
    Port            9200
    Match           whatever_*
    Index           whatever
    Type            logs
    Include_Tag_Key On
    Tag_Key         tag
```

**parsers.conf**
```yaml
[PARSER]
    Name   json_regex
    Format regex
    Regex  ^{"time_local":"(?<time_local>.*?)","client_ip":"(?<client_ip>.*?)"}$
```

### LINKED ISSUE #2939: Fluent bit not parsing lines correctly
## Bug _Report_

**Describe the bug**
Our dlt logs are generally parsed correctly and the correct fields are generated.  When the last field is missing it is not able to match any fields. When using regex101.com with the same lines and the regex it is working correctly. 

```
^(?<Index>[^ ]*) (?<log_time>[^ ]*\s[^ ]*) (?<Timestamp>[^ ]*) (?<Count>[^ ]*) (?<ECUID>[^ ]*) (?<APID>[^ ]*) (?<CTID>[^ ]*) (?<SessionID>[^ ]*) (?<Type>[^ ]*) (?<Subtype>[^ ]*) ?(?<Mode>[^ ]*) ?(?<Args>[^ ]*) ?(?<Payload>.*)?$
```

A message like this is matched: 
```
 2448 2020/12/08 14:41:24.000000 836.1025 59 OTAF PAGY COMP 1134 log warn verbose 1 SOME PAYLOAD
```
While this is not:
```
2448 2020/12/08 14:41:24.000000 836.1025 59 OTAF PAGY COMP 1134 log warn verbose 1 
``` 
(there is a whitespace as last letter in line)

### PR DESCRIPTION
**Pull request by nokute78**
Fixes #1486 
Fixes #2939 

This patch is based on #1913.
It is to add new option `Skip_Empty_Values`. Default is true to prevent breaking change.

|Name|Description|Default|
|-------|------------|--------|
|`Skip_Empty_Values`|If enabled, the parser ignores empty value of the record.| True|

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [ ] Documentation required for this feature

## Example Configuration

p.conf:
```
[PARSER]
    Name 2939
    Format regex
    Regex ^(?<Index>[^ ]*) (?<log_time>[^ ]*\s[^ ]*) (?<Timestamp>[^ ]*) (?<Count>[^ ]*) (?<ECUID>[^ ]*) (?<APID>[^ ]*) (?<CTID>[^ ]*) (?<SessionID>[^ ]*) (?<Type>[^ ]*) (?<Subtype>[^ ]*) ?(?<Mode>[^ ]*) ?(?<Args>[^ ]*) ?(?<Payload>.*)?$
    Skip_Empty_Values false
```

a.conf:
```
[SERVICE]
    Parsers_File p.conf

[INPUT]
    Name dummy
    Dummy {"log":"2448 2020/12/08 14:41:24.000000 836.1025 59 OTAF PAGY COMP 1134 log warn verbose 1 "}

[FILTER]
    Name parser
    Match *
    key_name log
    parser 2939

[OUTPUT]
    Name stdout
```

## Debug log
The point is `"Payload"=>""`

```
$ bin/fluent-bit -c 2939/a.conf 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/04/24 09:08:39] [ info] [engine] started (pid=34859)
[2021/04/24 09:08:39] [ info] [storage] version=1.1.1, initializing...
[2021/04/24 09:08:39] [ info] [storage] in-memory
[2021/04/24 09:08:39] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/04/24 09:08:39] [ info] [sp] stream processor started
[0] dummy.0: [1619222920.009091886, {"Index"=>"2448", "log_time"=>"2020/12/08 14:41:24.000000", "Timestamp"=>"836.1025", "Count"=>"59", "ECUID"=>"OTAF", "APID"=>"PAGY", "CTID"=>"COMP", "SessionID"=>"1134", "Type"=>"log", "Subtype"=>"warn", "Mode"=>"verbose", "Args"=>"1", "Payload"=>""}]
```

## Valgrind output

```
$ valgrind bin/fluent-bit -c 2939/a.conf 
==34865== Memcheck, a memory error detector
==34865== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==34865== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==34865== Command: bin/fluent-bit -c 2939/a.conf
==34865== 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/04/24 09:10:00] [ info] [engine] started (pid=34865)
[2021/04/24 09:10:00] [ info] [storage] version=1.1.1, initializing...
[2021/04/24 09:10:00] [ info] [storage] in-memory
[2021/04/24 09:10:00] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/04/24 09:10:00] [ info] [sp] stream processor started
==34865== Warning: client switching stacks?  SP change: 0x57e48b8 --> 0x4c9faf0
==34865==          to suppress, use: --max-stackframe=11816392 or greater
==34865== Warning: client switching stacks?  SP change: 0x4c9fa68 --> 0x57e48b8
==34865==          to suppress, use: --max-stackframe=11816528 or greater
==34865== Warning: client switching stacks?  SP change: 0x57e48b8 --> 0x4c9fa68
==34865==          to suppress, use: --max-stackframe=11816528 or greater
==34865==          further instances of this message will not be shown.
[0] dummy.0: [1619223001.020563341, {"Index"=>"2448", "log_time"=>"2020/12/08 14:41:24.000000", "Timestamp"=>"836.1025", "Count"=>"59", "ECUID"=>"OTAF", "APID"=>"PAGY", "CTID"=>"COMP", "SessionID"=>"1134", "Type"=>"log", "Subtype"=>"warn", "Mode"=>"verbose", "Args"=>"1", "Payload"=>""}]
[1] dummy.0: [1619223002.009108520, {"Index"=>"2448", "log_time"=>"2020/12/08 14:41:24.000000", "Timestamp"=>"836.1025", "Count"=>"59", "ECUID"=>"OTAF", "APID"=>"PAGY", "CTID"=>"COMP", "SessionID"=>"1134", "Type"=>"log", "Subtype"=>"warn", "Mode"=>"verbose", "Args"=>"1", "Payload"=>""}]
[2] dummy.0: [1619223003.009435344, {"Index"=>"2448", "log_time"=>"2020/12/08 14:41:24.000000", "Timestamp"=>"836.1025", "Count"=>"59", "ECUID"=>"OTAF", "APID"=>"PAGY", "CTID"=>"COMP", "SessionID"=>"1134", "Type"=>"log", "Subtype"=>"warn", "Mode"=>"verbose", "Args"=>"1", "Payload"=>""}]
[3] dummy.0: [1619223004.009353181, {"Index"=>"2448", "log_time"=>"2020/12/08 14:41:24.000000", "Timestamp"=>"836.1025", "Count"=>"59", "ECUID"=>"OTAF", "APID"=>"PAGY", "CTID"=>"COMP", "SessionID"=>"1134", "Type"=>"log", "Subtype"=>"warn", "Mode"=>"verbose", "Args"=>"1", "Payload"=>""}]
^C[2021/04/24 09:10:06] [engine] caught signal (SIGINT)
[0] dummy.0: [1619223005.042032225, {"Index"=>"2448", "log_time"=>"2020/12/08 14:41:24.000000", "Timestamp"=>"836.1025", "Count"=>"59", "ECUID"=>"OTAF", "APID"=>"PAGY", "CTID"=>"COMP", "SessionID"=>"1134", "Type"=>"log", "Subtype"=>"warn", "Mode"=>"verbose", "Args"=>"1", "Payload"=>""}]
[1] dummy.0: [1619223006.009507713, {"Index"=>"2448", "log_time"=>"2020/12/08 14:41:24.000000", "Timestamp"=>"836.1025", "Count"=>"59", "ECUID"=>"OTAF", "APID"=>"PAGY", "CTID"=>"COMP", "SessionID"=>"1134", "Type"=>"log", "Subtype"=>"warn", "Mode"=>"verbose", "Args"=>"1", "Payload"=>""}]
[2021/04/24 09:10:06] [ warn] [engine] service will stop in 5 seconds
[2021/04/24 09:10:11] [ info] [engine] service stopped
==34865== 
==34865== HEAP SUMMARY:
==34865==     in use at exit: 0 bytes in 0 blocks
==34865==   total heap usage: 658 allocs, 658 frees, 1,408,760 bytes allocated
==34865== 
==34865== All heap blocks were freed -- no leaks are possible
==34865== 
==34865== For lists of detected and suppressed errors, rerun with: -s
==34865== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by seveas** [comment]
> It is to add new option Skip_Empty_Values. Default is true to prevent breaking change.

I believe this will be a breaking change, as for example the logfmt parser currently defaults to _not_ skipping empty values. I kinda want it to, that's how I found this PR 😄 

I'd also want it to keep a field with the original message, would that be useful for your use case as well? For example, I have  a lot of log lines like:

```
This is a sloppy log line, but has some key-value pairs status=ok hello=world meaningOfLife=42
```

Which I'd like to result in a record like `{msg: "This is  a sloppy log line, but has some key-value pairs status=ok hello=world meaningOfLife=42", status: "ok", meaningOfLife: 42}`

**Comment by nokute78** [comment]
@seveas Thank you for comment.
This option is for regex parser not for logfmt, so this PR doesn't affect logfmt parser.

Note: This patch fixes common parser function, so I updated parse_logfmt_fuzzer.c.

**Comment by edsiper** [comment]
@nokute78 can you pls rebase on top of master ?

**Comment by nokute78** [comment]
@edsiper I merged from master.
However it seems to be conflict between multi line parser...

**Comment by nokute78** [comment]
@edsiper I fixed and CI passed.

**Comment by nokute78** [comment]
Thank you for merging.
Doc PR is https://github.com/fluent/fluent-bit-docs/pull/645

**Pull request merged**
