### PR TITLE
flb_utils: remove false positive error 'file not found'.

### PR DESCRIPTION
**Pull request by pwhelan**
# Summary

When retrieving the machine_id for agents, and in some other rare cases, the following error can be spuriously reported:

image

This pushes out the error log so it is not reported when not necessary.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205215063623017

### CODE REVIEW

**Review by niedbalski — APPROVED** [review]
LGTM

**Comment by leonardo-albertovich** [comment]
Hold this until tomorrow please, it seems to me that it actually introduces an error.

**Review by leonardo-albertovich — CHANGES_REQUESTED** [review]
We should remove the `flb_errno` in the `fread` error code pathbecause there are scenarios where a meaningful value for `errno` is not to be expected so we should probably improve that check instead of assuming that `0` means trouble. We should also add an `flb_errno` call in the `fopen` failure code path and a result check for that `fileno` call but I think we can safely ignore the result of `fclose`.

In any case, I can't really see the benefit of removing the `flb_calloc` `flb_errno` call because `flb_calloc` doesn't do it and adding those to the client code can actually print erroneous information and cause issues (eg. `flb_utils_get_machine_id` fails because `RAND_bytes` failed or the `flb_malloc` call in `flb_utils_get_machine_id` which already calls `flb_errno` so we repeat the same message).

Could you please explain the rationale behind this change so we are on the same page?

**Comment by pwhelan** [comment]
> Could you please explain the rationale behind this change so we are on the same page?

The problem is that `flb_utils_get_machine_id` attempts to read the machine id from two different files. If one of them does not exist it will print out 'file not found' error message. This spurious error message is a false negative at best in this scenario.

**Comment by leonardo-albertovich** [comment]
This will definitely affect other use cases, if all you care about is silencing that error message selectively then add a flag to that function named `silence_inexistent_file_error` so whoever uses it in the future is aware of it and has to opt-in to that, otherwise it's just asking for trouble.

**Comment by pwhelan** [comment]
> This will definitely affect other use cases, if all you care about is silencing that error message selectively then add a flag to that function named `silence_inexistent_file_error` so whoever uses it in the future is aware of it and has to opt-in to that, otherwise it's just asking for trouble.

The only two places that function are called have been accounted for. We really should decide where we log error messages. If we log them immediately always it can cause spurious messages, like this specific case. This one also harkens back to the "[lib] Backend failed" error message which has caused nothing but confusion.

**Comment by leonardo-albertovich** [comment]
I'm not against `flb_errno` being "demoted" to `debug` but it's an established behavior so changing it will have an impact and we can't make those changes lightly.

**Comment by leonardo-albertovich** [comment]
I think improving the logging paradigm is a project that we haven't yet started so I'm pretty sure your participation would be appreciated.

In regards to this change, sadly the argument doesn't convince me.

**Comment by pwhelan** [comment]
More than a few plugins already report flb_errno themselves after calling flb APIs. I can include some examples:

[filter_nest/nest.c](https://github.com/fluent/fluent-bit/blob/7c46a40e17858e4607f79cc37061d45f5f6b8e41/plugins/filter_nest/nest.c#L107):
```c
            wildcard->key = flb_strndup(kv->val, flb_sds_len(kv->val));
            if (wildcard->key == NULL) {
                flb_errno();
                flb_free(wildcard);
                return -1;
            }
```

[out_s3/s3_store.c](https://github.com/fluent/fluent-bit/blob/7c46a40e17858e4607f79cc37061d45f5f6b8e41/plugins/out_s3/s3_store.c#L59):
```shell
    /* flb_sds_printf allocs if the incoming sds is not at least 64 bytes */
    hash_str = flb_sds_create_size(64);
    if (!hash_str) {
        flb_errno();
        return NULL;
    }
```

[out_loki/loki.c](https://github.com/fluent/fluent-bit/blob/7c46a40e17858e4607f79cc37061d45f5f6b8e41/plugins/out_loki/loki.c#L475):
```c
        label_key = flb_sds_create_len(val->via.str.ptr, val->via.str.size);
        if (label_key == NULL) {
            flb_errno();
            return -1;
        }
```

Here is a case of an API calling an API and logging `flb_errno`.

[src/flb_pack.c](https://github.com/fluent/fluent-bit/blob/7c46a40e17858e4607f79cc37061d45f5f6b8e41/src/flb_pack.c#L71)
```c
        tmp = flb_realloc(state->tokens, new_size);
        if (!tmp) {
            flb_errno();
            return -1;
        }
```

And [src/flb_network.c](https://github.com/fluent/fluent-bit/blob/7c46a40e17858e4607f79cc37061d45f5f6b8e41/src/flb_network.c#L174) seems to always report with `flb_errno` in it's API. 

At the moment it looks to me like the outlier, but I have not checked every single instead inside src to see which ones apply to the runtime or the API (which is made more difficult by the fact that the separation between them is subjective, at best).

It is a toss up between functions reporting it themselves or the functions that call them reporting it, but with some precedence favoring reporting it from the API itself, but no precedence for some magical `just_keep_quiet` flag.

I personally do not favor adding a magical flag since it seems to me like some weird special case that is likely to amount to future technical debt. It pretty much just makes sense if there are concrete plans to actually remove it in the mid-term future.

**Comment by pwhelan** [comment]
I rewrote the solution to use instead `access(2)` to check the existence of the files `/var/lib/dbus/machine-id` and `/etc/machine-id` and in that way avoid emitting the false positive error message.

It only checks them with F_OK and not R_OK on purpose to not avoid situations where permissions are denied so that that situation can get logged.

This solution should not introduce any corner cases or technical debt and localizes the changes to the single function `flb_utils_get_machine_id` which is only used by the `out_calyptia` plugin at the moment.

**Review by niedbalski — APPROVED** [review]
Lgtm

**Pull request merged**
