### PR TITLE
dockerfile: packaging: Fix build check for centos-7 and failures of package creations 

### PR DESCRIPTION
**Pull request by cosmo0920**
Due to EOL of CentOS7 in the end of last month, we need to use vault repo to obtain CentOS 7 packages.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by cosmo0920** [comment]
In addition, EPEL repo is not moved to use vault. So, we needn't touch it,

**Review by patrick-stephens — DISMISSED** [review]

**Comment by patrick-stephens** [comment]
You don't typically need `yum update` as it is implicitly done, unlike `apt`, but it won't hurt.

**Comment by patrick-stephens** [comment]
@cosmo0920 it looks like we have some failures: https://github.com/fluent/fluent-bit/actions/runs/9791908413/job/27037013628?pr=9043

**Comment by edsiper** [comment]
CI issue here: https://github.com/fluent/fluent-bit/actions/runs/9791908413/job/27037013355?pr=9043

**Comment by cosmo0920** [comment]
Oh, we have to handle packaging side of Dockerfile.

**Comment by cosmo0920** [comment]
I sent patches luajit-cmake which are modified in this PR on https://github.com/zhaozg/luajit-cmake/pull/9.

**Comment by patrick-stephens** [comment]
@edsiper shall we disable CentOS 7 ARM builds until the PR is merged upstream?

**Comment by edsiper** [comment]
@cosmo0920 there are some luajit stuff in the commits

**Comment by edsiper** [comment]
well, its ok to rebase...

**Comment by edsiper** [comment]
thank you!

**Pull request merged**
