### PR TITLE
out_kafka: add dynamic kafka message key setting

### PR DESCRIPTION
**Pull request by pszemus**
To enable better partitioning of kafka messages one would like to set different values for message keys. The best option is to set message key based on one of the message field values.

This pull request adds a configuration parameter to kafka output plugin that provides the possibility of setting the name of the message field whose value will be used as a kafka message key.

In fluent-bit I've seen a convention of configuration parameter naming that adds a suffix "_Key" to parameter name that defines a message field's key name. But in this case it would end up naming "Message_Key_Key", so I chose "Message_Key_Field".

Algorithm:
- if `Message_Key_Field` is set:
   - and that field exists inside a message then that message field's value will be used as kafka message key
   - and that field is not found:
      - and `Message_Key` is set then `Message_Key` will be used as kafka message key
      - and `Message_Key` is not set then an empty kafka message key will be used
- if `Message_Key_Field` is not set then the previous behaviour is preserved

### CODE REVIEW

**Comment by pszemus** [comment]
ping

**Comment by edsiper** [comment]
thanks for the PR, it will be reviewed shortly.

**Comment by nigels-com** [comment]
Looks good to me.

**Comment by edsiper** [comment]
thanks for your contribution, the PR looks good.

Before to merge this feature, please also open a new PR on [fluent/fluent-bit-docs](https://github.com/fluent/fluent-bit-docs) documenting this new feature. Once done we can merge 

thanks

**Comment by pszemus** [comment]
@edsiper https://github.com/fluent/fluent-bit-docs/pull/155
(sorry for accidentally force-pushing those commits again)

**Comment by pszemus** [comment]
@edsiper ping?

**Comment by pszemus** [comment]
@edsiper ping? will you take a look at docs and please merge this PR?

**Comment by mariuscoto** [comment]
👍 would love to have this feature

**Comment by wkuranowski** [comment]
@mariuscoto We switched to "filebeat" because we no longer had the patience to wait for this and many other problems to be solved.

**Comment by gjcarneiro** [comment]
I'm also interested in this feature, so that we can ship kubernetes container logs and have them preserve order.  At the moment, message key is null, so different messages of the same container may end up in different partitions, resulting in the log server writing them to file in undefined order.

**Comment by gjcarneiro** [comment]
I tried to test this branch, but couldn't get message key to work.  I might have done something wrong.  I tried both `Message_Key_Field pod_name` and `Message_Key_Field kubernetes.pod_name`, no luck with either.

**Comment by thuandt** [comment]
This PR is not merge yet but documents has been merged. That's so confused :(

**Comment by nickbroon** [comment]
I bumped into this as well. The documentation was updated, but feature was never committed!
https://docs.fluentbit.io/manual/v/1.3/output/kafka

Can this PR be merged?

**Comment by Ju-Li-An** [comment]
We also need this feature. We want to switch from filebeat to fluentbit but without this feature we can't. Can you give us a date for this PR to be merged?
Thank you.

**Comment by ttqin** [comment]
we would love to see this feature too

**Comment by pathikritmodak** [comment]
Can we get this committed please, the docs have been updated but the feature hasn't been live yet.

**Comment by pjaitken** [comment]
@pszemus can you fix the conflicts?

**Comment by pszemus** [comment]
@pjaitken I've fixed all conflicts, but I doubt it'll make this PR merged.

**Comment by pjaitken** [comment]
@edsiper what do you need to get this merged?

**Comment by pjaitken** [comment]
@edsiper can this be merged now?

**Comment by potapum** [comment]
@edsiper we're also waiting for merge of this PR. Could you please expedite review?

**Comment by simonasr** [comment]
Well this is confusing.. We were designing new project based on recent documentation and heavily relied in this feature.. 😮 @edsiper could you please update status. Is this PR expected to be merged? 🙏

**Comment by wkuranowski** [comment]
This is not the only thing that is documented and not implemented. I suggest you to use filebeat, which seems to be more mature and has the necessary functionality.

**Comment by edsiper** [comment]
thanks everyone.

fyi: I've backported the patch to v1.3 branch, so the feature will be in the next v1.3.4 release this week

**Comment by agarwri** [comment]
I'm using td-agent-bit v1.3.11 and this feature doesn't seem to work. Do the td-agent-bit versions correspond to fluentbit?

**Comment by isaidashev** [comment]
How is this supposed to work?

**Comment by pjaitken** [comment]
@isaidashev the algorithm is described at the top of this page:

    if Message_Key_Field is set:
        and that field exists inside a message then that message field's value will be used as kafka message key
        and that field is not found:
            and Message_Key is set then Message_Key will be used as kafka message key
            and Message_Key is not set then an empty kafka message key will be used
    if Message_Key_Field is not set then the previous behaviour is preserved

It's also summarised in [the docs](https://github.com/fluent/fluent-bit-docs/blob/master/pipeline/outputs/kafka.md):

> Message_Key_Field | If set, the value of Message_Key_Field in the record  will indicate the message key. If not set nor found in the record,  Message_Key will be used (if set).

**Pull request merged**
