### PR TITLE
out_kafka: fix segmentation fault issue while produce_message

### LINKED ISSUE #6451: Occasional segmentation fault in out_kafka
## Bug Report

**Describe the bug**
Segmentation fault is caused occasionally. Actually, I did core file analysis using gdb and identified how to fix. I'll submit a PR soon.

Stacktrace:

```
Nov 23, 2022 @ 00:53:23.362 | [2022/11/22 15:53:23] [engine] caught signal (SIGSEGV)
-- | --

  | Nov 23, 2022 @ 00:53:23.473 | #0  0xaaaad87abb10      in  produce_message() at plugins/out_kafka/kafka.c:189

  | Nov 23, 2022 @ 00:53:23.473 | #1  0xaaaad87ac50b      in  cb_kafka_flush() at plugins/out_kafka/kafka.c:483

  | Nov 23, 2022 @ 00:53:23.473 | #2  0xaaaad84a4a17      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:519

  | Nov 23, 2022 @ 00:53:23.473 | #3  0xaaaad8ede3fb      in  co_switch() at lib/monkey/deps/flb_libco/aarch64.c:133

  | Nov 23, 2022 @ 00:53:23.473 | #4  0xffffffffffffffff  in  ???() at ???:0
```

**To Reproduce**
I don't know how to reproduce. I tried to input the same message, but it did not crash.

**Expected behavior**
It should not happen.

**Your Environment**
* Version used: fluent-bit:2.0.3-debug (https://hub.docker.com/layers/fluent/fluent-bit/2.0.3-debug/images/sha256-16b44e6a80ef583e780889bc05de0c18aa556243d0c863d0d4fddfd32a89f600?context=explore)
* Configuration: in_tail / filter_modify / out_kafka
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.22, attached to a pod as sidecar
* Server type and version: kafka
* Operating System and version: bottlerocket 1.9.2 on arm64
* Filters and plugins: filter_modify / out_kafka

### PR DESCRIPTION
**Pull request by qbx2**
Fix segmentation fault in out_kafka.

Stacktrace:
```
Nov 23, 2022 @ 00:53:23.362 | [2022/11/22 15:53:23] [engine] caught signal (SIGSEGV)
-- | --

  | Nov 23, 2022 @ 00:53:23.473 | #0  0xaaaad87abb10      in  produce_message() at plugins/out_kafka/kafka.c:189

  | Nov 23, 2022 @ 00:53:23.473 | #1  0xaaaad87ac50b      in  cb_kafka_flush() at plugins/out_kafka/kafka.c:483

  | Nov 23, 2022 @ 00:53:23.473 | #2  0xaaaad84a4a17      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:519

  | Nov 23, 2022 @ 00:53:23.473 | #3  0xaaaad8ede3fb      in  co_switch() at lib/monkey/deps/flb_libco/aarch64.c:133

  | Nov 23, 2022 @ 00:53:23.473 | #4  0xffffffffffffffff  in  ???() at ???:0
```

Fix #6451 

Thank you @Jinmo , for kindly helping me troubleshooting !

----
**Testing**
We tested this change by deploying custom-build to our production application. Segmentation fault is not being caused.

- [N/A] Example configuration file for the change
- [N/A] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [X] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by qbx2** [comment]
Because the core dump contains confidential memory, it's difficult to share. However, I may share some debugging information.

```
pwndbg> bt
#0  __GI_abort () at abort.c:107
#1  0x0000aaaade5847c4 in flb_signal_handler (signal=11) at /src/fluent-bit/src/fluent-bit.c:587
#2  <signal handler called>
#3  0x0000aaaade93bb10 in produce_message (tm=0xffff9a641568, map=0xffff9a651020, ctx=0xffff9d8160e0, config=0xffff9ea31580) at /src/fluent-bit/plugins/out_kafka/kafka.c:189
#4  0x0000aaaade93c50c in cb_kafka_flush (event_chunk=0xffff9d83ad20, out_flush=0xffff9a60d000, i_ins=0xffff9ea8c000, out_context=0xffff9d8160e0, config=0xffff9ea31580) at /src/fluent-bit/plugins/out_kafka/kafka.c:483
#5  0x0000aaaade634a18 in output_pre_cb_flush () at /src/fluent-bit/include/fluent-bit/flb_output.h:519
#6  0x0000aaaadf06e3fc in co_switch (handle=0x0) at /src/fluent-bit/lib/monkey/deps/flb_libco/aarch64.c:133
#7  0x0000000000000000 in ?? ()

pwndbg> frame 3
#3  0x0000aaaade93bb10 in produce_message (tm=0xffff9a641568, map=0xffff9a651020, ctx=0xffff9d8160e0, config=0xffff9ea31580) at /src/fluent-bit/plugins/out_kafka/kafka.c:189
189             key = map->via.map.ptr[i].key;
```
Note that `map->type` is `MSGPACK_OBJECT_FLOAT64`, and the code is referring `map->via` as `map` type.
```
pwndbg> p *map
$7 = {
  type = MSGPACK_OBJECT_FLOAT64,
  via = {
    boolean = 48,
    u64 = 4744787967024849456,
    i64 = 4744787967024849456,
    f64 = 1669206388.2559929,
    array = {
      size = 1561354800,
      ptr = 0xffff9a66a002
    },
    map = {
      size = 1561354800,
      ptr = 0xffff9a66a002
    },
    str = {
      size = 1561354800,
      ptr = 0xffff9a66a002 "\020b1\252@timestamp\313A\330\337\204]\020b0", '\300' <repeats 177 times>...
    },
    bin = {
      size = 1561354800,
      ptr = 0xffff9a66a002 "\020b1\252@timestamp\313A\330\337\204]\020b0", '\300' <repeats 177 times>...
    },
    ext = {
      type = 48 '0',
      size = 1104732036,
      ptr = 0xffff9a66a002 "\020b1\252@timestamp\313A\330\337\204]\020b0", '\300' <repeats 177 times>...
    }
  }
}
```
This is caused by:
```
pwndbg> frame 4
#4  0x0000aaaade93c50c in cb_kafka_flush (event_chunk=0xffff9d83ad20, out_flush=0xffff9a60d000, i_ins=0xffff9ea8c000, out_context=0xffff9d8160e0, config=0xffff9ea31580) at /src/fluent-bit/plugins/out_kafka/kafka.c:483
483             ret = produce_message(&tms, obj, ctx, config);

pwndbg> p result
$8 = {
  zone = 0x0,
  data = {
    type = MSGPACK_OBJECT_POSITIVE_INTEGER,
    via = {
      boolean = false,
      u64 = 0,
      i64 = 0,
      f64 = 0,
      array = {
        size = 0,
        ptr = 0xaaaadf0535c0 <msgpack_unpack_next+100>
      },
      map = {
        size = 0,
        ptr = 0xaaaadf0535c0 <msgpack_unpack_next+100>
      },
      str = {
        size = 0,
        ptr = 0xaaaadf0535c0 <msgpack_unpack_next+100> "\340/@\371\340\063"
      },
      bin = {
        size = 0,
        ptr = 0xaaaadf0535c0 <msgpack_unpack_next+100> "\340/@\371\340\063"
      },
      ext = {
        type = 0 '\000',
        size = 0,
        ptr = 0xaaaadf0535c0 <msgpack_unpack_next+100> "\340/@\371\340\063"
      }
    }
  }
}

pwndbg> p *event_chunk
$11 = {
  type = 0,
  tag = 0xffff9d84c090 "<tag removed>",
  data = 0xffff9ef1402a,
  size = 4911,
  total_events = 1
}

pwndbg> p off
$12 = 859
```
I dumped memory from event_chunk->data to event_chunk->data+size to file, and used msgpack-python to unpack it. 
```
>>> import msgpack
>>> msgpack.unpack(open('dump', 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hpcnt/.pyenv/versions/3.11.0/lib/python3.11/site-packages/msgpack/__init__.py", line 49, in unpack
    return unpackb(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
```
I sliced the file to offset 857, and it worked without an error.
```
>>> msgpack.unpackb(x[:857])[0]
ExtType(code=0, data=b'c~\x11t\x0fB$\n')
```

**Review by nokute78 — APPROVED** [review]
Thank you. LGTM.

**Comment by qbx2** [comment]
@nokute78 
Thank you for fast response. Could you tell me when is it going to be merged?

**Comment by nokute78** [comment]
@edsiper @niedbalski Could you merge this ?

There are similar PRs(#4320) to fix the issue #6451

**Comment by edsiper** [comment]
Thanks for troubleshooting and contributing to this PR. 

We will merge this as it makes sure to solve the problem and skip invalid records. Still, how those invalid records which are not an array were generated ?, this is an unexpected behavior, so I would encourage everybody to help to try to discover which input plugin or filter generated a damaged record.

**Comment by qbx2** [comment]
I was using tail_file as input plugin with json parser, filter_modify to add ip field, and out_kafka to produce message. Input is rotated by application, it seems not to be relevant because the segmentation fault usually happened (not always) 30 minutes after rotation. I did investigation with fluent-bit source code and coredump, but I could not find any abnormal signs.

**Comment by supergillis** [comment]
When can we expect new version including this fix?

**Pull request merged**
