### PR TITLE
filter_multiline: implemented buffered mode using in_emitter

### PR DESCRIPTION
**Pull request by PettitWesley**
Master version of: https://github.com/fluent/fluent-bit/pull/4383

Part of: https://github.com/fluent/fluent-bit/issues/4309

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [x] Documentation required for this feature
https://github.com/fluent/fluent-bit-docs/pull/675

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by PettitWesley** [comment]
@edsiper I am blocked in testing this till this issue is fixed: https://github.com/fluent/fluent-bit/issues/4670

**Comment by alexku7** [comment]
Hello
I am getting errors after upgrading to 1.18.12 and using the multiline filters. The pod is crashing.

I suspect that the issue is related to that PR.
The issue is described here:
https://github.com/fluent/fluent-bit/issues/4712

**Comment by edsiper** [comment]
looks like is failing due to old code ?

https://github.com/fluent/fluent-bit/runs/4910999830?check_suite_focus=true#step:5:1464

I suggest to rebase this on top of master so we can trigger the CI again

**Comment by PettitWesley** [comment]
@edsiper I rebased and then re-tested. However, some checks are still failing but it looks like its failing tests that weren't changed by my code...

**Comment by edsiper** [comment]
@PettitWesley not sure what can be, can you re-rebase again ?

**Comment by PettitWesley** [comment]
@lecaros Can we get this in 1.9.2? We already released it in 1.8, and I just pushed a commit which should fix the CI failure.

**Pull request merged**
