### PR TITLE
mem: add chance of failing flb_malloc when fuzzing

### PR DESCRIPTION
**Pull request by DavidKorczynski**
this will increase coverage of fluent-bit code when fuzzing and also
help us find places where there is no check on the value returned by
flb_malloc.

Signed-off-by: David Korczynski <david@adalogics.com>

This only changes fuzzing run time. 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [N/A] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Notice CIFuzz test fails because of this addition, however, I will like fixes should not happen at the same time? @edsiper please advice

**Comment by DavidKorczynski** [comment]
@edsiper - any updates on this one? Could this be merged?

**Comment by edsiper** [comment]
I see the fuzzing test failing, is it expected ?

**Comment by DavidKorczynski** [comment]
> I see the fuzzing test failing, is it expected ?

Yes. This will temporarily cause some fuzzers to find NULL-dereferences very early (in the first fuzz run). This is good to go.

**Comment by edsiper** [comment]
can you pls rebase on top of master ?

**Comment by DavidKorczynski** [comment]
> can you pls rebase on top of master ?

Done.

As I wrote above, CIFuzz fails intentionally. This is because the changes in this PR finds many places where there are missing NULL checks, and thus potential null dereferences in the (unlikely) event malloc return NULL. 

It would be great if this can be merged soon

**Pull request merged**
