### PR TITLE
out_stackdriver: Enable custom regex to parse tag for stackdriver meta labels

### PR DESCRIPTION
**Pull request by JeffLuoo**
Signed-off-by: Jeff Luo <jeffluoo@google.com>

With this patch, we can set an alternative regex to process record Tag and extract pod_name, namespace_name, container_name.

Similar to `Regex_Parser` from [kubernetes filter ](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#workflow-of-tail-kubernetes-filter).

Rule:
1. If the tag (without prefix) matches the regex specified in the `custom_regex` field, then the `loca_resource_id` won't be parsed to extract the meta labels. Meta labels will be extracted from log tag based on regex.
2. If the tag (without prefix) doesn't match the regex specified, `local_resource_id` will be parsed to extract meta labels.

Default regex is:
`"(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\\.log$"`

#3189 
----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change
- [x] Debug log output from testing the change

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [x] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by JeffLuoo** [comment]
```
jeffluoo@jeffluoo.c ~/fluent-bit/build% sudo valgrind ./bin/fluent-bit -c ../conf/in_dummy.conf
==2556930== Memcheck, a memory error detector
==2556930== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2556930== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==2556930== Command: ./bin/fluent-bit -c ../conf/in_dummy.conf
==2556930== 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/03/09 20:22:51] [ info] Configuration:
[2021/03/09 20:22:51] [ info]  flush time     | 1.000000 seconds
[2021/03/09 20:22:51] [ info]  grace          | 5 seconds
[2021/03/09 20:22:51] [ info]  daemon         | 0
[2021/03/09 20:22:51] [ info] ___________
[2021/03/09 20:22:51] [ info]  inputs:
[2021/03/09 20:22:51] [ info]      dummy
[2021/03/09 20:22:51] [ info] ___________
[2021/03/09 20:22:51] [ info]  filters:
[2021/03/09 20:22:51] [ info] ___________
[2021/03/09 20:22:51] [ info]  outputs:
[2021/03/09 20:22:51] [ info]      stackdriver.0
[2021/03/09 20:22:51] [ info] ___________
[2021/03/09 20:22:51] [ info]  collectors:
[2021/03/09 20:22:51] [ info] [engine] started (pid=2556930)
[2021/03/09 20:22:51] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2021/03/09 20:22:51] [debug] [storage] [cio scan] opening path /var/log/fluent-bit-buffers/
[2021/03/09 20:22:51] [debug] [storage] [cio stream] new stream registered: dummy.0
[2021/03/09 20:22:51] [debug] [storage] [cio stream] new stream registered: storage_backlog.1
[2021/03/09 20:22:51] [ info] [storage] version=1.1.1, initializing...
[2021/03/09 20:22:51] [ info] [storage] root path '/var/log/fluent-bit-buffers/'
[2021/03/09 20:22:51] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/03/09 20:22:51] [ info] [storage] backlog input plugin: storage_backlog.1
[2021/03/09 20:22:51] [ info] [input:storage_backlog:storage_backlog.1] queue memory limit: 95.4M
[2021/03/09 20:22:51] [debug] [stackdriver:stackdriver.0] created event channels: read=18 write=19
[2021/03/09 20:22:51] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2021/03/09 20:22:51] [debug] [output:stackdriver:stackdriver.0] JWT signature:
eyJhbGciOiAiUlMyNTYiLCAidHlwIjogIkpXVCJ9.eyJpc3MiOiAiamVmZmx1b28tZ2tlLWRldi1sb2dnaW5nQGplZmZsdW9vLWdrZS1kZXYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCAic2NvcGUiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vYXV0aC9sb2dnaW5nLndyaXRlIiwgImF1ZCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjQvdG9rZW4iLCAiZXhwIjogMTYxNTMyNDM3MSwgImlhdCI6IDE2MTUzMjEzNzF9.jvmmktjfxhMaTUrt4UgHK-IKzbfD6RV1KqtTkM8lXPAIE3WHzLHV2PzBIiFqT-dpoeQkd3BaOu_jZj8QjVPBDJHCeyxdDK3GKBzce1HKm6DiBFm9vPGw_mHmCB3XS3xMEgI5UghaqCBbM-Z-0H5P7SJIsppz_Dbg_B5JIFHx_i2MtAqoytWXU8M3ICTmpHCAc4D0X1Q429XojRve2pu2n0131GQ2c4fPV3LlOFnHrEtdr4WNd8aNI-A1iX5R0q8X4lXMBXcGhGrqA-trl7LViKr0QUC_og30Xu9LA0YlcLtZlAjxXFeOLkpCPyDIX2F3z9ZOHdHrggphdKfbwBR1YA
[2021/03/09 20:22:53] [debug] [http_client] not using http_proxy for header
[2021/03/09 20:22:53] [debug] [http_client] header=POST /oauth2/v4/token HTTP/1.1
Host: www.googleapis.com
Content-Length: 749
Content-Type: application/x-www-form-urlencoded


[2021/03/09 20:22:53] [ info] [oauth2] HTTP Status=200
[2021/03/09 20:22:53] [debug] [oauth2] payload:
{"access_token":"ya29.c.Kp8B9gc_vu9dxfv21xe7EXIeFn7CKnaFADa3BjIMcnPt3OxYqoU21K7Tabkx0raUXIac81kUQ3HuJPBKLz_0hoh3vySwpQsxyNEu6-7K1nk8jOJ7H61Dp1UksPdmj8Qdz1DWaggfc2merNm5UslnAUq75Mkby43y8BIXCnMQ7_OQTFHXjCUMUaL3qiPvnMQ3UrRwV2OeG12Jb3zp0oKqhk2l","expires_in":3599,"token_type":"Bearer"}
[2021/03/09 20:22:53] [ info] [oauth2] access token from 'www.googleapis.com:443' retrieved
[2021/03/09 20:22:53] [debug] [router] match rule dummy.0:stackdriver.0
[2021/03/09 20:22:53] [ info] [sp] stream processor started
[2021/03/09 20:22:54] [debug] [task] created task=0x5423a90 id=0 OK
[2021/03/09 20:22:54] [debug] [output:stackdriver:stackdriver.0] local_resource_id not found, tag [k8s_container.namespace.pod.container] is assigned for local_resource_id
[2021/03/09 20:22:54] [debug] [output:stackdriver:stackdriver.0] [logging.googleapis.com/monitored_resource] not found in the payload
[2021/03/09 20:22:54] [debug] [http_client] not using http_proxy for header
[2021/03/09 20:22:54] [debug] [http_client] header=POST /v2/entries:write HTTP/1.1
Host: logging.googleapis.com
Content-Length: 484
User-Agent: Fluent-Bit
Content-Type: application/json
Authorization: Bearer ya29.c.Kp8B9gc_vu9dxfv21xe7EXIeFn7CKnaFADa3BjIMcnPt3OxYqoU21K7Tabkx0raUXIac81kUQ3HuJPBKLz_0hoh3vySwpQsxyNEu6-7K1nk8jOJ7H61Dp1UksPdmj8Qdz1DWaggfc2merNm5UslnAUq75Mkby43y8BIXCnMQ7_OQTFHXjCUMUaL3qiPvnMQ3UrRwV2OeG12Jb3zp0oKqhk2l


[2021/03/09 20:22:54] [debug] [output:stackdriver:stackdriver.0] HTTP Status=200
[2021/03/09 20:22:54] [debug] [socket] could not validate socket status for #27 (don't worry)
[2021/03/09 20:22:54] [debug] [out coro] cb_destroy coro_id=0
[2021/03/09 20:22:54] [debug] [task] destroy task=0x5423a90 (task_id=0)
[2021/03/09 20:22:55] [debug] [task] created task=0x54df580 id=0 OK
[2021/03/09 20:22:55] [debug] [output:stackdriver:stackdriver.0] local_resource_id not found, tag [k8s_container.namespace.pod.container] is assigned for local_resource_id
[2021/03/09 20:22:55] [debug] [output:stackdriver:stackdriver.0] [logging.googleapis.com/monitored_resource] not found in the payload
[2021/03/09 20:22:55] [debug] [http_client] not using http_proxy for header
[2021/03/09 20:22:55] [debug] [http_client] header=POST /v2/entries:write HTTP/1.1
Host: logging.googleapis.com
Content-Length: 484
User-Agent: Fluent-Bit
Content-Type: application/json
Authorization: Bearer ya29.c.Kp8B9gc_vu9dxfv21xe7EXIeFn7CKnaFADa3BjIMcnPt3OxYqoU21K7Tabkx0raUXIac81kUQ3HuJPBKLz_0hoh3vySwpQsxyNEu6-7K1nk8jOJ7H61Dp1UksPdmj8Qdz1DWaggfc2merNm5UslnAUq75Mkby43y8BIXCnMQ7_OQTFHXjCUMUaL3qiPvnMQ3UrRwV2OeG12Jb3zp0oKqhk2l


[2021/03/09 20:22:55] [debug] [output:stackdriver:stackdriver.0] HTTP Status=200
[2021/03/09 20:22:55] [debug] [socket] could not validate socket status for #27 (don't worry)
[2021/03/09 20:22:55] [debug] [out coro] cb_destroy coro_id=1
[2021/03/09 20:22:55] [debug] [task] destroy task=0x54df580 (task_id=0)
^C[2021/03/09 20:22:56] [engine] caught signal (SIGINT)
[2021/03/09 20:22:56] [ info] [input] pausing storage_backlog.1
[2021/03/09 20:22:56] [debug] [task] created task=0x5592240 id=0 OK
[2021/03/09 20:22:56] [ warn] [engine] service will stop in 5 seconds
[2021/03/09 20:22:56] [debug] [output:stackdriver:stackdriver.0] local_resource_id not found, tag [k8s_container.namespace.pod.container] is assigned for local_resource_id
[2021/03/09 20:22:56] [debug] [output:stackdriver:stackdriver.0] [logging.googleapis.com/monitored_resource] not found in the payload
[2021/03/09 20:22:56] [debug] [http_client] not using http_proxy for header
[2021/03/09 20:22:56] [debug] [http_client] header=POST /v2/entries:write HTTP/1.1
Host: logging.googleapis.com
Content-Length: 484
User-Agent: Fluent-Bit
Content-Type: application/json
Authorization: Bearer ya29.c.Kp8B9gc_vu9dxfv21xe7EXIeFn7CKnaFADa3BjIMcnPt3OxYqoU21K7Tabkx0raUXIac81kUQ3HuJPBKLz_0hoh3vySwpQsxyNEu6-7K1nk8jOJ7H61Dp1UksPdmj8Qdz1DWaggfc2merNm5UslnAUq75Mkby43y8BIXCnMQ7_OQTFHXjCUMUaL3qiPvnMQ3UrRwV2OeG12Jb3zp0oKqhk2l


[2021/03/09 20:22:56] [debug] [output:stackdriver:stackdriver.0] HTTP Status=200
[2021/03/09 20:22:56] [debug] [socket] could not validate socket status for #24 (don't worry)
[2021/03/09 20:22:56] [debug] [out coro] cb_destroy coro_id=2
[2021/03/09 20:22:56] [debug] [task] destroy task=0x5592240 (task_id=0)
[2021/03/09 20:22:56] [debug] [input chunk] dummy.0 is paused, cannot append records
[2021/03/09 20:22:57] [debug] [input chunk] dummy.0 is paused, cannot append records
[2021/03/09 20:22:58] [debug] [input chunk] dummy.0 is paused, cannot append records
[2021/03/09 20:22:59] [debug] [input chunk] dummy.0 is paused, cannot append records
[2021/03/09 20:23:00] [debug] [input chunk] dummy.0 is paused, cannot append records
[2021/03/09 20:23:00] [ info] [engine] service stopped
[2021/03/09 20:23:00] [debug] [socket] could not validate socket status for #20 (don't worry)
==2556930== 
==2556930== HEAP SUMMARY:
==2556930==     in use at exit: 108,139 bytes in 3,678 blocks
==2556930==   total heap usage: 13,087 allocs, 9,409 frees, 3,043,243 bytes allocated
==2556930== 
==2556930== LEAK SUMMARY:
==2556930==    definitely lost: 0 bytes in 0 blocks
==2556930==    indirectly lost: 0 bytes in 0 blocks
==2556930==      possibly lost: 0 bytes in 0 blocks
==2556930==    still reachable: 108,139 bytes in 3,678 blocks
==2556930==         suppressed: 0 bytes in 0 blocks
==2556930== Rerun with --leak-check=full to see details of leaked memory
==2556930== 
==2556930== For lists of detected and suppressed errors, rerun with: -s
==2556930== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

```
[SERVICE]
    Flush                      1
    Log_Level                  debug
    Parsers_File               parsers.conf
    storage.path               /var/log/fluent-bit-buffers/
    storage.sync               normal
    http_server  Off

[INPUT]
    Name              dummy
    Tag               k8s_container.namespace.pod.container
    dummy             {"key": 1, "sub": {"stream": "stdout", "id": "some id"}, "kubernetes": {"labels": {"team": "Santiago Wanderers"}}}

[OUTPUT]
    Name        stackdriver
    Match       k8s_container.*
    Resource    k8s_container
    k8s_cluster_name test_cluster_name
    k8s_cluster_location  test_cluster_location
    google_service_credentials   /usr/local/google/home/jeffluoo/credentials.json
    custom_regex ^(?<namespace_name>[^_]+)\.(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<container_name>.+)$

```

**Comment by JeffLuoo** [comment]
Please add @erain @courageJ for review.

**Review by erain — APPROVED** [review]
LGTM, and this is very useful for Kubernetes use case since we can can set and make use of the regex as in https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#workflow-of-tail-kubernetes-filter

**Comment by JeffLuoo** [comment]
@edsiper PTAL when available : )
 Thanks!

**Pull request closed without merging**
