### PR TITLE
in_random : add test code and add explanation

### PR DESCRIPTION
**Pull request by nokute78**
I add new test code and update README.md.

Result of test is  like this.
```  sh
$ bin/flb_test_in_random 
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Inputs
[ RUN      ] Inputs.flush_5s
[2016/08/22 21:03:13] [ info] [engine] started
[2016/08/22 21:03:18] [ warn] [engine] service will stop in 5 seconds
[2016/08/22 21:03:23] [ info] [engine] service stopped
[       OK ] Inputs.flush_5s (9981 ms)
[----------] 1 test from Inputs (9981 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (9981 ms total)
[  PASSED  ] 1 test.
```

### CODE REVIEW

**Comment by nokute78** [comment]
The failure of Travis CI is caused by missing header `fluent-bit/flb_engine_task.h`.
It also happens 29a64313c96166a1460ee8e9f404036e6b06b22c . 
https://travis-ci.org/fluent/fluent-bit/jobs/152874646

Could you add the header file?

**Comment by edsiper** [comment]
Master branch is facing some changes, the runtime based on ucontext is working fine, but when using the pthreads mode (for compilers that do not support ucontext) is still pending. It uses the old interface. That should be updated shortly.

**Comment by nokute78** [comment]
Thanks.
So, I'm waiting.

**Comment by edsiper** [comment]
fixed by 0dc24675dd2b25f13ece4502e5911d39155d3b77

**Comment by nokute78** [comment]
0dc24675dd2b25f13ece4502e5911d39155d3b77 is not completely fixed. Travis-CI failed.
Could you check it ?

**Comment by edsiper** [comment]
fixed by 6ee443397d7f9df0b785123bfc843a1c0dbd7ec2

**Pull request merged**
