### PR TITLE
node_exporter_metrics: Align the collecting metrics of unit statuses

### PR DESCRIPTION
**Pull request by cosmo0920**
In the original node_exporter, it only uses 0 or 1 which means that this status is active or not.
To represent this specification on Fluent Bit, we need to fill as 0 at first. Then, we need filling with 1 for the active statuses.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [x] Example configuration file for the change

```
$bin/fluent-bit -i node_exporter_metrics -o stdout -v
```

- [ ] Debug log output from testing the change

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

```
==3791369== 
==3791369== HEAP SUMMARY:
==3791369==     in use at exit: 0 bytes in 0 blocks
==3791369==   total heap usage: 228,729 allocs, 228,729 frees, 13,302,851,339 bytes allocated
==3791369== 
==3791369== All heap blocks were freed -- no leaks are possible
==3791369== 
==3791369== For lists of detected and suppressed errors, rerun with: -s
==3791369== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by edsiper** [comment]
adding @pwhelan for review

**Comment by edsiper** [comment]
@cosmo0920 what's the main difference with the implementation proposed on #9136 ?

**Comment by cosmo0920** [comment]
> @cosmo0920 what's the main difference with the implementation proposed on #9136 ?

The main difference is: This PR will set _all of 0 value_. And set 1 only for an active state.
The #9136 will set 1 for an active state and other state will be set as 0.

**Comment by pwhelan** [comment]
I had not seen originally that this one set the states, since it does just merge this one.

**Comment by edsiper** [comment]
thanks both

**Comment by edsiper** [comment]
@cosmo0920 note: `in_node_exporter_metrics: ...`

**Pull request merged**
