### PR TITLE
Add output plugin: syslog_out plugin

### PR DESCRIPTION
**Pull request by ginobiliwang**
This plugin could output syslog format message, i have implemented syslog-rfc3164 format.Will add syslog-rfc5424 format shortly. 
Here is the demo output.

```
[root@sdw1 build]# cat bin/sys_out.conf
[OUTPUT]
    Name  syslog
    Match *
    Host  10.152.9.51
    Port  5140
    Format json
[INPUT]
    Name dummy
[root@sdw1 build]#
[root@sdw1 build]# cat /tmp/in_syslog.conf
[SERVICE]
    Flush        1
    Parsers_File parsers.conf

[INPUT]
    Name     syslog
    #Path     /tmp/in_syslog
    Listen   0.0.0.0
    Port     5140
    Mode     TCP
    Parser   syslog-rfc3164-local

[OUTPUT]
    Name     stdout
    Match    *
[root@sdw1 build]#
[root@sdw1 build]# bin/fluent-bit   -c  /tmp/in_syslog.conf  -R /home/fwang/fluent-bit/conf/parsers.conf
Fluent Bit v1.3.0
Copyright (C) Treasure Data

[2019/09/03 05:07:05] [Warning] [config] I cannot open /tmp/parsers.conf file
[2019/09/03 05:07:05] [ info] [storage] initializing...
[2019/09/03 05:07:05] [ info] [storage] in-memory
[2019/09/03 05:07:05] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2019/09/03 05:07:05] [ info] [engine] started (pid=17898)
[2019/09/03 05:07:05] [ info] [in_syslog] TCP server binding 0.0.0.0:5140
[2019/09/03 05:07:05] [ info] [sp] stream processor started
[0] syslog.0: [1567501626.000000000, {"pri"=>"177", "time"=>"Sep 03 09:07:06", "ident"=>"sdw1", "message"=>"[{"date":1567501615.000130,"message":"dummy"},{"date":1567501616.000087,"message":"dummy"},{"date":1567501617.000090,"message":"dummy"},{"date":1567501618.000088,"message":"dummy"}]"}]
[0] syslog.0: [1567501628.000000000, {"pri"=>"177", "time"=>"Sep 03 09:07:08", "ident"=>"sdw1", "message"=>"[{"date":1567501624.000220,"message":"dummy"},{"date":1567501625.000084,"message":"dummy"},{"date":1567501626.000108,"message":"dummy"},{"date":1567501627.000207,"message":"dummy"},{"date":1567501628.000156,"message":"dummy"}]"}]
[0] syslog.0: [1567501633.000000000, {"pri"=>"177", "time"=>"Sep 03 09:07:13", "ident"=>"sdw1", "message"=>"[{"date":1567501629.000213,"message":"dummy"},{"date":1567501630.000089,"message":"dummy"},{"date":1567501631.000088,"message":"dummy"},{"date":1567501632.000156,"message":"dummy"},{"date":1567501633.000091,"message":"dummy"}]"}]
[1] syslog.0: [1567501633.000000000, {"pri"=>"177", "time"=>"Sep 03 09:07:13", "ident"=>"sdw1", "message"=>"[{"date":1567501619.000393,"message":"dummy"},{"date":1567501620.000089,"message":"dummy"},{"date":1567501621.000089,"message":"dummy"},{"date":1567501622.000084,"message":"dummy"},{"date":1567501623.000088,"message":"dummy"}]"}]
[0] syslog.0: [1567501639.000000000, {"pri"=>"177", "time"=>"Sep 03 09:07:19", "ident"=>"sdw1", "message"=>"[{"date":1567501634.000254,"message":"dummy"},{"date":1567501635.000119,"message":"dummy"},{"date":1567501636.000112,"message":"dummy"},{"date":1567501637.000088,"message":"dummy"},{"date":1567501638.000091,"message":"dummy"}]"}]
^C[engine] caught signal (SIGINT)
[2019/09/03 05:07:21] [ info] [input] pausing syslog.0
[root@sdw1 build]#
```

```
[root@sdw1 build]# bin/fluent-bit   -c bin/sys_out.conf
Fluent Bit v1.3.0
Copyright (C) Treasure Data

[2019/09/03 05:06:54] [ info] [storage] initializing...
[2019/09/03 05:06:54] [ info] [storage] in-memory
[2019/09/03 05:06:54] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2019/09/03 05:06:54] [ info] [engine] started (pid=17896)
[2019/09/03 05:06:54] [ info] [sp] stream processor started
[2019/09/03 05:06:58] [error] [io] TCP connection failed: 10.152.9.51:5140 (Connection refused)
[2019/09/03 05:06:58] [error] [out_syslog] no upstream connections available to 10.152.9.51:5140
[2019/09/03 05:07:03] [error] [io] TCP connection failed: 10.152.9.51:5140 (Connection refused)
[2019/09/03 05:07:03] [error] [out_syslog] no upstream connections available to 10.152.9.51:5140
```

### CODE REVIEW

**Comment by nigels-com** [comment]
Some general comments:

- The indentation seems uneven, mix of spaces and tabs?
- A documentation addition to [fluent-bit-docs](https://github.com/fluent/fluent-bit-docs)

And a question:

- Is it legit to put JSON blobs in the syslog?  I don't think I've seen that in practice.

**Comment by ginobiliwang** [comment]
Hi @nigels-com , yup, i agree that jason format is not applicable in syslog output.  Let me use something like "msgpack_unpack" to decode msgpack to plain text. 
BTW, do you have any suggestions about how to decode msgpack to plain text ?

**Comment by nigels-com** [comment]
> BTW, do you have any suggestions about how to decode msgpack to plain text ?

Perhaps a line of comma separated INI file style key/value pairs?

But alas, I don't see an off-the-shelf solution to get there from msgpack.

**Comment by ginobiliwang** [comment]
OK, may be i have to draft some code to deal with format change.

**Comment by hev** [comment]
@ginobiliwang would this [go-lang 5424](https://github.com/pivotal-cf/fluent-bit-out-syslog) output plugin suit your needs? We actively maintain this if it does happen to.

**Comment by ginobiliwang** [comment]
> @ginobiliwang would this [go-lang 5424](https://github.com/pivotal-cf/fluent-bit-out-syslog) output plugin suit your needs? We actively maintain this if it does happen to.

I would like develop native syslog out plugin for fluent-bit itself, now rfc-3164 and will add rfc-5424.  Go plugin is very creative but some how heavy resource consumption.

**Comment by ginobiliwang** [comment]
> > BTW, do you have any suggestions about how to decode msgpack to plain text ?
> 
> Perhaps a line of comma separated INI file style key/value pairs?
> 
> But alas, I don't see an off-the-shelf solution to get there from msgpack.

@nigels-com 
i saw another [PR](https://github.com/fluent/fluent-bit/pull/1601)  that has just submitted for the same function of this one.   He is NOT using JSON as output format of syslog message body,  quoted here. 
`<14>1 2019-09-29T22:43:06.000161Z localhost appname - - [info__1 key_1="[1\]" key2="2"][info2 key3="3" key4="4"] test message`
which appears not that friendly  comparing to JSON format.

Meanwhile, based on the facts, the contents that been through fluent-bit are mostly JSON format,  and  it is difficult to organize such complicated schema with other format.

Hope to get your opinion.

**Comment by ginobiliwang** [comment]
@edsiper 
Can you shed some light on this PR or on the discussion about JSON format topics.

**Comment by edsiper** [comment]
Thanks for your contribution.

Please note that this is the first time that we get two PRs for the same plugin type implementation. 

After the review, we will stick with the implementation of #1601 and we would appreciate your contributions to it. We still need to polish it and build extra optional features.


Review from #1648 

```
I did a review of both plugins. 

Based on community feedback, features and general API usage (Fluent Bit API), 
we would stay with #1601 . 

While that PR will be merged, there is still more work on it to do like optional JSON 
formatting, we should discuss that based on use case and community needs.

Thanks everybody for your time on this.
```

thanks again for your work and support on this.

**Pull request closed without merging**
