### PR TITLE
out_cloudwatch_logs: fail request when x-amzn-RequestId header is not set

### PR DESCRIPTION
**Pull request by PettitWesley**
Temporary fix for https://github.com/aws/aws-for-fluent-bit/issues/161

### CODE REVIEW

**Comment by PettitWesley** [comment]
@DrewZhang13 @zhonghui12

**Comment by edsiper** [comment]
@PettitWesley is this ready to go ?

**Comment by edsiper** [comment]
ping

**Comment by PettitWesley** [comment]
@edsiper Let me update this one in a moment and then I will merge it

**Comment by PettitWesley** [comment]
@edsiper merged

**Pull request merged**
