### PR TITLE
Filter conditional rename

### PR DESCRIPTION
**Pull request by jlpettersson**
Filter plugin, for renaming (As "modify"-filter can do https://fluentbit.io/documentation/0.13/filter/modify.html) but based on a condtion; when a specific key with a specific value is present in the record.

e.g. when log_type="access" is present in the record, rename key my_key_x to key_x.

We use this plugin for conditionally set index and sourcetype, base on content in the log message, in our Splunk HEC integration.

### CODE REVIEW

**Comment by michiel** [comment]
I am working on extending the functionality of `filter_modify` to perform additional operations, see #601 

I like the idea of adding conditional logic to modification rules but creating a filter for each combination might be overkill. I can easily imagine scenarios that would ask for conditions like,

 - key X exists
 - key X does not exist
 - key X has value that equals string Y
 - key X has value that does not equal string Y
 - key X has value that matches pattern Y
 - key X has value that does not match pattern Y

I'd be happy to extend the `modify` filter to include conditional logic. I think that would cover a wider range of future use cases.

**Comment by jlpettersson** [comment]
@michiel yes, that would be very good! Our conditional is very basic and the rename-functionallity is from your plugin, so it would be better to have it all in your plugin. It's better to have it in one config-line e.g. "If_key_value_match my_key my_value then rename field field_renamed

**Comment by edsiper** [comment]
should I close this PR ?

**Comment by michiel** [comment]
I am working on an implementation adds conditional evaluation to the `modify` filter. See #616 

I did consider the one-line implementation, but this becomes very cumbersome when you want to combine rules. E.g.

```
If_key_value_match my_key my_value AND If_key_exists my_other_key then rename field field_renamed
```

**Comment by jlpettersson** [comment]
@edsiper yes this can be closed now when @michiel implement the same feature in #616

**Comment by michiel** [comment]
This feature has been added in PR #618.
Examples can be found in the fluent-bit-docs PR at https://github.com/michiel/fluent-bit-docs/blob/feature/pr_extend_filter_modify/filter/modify.md

**Comment by edsiper** [comment]
thanks, closing this due to #618

**Pull request closed without merging**
