### PR TITLE
filter_kubernetes: always add meta extracted from the record itself

### PR DESCRIPTION
**Pull request by yann-soubeyrand**
Some meta are possibly extracted from the record itself (for example the namespace name, the pod name and the container name can be extracted from the tag). If the full meta could not be fetched from the API server, no meta at all were added to the record. This commit changes that behaviour to add at least the meta extracted from the record itself.

This commit also fixes two memory leaks in the code which has been modified.

Based on PR #1257.

### CODE REVIEW

**Comment by edsiper** [comment]
@yann-soubeyrand 

this PR touches 160 files, please submit only the commits relevant to the main issue to address/fix

**Comment by yann-soubeyrand** [comment]
@edsiper Once #1257 has been merged, I'll be able to rebase this PR on master and only the last commit will remain (which touches 3 files and adds a test). I cannot rebase it on master until the merge of #1257 as  it's based on it.

**Comment by edsiper** [comment]
@yann-soubeyrand is this one ready to go ?

**Comment by yann-soubeyrand** [comment]
Yes, I think so ;-)

**Comment by edsiper** [comment]
thanks!

**Pull request merged**
