### PR TITLE
storage: corrupted chunk deletion patch port

### PR DESCRIPTION
**Pull request by leonardo-albertovich**
This PR fixes an issue in fluent-bit where if the currently active chunk in a pipeline got corrupted the system would not be able to continue ingesting data.

Additionally this PR adds the `storage.delete_irrecoverable_chunks` option to make fluent-bit delete corrupted chunks.

Note: This PR should be merged only after the sibling chunkio PR is merged and fluent-bit PR that updates chunkio is created and merged so we can rebase and have this code go through the CI process.

### CODE REVIEW

**Comment by edsiper** [comment]
@leonardo-albertovich the CI is failing here:

```
/home/runner/work/fluent-bit/fluent-bit/src/flb_storage.c:608:18: error: use of undeclared identifier 'CIO_DELETE_IRRECOVERABLE'
        flags |= CIO_DELETE_IRRECOVERABLE;
                 ^
```

**Comment by leonardo-albertovich** [comment]
That's because this PR needs the latest version of chunkio (with my latest PR merged) which adds this flag.

**Comment by lecaros** [comment]
@leonardo-albertovich can you please link or point to the required chunkio PR? Thanks!

**Comment by leonardo-albertovich** [comment]
The PR was https://github.com/calyptia/chunkio/pull/91 and @edsiper merged it 18 hours ago, I'll send a PR to fluent-bit today to update chunkio and then once that one is merged I'll rebase this PR so it goes through the CI pipeline process as it should.

**Comment by edsiper** [comment]
@leonardo-albertovich it's all merged now, can you rebase it pls ?

**Comment by edsiper** [comment]
I messed up the branch history, finally found that I already cherry-picked the changes:

- 63ab1aaf9 config: added a new storage config to delete irrecoverable chunks
- 512b9ec48 input_chunk: added a function to destroy corrupted chunks
- 2d62aa5f4 storage: added code to set the irrecoverable chunk deletion flag
- c0e7af3a7 in_storage_backlog: added code to discard irrecoverable chunks if desired

**Comment by edsiper** [comment]
commits merged by mistake in PR #6598 , closing this PR since changes are already there.

**Pull request closed without merging**
