### PR TITLE
Add filter plugin tests (stdout, grep)

### PR DESCRIPTION
**Pull request by takahasi**
Hi, I added new tests for filter plugin the below.
- stdout
- grep

Could you review my commits?

### CODE REVIEW

**Comment by edsiper** [comment]
thanks

**Comment by okkez** [comment]
@takahasi Which e-mail address is right? `3263 at gmail.com` or `takahashi at sample.com`.
sample.com is not suitable for Git author's e-mail address if you are not owner nor member of sample.com. Because http://sample.com exists. See also https://tools.ietf.org/html/rfc6761

@edsiper sorry for noisy trivial comment.

**Comment by edsiper** [comment]
@okkez thanks for catching that. 

@takahasi please update your email in your local repo:

```
git config user.email yourreal@email.com
```

**Comment by takahasi** [comment]
@okkez thanks!

I updated configuration.

**Pull request merged**
