### PR TITLE
utils: not to convert codepoint string (#3280)

### LINKED ISSUE #3280: Fluent Bit mishandles japanese characters
## Bug Report

Here's my config:

```
[INPUT]
    Name        tail
    Path        /home/ec2-user/config/logs/japan.log
    Read_from_Head On

[OUTPUT]
    Name stdout
    Match *
    Format json_lines
```

And my log file:
(*Content Warning: I can't read Japanese so I don't know what this means... I got it from a user who reported this issue*)
```
someasciiilogline
あいうえお
asciiagain
```

When the format is json, these characters aren't handled properly:

```
{"date":1616654459.55218,"log":"someasciiilogline"}
{"date":1616654459.552188,"log":"\u3042\u3044\u3046\u3048\u304a"}
{"date":1616654459.55219,"log":"asciiagain"}
```

But when I change the format to `msgpack` we get:

```
[0] tail.0: [1616654319.474995365, {"log"=>"someasciiilogline"}]
[1] tail.0: [1616654319.475004612, {"log"=>"あいうえお"}]
[2] tail.0: [1616654319.475007521, {"log"=>"asciiagain"}]
```

### PR DESCRIPTION
**Pull request by nokute78**
Fixes #3280 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [N/A] Documentation required for this feature

## Example Configuration
```
[INPUT]
    Name dummy
    Dummy {"val":"あいうえお"}
    samples 1

[OUTPUT]
    Name stdout
    Format json_lines
```

## Debug output
```
$ ../bin/fluent-bit -c a.conf 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/03/26 09:24:05] [ info] [engine] started (pid=132201)
[2021/03/26 09:24:05] [ info] [storage] version=1.1.1, initializing...
[2021/03/26 09:24:05] [ info] [storage] in-memory
[2021/03/26 09:24:05] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/03/26 09:24:05] [ info] [sp] stream processor started
{"date":1616718246.357483,"val":"あいうえお"}
```

## Valgrind output
```
$ valgrind --leak-check=full ../bin/fluent-bit -c a.conf 
==132204== Memcheck, a memory error detector
==132204== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==132204== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==132204== Command: ../bin/fluent-bit -c a.conf
==132204== 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/03/26 09:24:35] [ info] [engine] started (pid=132204)
[2021/03/26 09:24:35] [ info] [storage] version=1.1.1, initializing...
[2021/03/26 09:24:35] [ info] [storage] in-memory
[2021/03/26 09:24:35] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/03/26 09:24:35] [ info] [sp] stream processor started
==132204== Warning: client switching stacks?  SP change: 0x57e48b8 --> 0x4c69970
==132204==          to suppress, use: --max-stackframe=12037960 or greater
==132204== Warning: client switching stacks?  SP change: 0x4c698e8 --> 0x57e48b8
==132204==          to suppress, use: --max-stackframe=12038096 or greater
==132204== Warning: client switching stacks?  SP change: 0x57e48b8 --> 0x4c698e8
==132204==          to suppress, use: --max-stackframe=12038096 or greater
==132204==          further instances of this message will not be shown.
{"date":1616718276.374024,"val":"あいうえお"}
^C[2021/03/26 09:24:41] [engine] caught signal (SIGINT)
[2021/03/26 09:24:41] [ warn] [engine] service will stop in 5 seconds
[2021/03/26 09:24:45] [ info] [engine] service stopped
==132204== 
==132204== HEAP SUMMARY:
==132204==     in use at exit: 0 bytes in 0 blocks
==132204==   total heap usage: 325 allocs, 325 frees, 670,661 bytes allocated
==132204== 
==132204== All heap blocks were freed -- no leaks are possible
==132204== 
==132204== For lists of detected and suppressed errors, rerun with: -s
==132204== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by nokute78** [comment]
This patch causes breaking change.
e.g. Older output is `\u3042\u3044\u3046\u3048\u304a`. New output is `あいうえお`.

If user expects older outputs, we may need some new option to handle this.

**Comment by edsiper** [comment]
@nokute78 how Fluentd handle such cases ?

**Comment by nokute78** [comment]
@edsiper Fluentd's out_stdout output is like this. It is similar to this PR's output.
```
2021-03-26 22:52:51.048964125 +0000 sample: {"val":"あいうえお"}
```

I used the docker container `fluent/fluentd:v1.12-1`.
Config file is
```
<source>
    @type sample
    tag sample
    sample [
           {"val":"あいうえお"}
    ]
</source>

<match *>
    @type stdout
</match>
```

Full log is
```
$ sudo docker run -it --rm -v ~/fluentd/conf:/fluentd/etc fluent/fluentd:v1.12-1 -c /fluentd/etc/out_stdout.conf -v
fluentd -c /fluentd/etc/out_stdout.conf -v
2021-03-26 22:52:49 +0000 [info]: fluent/log.rb:329:info: parsing config file is succeeded path="/fluentd/etc/out_stdout.conf"
2021-03-26 22:52:49 +0000 [info]: fluent/log.rb:329:info: gem 'fluentd' version '1.12.1'
2021-03-26 22:52:49 +0000 [warn]: fluent/log.rb:350:warn: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2021-03-26 22:52:49 +0000 [warn]: fluent/log.rb:350:warn: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2021-03-26 22:52:49 +0000 [debug]: fluent/log.rb:308:debug: No fluent logger for internal event
2021-03-26 22:52:49 +0000 [info]: fluent/log.rb:329:info: using configuration file: <ROOT>
  <source>
    @type sample
    tag "sample"
    sample [{"val":"あいうえお"}]
  </source>
  <match *>
    @type stdout
  </match>
</ROOT>
2021-03-26 22:52:49 +0000 [info]: fluent/log.rb:329:info: starting fluentd-1.12.1 pid=6 ruby="2.7.2"
2021-03-26 22:52:49 +0000 [info]: fluent/log.rb:329:info: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/out_stdout.conf", "-v", "-p", "/fluentd/plugins", "--under-supervisor"]
2021-03-26 22:52:50 +0000 [info]: fluent/log.rb:329:info: adding match pattern="*" type="stdout"
2021-03-26 22:52:50 +0000 [info]: fluent/log.rb:329:info: adding source type="sample"
2021-03-26 22:52:50 +0000 [warn]: #0 fluent/log.rb:350:warn: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2021-03-26 22:52:50 +0000 [warn]: #0 fluent/log.rb:350:warn: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2021-03-26 22:52:50 +0000 [debug]: #0 fluent/log.rb:308:debug: No fluent logger for internal event
2021-03-26 22:52:50 +0000 [info]: #0 fluent/log.rb:329:info: starting fluentd worker pid=15 ppid=6 worker=0
2021-03-26 22:52:50 +0000 [info]: #0 fluent/log.rb:329:info: fluentd worker is now running worker=0
2021-03-26 22:52:51.048964125 +0000 sample: {"val":"あいうえお"}
2021-03-26 22:52:52.054738482 +0000 sample: {"val":"あいうえお"}
2021-03-26 22:52:53.058601953 +0000 sample: {"val":"あいうえお"}
```

**Comment by nokute78** [comment]
Note: We can also test using emoji.

```
[INPUT]
    Name dummy
    Dummy {"val":"🤔🤔🤔"}
    samples 1

[OUTPUT]
    Name stdout
    Format json_lines
```

Current master output is
```
{"date":1616800735.094623,"val":"\u1f914\u1f914\u1f914"}
```

This PR's output is
```
{"date":1616800698.097083,"val":"🤔🤔🤔"}
```

**Comment by edsiper** [comment]
@l2dy @bluebike @nigels-com 

what do you think about this change ?

**Comment by nokute78** [comment]
Note2: This behavior heppens only if ` Format` is  `json_lines`. https://github.com/fluent/fluent-bit/issues/3280#issue-840634788

On the other hand , if we set `msgpack` mode (default mode of out_stdout) then it outputs like this.
```
[0] tail.0: [1616654319.474995365, {"log"=>"someasciiilogline"}]
[1] tail.0: [1616654319.475004612, {"log"=>"あいうえお"}]
[2] tail.0: [1616654319.475007521, {"log"=>"asciiagain"}]
```

**Comment by nokute78** [comment]
I updated some testcases.
Because this breaking change breaks some testcases.
e.g. compare 🔔 bell emoji.

**Comment by nigels-com** [comment]
> what do you think about this change ?

Hello @edsiper I took a bit of a look at the discussion, the diff and the `git blame` to get some context.

My first thought is that UTF-8 and JSON are like peas in a pod (they go together) and we shouldn't be concerning fluent-bit with outputting non-UTF-8 JSON.  And beyond that it is a positive thing to aggregate various sources into a common UTF-8 log stream, which is "hiding" the implementation details of various systems, locates and conventions (encodings) which is a valuable and desirable feature for fluent-bit to provide.

My second thought is that it appears to be the author's (@edsiper) intention that this particular function `flb_utils_write_str` to emit ASCII, rather than UTF-8.

```
59b4943ac src/flb_utils.c  (Eduardo Silva   2017-10-09 09:50:00 -0600 600) /*
59b4943ac src/flb_utils.c  (Eduardo Silva   2017-10-09 09:50:00 -0600 601)  * Write string pointed by 'str' to the destination buffer 'buf'. It's make sure
59b4943ac src/flb_utils.c  (Eduardo Silva   2017-10-09 09:50:00 -0600 602)  * to escape sepecial characters and convert utf-8 byte characters to string
59b4943ac src/flb_utils.c  (Eduardo Silva   2017-10-09 09:50:00 -0600 603)  * representation.
59b4943ac src/flb_utils.c  (Eduardo Silva   2017-10-09 09:50:00 -0600 604)  */
59b4943ac src/flb_utils.c  (Eduardo Silva   2017-10-09 09:50:00 -0600 605) int flb_utils_write_str(char *buf, int *off, size_t size,
97b942b87 src/flb_utils.c  (Yann Soubeyrand 2019-05-28 11:20:36 +0200 606)                         const char *str, size_t str_len)
```
..which for me raises the question if there are legitimate non-JSON codepaths that really want ASCII, rather than UTF-8?

And my third thought is that there are two blocks of unicode codepoints handled, but this change only affects the second one.  
Abbreviated here:

```
81cf6bcf5 src/flb_pack.c   (Eduardo Silva      2017-07-28 15:13:09 -0600 675)         else if (c >= 0x80 && c <= 0xFFFF) {
...
73f34c09d src/flb_pack.c   (Eduardo Silva      2017-07-31 16:50:54 -0600 701)                 len = snprintf(tmp, sizeof(tmp) - 1, "\\u%.4x", codepoint);
...
73f34c09d src/flb_pack.c   (Eduardo Silva      2017-07-31 16:50:54 -0600 709)         }
81cf6bcf5 src/flb_pack.c   (Eduardo Silva      2017-07-28 15:13:09 -0600 710)         else if (c > 0xFFFF) {
...
59b4943ac src/flb_utils.c  (Eduardo Silva      2017-10-09 09:50:00 -0600 719)             for (b = 0; b < hex_bytes; b++) {
fd512c795 src/flb_utils.c  (Takahiro Yamashita 2021-03-26 09:22:25 +0900 720)                 tmp[b] = str[i+b];
59b4943ac src/flb_utils.c  (Eduardo Silva      2017-10-09 09:50:00 -0600 721)             }
...
73f34c09d src/flb_pack.c   (Eduardo Silva      2017-07-31 16:50:54 -0600 725)         }

```
So I do think that @takahasi may need to consider the case of `c >= 0x80 && c <= 0xFFFF` and why we'd do ASCII for those and UTF-8 for `c > 0xFFFF`.  Possibly an oversight.

Perhaps fluent-bit needs both ASCII and UTF-8 `flb_utils_write_str` utility functions?

Perhaps the wording of the function comment block could clarify "...convert utf-8 byte characters to string representation..." to specify ASCII or UTF-8?

It's plausible that some use cases prefer ASCII, but in my opinion UTF-8 is preferable for JSON purposes.

**Comment by nigels-com** [comment]
One more question in my mind is if the `\` escaped unicode is a valid, supported or reasonable way to emit JSON.

In the sense of this as "fixing a bug" to make the JSON valid, or a "breaking change" that perhaps ought to be held back for a version increment and documented/flagged.

I don't have a firm opinion about that, but I would want more clarity to accept it into the mainline, personally.

**Comment by nokute78** [comment]
@nigels-com oops, I just forgot the case ` c >= 0x80 && c <= 0xFFFF` .

**Comment by nokute78** [comment]
Hmm, I added `flb_warn`  to print variable `c` and run internal test `flb-it-pack`.
https://github.com/fluent/fluent-bit/blob/bfde6df38c2683d2d04abd00b7b82945ebe89653/src/flb_utils.c#L635

`flb-it-pack` outputs only `0 < c < 0x7f` and ` c > 0xffff`. 
Test case contains Copyright (U+00A9 and its hex `0xc2a9`), it should be contained `c >= 0x80 && c <= 0xFFFF` case. 
It may be a bug.

**Review by PettitWesley — APPROVED** [review]
This fixes the issue with S3 and stdout outputs that I originally reported

**Comment by nokute78** [comment]
@PettitWesley Thank you for testing.

@edsiper Can you merge this ?
https://github.com/fluent/fluent-bit/pull/3284#issuecomment-808973353
This bug will be followed another PR.

**Comment by edsiper** [comment]
thanks!

**Pull request merged**
