### PR TITLE
out_s3: New plugin for Amazon S3

### PR DESCRIPTION
**Pull request by PettitWesley**
#1004 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [ ] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by edsiper** [comment]
unit test is failing https://travis-ci.org/github/fluent/fluent-bit/jobs/730123191#L2153

**Comment by PettitWesley** [comment]
@edsiper Should be fixed now

**Comment by edsiper** [comment]
thanks!

**Comment by avdhoot** [comment]
@PettitWesley Thank for all effort. hope it will get release soon. Will it support  [AssumeRoleWithWebIdentity](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html). This will helpful in k8s environment.  more --> https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

**Comment by PettitWesley** [comment]
@avdhoot The core Fluent Bit AWS credential library I built supports EKS IAM Roles for Service Accounts. So all AWS outputs support that.

See my comment here for a pre-release version: https://github.com/fluent/fluent-bit/issues/1004#issuecomment-697196195

If you have time to test it out and verify that everything works that'd be awesome!

**Pull request merged**
