### PR TITLE
Generic Avro Encoding Support for the Kafka Plugin

### PR DESCRIPTION
**Pull request by xmcqueen**
Support for generic avro-encoding for the kafka output plugin.  Uses the official apache avro-c library.  

There was no ticket for this.
----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A ] Example configuration file for the change
- [N/A] Debug log output from testing the change

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [ ] Documentation required for this feature

** Dependencies **
The Avro-c code comes from here:
[apache/avro](https://github.com/apache/avro)

I took the avro-c (lang/c) directory, and added CMake files to get it to build in the fluent-bit framework.

avro-c also has a dependency on [jansson](https://github.com/akheron/jansson):

I also added that and made it build and link as required.

I've put in ifdefs everywhere as-needed to make avro encoding be optional.

** Example Config **

`
    [OUTPUT]
        Name kafka
        Match       *
        Brokers     kafka.www.xxx.com:1667
        Topics      fb1
        Schema_str  {"name":"qavrov2_record","type":"record","fields":[{"name":"log","type":"string"},{"name":"kubernetes","type":{"name":"krec","type":"record","fields":[{"name":"pod_name","type":"string"},{"name":"namespace_name","type":"string"},{"name":"pod_id","type":"string"},{"name":"labels","type":{"type":"map","values":"string"}},{"name":"annotations","type":{"type":"map","values":"string"}},{"name":"host","type":"string"},{"name":"container_name","type":"string"},{"name":"docker_id","type":"string"},{"name":"container_hash","type":"string"},{"name":"container_image","type":"string"}]}}]}
        Schema_id 5a788141209bbd3d5e450b74505439ba
        rdkafka.client.id fluentbit-kubernetes-producer
        rdkafka.debug All
        rdkafka.enable.ssl.certificate.verification false

        rdkafka.ssl.certificate.location /ddd/identity.cert
        rdkafka.ssl.key.location /eee/identity.key
        rdkafka.ssl.ca.location /jjj/bundle.crt
        rdkafka.security.protocol ssl
        rdkafka.request.required.acks 1
        rdkafka.log.connection.close false

        Format avro
        rdkafka.log_level 7
        rdkafka.metadata.broker.list kafka.www.xxx.com:1667
`

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by xmcqueen** [comment]
Here's a valgrind run:

`
[zzz@zzz fluent-bit]$ valgrind ./build/bin/flb-it-avro 
==78071== Memcheck, a memory error detector
==78071== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==78071== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==78071== Command: ./build/bin/flb-it-avro
==78071== 
.
.
.
[   OK   ]
==78074== 
==78074== HEAP SUMMARY:
==78074==     in use at exit: 18 bytes in 2 blocks
==78074==   total heap usage: 163 allocs, 161 frees, 39,252 bytes allocated
==78074== 
==78074== LEAK SUMMARY:
==78074==    definitely lost: 0 bytes in 0 blocks
==78074==    indirectly lost: 0 bytes in 0 blocks
==78074==      possibly lost: 0 bytes in 0 blocks
==78074==    still reachable: 18 bytes in 2 blocks
==78074==         suppressed: 0 bytes in 0 blocks
==78074== Rerun with --leak-check=full to see details of leaked memory
==78074== 
==78074== For counts of detected and suppressed errors, rerun with: -v
==78074== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
.
.
.

[   OK   ]
==78075== 
==78075== HEAP SUMMARY:
==78075==     in use at exit: 18 bytes in 2 blocks
==78075==   total heap usage: 345 allocs, 343 frees, 54,901 bytes allocated
==78075== 
==78075== LEAK SUMMARY:
==78075==    definitely lost: 0 bytes in 0 blocks
==78075==    indirectly lost: 0 bytes in 0 blocks
==78075==      possibly lost: 0 bytes in 0 blocks
==78075==    still reachable: 18 bytes in 2 blocks
==78075==         suppressed: 0 bytes in 0 blocks
==78075== Rerun with --leak-check=full to see details of leaked memory
==78075== 
==78075== For counts of detected and suppressed errors, rerun with: -v
==78075== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
SUCCESS: All unit tests have passed.
==78071== 
==78071== HEAP SUMMARY:
==78071==     in use at exit: 0 bytes in 0 blocks
==78071==   total heap usage: 5 allocs, 5 frees, 1,274 bytes allocated
==78071== 
==78071== All heap blocks were freed -- no leaks are possible
==78071== 
==78071== For counts of detected and suppressed errors, rerun with: -v
==78071== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
[zzz@zzzz fluent-bit]$ 
`

**Comment by xmcqueen** [comment]
Build it like this:

`
cmake -DFLB_DEV=On  -DFLB_OUT_KAFKA=On -DFLB_TLS=On -DFLB_TESTS_RUNTIME=On -DFLB_TESTS_INTERNAL=On -DFLB_AVRO_ENCODER=Yes ../
`

**Comment by jacobhjkim** [comment]
Any updates on this PR?

**Comment by xmcqueen** [comment]
yes @edsiper and I are working on getting this into 1.7

**Comment by edsiper** [comment]
Closing this PR since #2820 re-implemented this.

**Pull request closed without merging**
