### PR TITLE
lib: c-ares: upgrade from v1.19.1 to v1.24.0

### PR DESCRIPTION
**Pull request by edsiper**
----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by patrick-stephens** [comment]
Looks like the recent upgrade to upload-artifact dependency version is triggering a failure on Windows builds, need to have a look at that. I don't think it affects the actual PR here.

**Comment by patrick-stephens** [comment]
Rebase after https://github.com/fluent/fluent-bit/issues/8298 merged should hopefully resolve the CI failures around upload-artifact.

**Comment by edsiper** [comment]
rebased, thanks @patrick-stephens

**Comment by nokute78** [comment]
This may cause issue https://github.com/fluent/fluent-bit/issues/8342

**Pull request merged**
