### PR TITLE
build: luajit-cmake: add new luajit-cmake project

### PR DESCRIPTION
**Pull request by edsiper**
In order to simplify the build of LuaJIT, this patch adds the project 'luajit-cmake', which is just a CMake wrapper with proper rules to compile an external luajit source code repository.

Signed-off-by: Eduardo Silva <eduardo@calyptia.com>

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by edsiper** [comment]
@cosmo0920 can you take a look if this PR makes sense ?, I noticed that luajit-cmake add certain build flags to luajit (check luajit.cmake in lib/luajit-cmake), not sure if there are possible side effects.

**Comment by cosmo0920** [comment]
I suspected that luajit and buildvm executables might be installed in fluent-bit packages. But, it didn't occurred.
And CI tasks for Windows are fine. As far as I look, there is no significant side effects by migrating cmake based LuaJIT bundling.

**Review by cosmo0920 — COMMENTED** [review]
Makes sense for me. :+1:

**Comment by cosmo0920** [comment]
But I have a concerns for cross compilation on LuaJIT.
I didn't succeeded to build LuaJIT for raspbian/buster.

**Comment by cosmo0920** [comment]
Building packages for raspbian/buster seems to be broken before this PR.
And I confirmed that non-cross compilation on Linux aarch64 box can build bundled LuaJIT

**Pull request merged**
