### PR TITLE
Nanosecond support Step1

### PR DESCRIPTION
**Pull request by nokute78**
refer to #193
I added a code to support nanosecond. 

Note : this is a step1 of the roadmap.

1. define flb_time struct and utilities. (append to msgpack, pop from msgpack, generate flb_time ...)
2. modify output plugins.
3. modify filter plugins.
4. modify input plugins.

### CODE REVIEW

**Comment by edsiper** [comment]
FYI: to be reviewed after 0.11 release

**Comment by nokute78** [comment]
@edsiper Thanks.
Now, I modified `in_random` and `out_stdout` to use new timer API.
We can test like this.

## Try
```
$ bin/fluent-bit -i random -o stdout
Fluent-Bit v0.11.0
Copyright (C) Treasure Data

[2017/03/24 19:57:14] [ info] [engine] started
[0] random.0: [1490353035.001391527, {"rand_value"=>2555226334427575671}]
[1] random.0: [1490353036.000221516, {"rand_value"=>5790921205879452352}]
[2] random.0: [1490353037.000205725, {"rand_value"=>6804175939855423656}]
[3] random.0: [1490353038.000218504, {"rand_value"=>9990361705380242913}]
```

## Try with fluentd
We can also test with fluentd.

Execute fluentd using this fluent.conf
```xml
<source>
  type forward
  tag raw.test
  port 24224
</source>
<match *.*>
   type   stdout
</match>
```

And execute fluent-bit like this.
```
$ bin/fluent-bit -i random -o forward
```

sample output is
```
2017-03-24 20:01:36.000526720 +0900 random.0: {"rand_value":13093173013433410333}
2017-03-24 20:01:37.000561503 +0900 random.0: {"rand_value":6573782616415017107}
2017-03-24 20:01:38.000659051 +0900 random.0: {"rand_value":5798840771373968564}
2017-03-24 20:01:39.000240777 +0900 random.0: {"rand_value":5447420022338566362}
```

**Comment by nokute78** [comment]
Hmm, macOS doesn't have 'clock_gettime'.
'clock_get_time' (very similar to clock_gettime) is supported and it returns 'mach_timespec_t'...
https://developer.apple.com/reference/kernel/1420035-clock_get_time?language=objc

It also has a member tv_sec and tv_nsec, but their types are different from linux and BSDs...

I don't have macOS, so I can't test it :(
Hmm.

**Comment by nokute78** [comment]
Travis CI passed!!!!!

It's ready for reviewing.

## Disclaimer

macOS is not supported nanosecond timestamp now.
We should call `clock_get_time` on macOS, but I can't test it since I don't have macOS PCs...

**Comment by edsiper** [comment]
wow! this is impressive!

thanks for research and work on this, it works pretty good.

I will try to do some testing in OSX. 

btw, can you remove the typedef and just use "struct flb_time" instead ?

**Comment by nokute78** [comment]
@edsiper Thank you for helping test.

> can you remove the typedef and just use "struct flb_time" instead ?

struct timespec is defined all platforms.
I think it is useful to divert standard structure as flb_time to handle timestamp.

Is there any reason not to use typedef?

**Comment by edsiper** [comment]
reason: just to make it easy to understand what it is (try not to hide what it is"),  unless is the Lib API.

**Comment by nokute78** [comment]
@edsiper Thanks. I wrote 3 types of structure. Which one is prefer?
 I like 1.

1. wrapper structure

```C
struct flb_time{
  struct timespec tm;
};
```
It's explicit to use timespec and easy to extend (e.g. add a member as protocol type.)
We can pass it to standard API which needs timespec.
It's redundant to access. (e.g. str.tm.tv_nsec)

2. redefinition
```C
struct flb_time{
   time_t tv_sec;
   long tv_nsec;
};
``` 
It has explicit members and easy to extend.
However it's re-definition of timespec and implicit to use timespec.
It always needs to convert from timespec and can't pass it to standard API directly. 

3. typedef (now implemented)

```C
typedef struct timespec flb_time;
```

It's explicit to use standard structure and implicit its members.
We can pass it to standard API which needs timespec.
It's hard to extend the structure.

**Comment by edsiper** [comment]
I like #1 too, anyways in C by definition the first member of the structure is the structure address:

```
struct flb_time {
    struct timespec tm;
};

int main()
{
    struct flb_time a;
    printf("%p %p\n", &a, &a.tm);
    return 0;
}
```

```
$ ./flb_time 
0x7ffc16731370 0x7ffc16731370
```

**Comment by nokute78** [comment]
@edsiper Thanks for your comment. So I modified flb_time.

> in C by definition the first member of the structure is the structure address:

Yes, but someone can modify flb_time and it means the offset of timespec can be changed.
So, I wrote explicit like tm.tm.tv_sec.

**Comment by edsiper** [comment]
thanks

**Pull request merged**
