### PR TITLE
out_kinesis_streams: New high performance plugin for kinesis_streams

### PR DESCRIPTION
**Pull request by PettitWesley**
Signed-off-by: Wesley Pettit <wppttt@amazon.com>

#2485 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [ ] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by edsiper** [comment]
@PettitWesley 

thanks for this contribution.

The test cases are failing, looks like the old TLS API is being used, ref:

https://travis-ci.org/github/fluent/fluent-bit/jobs/756389342#L1442

**Comment by edsiper** [comment]
thanks

**Comment by ravinaik1312** [comment]
Has this change made it to any of the releases? I don't see it in the latest documentation for fluentbit outputs at https://docs.fluentbit.io/manual/pipeline/outputs

**Comment by PettitWesley** [comment]
@ravinaik1312 It has been released in `1.7.0` which just went out this morning I think. There are no docs yet since I have been procrastinating on writing them. But the options can be seen here: https://github.com/fluent/fluent-bit/blob/master/plugins/out_kinesis_streams/kinesis.c#L398

**Comment by ravinaik1312** [comment]
@PettitWesley thanks for the quick response. The options are similar to the go plugin, which is good. Like the go plugin, this one doesn't provide an option to pass `credentials` in the plugin config, is that intentional? I'm trying to ship logs from a non-AWS compute to AWS kinesis stream and wanted to point the plugin to read AWS credentials from a credentials file.

**Comment by PettitWesley** [comment]
@ravinaik1312 Yes that is intentional. Specifying raw creds in the config would be a bad practice which AWS security would never allow me to implement. Some Fluentd aws plugins have that as an option since AWS did not build/vet them.

You can use any standard credential mechanism with Fluent Bit. If you are not running on an EC2 instance or within AWS, then the easiest are the following:
1. Set credentials as env vars
2. Use the shared credential file (the AWS CLI creates this). Set the `AWS_SHARED_CREDENTIALS_FILE` env var if you don't put the file in the default location.

Unfortunately AWS doesn't have a nice official doc on what we mean when we say "standard credential sources" but you can piece it together using the docs for the AWS CLI and the AWS SDKs:
- https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
- https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html
- https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html

**Comment by ravinaik1312** [comment]
Awesome, that makes sense. I was meaning to use something like [shared credentials](https://github.com/awslabs/aws-fluent-plugin-kinesis#shared_credentials), wasn't sure if that was already baked into this (or the go plugin for fluent-bit-kinesis output)

**Comment by PettitWesley** [comment]
@ravinaik1312 Yeah that project was donated to us AFAIK. The way they implemented it is weird and not standard. The standard way is to use env vars. `AWS_PROFILE` specifies the profile name and `AWS_SHARED_CREDENTIALS_FILE` specifies the path to the file. Neither of those are needed if you use the default profile and default path.

**Comment by ravinaik1312** [comment]
Hi @PettitWesley, I took this output plugin for a spin and it doesn't look like it's reading the credentials from the environment variables. I'm happy to create an issue as well if this turns out to be actually an issue so that the wider community benefits from it. Here is the relevant info. 

<details>
    <summary>td-agent-bit version information</summary>

```
(.venv) [rnaik@utility-video sceptre-skeleton]$ yum info td-agent-bit
Loaded plugins: changelog, fastestmirror, versionlock
Loading mirror speeds from cached hostfile
 * centos-sclo-rh: mirror.sjc02.svwh.net
 * centos-sclo-sclo: mirrors.xmission.com
Installed Packages
Name        : td-agent-bit
Arch        : x86_64
Version     : 1.7.0
Release     : 1
Size        : 27 M
Repo        : installed
From repo   : td-agent-bit
Summary     : Fast data collector for Linux
License     : Apache v2.0
Description : Fluent Bit is a high performance and multi platform Log Forwarder.
```
</details>

<details>
    <summary>Relevant environment variables set</summary>

```
(.venv) [rnaik@utility-video sceptre-skeleton]$ echo $AWS_PROFILE
fluent
(.venv) [rnaik@utility-video sceptre-skeleton]$ echo $AWS_SHARED_CREDENTIALS_FILE
/etc/.aws/credentials
(.venv) [rnaik@utility-video sceptre-skeleton]$
```
</details>

<details>
    <summary>Credentials file has read permission for all users</summary>

```
(.venv) [rnaik@utility-video sceptre-skeleton]$ ls -altr /etc/ | grep .aws
drwxr-xr-x    2 root     root         25 Feb 15 12:54 .aws
(.venv) [rnaik@utility-video sceptre-skeleton]$ ls -altr /etc/.aws | grep credentials
-rw-r--r--    1 root root  232 Feb 15 12:54 credentials
(.venv) [rnaik@utility-video sceptre-skeleton]$
```
</details>

<details>
    <summary>td-agent config</summary>

```
[SERVICE]
    Log_Level debug
    Log_File /var/log/td-agent-bit.log
[INPUT]
    Name   dummy
    Tag    dummy
    Dummy {"hello": "world from fluent bit"}

[OUTPUT]
    Name            kinesis_streams
    Match           dummy
    region          us-west-2
    stream          <my-stream-name>
```
</details>

<details>
    <summary>debug level td-agent-bit logs</summary>

```
[2021/02/17 12:44:11] [ warn] [aws_credentials] No cached credentials are available and a credential refresh is already in progress. The current co-routine will retry.
[2021/02/17 12:44:11] [error] [signv4] Provider returned no credentials, service=kinesis
[2021/02/17 12:44:11] [error] [aws_client] could not sign request
[2021/02/17 12:44:11] [debug] [upstream] KA connection #24 to kinesis.us-west-2.amazonaws.com:443 is now available
[2021/02/17 12:44:11] [error] [output:kinesis_streams:kinesis_streams.0] Failed to send log records to <my-stream-name>
[2021/02/17 12:44:11] [error] [output:kinesis_streams:kinesis_streams.0] Failed to send log records
[2021/02/17 12:44:11] [error] [output:kinesis_streams:kinesis_streams.0] Failed to send records to kinesis
[2021/02/17 12:44:11] [debug] [out coro] cb_destroy coro_id=1188
[2021/02/17 12:44:11] [debug] [task] task_id=2 reached retry-attempts limit 1/1
[2021/02/17 12:44:11] [ warn] [engine] chunk '26737-1613591038.475217072.flb' cannot be retried: task_id=2, input=dummy.0 > output=kinesis_streams.0
[2021/02/17 12:44:11] [debug] [task] destroy task=0x7f0b521214e0 (task_id=2)
[2021/02/17 12:44:12] [ info] [engine] started (pid=9505)
[2021/02/17 12:44:12] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2021/02/17 12:44:12] [debug] [storage] [cio stream] new stream registered: dummy.0
[2021/02/17 12:44:12] [ info] [storage] version=1.1.0, initializing...
[2021/02/17 12:44:12] [ info] [storage] in-memory
[2021/02/17 12:44:12] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/02/17 12:44:12] [debug] [kinesis_streams:kinesis_streams.0] created event channels: read=19 write=20
[2021/02/17 12:44:12] [debug] [aws_credentials] Initialized Env Provider in standard chain
[2021/02/17 12:44:12] [ warn] [aws_credentials] Failed to initialized profile provider: $HOME not set and AWS_SHARED_CREDENTIALS_FILE not set.
[2021/02/17 12:44:12] [debug] [aws_credentials] Not initializing EKS provider because AWS_ROLE_ARN was not set
[2021/02/17 12:44:12] [debug] [aws_credentials] Not initializing ECS Provider because AWS_CONTAINER_CREDENTIALS_RELATIVE_URI is not set
[2021/02/17 12:44:12] [debug] [aws_credentials] Initialized EC2 Provider in standard chain
[2021/02/17 12:44:12] [debug] [aws_credentials] Sync called on the EC2 provider
[2021/02/17 12:44:12] [debug] [aws_credentials] Init called on the env provider
[2021/02/17 12:44:12] [debug] [aws_credentials] Init called on the EC2 IMDS provider
[2021/02/17 12:44:12] [debug] [aws_credentials] requesting credentials from EC2 IMDS
[2021/02/17 12:44:12] [debug] [imds] Using instance metadata V1
[2021/02/17 12:44:12] [debug] [http_client] not using http_proxy for header
[2021/02/17 12:44:12] [debug] [http_client] header=GET /latest/meta-data/iam/security-credentials/ HTTP/1.1
Host: 169.254.169.254:80
Content-Length: 0
User-Agent: aws-fluent-bit-plugin


[2021/02/17 12:44:12] [debug] [aws_client] (null): http_do=0, HTTP Status: 404
[2021/02/17 12:44:12] [debug] [upstream] KA connection #18 to 169.254.169.254:80 is now available
[2021/02/17 12:44:12] [debug] [ecs_imds] IMDS metadata response
404 Not Found

The resource could not be found.
```
</details>

The most interesting logline to me is: 
`[2021/02/17 12:44:12] [ warn] [aws_credentials] Failed to initialized profile provider: $HOME not set and AWS_SHARED_CREDENTIALS_FILE not set.`  because when I `$echo` it out, it prints that that variable is set.

**Comment by ravinaik1312** [comment]
It was actually the case of fluentbit running as a service as that service wasn't able to read the environment variable on the shell. When I ran it directly from the shell where I had set the environment variables, it worked :)

```
(.venv) [rnaik@utility-video td-agent-bit]$ cd /opt/td-agent-bit/
(.venv) [rnaik@utility-video td-agent-bit]$ echo $AWS_SHARED_CREDENTIALS_FILE
/etc/.aws/credentials
(.venv) [rnaik@utility-video td-agent-bit]$ echo $AWS_PROFILE
fluent
(.venv) [rnaik@utility-video td-agent-bit]$ bin/td-agent-bit -c /etc/td-agent-bit/td-agent-bit.conf...[2021/02/17 15:53:53] [debug] [output:kinesis_streams:kinesis_streams.0] Sending 4 records
[log] error opening log file /var/log/td-agent-bit.log. Using stderr.
[2021/02/17 15:53:53] [debug] [output:kinesis_streams:kinesis_streams.0] Sending log records to stream <my-stream-name>
```

Apologies for the alarm :|

**Pull request merged**
