### PR TITLE
[out_http] Change successful requests log level from info to debug.

### LINKED ISSUE #1141: Reduce excessive info logging in out_http
**Is your feature request related to a problem? Please describe.**

Currently, the `out_http` plugin does excessive info logging, in my opinion, logging a line like
```
[$dateTime] [ info] [out_http] $host:$port, HTTP status=$status
```
for every successful request. That (uselessly) fills up docker logs when running in a pod inside a kubernetes cluster, and also has the side-effect of a "logging amplification loop" if collecting the `fluent-bit` container logs, and not filtering the above mentioned lines, where every logged line will generate a `fluent-bit` log line that will be logged in turn.

**Describe the solution you'd like**

I'd suggest to change the log level of those successful requests from `info` to `debug`.

If you think that's a reasonable request, I can open a PR.

### PR DESCRIPTION
**Pull request by lbogdan**
Fixes #1141 , see that for details.

### CODE REVIEW

**Comment by nigels-com** [comment]
Info does look a bit chatty on the face of it.

I generally tend to think there should be a level in between (brief) INFO and (detailed) DEBUG called something like VERBOSE or DETAILED.  Where INFO is the once-at-startup sort of information and perhaps VERBOSE is the per-item or per-transaction level of detail.

```
/* Message types */
#define FLB_LOG_OFF     0
#define FLB_LOG_ERROR   1
#define FLB_LOG_WARN    2
#define FLB_LOG_INFO    3  /* default */
#define FLB_LOG_DEBUG   4
#define FLB_LOG_TRACE   5
```

**Comment by lbogdan** [comment]
I partially agree. In my opinion, all messages logged from the run loop's happy path should be `DEBUG` (or `VERBOSE` / `DETAILED`, as in your suggestion). On the other hand, I think your suggestion calls for an additional developer cognitive load in deciding between `DEBUG` and `VERBOSE`, for no obvious gain.

**Comment by nigels-com** [comment]
I think the counter-argument to this change is that web servers typically log per-request.  So an advantage of VERBOSE or DETAILED is to put that within reach without the possible excess of all the other DEBUG messages.

**Comment by lbogdan** [comment]
PIng?

**Comment by nigels-com** [comment]
I do still think that info is "too hot" debug is "too cold" and verbose would be "just right".

download

**Comment by edsiper** [comment]
Sorry for the late reply on this.

Since Fluent Bit v1.4 we introduced granular ```log_level ```, e.g:

__1__ Normal output of HTTP output

```
$ bin/fluent-bit -i random -p samples=1 -o http://127.0.0.1:8080 -f 1
Fluent Bit v1.5.0
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/05/05 11:06:42] [ info] [storage] version=1.0.3, initializing...
[2020/05/05 11:06:42] [ info] [storage] in-memory
[2020/05/05 11:06:42] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/05/05 11:06:42] [ info] [engine] started (pid=3608437)
[2020/05/05 11:06:42] [ info] [sp] stream processor started
[2020/05/05 11:06:43] [ info] [output:http:http.0] 127.0.0.1:8080, HTTP status=200
Post from website! r.PostFrom = map[]
Name = 
Address = 
```

__2__ Decreasing ```log_level``` to ```warn``` (which includes ```error``` also):

```
$ bin/fluent-bit -i random -p samples=1 -o http://127.0.0.1:8080 -p log_level=warn -f 1
Fluent Bit v1.5.0
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/05/05 11:10:11] [ info] [storage] version=1.0.3, initializing...
[2020/05/05 11:10:11] [ info] [storage] in-memory
[2020/05/05 11:10:11] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/05/05 11:10:11] [ info] [engine] started (pid=3610030)
[2020/05/05 11:10:11] [ info] [sp] stream processor started
```

is setting up the log_level to warn an acceptable workaround ?, should we change the default behavior of out_http ?, please comment.

**Comment by edsiper** [comment]
ping

**Comment by edsiper** [comment]
ping

**Comment by lbogdan** [comment]
@edsiper Sorry, I didn't get a change to upgrade to 1.4 yet, I'm still using a custom 1.3 build which includes this PR. But yeah, if it works like you described in your comment, I guess it should be enough, and you can close this and the [related issue](https://github.com/fluent/fluent-bit/issues/1141).

**Comment by edsiper** [comment]
thanks. Closing this one.

**Pull request closed without merging**
