### PR TITLE
tests: internal: parser_json: add test for parser_json

### PR DESCRIPTION
**Pull request by nokute78**
This patch is to add internal test for json parser.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

## Debug/Valgrind output

```
$ valgrind --leak-check=full bin/flb-it-parser_json 
==64057== Memcheck, a memory error detector
==64057== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==64057== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==64057== Command: bin/flb-it-parser_json
==64057== 
Test basic...                                   ==64058== Warning: invalid file descriptor -1 in syscall close()
[ OK ]
==64058== Warning: invalid file descriptor -1 in syscall close()
==64058== 
==64058== HEAP SUMMARY:
==64058==     in use at exit: 80 bytes in 1 blocks
==64058==   total heap usage: 1,666 allocs, 1,665 frees, 202,514 bytes allocated
==64058== 
==64058== LEAK SUMMARY:
==64058==    definitely lost: 0 bytes in 0 blocks
==64058==    indirectly lost: 0 bytes in 0 blocks
==64058==      possibly lost: 0 bytes in 0 blocks
==64058==    still reachable: 80 bytes in 1 blocks
==64058==         suppressed: 0 bytes in 0 blocks
==64058== Reachable blocks (those to which a pointer was found) are not shown.
==64058== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==64058== 
==64058== For lists of detected and suppressed errors, rerun with: -s
==64058== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Test time_key...                                ==64059== Warning: invalid file descriptor -1 in syscall close()
[ OK ]
==64059== Warning: invalid file descriptor -1 in syscall close()
==64059== 
==64059== HEAP SUMMARY:
==64059==     in use at exit: 80 bytes in 1 blocks
==64059==   total heap usage: 1,677 allocs, 1,676 frees, 215,527 bytes allocated
==64059== 
==64059== LEAK SUMMARY:
==64059==    definitely lost: 0 bytes in 0 blocks
==64059==    indirectly lost: 0 bytes in 0 blocks
==64059==      possibly lost: 0 bytes in 0 blocks
==64059==    still reachable: 80 bytes in 1 blocks
==64059==         suppressed: 0 bytes in 0 blocks
==64059== Reachable blocks (those to which a pointer was found) are not shown.
==64059== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==64059== 
==64059== For lists of detected and suppressed errors, rerun with: -s
==64059== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Test time_keep...                               ==64060== Warning: invalid file descriptor -1 in syscall close()
[ OK ]
==64060== Warning: invalid file descriptor -1 in syscall close()
==64060== 
==64060== HEAP SUMMARY:
==64060==     in use at exit: 80 bytes in 1 blocks
==64060==   total heap usage: 1,677 allocs, 1,676 frees, 215,527 bytes allocated
==64060== 
==64060== LEAK SUMMARY:
==64060==    definitely lost: 0 bytes in 0 blocks
==64060==    indirectly lost: 0 bytes in 0 blocks
==64060==      possibly lost: 0 bytes in 0 blocks
==64060==    still reachable: 80 bytes in 1 blocks
==64060==         suppressed: 0 bytes in 0 blocks
==64060== Reachable blocks (those to which a pointer was found) are not shown.
==64060== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==64060== 
==64060== For lists of detected and suppressed errors, rerun with: -s
==64060== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Test types_is_not_supported...                  ==64061== Warning: invalid file descriptor -1 in syscall close()
[ OK ]
==64061== Warning: invalid file descriptor -1 in syscall close()
==64061== 
==64061== HEAP SUMMARY:
==64061==     in use at exit: 80 bytes in 1 blocks
==64061==   total heap usage: 1,668 allocs, 1,667 frees, 202,534 bytes allocated
==64061== 
==64061== LEAK SUMMARY:
==64061==    definitely lost: 0 bytes in 0 blocks
==64061==    indirectly lost: 0 bytes in 0 blocks
==64061==      possibly lost: 0 bytes in 0 blocks
==64061==    still reachable: 80 bytes in 1 blocks
==64061==         suppressed: 0 bytes in 0 blocks
==64061== Reachable blocks (those to which a pointer was found) are not shown.
==64061== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==64061== 
==64061== For lists of detected and suppressed errors, rerun with: -s
==64061== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Test decode_field_json...                       ==64062== Warning: invalid file descriptor -1 in syscall close()
[ OK ]
==64062== Warning: invalid file descriptor -1 in syscall close()
==64062== 
==64062== HEAP SUMMARY:
==64062==     in use at exit: 80 bytes in 1 blocks
==64062==   total heap usage: 1,703 allocs, 1,702 frees, 287,671 bytes allocated
==64062== 
==64062== LEAK SUMMARY:
==64062==    definitely lost: 0 bytes in 0 blocks
==64062==    indirectly lost: 0 bytes in 0 blocks
==64062==      possibly lost: 0 bytes in 0 blocks
==64062==    still reachable: 80 bytes in 1 blocks
==64062==         suppressed: 0 bytes in 0 blocks
==64062== Reachable blocks (those to which a pointer was found) are not shown.
==64062== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==64062== 
==64062== For lists of detected and suppressed errors, rerun with: -s
==64062== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
SUCCESS: All unit tests have passed.
==64057== 
==64057== HEAP SUMMARY:
==64057==     in use at exit: 0 bytes in 0 blocks
==64057==   total heap usage: 3 allocs, 3 frees, 1,141 bytes allocated
==64057== 
==64057== All heap blocks were freed -- no leaks are possible
==64057== 
==64057== For lists of detected and suppressed errors, rerun with: -s
==64057== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by edsiper** [comment]
where are the leaks coming from ?

```
80 bytes
```

**Comment by nokute78** [comment]
@edsiper It is acutest.
I don't know how to remove it.

I know that valgrind reports following error for some test codes.

```
  valgrind --leak-check=full --show-leak-kinds=all bin/flb-it-parser_json 
==9085== Memcheck, a memory error detector
==9085== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==9085== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==9085== Command: bin/flb-it-parser_json
==9085== 
Test basic...                                   ==9086== Warning: invalid file descriptor -1 in syscall close()
[ OK ]
==9086== Warning: invalid file descriptor -1 in syscall close()
==9086== 
==9086== HEAP SUMMARY:
==9086==     in use at exit: 80 bytes in 1 blocks
==9086==   total heap usage: 1,666 allocs, 1,665 frees, 202,514 bytes allocated
==9086== 
==9086== 80 bytes in 1 blocks are still reachable in loss record 1 of 1
==9086==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==9086==    by 0x144FA8: main (acutest.h:1632)
==9086== 
==9086== LEAK SUMMARY:
==9086==    definitely lost: 0 bytes in 0 blocks
==9086==    indirectly lost: 0 bytes in 0 blocks
==9086==      possibly lost: 0 bytes in 0 blocks
==9086==    still reachable: 80 bytes in 1 blocks
==9086==         suppressed: 0 bytes in 0 blocks
==9086== 
==9086== For lists of detected and suppressed errors, rerun with: -s
==9086== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Test time_key...                                ==9087== Warning: invalid file descriptor -1 in syscall close()
[ OK ]
==9087== Warning: invalid file descriptor -1 in syscall close()
==9087== 
==9087== HEAP SUMMARY:
==9087==     in use at exit: 80 bytes in 1 blocks
==9087==   total heap usage: 1,677 allocs, 1,676 frees, 215,527 bytes allocated
==9087== 
==9087== 80 bytes in 1 blocks are still reachable in loss record 1 of 1
==9087==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==9087==    by 0x144FA8: main (acutest.h:1632)
==9087== 
==9087== LEAK SUMMARY:
==9087==    definitely lost: 0 bytes in 0 blocks
==9087==    indirectly lost: 0 bytes in 0 blocks
==9087==      possibly lost: 0 bytes in 0 blocks
==9087==    still reachable: 80 bytes in 1 blocks
==9087==         suppressed: 0 bytes in 0 blocks
==9087== 
==9087== For lists of detected and suppressed errors, rerun with: -s
==9087== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Test time_keep...                               ==9088== Warning: invalid file descriptor -1 in syscall close()
[ OK ]
==9088== Warning: invalid file descriptor -1 in syscall close()
==9088== 
==9088== HEAP SUMMARY:
==9088==     in use at exit: 80 bytes in 1 blocks
==9088==   total heap usage: 1,677 allocs, 1,676 frees, 215,527 bytes allocated
==9088== 
==9088== 80 bytes in 1 blocks are still reachable in loss record 1 of 1
==9088==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==9088==    by 0x144FA8: main (acutest.h:1632)
==9088== 
==9088== LEAK SUMMARY:
==9088==    definitely lost: 0 bytes in 0 blocks
==9088==    indirectly lost: 0 bytes in 0 blocks
==9088==      possibly lost: 0 bytes in 0 blocks
==9088==    still reachable: 80 bytes in 1 blocks
==9088==         suppressed: 0 bytes in 0 blocks
==9088== 
==9088== For lists of detected and suppressed errors, rerun with: -s
==9088== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Test types_is_not_supported...                  ==9089== Warning: invalid file descriptor -1 in syscall close()
[ OK ]
==9089== Warning: invalid file descriptor -1 in syscall close()
==9089== 
==9089== HEAP SUMMARY:
==9089==     in use at exit: 80 bytes in 1 blocks
==9089==   total heap usage: 1,668 allocs, 1,667 frees, 202,534 bytes allocated
==9089== 
==9089== 80 bytes in 1 blocks are still reachable in loss record 1 of 1
==9089==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==9089==    by 0x144FA8: main (acutest.h:1632)
==9089== 
==9089== LEAK SUMMARY:
==9089==    definitely lost: 0 bytes in 0 blocks
==9089==    indirectly lost: 0 bytes in 0 blocks
==9089==      possibly lost: 0 bytes in 0 blocks
==9089==    still reachable: 80 bytes in 1 blocks
==9089==         suppressed: 0 bytes in 0 blocks
==9089== 
==9089== For lists of detected and suppressed errors, rerun with: -s
==9089== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Test decode_field_json...                       ==9090== Warning: invalid file descriptor -1 in syscall close()
[ OK ]
==9090== Warning: invalid file descriptor -1 in syscall close()
==9090== 
==9090== HEAP SUMMARY:
==9090==     in use at exit: 80 bytes in 1 blocks
==9090==   total heap usage: 1,703 allocs, 1,702 frees, 287,671 bytes allocated
==9090== 
==9090== 80 bytes in 1 blocks are still reachable in loss record 1 of 1
==9090==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==9090==    by 0x144FA8: main (acutest.h:1632)
==9090== 
==9090== LEAK SUMMARY:
==9090==    definitely lost: 0 bytes in 0 blocks
==9090==    indirectly lost: 0 bytes in 0 blocks
==9090==      possibly lost: 0 bytes in 0 blocks
==9090==    still reachable: 80 bytes in 1 blocks
==9090==         suppressed: 0 bytes in 0 blocks
==9090== 
==9090== For lists of detected and suppressed errors, rerun with: -s
==9090== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
SUCCESS: All unit tests have passed.
==9085== 
==9085== HEAP SUMMARY:
==9085==     in use at exit: 0 bytes in 0 blocks
==9085==   total heap usage: 3 allocs, 3 frees, 1,141 bytes allocated
==9085== 
==9085== All heap blocks were freed -- no leaks are possible
==9085== 
==9085== For lists of detected and suppressed errors, rerun with: -s
==9085== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by edsiper** [comment]
pls fix the conflict, I will take a look at acutest after that.

**Comment by nokute78** [comment]
@edsiper Thank you for fixing conflict.

> acutest 

Valgrind reports same leak for other test case. e.g. flb-it-sds.
The leak size is proportional to a number of test case. (= 16byte x test case.)

**Pull request merged**
