### PR TITLE
node_exporter_metrics: Support individual on/off and intervals for metrics

### PR DESCRIPTION
**Pull request by cosmo0920**
Currently, node_exporter_metrics does not support switch on/off for each of metrics and support each of intervals of scrapiong metrics neither. 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change
```python
[SERVICE]
    flush           1
    log_level       info

[INPUT]
    name            node_exporter_metrics
    tag             fluentbit.metrics.${HOSTNAME}
    scrape_interval 5
    collector.cpu.scrape_interval 5
    collector.cpufreq.scrape_interval 15
    collector.meminfo.scrape_interval 5
    collector.diskstats.scrape_interval 30
    collector.filesystem.scrape_interval 25
    collector.uname.scrape_interval 50
    collector.stat.scrape_interval 35
    collector.time.scrape_interval 55
    collector.loadavg.scrape_interval 20
    collector.vmstat.scrape_interval 40
    collector.netdev.scrape_interval 60
    collector.filefd.scrape_interval 70

[OUTPUT]
    name stdout
    Match *
```
- [x] Debug log output from testing the change

<details>

```
Fluent Bit v2.0.9
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/01/26 16:56:13] [ info] [fluent bit] version=2.0.9, commit=16eae10786, pid=468078
[2023/01/26 16:56:13] [ info] [storage] ver=1.2.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/01/26 16:56:13] [ info] [cmetrics] version=0.5.8
[2023/01/26 16:56:13] [ info] [ctraces ] version=0.2.7
[2023/01/26 16:56:13] [ info] [input:node_exporter_metrics:node_exporter_metrics.0] initializing
[2023/01/26 16:56:13] [ info] [input:node_exporter_metrics:node_exporter_metrics.0] storage_strategy='memory' (memory only)
[2023/01/26 16:56:13] [ info] [input:node_exporter_metrics:node_exporter_metrics.0] path.procfs = /proc
[2023/01/26 16:56:13] [ info] [input:node_exporter_metrics:node_exporter_metrics.0] path.sysfs  = /sys
[2023/01/26 16:56:13] [ info] [output:stdout:stdout.0] worker #0 started
[2023/01/26 16:56:13] [ info] [sp] stream processor started
1970-01-01T00:00:00.000000000Z node_intr_total = 0
1970-01-01T00:00:00.000000000Z node_context_switches_total = 0
1970-01-01T00:00:00.000000000Z node_forks_total = 0
1970-01-01T00:00:00.000000000Z node_vmstat_pgpgin = 0
1970-01-01T00:00:00.000000000Z node_vmstat_pgpgout = 0
1970-01-01T00:00:00.000000000Z node_vmstat_pswpin = 0
1970-01-01T00:00:00.000000000Z node_vmstat_pswpout = 0
1970-01-01T00:00:00.000000000Z node_vmstat_pgfault = 0
1970-01-01T00:00:00.000000000Z node_vmstat_pgmajfault = 0
1970-01-01T00:00:00.000000000Z node_vmstat_oom_kill = 0
1970-01-01T00:00:00.000000000Z node_memory_MemTotal_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_MemFree_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_MemAvailable_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Buffers_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Cached_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_SwapCached_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Active_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Inactive_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Active_anon_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Inactive_anon_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Active_file_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Inactive_file_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Unevictable_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Mlocked_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_SwapTotal_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_SwapFree_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Dirty_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Writeback_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_AnonPages_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Mapped_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Shmem_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_KReclaimable_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Slab_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_SReclaimable_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_SUnreclaim_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_KernelStack_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_PageTables_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_NFS_Unstable_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Bounce_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_WritebackTmp_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_CommitLimit_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Committed_AS_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_VmallocTotal_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_VmallocUsed_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_VmallocChunk_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Percpu_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_HardwareCorrupted_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_AnonHugePages_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_ShmemHugePages_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_ShmemPmdMapped_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_FileHugePages_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_FilePmdMapped_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_HugePages_Total = 0
1970-01-01T00:00:00.000000000Z node_memory_HugePages_Free = 0
1970-01-01T00:00:00.000000000Z node_memory_HugePages_Rsvd = 0
1970-01-01T00:00:00.000000000Z node_memory_HugePages_Surp = 0
1970-01-01T00:00:00.000000000Z node_memory_Hugepagesize_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_Hugetlb_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_DirectMap4k_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_DirectMap2M_bytes = 0
1970-01-01T00:00:00.000000000Z node_memory_DirectMap1G_bytes = 0
1970-01-01T00:00:00.000000000Z node_boot_time_seconds = 0
1970-01-01T00:00:00.000000000Z node_procs_running = 0
1970-01-01T00:00:00.000000000Z node_procs_blocked = 0
1970-01-01T00:00:00.000000000Z node_time_seconds = 0
1970-01-01T00:00:00.000000000Z node_load1 = 0
1970-01-01T00:00:00.000000000Z node_load5 = 0
1970-01-01T00:00:00.000000000Z node_load15 = 0
1970-01-01T00:00:00.000000000Z node_filefd_allocated = 0
1970-01-01T00:00:00.000000000Z node_filefd_maximum = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="0",mode="idle"} = 104132.46000000001
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="0",mode="iowait"} = 268.00999999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="0",mode="irq"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="0",mode="nice"} = 13.32
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="0",mode="softirq"} = 1207.3299999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="0",mode="steal"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="0",mode="system"} = 2438.0500000000002
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="0",mode="user"} = 5879.3999999999996
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="1",mode="idle"} = 21159.650000000001
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="1",mode="iowait"} = 30.5
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="1",mode="irq"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="1",mode="nice"} = 9.5399999999999991
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="1",mode="softirq"} = 1713.21
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="1",mode="steal"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="1",mode="system"} = 2469.8899999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="1",mode="user"} = 6275.2600000000002
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="2",mode="idle"} = 21795.369999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="2",mode="iowait"} = 27.41
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="2",mode="irq"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="2",mode="nice"} = 9.6999999999999993
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="2",mode="softirq"} = 28.109999999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="2",mode="steal"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="2",mode="system"} = 2505.1199999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="2",mode="user"} = 6550.5
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="3",mode="idle"} = 21960.639999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="3",mode="iowait"} = 52.659999999999997
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="3",mode="irq"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="3",mode="nice"} = 16.210000000000001
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="3",mode="softirq"} = 5.7599999999999998
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="3",mode="steal"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="3",mode="system"} = 2331.5500000000002
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="3",mode="user"} = 6311.4200000000001
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="4",mode="idle"} = 21772.98
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="4",mode="iowait"} = 33.530000000000001
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="4",mode="irq"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="4",mode="nice"} = 12.67
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="4",mode="softirq"} = 6.8899999999999997
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="4",mode="steal"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="4",mode="system"} = 2483.0500000000002
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="4",mode="user"} = 6632.3599999999997
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="5",mode="idle"} = 21964.439999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="5",mode="iowait"} = 34.409999999999997
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="5",mode="irq"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="5",mode="nice"} = 7.6100000000000003
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="5",mode="softirq"} = 4
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="5",mode="steal"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="5",mode="system"} = 2398.9400000000001
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="5",mode="user"} = 6597.71
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="6",mode="idle"} = 21839.110000000001
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="6",mode="iowait"} = 29.879999999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="6",mode="irq"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="6",mode="nice"} = 11.48
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="6",mode="softirq"} = 3.52
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="6",mode="steal"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="6",mode="system"} = 2525.5500000000002
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="6",mode="user"} = 6717.9700000000003
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="7",mode="idle"} = 21806.389999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="7",mode="iowait"} = 28.690000000000001
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="7",mode="irq"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="7",mode="nice"} = 7.1799999999999997
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="7",mode="softirq"} = 1.47
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="7",mode="steal"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="7",mode="system"} = 2520.8299999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="7",mode="user"} = 6621.0699999999997
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="8",mode="idle"} = 21937.279999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="8",mode="iowait"} = 30.879999999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="8",mode="irq"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="8",mode="nice"} = 6.3099999999999996
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="8",mode="softirq"} = 4.8399999999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="8",mode="steal"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="8",mode="system"} = 2451.6199999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="8",mode="user"} = 6408.1199999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="9",mode="idle"} = 21829.759999999998
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="9",mode="iowait"} = 30.370000000000001
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="9",mode="irq"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="9",mode="nice"} = 7.7199999999999998
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="9",mode="softirq"} = 1.1200000000000001
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="9",mode="steal"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="9",mode="system"} = 4706.79
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="9",mode="user"} = 3915.1199999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="10",mode="idle"} = 21965.18
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="10",mode="iowait"} = 32.289999999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="10",mode="irq"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="10",mode="nice"} = 12.710000000000001
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="10",mode="softirq"} = 7.7300000000000004
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="10",mode="steal"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="10",mode="system"} = 2485.1700000000001
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="10",mode="user"} = 6243.7700000000004
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="11",mode="idle"} = 21905.73
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="11",mode="iowait"} = 35.649999999999999
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="11",mode="irq"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="11",mode="nice"} = 13.48
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="11",mode="softirq"} = 126.12
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="11",mode="steal"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="11",mode="system"} = 2456.6999999999998
2023-01-26T07:56:18.271001386Z node_cpu_seconds_total{cpu="11",mode="user"} = 6433.1999999999998
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="0",mode="user"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="0",mode="nice"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="1",mode="user"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="1",mode="nice"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="2",mode="user"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="2",mode="nice"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="3",mode="user"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="3",mode="nice"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="4",mode="user"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="4",mode="nice"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="5",mode="user"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="5",mode="nice"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="6",mode="user"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="6",mode="nice"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="7",mode="user"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="7",mode="nice"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="8",mode="user"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="8",mode="nice"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="9",mode="user"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="9",mode="nice"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="10",mode="user"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="10",mode="nice"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="11",mode="user"} = 0
2023-01-26T07:56:18.271001386Z node_cpu_guest_seconds_total{cpu="11",mode="nice"} = 0
1970-01-01T00:00:00.000000000Z node_intr_total = 0
1970-01-01T00:00:00.000000000Z node_context_switches_total = 0
1970-01-01T00:00:00.000000000Z node_forks_total = 0
1970-01-01T00:00:00.000000000Z node_vmstat_pgpgin = 0
1970-01-01T00:00:00.000000000Z node_vmstat_pgpgout = 0
1970-01-01T00:00:00.000000000Z node_vmstat_pswpin = 0
1970-01-01T00:00:00.000000000Z node_vmstat_pswpout = 0
1970-01-01T00:00:00.000000000Z node_vmstat_pgfault = 0
1970-01-01T00:00:00.000000000Z node_vmstat_pgmajfault = 0
1970-01-01T00:00:00.000000000Z node_vmstat_oom_kill = 0
2023-01-26T07:56:18.298807727Z node_memory_MemTotal_bytes = 67356889088
2023-01-26T07:56:18.298807727Z node_memory_MemFree_bytes = 40800112640
2023-01-26T07:56:18.298807727Z node_memory_MemAvailable_bytes = 60581879808
2023-01-26T07:56:18.298807727Z node_memory_Buffers_bytes = 548032512
2023-01-26T07:56:18.298807727Z node_memory_Cached_bytes = 17622319104
2023-01-26T07:56:18.298807727Z node_memory_SwapCached_bytes = 65536
2023-01-26T07:56:18.298807727Z node_memory_Active_bytes = 6049935360
2023-01-26T07:56:18.298807727Z node_memory_Inactive_bytes = 17123610624
2023-01-26T07:56:18.298807727Z node_memory_Active_anon_bytes = 9625600
2023-01-26T07:56:18.298807727Z node_memory_Inactive_anon_bytes = 5022892032
2023-01-26T07:56:18.298807727Z node_memory_Active_file_bytes = 6040309760
2023-01-26T07:56:18.298807727Z node_memory_Inactive_file_bytes = 12100718592
2023-01-26T07:56:18.298807727Z node_memory_Unevictable_bytes = 13524992
2023-01-26T07:56:18.298807727Z node_memory_Mlocked_bytes = 13524992
2023-01-26T07:56:18.298807727Z node_memory_SwapTotal_bytes = 8538550272
2023-01-26T07:56:18.298807727Z node_memory_SwapFree_bytes = 8536190976
2023-01-26T07:56:18.298807727Z node_memory_Dirty_bytes = 98304
2023-01-26T07:56:18.298807727Z node_memory_Writeback_bytes = 0
2023-01-26T07:56:18.298807727Z node_memory_AnonPages_bytes = 5016838144
2023-01-26T07:56:18.298807727Z node_memory_Mapped_bytes = 1534320640
2023-01-26T07:56:18.298807727Z node_memory_Shmem_bytes = 126562304
2023-01-26T07:56:18.298807727Z node_memory_KReclaimable_bytes = 2383560704
2023-01-26T07:56:18.298807727Z node_memory_Slab_bytes = 2751250432
2023-01-26T07:56:18.298807727Z node_memory_SReclaimable_bytes = 2383560704
2023-01-26T07:56:18.298807727Z node_memory_SUnreclaim_bytes = 367689728
2023-01-26T07:56:18.298807727Z node_memory_KernelStack_bytes = 31326208
2023-01-26T07:56:18.298807727Z node_memory_PageTables_bytes = 66166784
2023-01-26T07:56:18.298807727Z node_memory_NFS_Unstable_bytes = 0
2023-01-26T07:56:18.298807727Z node_memory_Bounce_bytes = 0
2023-01-26T07:56:18.298807727Z node_memory_WritebackTmp_bytes = 0
2023-01-26T07:56:18.298807727Z node_memory_CommitLimit_bytes = 42216992768
2023-01-26T07:56:18.298807727Z node_memory_Committed_AS_bytes = 16481423360
2023-01-26T07:56:18.298807727Z node_memory_VmallocTotal_bytes = 35184372087808
2023-01-26T07:56:18.298807727Z node_memory_VmallocUsed_bytes = 120168448
2023-01-26T07:56:18.298807727Z node_memory_VmallocChunk_bytes = 0
2023-01-26T07:56:18.298807727Z node_memory_Percpu_bytes = 35258368
2023-01-26T07:56:18.298807727Z node_memory_HardwareCorrupted_bytes = 0
2023-01-26T07:56:18.298807727Z node_memory_AnonHugePages_bytes = 0
2023-01-26T07:56:18.298807727Z node_memory_ShmemHugePages_bytes = 0
2023-01-26T07:56:18.298807727Z node_memory_ShmemPmdMapped_bytes = 0
2023-01-26T07:56:18.298807727Z node_memory_FileHugePages_bytes = 0
2023-01-26T07:56:18.298807727Z node_memory_FilePmdMapped_bytes = 0
2023-01-26T07:56:18.298807727Z node_memory_HugePages_Total = 0
2023-01-26T07:56:18.298807727Z node_memory_HugePages_Free = 0
2023-01-26T07:56:18.298807727Z node_memory_HugePages_Rsvd = 0
2023-01-26T07:56:18.298807727Z node_memory_HugePages_Surp = 0
2023-01-26T07:56:18.298807727Z node_memory_Hugepagesize_bytes = 2097152
2023-01-26T07:56:18.298807727Z node_memory_Hugetlb_bytes = 0
2023-01-26T07:56:18.298807727Z node_memory_DirectMap4k_bytes = 2825691136
2023-01-26T07:56:18.298807727Z node_memory_DirectMap2M_bytes = 26086473728
2023-01-26T07:56:18.298807727Z node_memory_DirectMap1G_bytes = 39728447488
1970-01-01T00:00:00.000000000Z node_boot_time_seconds = 0
1970-01-01T00:00:00.000000000Z node_procs_running = 0
1970-01-01T00:00:00.000000000Z node_procs_blocked = 0
1970-01-01T00:00:00.000000000Z node_time_seconds = 0
1970-01-01T00:00:00.000000000Z node_load1 = 0
1970-01-01T00:00:00.000000000Z node_load5 = 0
1970-01-01T00:00:00.000000000Z node_load15 = 0
1970-01-01T00:00:00.000000000Z node_filefd_allocated = 0
1970-01-01T00:00:00.000000000Z node_filefd_maximum = 0
^C[2023/01/26 16:56:27] [engine] caught signal (SIGINT)
[2023/01/26 16:56:27] [ warn] [engine] service will shutdown in max 5 seconds
[2023/01/26 16:56:27] [ info] [input] pausing node_exporter_metrics.0
```

</details>

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

```
==474863== 
==474863== HEAP SUMMARY:
==474863==     in use at exit: 0 bytes in 0 blocks
==474863==   total heap usage: 21,879 allocs, 21,879 frees, 15,551,313 bytes allocated
==474863== 
==474863== All heap blocks were freed -- no leaks are possible
==474863== 
==474863== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [x] Documentation required for this feature

~~Documentation is needed.~~ https://github.com/fluent/fluent-bit-docs/pull/1034

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by patrick-stephens** [comment]
A query: if we disable metrics does that mean we no longer need to mount things like the host procfs into a container or will it still error it is missing? Specifically thinking around security configuration where we want to limit what is exposed and mounted.

**Comment by cosmo0920** [comment]
> A query: if we disable metrics does that mean we no longer need to mount things like the host procfs into a container or will it still error it is missing? Specifically thinking around security configuration where we want to limit what is exposed and mounted.

```c
../plugins/in_node_exporter_metrics/ne_loadavg_linux.c
70:    ret = ne_utils_file_read_lines(ctx->path_procfs, "/loadavg", &list);

../plugins/in_node_exporter_metrics/ne_netdev_linux.c
101:    ret = ne_utils_file_read_lines(ctx->path_procfs, "/net/dev", &list);
239:    ret = ne_utils_file_read_lines(ctx->path_procfs, "/net/dev", &list);

../plugins/in_node_exporter_metrics/ne_filefd_linux.c
61:    ret = ne_utils_file_read_lines(ctx->path_procfs, "/sys/fs/file-nr", &list);

../plugins/in_node_exporter_metrics/ne.h
35:    flb_sds_t path_procfs;

../plugins/in_node_exporter_metrics/ne_config.c
44:    flb_plg_info(ins, "path.procfs = %s", ctx->path_procfs);

../plugins/in_node_exporter_metrics/ne_diskstats_linux.c
408:    ret = ne_utils_file_read_lines(ctx->path_procfs, "/diskstats", &list);

../plugins/in_node_exporter_metrics/ne_vmstat_linux.c
67:    ret = ne_utils_file_read_lines(ctx->path_procfs, "/vmstat", &list);
142:    ret = ne_utils_file_read_lines(ctx->path_procfs, "/vmstat", &list);

../plugins/in_node_exporter_metrics/ne_meminfo_linux.c
55:    ret = ne_utils_file_read_lines(ctx->path_procfs, "/meminfo", &list);
183:    ret = ne_utils_file_read_lines(ctx->path_procfs, "/meminfo", &list);

../plugins/in_node_exporter_metrics/ne_stat_linux.c
86:    ret = ne_utils_file_read_lines(ctx->path_procfs, "/stat", &list);

../plugins/in_node_exporter_metrics/ne_cpu_linux.c
330:    ret = ne_utils_file_read_lines(ctx->path_procfs, "/stat", &list);

../plugins/in_node_exporter_metrics/ne.c
856:     0, FLB_TRUE, offsetof(struct flb_ne, path_procfs),
```

loadavg, netdev, filefd, diskstats, vmstat, meminfo. stat, cpu are depending on `procfs`. 

```c
../plugins/in_node_exporter_metrics/ne_config.c
45:    flb_plg_info(ins, "path.sysfs  = %s", ctx->path_sysfs);

../plugins/in_node_exporter_metrics/ne_cpufreq_linux.c
99:    ret = ne_utils_path_scan(ctx, ctx->path_sysfs, pattern, NE_SCAN_DIR, &list);
121:        ret = ne_utils_file_read_uint64(ctx->path_sysfs,
131:        ret = ne_utils_file_read_uint64(ctx->path_sysfs,
141:        ret = ne_utils_file_read_uint64(ctx->path_sysfs,
152:        ret = ne_utils_file_read_uint64(ctx->path_sysfs,
162:        ret = ne_utils_file_read_uint64(ctx->path_sysfs,
172:        ret = ne_utils_file_read_uint64(ctx->path_sysfs,

../plugins/in_node_exporter_metrics/ne_cpu_linux.c
104:    ret = ne_utils_path_scan(ctx, ctx->path_sysfs, pattern, NE_SCAN_DIR, &list);
122:        ret = ne_utils_file_read_uint64(ctx->path_sysfs,
131:        ret = ne_utils_file_read_uint64(ctx->path_sysfs,
146:        ret = ne_utils_file_read_uint64(ctx->path_sysfs,
173:        ret = ne_utils_file_read_uint64(ctx->path_sysfs,

../plugins/in_node_exporter_metrics/ne.h
36:    flb_sds_t path_sysfs;

../plugins/in_node_exporter_metrics/ne.c
862:     0, FLB_TRUE, offsetof(struct flb_ne, path_sysfs),
```

And cpu and cpufreq are depending on sysfs.
So, if we don't mount procfs or sysfs, fluent-bit just raises errors for depending metrics.

**Comment by patrick-stephens** [comment]
> if we don't mount procfs or sysfs, fluent-bit just raises errors for depending metrics.

Sorry to be unclear @cosmo0920 but does this mean if we disable a feature it will still fail to run with an error? If it reports an error but continues can we just suppress the noisy error?

**Comment by cosmo0920** [comment]
> Sorry to be unclear @cosmo0920 but does this mean if we disable a feature it will still fail to run with an error?

Yes. `in_node_exporter_metrics` is highly tight coupled for procfs and sysfs. So, we can't proceed to retrieve metrics without mounting procfs/sysfs.

**Comment by edsiper** [comment]
@cosmo0920 to get this merged pls:

- what about to rename `ne.` prefix to `collector.` ?
- fix code conflict

**Comment by cosmo0920** [comment]
> * what about to rename `ne.` prefix to `collector.` ?
> 
> * fix code conflict

Done!

**Comment by patrick-stephens** [comment]
Covers https://github.com/fluent/fluent-bit/issues/5768

**Pull request merged**
