### PR TITLE
examples: filter_wasm_go: Upgrade to support Go 1.22.5 and TinyGo 0.32

### PR DESCRIPTION
**Pull request by opencmit2**
examples: filter_wasm_go: Upgrade to support Go 1.22.5 and TinyGo 0.32
  
Changes include:  
  
1. **Go Toolchain Update**: The Go toolchain used for building WebAssembly modules has  
   been upgraded to Go 1.22.5. This ensures that the compiled WASM modules take advantage  
   of the latest compiler optimizations and language improvements.  
  
2. **TinyGo Integration**: TinyGo support has been updated to version 0.32, which  
   introduces new optimizations and potentially new APIs for WebAssembly development.  
   This allows for smaller binary sizes and potentially better performance in  
   resource-constrained environments.  
  
3. **Documentation Updates**: The documentation for filter_wasm_go has been updated to  
   reflect the new supported versions of Go and TinyGo, as well as any changes in  
   build/deployment instructions.  
  
4. **Dependency Management**: Any third-party dependencies required for building or  
   testing the WebAssembly filters have been updated to be compatible with the new  
   versions of Go and TinyGo.  

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [x] Example configuration file for the change
- [x] Debug log output from testing the change

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [x] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [x] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [x] Documentation required for this feature

**Backporting**

- [x] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by cosmo0920** [comment]
@opencmit2 Could you use `examples: filter_wasm_go: Upgrade to support Go 1.22.5 and TinyGo 0.32` in your commit message to follow the contribution guide?

**Comment by opencmit2** [comment]
@cosmo0920 Is this the case?

**Comment by cosmo0920** [comment]
> @cosmo0920 Is this the case?

No. You should update your commit message with: `examples: filter_wasm_go: Upgrade to support Go 1.22.5 and TinyGo 0.32`.
I didn't observed that yet.

**Comment by opencmit2** [comment]
@cosmo0920 Modified, but I accidentally used a private account to submit

**Review by im-jinxinwang — COMMENTED** [review]
examples: filter_wasm_go: Upgrade to support Go 1.22.5 and TinyGo 0.32

**Pull request closed without merging**
