### PR TITLE
[WIP] Throttling filter

### PR DESCRIPTION
**Pull request by onorua**
There are cases when you need to handle only the load you agreed on, and drop the rest (some sort of internal service with SLA). This plugin does exactly this. We have some rate per second, and we drop messages above it. It implements leaky bucket, based on sliding window algorithm. 

There are couple of things we could improve on though (looking forward to your suggestions):

1. I would like to have a background time ticker, don't know how to make it using fluent-bit framework. Should I wake up on the event, or some background thread is enough. 
2. Do you think we need different time ranges, like per minute, per hour etc? 
3. Do think anything can be improved? I got 1 core nocked out for more than 100k req/sec.

What do you think about the idea in general?

### CODE REVIEW

**Comment by onorua** [comment]
@edsiper should I create something similar to `flb_input_set_collector_time` for filter? Do you think such a functionality can be merged when done, or this is something you don't want in mainline?

**Comment by edsiper** [comment]
hi @onorua 

If this plugin is for a production use-case I am happy to have it there.

regarding your questions:

1. __I would like to have a background time ticker, don't know how to make it using fluent-bit framework__
Ideally this need to have a time_collector into the filters which don't exists at the moment. I think it's necessary, I can add the bits for that.

2. __Should I wake up on the event, or some background thread is enough.__
I think #1 is enough

3. __Do you think we need different time ranges, like per minute, per hour etc?__
do you have more use-cases ?, I would like to learn more from that.

4. __Do think anything can be improved? I got 1 core nocked out for more than 100k req/sec.__
do you mean to increase performance ?

**Comment by edsiper** [comment]
@onorua are you still interested into merge improve this feature ?

**Comment by onorua** [comment]
Yes, we have this in production for some time and really happy about it. Give me couple of days for tests coverage. I'll split this PR into 2 PRs one for throttling and another one for elastic search index regexp.

**Comment by onorua** [comment]
closing in favor of https://github.com/fluent/fluent-bit/pull/511

**Pull request closed without merging**
