### PR TITLE
core: Add 'Match_Regex' option to filter/task/output

### PR DESCRIPTION
**Pull request by donbowman**
If Match_Regex is specified it will be used in flb_router_match().

Signed-off-by: Don Bowman <don@agilicus.com>

### CODE REVIEW

**Comment by kskewes** [comment]
Nice! This would be great. Happy to test out.

**Comment by edsiper** [comment]
thanks for this contribution, looks like a good addition.

In order to add this feature and do not disable the old way I think it should go in the following way:

- If FLB_HAVE_REGEX is enabled, support match with regex rule
- Use _only_ the _Match_ key to put either the old pattern or the regular expression
- The new option _Match_Regex_ be a boolean, if enabled, _Match_ uses the Regex match backend, otherwise, it keeps working as of now.

with these changes, we continue supporting the old mode and we let the user decide how to proceed, since Regex can be more expensive I prefer the user decide what to use on every filter/output section/

**Comment by donbowman** [comment]
OK.
I think it does achieve this already tho? e.g. the user can continue to use match as-is, and it will only use match_regex if specified? so only the individual sections that specified a regex would use it.

i'll make the change but maybe you can comment on how this would be different? E.g. if Match_Regex is boolean, then the interpretation of Match is different, vs Match is always Glob and Match_Regex, if specified, is always regex. It seems these achieve the same goal.

**Comment by edsiper** [comment]
I see the Match Regex feature (if enabled), overrides the old mechanism at build time:

https://github.com/fluent/fluent-bit/pull/918/files#diff-9c8c857db25214091f8d282566975a73R32

they should be two separate functions so the user can decide which mechanism to use.

**Comment by donbowman** [comment]
no, it doesn't override. only if its been set by the user:

case 1:
```
[OUTPUT]
  Match tag.*
```
Uses only the 'glob' match, no regex
case 2:
```
[OUTPUT]
  Match_Regex tag.*
```
Uses only the regex match

case 3:
```
[OUTPUT]
  Match tag.*
  Match_Regex tag.*
```

Uses only the Match_Regex

**Comment by edsiper** [comment]
thanks for the clarification

**Pull request merged**
