### PR TITLE
filter_parser: add new plugin filter_parser

### PR DESCRIPTION
**Pull request by nokute78**
I added a new plugin filter_parser.
It parses records at filter plugin.

## Configuration file

I got a nginx log from 
https://raw.githubusercontent.com/elastic/examples/master/ElasticStack_NGINX/nginx_logs

This example is to parse record which is generated  by in_head.

```
[SERVICE]
    Parsers_File /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/conf/parsers.conf

[INPUT]
    Name head
    file /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/build/nginx.log
    line 1


[FILTER]
    Name parser
    Match *
    Key_Name head
    Parser nginx

[OUTPUT]
    Name stdout
    Match *
```

## result
```
$ bin/fluent-bit -c dummy.conf  
Fluent-Bit v0.12.0
Copyright (C) Treasure Data

[2017/06/24 00:23:23] [ info] [engine] started
[0] head.0: [1498231404.001205864, {"remote"=>"93.180.71.3", "host"=>"-", "user"=>"-", "method"=>"GET", "path"=>"/downloads/product_1", "code"=>"304", "size"=>"0", "referer"=>"-", "agent"=>"Debian APT-HTTP/1.3 (0.8.16~exp12ubuntu10.21)"}]
```

### CODE REVIEW

**Comment by edsiper** [comment]
you won! I planed to start working on this next week :P 

It will be reviewed shortly (Monday)

**Comment by nokute78** [comment]
yeah!

I'm waiting, thanks.

**Comment by edsiper** [comment]
The filter looks very good. 

One thing to add is to do timestamp management, note that parsers might be aware about how to retrieve a timestamp, check how this is being done in in_tail:

```C
ret = flb_parser_do(ctx->parser, data, len, &out_buf, &out_size, &out_time);
if (ret >= 0) {
    if (flb_time_to_double(&out_time) == 0) {
         flb_time_get(&out_time);
    }
}
```
https://github.com/fluent/fluent-bit/blob/master/plugins/in_tail/tail_file.c#L209

**Comment by nokute78** [comment]
@edsiper Thank you for reviewing.

Your patch is to handle timestamp at parsing.
So, I will fix it and add "reserve_time" feature which comes from fluentd and it is to handle event time at parsing.

http://docs.fluentd.org/v0.14/articles/filter_parser#reservetime

**Comment by edsiper** [comment]
Reserve time is not required as this is handled by the parsers (check Time_Keep option)

**Comment by nokute78** [comment]
@edsiper Yes, so is it better to send another PR to support "reserve_time" feature ?

Fluentd handles timestamp like this. "else case" will be implemented with your patch.
I thought it is clear to add codes to handle timestamp with reserve_time in this PR and I sent a comment.
```ruby
        @parser.parse(raw_value) do |t, values|
          if values
            t = if @reserve_time
                  time
                else
                  t.nil? ? time : t
                end
            r = handle_parsed(tag, record, t, values)
            return t, r
```

**Comment by edsiper** [comment]
No, it should __not__ be implemented because is already supported when you use a parser

**Comment by nokute78** [comment]
I updated timestamp handling and we can get timestamp from record.

The timestamp "1431849932.000000000" comes from nginx.log.
```
$ bin/fluent-bit -c dummy.conf 
Fluent-Bit v0.12.0
Copyright (C) Treasure Data

[2017/06/27 10:11:00] [ info] [engine] started
[0] head.0: [1431849932.000000000, {"remote"=>"93.180.71.3", "host"=>"-", "user"=>"-", "method"=>"GET", "path"=>"/downloads/product_1", "code"=>"304", "size"=>"0", "referer"=>"-", "agent"=>"Debian APT-HTTP/1.3 (0.8.16~exp12ubuntu10.21)"}]
[1] head.0: [1431849932.000000000, {"remote"=>"93.180.71.3", "host"=>"-", "user"=>"-", "method"=>"GET", "path"=>"/downloads/product_1", "code"=>"304", "size"=>"0", "referer"=>"-", "agent"=>"Debian APT-HTTP/1.3 (0.8.16~exp12ubuntu10.21)"}]
[2] head.0: [1431849932.000000000, {"remote"=>"93.180.71.3", "host"=>"-", "user"=>"-", "method"=>"GET", "path"=>"/downloads/product_1", "code"=>"304", "size"=>"0", "referer"=>"-", "agent"=>"Debian APT-HTTP/1.3 (0.8.16~exp12ubuntu10.21)"}]
[3] head.0: [1431849932.000000000, {"remote"=>"93.180.71.3", "host"=>"-", "user"=>"-", "method"=>"GET", "path"=>"/downloads/product_1", "code"=>"304", "size"=>"0", "referer"=>"-", "agent"=>"Debian APT-HTTP/1.3 (0.8.16~exp12ubuntu10.21)"}]
```

**Comment by nokute78** [comment]
@edsiper Oops, I missed your comment.

> No, it should not be implemented because is already supported when you use a parser

I don't think so.

Parser API returns timestamp either of
* parsed time from key-value
* 0
* now time
https://github.com/fluent/fluent-bit/blob/master/src/flb_parser_regex.c#L131

There is no way to get event time of record with parser API.

Fluentd uses timestamp either  of
* parsed time from key-value
* event time of record ( if parsed time is 0. fluentd also uses eventtime of record )

**Comment by edsiper** [comment]
I've tested the following:

1. reset to 7bcfc7f370dbdb89233894315b3781d1dca74b0d commit

2. do this change:

```
@@ -171,6 +171,9 @@ static int cb_parser_filter(void *data, size_t bytes,
                     if ( flb_parser_do(ctx->parser,
                                         val_str, val_len,
                                        (void **)&out_buf, &out_size, &not_use) >= 0) {
+                        if (flb_time_to_double(&not_use) != 0) {
+                            flb_time_copy(&tm, &not_use);
+                        }
                         break;
```

3. recompile and run Fluent Bit with this command:

```
bin/fluent-bit -R ../conf/parsers.conf -i tail -p path=../nginx.log -F parser -m '*' -p parser=nginx -p key_name=log -o stdout -f 1
```

the content of nginx.log is:

```
80.154.42.54 - - [23/Aug/2010:15:25:35 +0000] "GET /phpmy-admin/scripts/setup.php HTTP/1.1" 404 347 "-" "ZmEu"
80.154.42.80 - - [23/Aug/2010:15:25:35 +0000] "GET /phpmy-admin/scripts/setup.php HTTP/1.1" 404 347 "-" "aaaa"
```

You will see the following output:

```
[0] tail.0: [1282577135.000000000, {"remote"=>"80.154.42.54", "host"=>"-", "user"=>"-", "method"=>"GET", "path"=>"/phpmy-admin/scripts/setup.php", "code"=>"404", "size"=>"347", "referer"=>"-", "agent"=>"ZmEu"}]
[1] tail.0: [1282577135.000000000, {"remote"=>"80.154.42.80", "host"=>"-", "user"=>"-", "method"=>"GET", "path"=>"/phpmy-admin/scripts/setup.php", "code"=>"404", "size"=>"347", "referer"=>"-", "agent"=>"aaaa"}]
```

Now if you want to keep the time field in the final record just edit parsers.conf in the nginx section and append Time_Keep On, e.g:

```
[PARSER]
    Name   nginx
    Format regex
    Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z
    Time_Keep On
```

Then you will see:

```
[0] tail.0: [1282577135.000000000, {"remote"=>"80.154.42.54", "host"=>"-", "user"=>"-", "time"=>"23/Aug/2010:15:25:35 +0000", "method"=>"GET", "path"=>"/phpmy-admin/scripts/setup.php", "code"=>"404", "size"=>"347", "referer"=>"-", "agent"=>"ZmEu"}]
[1] tail.0: [1282577135.000000000, {"remote"=>"80.154.42.80", "host"=>"-", "user"=>"-", "time"=>"23/Aug/2010:15:25:35 +0000", "method"=>"GET", "path"=>"/phpmy-admin/scripts/setup.php", "code"=>"404", "size"=>"347", "referer"=>"-", "agent"=>"aaaa"}]
```

So the reserve_time is not required because Parsers in Fluent Bit already have that feature.

**Comment by nokute78** [comment]
@edsiper Thanks, but it is not about "reserve_time" of fluentd.
http://docs.fluentd.org/v0.14/articles/filter_parser#reservetime

It is an option to control "timestamp of each record" not to control "time_key value" included each record.


I tested fluentd v0.14.18 with the configuration file of fluentd.
```
<source>
  @type tail
  tag raw.test
  path /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/build/nginx.log
  format none
  read_from_head true
</source>
<filter *.*>
  @type parser
  format nginx
  key_name message
  reserve_time false # This is the point.
</filter>

<match *.*>
   @type   stdout
</match>
```

## reserve_time is true

The output is like this.
The timestamp is "2017-06-27 14:20:19.250932861 +0900" which is the time in_tail read.
```
2017-06-27 14:20:19.250932861 +0900 raw.test: {"remote":"93.180.71.3","host":"-","user":"-","method":"GET","path":"/downloads/product_1","code":"304","size":"0","referer":"-","agent":"Debian APT-HTTP/1.3 (0.8.16~exp12ubuntu10.21)"}
```

## reserve_time is false

The output is like this. 
The timestamp is "2015-05-17 17:05:32.000000000 +0900" which comes from nginx.log.
```
2015-05-17 17:05:32.000000000 +0900 raw.test: {"remote":"93.180.71.3","host":"-","user":"-","method":"GET","path":"/downloads/product_1","code":"304","size":"0","referer":"-","agent":"Debian APT-HTTP/1.3 (0.8.16~exp12ubuntu10.21)"}
```

**Comment by edsiper** [comment]
reserve_time true in Fluent Bit becomes (parsers.conf):

```
[PARSER]
    Name   nginx
    Format regex
    Regex ^(?<remote>...
```

> No time key resolution

reserve_time true becomes:

```
[PARSER]
    Name   nginx
    Format regex
    Regex ^...
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z
```

Optionally Time_Keep exists to manage the time key record, but the parser is done to override record timestamp too

**Comment by nokute78** [comment]
@edsiper That's what I want to do.
I reset latest commit and merged your patch.

Thank you so much!

**Comment by edsiper** [comment]
thanks.

**Comment by spatialvlad** [comment]
It looks like the filter_parser plugin has an error in processing timestamp.

The timestamp that I get out of the filter_parser is (what it looks like) randomly substantially bigger or smaller than the original one.

E.g. 
I get this event (the time field shows time printed out of the logger in my code) when stdout output plugin:
`[1] fe7dbb4a4b27: [731261672.100973344, {"time"=>"2017-07-07T19:31:51.142Z"}]`
Converting this timestamp to human readable format I get:

`GMT: Thursday, March 4, 1993 4:14:32.100 PM`
Elasticsearch also gives same wrong value:
```
"_source": {
          "@timestamp": "1993-03-04T16:14:32.100Z",
          "time": "2017-07-07T19:31:47.693Z"
}
```

Next time when I start the services and use them again, I can get something like this:
```
"_source": {
          "@timestamp": "2099-09-03T16:39:04.6Z",
          "time": "2017-07-07T19:31:45.736Z",
}
```

My Filter config is:
```
[FILTER]
    Name            parser
    Match           *
    Key_Name    log
    Parser           json
```
I tried different variations of parsers and their setup in the Filter config with same result.

Commenting out filter_parser fixes the issue. Stdout output:
`[0] fe7dbb4a4b27: [1499457024.000000000, {"time":"2017-07-07T19:50:24.910Z"}]`

Converting this timestamp I get:
GMT: Friday, July 7, 2017 7:50:24 PM

And Elastisearch also outputs similar data (with the problem of log being not parsed, but with correct timestamp):
"_source": {
          "@timestamp": "2017-07-07T19:50:05.0Z",
          "log": """{"time":"2017-07-07T19:50:05.252Z"}"""
}

**Comment by edsiper** [comment]
@spatialvlad in order to troubleshoot please provide:

1. output of fluent-bit -c yourconffile.conf  --sosreport
2. the content of your parser.conf file

**Comment by spatialvlad** [comment]
@edsiper ,
It looks like it might have been a false alarm on my end.
I likely used a wrong type of parser initially (even though I think I did try multiple variants without getting results initial).

Anyway, if I use the standard docker one:
```
[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   On
```
I end up getting correct timestamp.
Thanks.

**Comment by edsiper** [comment]
@spatialvlad  thanks for confirming.

**Comment by davide-romanini** [comment]
I'm using filter_parser to better parse php-fpm output from docker containers. It works fine, but it looses any other key originally present in the log:
```
{"log":"[17-Jul-2017 09:31:09] WARNING: [pool www] child 22 said into stderr: \"{\"foo\":\"Foo\",\"bar\":\"Baz\"}\"\r\n","stream":"stdout","time":"2017-07-17T09:31:09.949290842Z"}
```
with parser and filter:
```
[PARSER]
    Name fpm
    Format regex
    Regex ^\[.*\] WARNING: \[pool (?<pool>[a-z]*)\] child .* said into *: \\"(?<log>.*)\\"\\r\\n$

[FILTER]
    Name parser
    Parser fpm
    Match kube.*
    Key_Name log
```
results:
```
[0] tcp.0: [1500289543.082535216, {"pool"=>"www", "log"=>"{\"foo\":\"Foo\",\"bar\":\"Baz\"}"}]
```
In practice `stream` and `time` keys are lost. I think it would be useful adding an option to keep them and just merge with the resulting parser hash. For the php-fpm case I could workaround with:
```
[PARSER]
    Name fpm
    Format regex
    Regex ^\[(?<time>.*)\] WARNING: \[pool (?<pool>[a-z]*)\] child (?<pid>.*) said into (?<stream>.*): \\"(?<log>.*)\\"\\r\\n$
    Time_Key time
    Time_Format %d-%b-%Y %H:%M:%S
```
but I wonder that the time as reported by fpm could be inconsistent with other logs. I would prefer keeping the timestamp as reported by docker.

**Comment by nokute78** [comment]
@davide-romanini Thank you for reporting

I think what you need is "reserve_data" which fluentd supports, but fluent-bit doesn't support now.
http://docs.fluentd.org/v0.12/articles/filter_parser#reservedata

If so, I will try to implement it.

**Comment by spatialvlad** [comment]
@nokute78 , yes, "reserve_data" will be a helpful option, I was going to ask for it as well.
I guess it should solve the problem of @davide-romanini

**Comment by nokute78** [comment]
I pushed #336 to support "reserve_data". Could you check it ?

**Pull request merged**
