### PR TITLE
fluent-bit: fix printf-like format and arguments

### PR DESCRIPTION
**Pull request by ChezBunch**
Fixed format and arguments for:
- flb_log_print(), and associated macros like flb_error() and flb_plg_error()
- flb_sds_printf()

These formatting issues were revealed by #6921 and #6925.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Review by leonardo-albertovich — APPROVED** [review]
Coolest PR ever, do you want to backport it to 2.0 once it's merged or would you rather have me do it?

**Comment by ChezBunch** [comment]
I thought the master branch was still the 2.0.x branch, so I'm confused.
Anyway, I'm not really at ease with your backporting process, so I would prefer you do it yourself (with the backporting of both #6921 and #6925 if necessary).

**Comment by leonardo-albertovich** [comment]
Master is the next version (2.1) and then there's 2.0 which gets fixes but not new features and 1.9 but I'm not really sure what's its status.

Don't worry, once this is merged I'll backport the three of them. 

Thank you very much!

**Comment by edsiper** [comment]
thank you!

**Pull request merged**
