### PR TITLE
lib: librdkafka: upgrade to v2.1.0

### LINKED ISSUE #7175: Build fails with option -DFLB_OUT_KAFKA  ON
## Bug Report
Build fails with option -DFLB_OUT_KAFKA  ON. Tried on fluent-bit v2.0.9 and v2.0.10

**Describe the bug**

**To Reproduce**
***Steps to reproduce the problem:***
- Run cmake with -DFLB_OUT_KAFKA option
```
cmake \
        -DFLB_OUT_KAFKA=On \
        -DFLB_TLS=On \
        -DFLB_HTTP_SERVER=true \
        -DFLB_AVRO_ENCODER=On \
        .
```
- Run build `make`
- You will see below error
```
../library/librdkafka.a(rdhttp.c.o): In function `rd_http_req_destroy':
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:109: undefined reference to `curl_easy_cleanup'
../library/librdkafka.a(rdhttp.c.o): In function `rd_http_req_init':
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:135: undefined reference to `curl_easy_init'
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:141: undefined reference to `curl_easy_setopt'
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:142: undefined reference to `curl_easy_setopt'
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:144: undefined reference to `curl_easy_setopt'
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:145: undefined reference to `curl_easy_setopt'
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:146: undefined reference to `curl_easy_setopt'
../library/librdkafka.a(rdhttp.c.o):/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:148: more undefined references to `curl_easy_setopt' follow
../library/librdkafka.a(rdhttp.c.o): In function `rd_http_req_perform_sync':
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:163: undefined reference to `curl_easy_perform'
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:167: undefined reference to `curl_easy_getinfo'
../library/librdkafka.a(rdhttp.c.o): In function `rd_http_req_get_content_type':
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:184: undefined reference to `curl_easy_getinfo'
../library/librdkafka.a(rdhttp.c.o): In function `rd_http_post_expect_json':
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:316: undefined reference to `curl_easy_setopt'
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:317: undefined reference to `curl_easy_setopt'
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:319: undefined reference to `curl_easy_setopt'
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:321: undefined reference to `curl_easy_setopt'
../library/librdkafka.a(rdhttp.c.o): In function `rd_http_global_init':
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdhttp.c:443: undefined reference to `curl_global_init'
../library/librdkafka.a(rdkafka_sasl_oauthbearer_oidc.c.o): In function `rd_kafka_oidc_build_headers':
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdkafka_sasl_oauthbearer_oidc.c:116: undefined reference to `curl_slist_append'
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdkafka_sasl_oauthbearer_oidc.c:117: undefined reference to `curl_slist_append'
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdkafka_sasl_oauthbearer_oidc.c:119: undefined reference to `curl_slist_append'
../library/librdkafka.a(rdkafka_sasl_oauthbearer_oidc.c.o): In function `rd_kafka_oidc_token_refresh_cb':
/home/user/code/fluent-bit-upstream/fluent-bit-2.0.9/lib/librdkafka-1.9.2/src/rdkafka_sasl_oauthbearer_oidc.c:397: undefined reference to `curl_slist_free_all'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/fluent-bit] Error 1
make[1]: *** [src/CMakeFiles/fluent-bit-bin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target fluent-bit-shared
make: *** [all] Error 2
```

**Expected behavior**

`make` should run successfully

**Screenshots**

**Your Environment**

* Version used: v2.0.9, v2.0.10
* Configuration: cmake v3.23.2
* Environment name and version (e.g. Kubernetes? What version?): N/A
* Server type and version: 
* Operating System and version: CentOS Linux 7
* Filters and plugins:

**Additional context**
How has this issue affected you? What are you trying to accomplish?
We use Kafka as an Output and this is currently blocking our fluent-bit upgrade.

### PR DESCRIPTION
**Pull request by nareshku**
Fixes #7175

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [N/A] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [N/A] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----
**Build**
Build completed successfully.

```
cmake -DFLB_OUT_KAFKA=yes && make
```

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by patrick-stephens** [comment]
Can you resolve the DCO failure?

**Comment by nareshku** [comment]
> Can you resolve the DCO failure?

Yes, signed off DCO.

**Comment by nareshku** [comment]
@patrick-stephens How do I fix the 2 failed checks? One of them seems to be a transient issue, other one for the MacOS build not sure what's the issue is.

**Comment by patrick-stephens** [comment]
I think the macos one may be already fixed, did you rebase the PR?

**Pull request merged**
