### PR TITLE
Added parsing to strip tag string

### PR DESCRIPTION
**Pull request by hassanfarid**
With latest version `fluent/fluent-bit:1.3`, the tag had more data than expected.

### CODE REVIEW

**Comment by edsiper** [comment]
would you please elaborate on what do you mean with "extra data" ?

**Comment by hassanfarid** [comment]
@edsiper - I am getting complete object, including tag, timestamp, log, when accessing tag in Lua script.

**Comment by edsiper** [comment]
I cannot reproduce the original issue:

```
$ bin/fluent-bit -i dummy -p tag=something -p dummy="{\"key1\": {\"s1\": 123}, \"key2\": false}" -F lua -p script=append_tag.lua -p call=append_tag -m '*' -o stdout -f 1
Fluent Bit v1.5.0
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/05/05 17:20:38] [ info] [storage] version=1.0.3, initializing...
[2020/05/05 17:20:38] [ info] [storage] in-memory
[2020/05/05 17:20:38] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/05/05 17:20:38] [ info] [engine] started (pid=3945717)
[2020/05/05 17:20:38] [ info] [sp] stream processor started
[0] something: [1588720838.798947811, {"key1"=>{"s1"=>123.000000}, "key2"=>false, "tag"=>"something"}]
```

script used for the test:

```
function append_tag(tag, timestamp, record)
    new_record = record
    new_record["tag"] = tag
    return 1, timestamp, new_record
end
```

**Comment by edsiper** [comment]
Since no issue is found, I am closing this PR.

If there is a way to reproduce the issue, let's open a new ticket and PR.

**Pull request closed without merging**
