### PR TITLE
out_opentelemetry: add support for OTLP Logs

### LINKED ISSUE #5559: OTLP Support for Logs
**Is your feature request related to a problem? Please describe.**

No. Other than the fact that I can't send logs to OTLP 😂 

**Describe the solution you'd like**

I would like the current OTEL output to be modified to support logs. Specifically support for sending logs to any [OTLP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md) compliant endpoint.

**Describe alternatives you've considered**

n/a

**Additional context**

### PR DESCRIPTION
**Pull request by Syn3rman**
Adds support for exporting Fluent Bit logs to OpenTelemetry collector using OTLP

Fixes #5559 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
```
[INPUT]
	Name dummy
	Tag dummy.log
	Rate 3

[INPUT]
	name node_exporter_metrics
	tag node_metrics
	scrape_interval 2

[OUTPUT]
	name opentelemetry
	match *
	host 172.18.0.2
	port 4318
	logs_uri /v1/logs
	metrics_uri /v1/metrics
```
- [ ] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
```
[2022/07/19 09:45:04] [ info] [fluent bit] version=1.9.5, commit=238dbece1c, pid=79063
[2022/07/19 09:45:04] [ info] [storage] version=1.2.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
[2022/07/19 09:45:04] [ info] [cmetrics] version=0.3.1
[2022/07/19 09:45:04] [ info] [input:node_exporter_metrics:node_exporter_metrics.1] path.procfs = /proc
[2022/07/19 09:45:04] [ info] [input:node_exporter_metrics:node_exporter_metrics.1] path.sysfs  = /sys
[2022/07/19 09:45:04] [ info] [sp] stream processor started
[2022/07/19 09:45:06] [ info] [output:opentelemetry:opentelemetry.0] 172.18.0.2:4318, HTTP status=200
[2022/07/19 09:45:07] [ info] [output:opentelemetry:opentelemetry.0] 172.18.0.2:4318, HTTP status=200
[2022/07/19 09:45:07] [ info] [output:opentelemetry:opentelemetry.0] 172.18.0.2:4318, HTTP status=200
[2022/07/19 09:45:08] [ info] [output:opentelemetry:opentelemetry.0] 172.18.0.2:4318, HTTP status=200
[2022/07/19 09:45:09] [ info] [output:opentelemetry:opentelemetry.0] 172.18.0.2:4318, HTTP status=200
[2022/07/19 09:45:09] [ info] [output:opentelemetry:opentelemetry.0] 172.18.0.2:4318, HTTP status=200
[2022/07/19 09:45:10] [ info] [output:opentelemetry:opentelemetry.0] 172.18.0.2:4318, HTTP status=200
^C[2022/07/19 09:45:10] [engine] caught signal (SIGINT)
[2022/07/19 09:45:10] [ info] [input] pausing node_exporter_metrics.1
[2022/07/19 09:45:10] [ warn] [engine] service will shutdown in max 5 seconds
[2022/07/19 09:45:10] [ info] [output:opentelemetry:opentelemetry.0] 172.18.0.2:4318, HTTP status=200
[2022/07/19 09:45:10] [ info] [output:opentelemetry:opentelemetry.0] 172.18.0.2:4318, HTTP status=200
[2022/07/19 09:45:11] [ info] [engine] service has stopped (0 pending tasks)
==79063==
==79063== HEAP SUMMARY:
==79063==     in use at exit: 66,451 bytes in 2,263 blocks
==79063==   total heap usage: 56,284 allocs, 54,021 frees, 7,764,864 bytes allocated
==79063==
==79063== LEAK SUMMARY:
==79063==    definitely lost: 0 bytes in 0 blocks
==79063==    indirectly lost: 0 bytes in 0 blocks
==79063==      possibly lost: 0 bytes in 0 blocks
==79063==    still reachable: 66,451 bytes in 2,263 blocks
==79063==         suppressed: 0 bytes in 0 blocks
==79063== Rerun with --leak-check=full to see details of leaked memory
==79063==
==79063== For lists of detected and suppressed errors, rerun with: -s
==79063== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [X] Documentation required for this feature

Documentation PR: https://github.com/fluent/fluent-bit-docs/pull/852

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by edsiper** [comment]
@leonardo-albertovich is this PR approved ?

**Comment by edsiper** [comment]
we need a PR for the documentation

**Comment by Syn3rman** [comment]
@edsiper Added link to PR in description  ✅

**Comment by epsteina16** [comment]
Is support for traces for the opentelemetry output plugin currently under development?

**Comment by Syn3rman** [comment]
@epsteina16 yes

**Comment by svettwer** [comment]
Heyho! :wave: 

Thanks a lot @Syn3rman for adding this! :bow: 

I've one question on testing this new feature:

With 
```bash
docker run -p 127.0.0.1:24224:24224 ghcr.io/fluent/fluent-bit/master /fluent-bit/bin/fluent-bit -i forward -f 1 -o opentelemetry logs_uri="/v1/logs"
```
I still get 
```bash
[2022/09/27 10:28:41] [debug] [router] data generated by forward.0 input are logs, but matching destination plugin opentelemetry.0 don't handle logs. Skipping destination.
```

Is there something missing to add this feature to the container build from master? Same goes for the staging container btw. 

Thanks! :smiley:

**Comment by Syn3rman** [comment]
Hey @svettwer ,
Sorry for the late response 😓 
My best guess would be that the url you are using defaults to [`master:latest`](https://github.com/fluent/fluent-bit/pkgs/container/fluent-bit%2Fmaster/21411490?tag=latest) which seems to have been published 5 months ago thus does not have this feature. Could you perhaps try using something like `master:x86-64` instead which I have confirmed works with the following output:
```
[2022/10/05 06:28:29] [debug] [opentelemetry:opentelemetry.0] created event channels: read=24 write=25
[2022/10/05 06:28:29] [debug] [router] default match rule forward.0:opentelemetry.0
```

**Comment by svettwer** [comment]
Took me a while now to come back with feedback. `master:x86-64` indeed contains the new logs output. Thanks again for the hint! :smile:

**Pull request merged**
