### PR TITLE
tail: added configuration for journal mode in WAL

### PR DESCRIPTION
**Pull request by AkshayDubey29**
Signed-off-by: Akshay Dubey <akshay.dubey@walmartlabs.com>

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [x] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by AkshayDubey29** [comment]
#3073

**Comment by AkshayDubey29** [comment]
`[INPUT]
    name    tail
    path    /var/log/containers/*.log
    db.journal_Mode       DELETE | TRUNCATE | PERSIST | MEMORY | WAL | OFF`

**Comment by edsiper** [comment]
@AkshayDubey29 please cleanup the PR and commits, it contains some extra content that is not part of the context of the PR

**Comment by AkshayDubey29** [comment]
Done

**Comment by nokute78** [comment]
@AkshayDubey29 Could you update documentation? 
We need to add `db.journal_Mode` and remove `db.wal`
https://github.com/fluent/fluent-bit-docs/blob/master/pipeline/inputs/tail.md

**Comment by AkshayDubey29** [comment]
@nokute78  I have raised the PR:-

https://github.com/fluent/fluent-bit-docs/pull/492/files

**Comment by nokute78** [comment]
@AkshayDubey29 Oops, I'll comment that PR.
Thank you.

**Pull request merged**
