### PR TITLE
out_influxdb: add support v2

### LINKED ISSUE #3032: out_influxdb support for v2 API
## Bug Report

**Describe the bug**

Unable to ship data to an InfluxDB 2.0 instance as it only supports `Token` authorization header, not basic auth (as currently implemented in out_influxdb)

I've modified the built-in out_influxdb to support v2 (in https://github.com/fopina/fluent-bit-out-influxdb-v2). Should I submit it as PR? If so, should it be added to `out_influxdb`or kept as separate output plugin?

### PR DESCRIPTION
**Pull request by fopina**
Fixes #3032 
----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change
- [x] Debug log output from testing the change

- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [x] Documentation required for this feature

https://github.com/fluent/fluent-bit-docs/pull/457
----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by fopina** [comment]
## testing

Compiled with:

```
cmake -DFLB_DEBUG=On \
          -DFLB_TRACE=Off \
          -DFLB_JEMALLOC=On \
          -DFLB_TLS=On \
          -DFLB_SHARED_LIB=Off \
          -DFLB_EXAMPLES=Off \
          -DFLB_HTTP_SERVER=On \
          -DFLB_IN_SYSTEMD=Off \
          -DFLB_OUT_KAFKA=Off \
          -DFLB_OUT_PGSQL=Off ../
```

test.conf

```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    debug
    HTTP_Server  Off

[INPUT]
    Name cpu
    Tag cpu
    Interval_Sec 10

[OUTPUT]
    Name influxdb
    Match *
    Host influxdb.localhost
    Port 443
    tls on
    tls.verify off
    org wtv
    http_token XXX
    Tag_Keys hostname
```

**Comment by edsiper** [comment]
thanks Filipe!

**Comment by Tautcius** [comment]
Is it avialable for testing? I was looking for this for past few days :)

**Comment by fopina** [comment]
I built it as external plugin before doing the PR - https://github.com/fopina/fluent-bit-out-influxdb-v2
Though latest build (compatible with fluent but 1.7.0) is segfaulting in arm, not sure why yet

**Comment by edsiper** [comment]
@fopina just to clarify, the current plugin merged in 1.7 branch (and master) is segfaulting in Arm ?

**Comment by fopina** [comment]
@edsiper the current plugin changes in master didn’t make it to 1.7 and I haven’t tested it again with 1.7 (only 1.6.10 and it worked)
My external plugin (which drove the PR) is segfaulting, but only in 1.7, it works with 1.6.10
Only noticed last night when I was upgrading my agents but there was no obvious trace/debug message and couldn’t look into it yet.

**Comment by edsiper** [comment]
@fopina I aim to release this into 1.7 today, please confirm if branch 1.7 works :)

**Comment by fopina** [comment]
@edsiper I'll try to test as I need it as well. Any hint what could it be (from changes to the plugin API), as the changes themselves in the plugin are hardly the cause?

**Comment by edsiper** [comment]
ok, I will keep the current change but keep it experimental, on that way we set right expectations

**Comment by fopina** [comment]
@edsiper just tested something: disabling https on my influxdb and it worked.
changed my amd64 test to use https (it wasn't using before) and it crashed as well

```
[2021/02/19 23:28:25] [engine] caught signal (SIGSEGV)
#0  0x5561ec21fb20      in  flb_tls_session_create() at src/tls/flb_tls.c:298
#1  0x5561ec2288dd      in  flb_io_net_connect() at src/flb_io.c:108
#2  0x5561ec211fdc      in  create_conn() at src/flb_upstream.c:418
#3  0x5561ec21246e      in  flb_upstream_conn_get() at src/flb_upstream.c:553
#4  0x7f4843bfd16b      in  ???() at ???:0
#5  0x5561ec1fd4a4      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:463
#6  0x5561ec69a526      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
#7  0xffffffffffffffff  in  ???() at ???:0
```

as I said before, it was hardly related to my change: adding a few fields that worked in 1.6.10 and no longer works in 1.7.0...

maybe TLS lib upgrade broke something (and if so, it probably impacts everything, not just this plugin)?

again, this test was done from my external plugin build, not the master branch. I'll try the master branch now

**Comment by fopina** [comment]
@edsiper follow up: just tested with master branch, branded 1.8.0, and builtin influxdb output, not my external plugin ✔️ 
no segfault, so just something related with my external plugin build (maybe something changed in the plugin API...?)

feel free to release at will 🙏

**Pull request merged**
