### PR TITLE
Add map support for out_Influxdb plugin

### PR DESCRIPTION
**Pull request by huangyingting**
out_Influxdb doesn't support adding map object to influxdb, this PR will convert map object to string so out_influxdb can insert it to influxdb with line protocol.

### CODE REVIEW

**Comment by edsiper** [comment]
What's the use case where storing a map as a string will be needed ?

**Comment by edsiper** [comment]
ping

**Comment by edsiper** [comment]
ping

**Comment by huangyingting** [comment]
@edsiper sorry that I was aware of this ping, the user cases is to insert docker log with json map format into influxdb.

**Pull request closed without merging**
