### PR TITLE
[sds] add flb_sds_cat_replace: concatenate a string by replacing a set of chars

### PR DESCRIPTION
**Pull request by manuelluis**

### CODE REVIEW

**Comment by manuelluis** [comment]
Fixes https://github.com/fluent/fluent-bit/issues/1291

**Comment by edsiper** [comment]
would flb_sds_copy() solve the requirement ?

**Comment by manuelluis** [comment]
No,  flb_sds_copy()  not solve the problem.
I was trying to make a generic implementation to replace a set of characters when concatenate a string, but it was a bit over-engineering.

We can do with in a simple for loop after concatenate the string:

    int i;
    flb_sds_t tmp;
    /* check valid key char [A-Za-z0-9_\.\-] */
    static char valid_char[256] = {
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };

    if (in_array == FLB_FALSE) {
        tmp = flb_sds_cat(*s, ", \"", 3);
        if (tmp == NULL) return NULL;
        *s = tmp;
    }

    if (prefix_key_len > 0) {
        int start_len, end_len;

        start_len = flb_sds_len(s);

        tmp = flb_sds_cat(*s, prefix_key, prefix_key_len);
        if (tmp == NULL) return NULL;
        *s = tmp;

        end_len = flb_sds_len(s);
        for(i=start_len; i < end_len; i++) {
            if (!valid_char[(unsigned char)(*s)[i]]) {
                (*s)[i] = '_';
            }
        }
    }

    if (concat == FLB_TRUE) {
        tmp = flb_sds_cat(*s, "_", 1);
        if (tmp == NULL) return NULL;
        *s = tmp;
    }

    if (key_len > 0) {
        int start_len, end_len;

        start_len = flb_sds_len(s);

        tmp = flb_sds_cat(*s, prefix_key, prefix_key_len);
        if (tmp == NULL) return NULL;
        *s = tmp;

        end_len = flb_sds_len(s);
        for(i=start_len; i < end_len; i++) {
            if (!valid_char[(unsigned char)(*s)[i]]) {
                (*s)[i] = '_';
            }
        }
    }

**Comment by edsiper** [comment]
got it. 

Please resolve the conflicts and we are ready to go

**Comment by bluebike** [comment]
I would split this to two commits.
1.  add flb_sds_t flb_sds_cat_replace  ( src/flb_sds.c ,  include/fluent-bit/flb_sds.h )
2. flb_msgpack_gelf_key    ( src/flb_pack.c )

**Comment by wrossmann** [comment]
Is this going to get merged at some point?

**Comment by edsiper** [comment]
thanks!

**Pull request merged**
