### PR TITLE
filter_type_converter: new filter plugin

### PR DESCRIPTION
**Pull request by nokute78**
This patch is to add type casting API/plugin.

## Use case 

Some filter plugins expect incoming value is string.
e.g. filter_rewrite_tag #4010,  filter_grep #4004

This plugin converts integer value and appends as a string value.

## ToDo

We already support `Types` property for parser.
https://docs.fluentbit.io/manual/v/1.3/parser#configuration-parameters

I will modify `Types` to use this new API after merging this patch.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [ ] Documentation required for this feature

## Example configuration

```
[INPUT]
    Name dummy
    Dummy {"k_int":1234, "k_float":123.456, "k_str":"123456"}
    Samples 1

[FILTER]
    Name type_converter
    Match *
    int_key    k_int    int_s    string
    float_key  k_float  float_s  string
    str_key    k_str    str_i    int


[OUTPUT]
    Name stdout
```

## Debug output

before: `[1630208727.777381748, {"k_int"=>1234, "k_float"=>123.456000, "k_str"=>"123456"}]`
after:   `[1630208727.777381748, {"k_int"=>1234, "k_float"=>123.456000, "k_str"=>"123456", "int_s"=>"1234", "float_s"=>"123.456", "str_i"=>123456}]`

```
$ bin/fluent-bit -c a.conf 
Fluent Bit v1.9.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/08/29 12:45:26] [ info] [engine] started (pid=93793)
[2021/08/29 12:45:26] [ info] [storage] version=1.1.1, initializing...
[2021/08/29 12:45:26] [ info] [storage] in-memory
[2021/08/29 12:45:26] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/08/29 12:45:26] [ info] [cmetrics] version=0.2.1
[2021/08/29 12:45:26] [ info] [sp] stream processor started
[0] dummy.0: [1630208727.777381748, {"k_int"=>1234, "k_float"=>123.456000, "k_str"=>"123456", "int_s"=>"1234", "float_s"=>"123.456", "str_i"=>123456}]
^C[2021/08/29 12:45:32] [engine] caught signal (SIGINT)
[2021/08/29 12:45:32] [ warn] [engine] service will stop in 5 seconds
```

## Valgrind output

```
$ valgrind --leak-check=full bin/fluent-bit -c a.conf 
==93797== Memcheck, a memory error detector
==93797== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==93797== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==93797== Command: bin/fluent-bit -c a.conf
==93797== 
Fluent Bit v1.9.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/08/29 12:46:52] [ info] [engine] started (pid=93797)
[2021/08/29 12:46:53] [ info] [storage] version=1.1.1, initializing...
[2021/08/29 12:46:53] [ info] [storage] in-memory
[2021/08/29 12:46:53] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/08/29 12:46:53] [ info] [cmetrics] version=0.2.1
[2021/08/29 12:46:53] [ info] [sp] stream processor started
[0] dummy.0: [1630208813.789137615, {"k_int"=>1234, "k_float"=>123.456000, "k_str"=>"123456", "int_s"=>"1234", "float_s"=>"123.456", "str_i"=>123456}]
^C[2021/08/29 12:46:58] [engine] caught signal (SIGINT)
[2021/08/29 12:46:58] [ warn] [engine] service will stop in 5 seconds
[2021/08/29 12:47:02] [ info] [engine] service stopped
==93797== 
==93797== HEAP SUMMARY:
==93797==     in use at exit: 0 bytes in 0 blocks
==93797==   total heap usage: 1,206 allocs, 1,206 frees, 807,825 bytes allocated
==93797== 
==93797== All heap blocks were freed -- no leaks are possible
==93797== 
==93797== For lists of detected and suppressed errors, rerun with: -s
==93797== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by nokute78** [comment]
## Example 2

This  is an example to grep http status code(int).

1. incoming status code as **int**.
2. `filter_type_converter` converts to string and appends as `status_str`.
3. `filter_grep` tries to grep for `status_str`

```
[INPUT]
    Name dummy
    Dummy {"status":404, "stream":"stdout", "time":"2018-06-11T14:37:30.681701731Z"}
    Samples 1

[FILTER]
    Name type_converter
    Match *
    int_key    status   status_str string

[FILTER]
    Name grep
    Match *
    Regex status_str 404


[OUTPUT]
    Name stdout
```

## Output 

```
$ bin/fluent-bit -c b.conf 
Fluent Bit v1.9.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/08/29 12:53:14] [ info] [engine] started (pid=93816)
[2021/08/29 12:53:14] [ info] [storage] version=1.1.1, initializing...
[2021/08/29 12:53:14] [ info] [storage] in-memory
[2021/08/29 12:53:14] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/08/29 12:53:14] [ info] [cmetrics] version=0.2.1
[2021/08/29 12:53:14] [ info] [sp] stream processor started
[0] dummy.0: [1630209194.777213823, {"status"=>404, "stream"=>"stdout", "time"=>"2018-06-11T14:37:30.681701731Z", "status_str"=>"404"}]
^C[2021/08/29 12:53:19] [engine] caught signal (SIGINT)
[2021/08/29 12:53:19] [ warn] [engine] service will stop in 5 seconds
[2021/08/29 12:53:23] [ info] [engine] service stopped
```

**Comment by srbhklkrn** [comment]
Any timeline when this PR is going to get merged?

**Comment by nokute78** [comment]
I fixed conflict.

**Comment by madianas** [comment]
Please merge this or any other method to convert string to integer

**Comment by madianas** [comment]
+

**Pull request merged**
