### PR TITLE
Minor clarification of runtime error message in Kubernetes filtering

### PR DESCRIPTION
**Pull request by daixiang0**
Make help info more clear, once this error happend, kubernetes filter would skip,

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
@edsiper mind have a look?

**Comment by daixiang0** [comment]
@bluebike @edsiper mind have a look?

**Comment by nigels-com** [comment]
Looks good to me.  Minor change.

**Comment by nigels-com** [comment]
I'd suggest changing the title to something like "Minor clarification of runtime error message in Kubernetes filtering".

**Comment by edsiper** [comment]
thanks!

**Pull request merged**
