### PR TITLE
out_stackdriver: fixed a memory leak (CID 508244)

### PR DESCRIPTION
**Pull request by leonardo-albertovich**

### CODE REVIEW

**Comment by leonardo-albertovich** [comment]
@igorpeshansky I performed a cursory inspection to validate (and expand) the findings and patched the leaks I could confirm, however I'm not familiar with the stackdriver plugin and would greatly appreciate if someone from the team could verify this PR.

Additionally, It seems that `source_location_file` and `source_location_function` are also leaked, could you verify this?

**Comment by braydonk** [comment]
Thanks for fixing this. These cleanups were missed when I reviewed the PRs by external contributor, I should have caught them.

`source_location_file` and `source_location_function` don't look like they should be leaked, at least a look at the code indicates they should be cleaned up.

They are allocated here (not guarded by any condition): https://github.com/fluent/fluent-bit/blob/d873502de1e1a7f050c7bba6336d682a3327a7af/plugins/out_stackdriver/stackdriver.c#L2328-L2331

Then cleaned up here (also not guarded by any conditions): https://github.com/fluent/fluent-bit/blob/d873502de1e1a7f050c7bba6336d682a3327a7af/plugins/out_stackdriver/stackdriver.c#L2461-L2462

**Comment by leonardo-albertovich** [comment]
I meant they would be leaked if [this](https://github.com/fluent/fluent-bit/blob/d873502de1e1a7f050c7bba6336d682a3327a7af/plugins/out_stackdriver/stackdriver.c#L2355) code path was taken.

**Comment by braydonk** [comment]
I didn't notice that, yeah you're right that's a leak.

**Review by braydonk — APPROVED** [review]

**Pull request merged**
