### PR TITLE
simd: add new SIMD support for JSON escaping

### PR DESCRIPTION
**Pull request by edsiper**
For cases where JSON encoding is needed, if SIMD is available, this brings 30%-50% performance improvement.

__PostgreSQL SIMD__ 

The  _header file_ with SIMD functionality has been taken from the PostgreSQL project, stripped down, and adapted for our specific needs. 

__Notes on other improvements__

- the routine that is used to escape characters, now uses a lookup table which heavily improves performance when Fluent Bit is built on release mode (optimizations on). This brings performance improvements for all systems/architectures.

- SIMD operations are available for architectures that implement SSE2 (Intel/AMD) and Neon (Arm) based instructions. Note that AVX2 is not implemented so there is still more room for improvement. 

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by edsiper** [comment]
@pwhelan @leonardo-albertovich @cosmo0920 @pwhelan  @patrick-stephens I need your help on this for workflows and overall testing:

- I have introduced a new CMake option called `FLB_SIMD` (default: off)
- SIMD operations are supported for x86_64, amd64 (SSE2) and aarch64 (Neon)
- SIMD is enabled at build time and the backend selected per [compiler definitions](https://github.com/fluent/fluent-bit/pull/9500/files#diff-a21be6e0197b398134116caaf39dc7f9ffa30d7ff0370ccf5b6958ed1f281c3fR32) 
- A fallback mechanism exists if SIMD is not available.

so:

- is there a chance a special architecture don't allow SIMD operations event those are supported ?
- would be possible to ship this as a default/enabled on certain builds like containers without introducing any potential breaking change ? 

comments are welcome

**Comment by cosmo0920** [comment]
> is there a chance a special architecture don't allow SIMD operations event those are supported ?

The one of the candidates is RISC-V vector extension("RVV"):
https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/main/doc/rvv-intrinsic-spec.adoc

**Comment by cosmo0920** [comment]
> * would be possible to ship this as a default/enabled on certain builds like containers without introducing any potential breaking change ?

For safety, we need to have two images for PC architecture that is:
* x86_64-generic means without SIMD support
* x86_64-simd means with SIMD support

PC architectures are fragmented. 
So, if we enforce to use SIMD support in our container images, illegal instruction errors might be happened in the ancient instances/boxes in unsupported SIMD environments..
But, SSE2 has been supported since Intel Pentium or AMD Athlon 64. So, they have 20 years history.

**Comment by edsiper** [comment]
thanks for the feedback. Merging it for now since the feature needs to be enabled at build time

**Pull request merged**
