### PR TITLE
out_stackdriver: add k8s_cluster resource type

### PR DESCRIPTION
**Pull request by ryanohnemus**
Add k8s_cluster resource type to out_stackdriver plugin. 

This can be used in combination with the in_kubernetes_events to write k8s_cluster type events to stackdriver (such as any non-Pod based kubernetes events)

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [X] Example configuration file for the change
```
[INPUT]
    Name kubernetes_events
    Tag k8s_events

[FILTER]
    Name rewrite_tag
    Match k8s_events
    Rule $involvedObject['Kind'] Pod k8s_events.$metadata['namespace'].k8s_pod false
    Rule $metadata['namespace'] .* k8s_events.$metadata['namespace'].k8s_cluster false

[OUTPUT]
    Name stackdriver
    Match k8s_events*k8s_cluster
    resource k8s_cluster
    k8s_cluster_name my-cluster-name
    k8s_cluster_location us-central1
```
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [X] Documentation required for this feature
https://github.com/fluent/fluent-bit-docs/pull/1284

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by ryanohnemus** [comment]
test failure looks like a flake

**Review by braydonk — CHANGES_REQUESTED** [review]
The change looks good to me!

Would you mind adding a test for this as well? You can use [this other resource test](https://github.com/fluent/fluent-bit/blob/master/tests/runtime/out_stackdriver.c#L3823) as a reference. I can intuitively see that this will work based on the implementation, so it's just a matter of getting a test for it.

I'll be good to merge it after a test is added!

**Comment by ryanohnemus** [comment]
@braydonk, just rebased and pushed with a test. I will watch the CI checks for any failures, but otherwise we should be good to go

**Review by braydonk — APPROVED** [review]
LGTM, unless something in CI fails I will merge.

**Pull request merged**
