### PR TITLE
windows: build: Enable kafka plugins on Windows

### PR DESCRIPTION
**Pull request by cosmo0920**
In Windows, we forcibly disabled out_kafka plugin on Windows for OpenSSL linkage issues.
Nowadays, this linkage issue seems to be fixed on CI/CD.
So, I'm trying to enable this plugin on Windows.

In AppVeyor, we're able to resolve OpenSSL linkage to use vcpkg built ones.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:

- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.

- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by patrick-stephens** [comment]
I would just remove AppVeyor entirely, let's not complicate CMake because of it.

**Comment by cosmo0920** [comment]
Hmm..., AppVeyor CI is still alive. So, would we remove or disable AppVeyor CI from this repo?

**Comment by patrick-stephens** [comment]
Configure it not to run for PRs or similar. I think complicating CMake for it is not a good idea here.

It may be better as a separate PR just to remove AppVeyor entirely.

**Comment by cosmo0920** [comment]
I updated to disable almost of the AppVeyor/s CI/CD tasks. To remove this workflow or delete AppVeyor's project should be handled in the separated PR, I believe.

**Review by patrick-stephens — APPROVED** [review]

**Comment by patrick-stephens** [comment]
Note, once merged we need to update the release workflow as well to ensure it does not try to pull AppVeyor binaries as this will fail now.

**Comment by cosmo0920** [comment]
Hi, is this PR able to get merged? Because an article https://laurierhodes.info/node/156 was up to seek opportunity to use out_kafka plugin on Windows. We need to cover this case. :)

**Comment by yangliuqing5470** [comment]
Can you share the compiled windows zip with kafka?

**Comment by cosmo0920** [comment]
> Can you share the compiled windows zip with kafka?

This will be up on the next release. Or, unstable build will bring up them if this PR is merged.

**Comment by yangliuqing5470** [comment]
> > Can you share the compiled windows zip with kafka?
> 
> This will be up on the next release. Or, unstable build will bring up them if this PR is merged.

OK! Thanks

**Comment by yangliuqing5470** [comment]
There is no 3.1.5  in the installation documentation for windows

**Pull request merged**
