### PR TITLE
in_disk: add a new input plugin in_disk

### PR DESCRIPTION
**Pull request by nokute78**
I added a new plugin in_disk.
It is helpful to monitor disk I/O.

in_disk reads `/proc/diskstats` and calculates write/read size per interval.
(I don't know the unit of  each field of `/proc/diskstats`. So we should convert its unit in the future ... )

## example
```
$ bin/fluent-bit -i disk  -o stdout 
Fluent-Bit v0.11.0
Copyright (C) Treasure Data

[2017/01/25 23:38:34] [ info] [engine] started
[0] disk.0: [1485355115, {"read_size"=>0, "write_size"=>0}]
[1] disk.0: [1485355116, {"read_size"=>0, "write_size"=>0}]
[2] disk.0: [1485355117, {"read_size"=>0, "write_size"=>27}]
[3] disk.0: [1485355118, {"read_size"=>0, "write_size"=>0}]
[0] disk.0: [1485355119, {"read_size"=>0, "write_size"=>0}]
[1] disk.0: [1485355120, {"read_size"=>0, "write_size"=>0}]
[2] disk.0: [1485355121, {"read_size"=>0, "write_size"=>0}]
[3] disk.0: [1485355122, {"read_size"=>0, "write_size"=>0}]
[4] disk.0: [1485355123, {"read_size"=>0, "write_size"=>0}]
[0] disk.0: [1485355124, {"read_size"=>0, "write_size"=>0}]
[1] disk.0: [1485355125, {"read_size"=>0, "write_size"=>0}]
[2] disk.0: [1485355126, {"read_size"=>0, "write_size"=>0}]
[3] disk.0: [1485355127, {"read_size"=>71, "write_size"=>0}]
[4] disk.0: [1485355128, {"read_size"=>27, "write_size"=>0}]
```

We can trace only specific device with option "dev_name".
```
$ bin/fluent-bit -i disk -p dev_name=sda1 -o stdout 
Fluent-Bit v0.11.0
Copyright (C) Treasure Data

[2017/01/25 23:36:47] [ info] [engine] started
[0] disk.0: [1485355032, {"read_size"=>0, "write_size"=>0}]
[1] disk.0: [1485355033, {"read_size"=>0, "write_size"=>0}]
[2] disk.0: [1485355034, {"read_size"=>0, "write_size"=>0}]
[3] disk.0: [1485355035, {"read_size"=>0, "write_size"=>0}]
[4] disk.0: [1485355036, {"read_size"=>0, "write_size"=>0}]
[0] disk.0: [1485355037, {"read_size"=>14, "write_size"=>0}]
[1] disk.0: [1485355038, {"read_size"=>0, "write_size"=>0}]
[2] disk.0: [1485355039, {"read_size"=>0, "write_size"=>0}]
[3] disk.0: [1485355040, {"read_size"=>0, "write_size"=>0}]
[4] disk.0: [1485355041, {"read_size"=>0, "write_size"=>0}]
```

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for the contribution.

Doing a quick check, looks like the source /proc/diskstats do not aim to provide the number of bytes read or written, instead more generic I/O access and operations over it:

- https://www.kernel.org/doc/Documentation/iostats.txt
- https://github.com/torvalds/linux/blob/5924bbecd0267d87c24110cbe2041b5075173a25/block/genhd.c#L1199

**Comment by nokute78** [comment]
Thank you for reviewing.

https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats
Field 6 and 10 are number of sectors read/written, So,
read or write size  = (number of sector)  x 512 bytes

We can also get statistics via `/sys/block/<dev>/stat`.
The document is here , and units  of data are written.
https://www.kernel.org/doc/Documentation/block/stat.txt

This is a implementation of block stat.
https://github.com/torvalds/linux/blob/5924bbecd0267d87c24110cbe2041b5075173a25/block/partition-generic.c#L112
`/proc/diskstats` and `/sys/block/<dev>/stat` return same value (member of `struct hd_struct`).
This means the unit of each stat are same.
e.g. Field 6 of diskstats corresponds to Field 3 of block stat.

Documentation of block stat says the sector corresponds 512-byte.
So we can get data size in byte using a number of sector.
```
read sectors, write sectors
===========================

These values count the number of sectors read from or written to this
block device.  The "sectors" in question are the standard UNIX 512-byte
sectors, not any device- or filesystem-specific block size.  The
counters are incremented when the I/O completes.
```

**Comment by nokute78** [comment]
Note : "dstat" also reads a number of sector via `/proc/diskstats` and number are multiplied  by 512  at `dstat_disk#extract`
https://github.com/dagwieers/dstat/blob/master/dstat#L841

**Comment by edsiper** [comment]
thanks for the update.

please just fix the issue found with in Travis with an older toolchain and we should be ok:

https://travis-ci.org/fluent/fluent-bit/builds/195543676

```
/home/travis/build/fluent/fluent-bit/plugins/in_disk/in_disk.c: In function ‘in_disk_collect’:
/home/travis/build/fluent/fluent-bit/plugins/in_disk/in_disk.c:143: error: ‘ULLONG_MAX’ undeclared (first use in this function)
```

**Comment by nokute78** [comment]
> please just fix the issue found with in Travis with an older toolchain and we should be ok:

oops, I fixed it .

**Comment by edsiper** [comment]
awesome, thanks!

**Pull request merged**
