### PR TITLE
regex: support /patttern/option

### PR DESCRIPTION
**Pull request by nokute78**
https://github.com/fluent/fluent-bit/issues/6122#issuecomment-1286169205

Ruby supports `/pattern/option` format.
https://ruby-doc.org/core-3.1.2/doc/regexp_rdoc.html#label-Options
This patch is to support `/m`(multiline), `/i` (ignore case), `/x` (ignore white space).

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

## Configuration

```
[SERVICE]
    flush 1
    log_level info
    parsers_file parsers_multiline.conf
    Parsers_file p.conf

[INPUT]
    name tail
    path test.log
    read_from_head true

[FILTER]
    name multiline
    match *
    multiline.key_content log
    multiline.parser go, multiline-regex-test

[FILTER]
    Name parser
    match *
    Key_Name log
    Parser sample

[OUTPUT]
    name stdout
    match *
```
p.conf:
```
[PARSER]
    Name sample
    Format regex
    Regex /^(?<date>Dec \d+ \d+\:\d+\:\d+) (?<message>.*)/m
```

test.log:
```
Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
  at.hoge
  at.moge
New line
```

## Debug/Valgrind  output

Fluent-bit can parse concatenated multiline log.
```
[0] tail.0: [1666509431.715223910, {"date"=>"Dec 14 06:41:08", "message"=>"Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
  at.hoge
  at.moge"}]
```

Full log:
```
$ valgrind --leak-check=full ../../bin/fluent-bit -c a.conf 
==126744== Memcheck, a memory error detector
==126744== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==126744== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==126744== Command: ../../bin/fluent-bit -c a.conf
==126744== 
Fluent Bit v2.0.0
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/10/23 16:17:10] [ info] [fluent bit] version=2.0.0, commit=84f6d302f5, pid=126744
[2022/10/23 16:17:10] [ info] [storage] ver=1.2.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/10/23 16:17:10] [ info] [cmetrics] version=0.5.3
[2022/10/23 16:17:11] [ info] [input:tail:tail.0] initializing
[2022/10/23 16:17:11] [ info] [input:tail:tail.0] storage_strategy='memory' (memory only)
[2022/10/23 16:17:11] [ info] [filter:multiline:multiline.0] created emitter: emitter_for_multiline.0
[2022/10/23 16:17:11] [ info] [input:emitter:emitter_for_multiline.0] initializing
[2022/10/23 16:17:11] [ info] [input:emitter:emitter_for_multiline.0] storage_strategy='memory' (memory only)
[2022/10/23 16:17:11] [ info] [sp] stream processor started
[2022/10/23 16:17:11] [ info] [output:stdout:stdout.0] worker #0 started
[2022/10/23 16:17:11] [ info] [filter:multiline:multiline.0] created new multiline stream for tail.0_tail.0
==126744== Warning: client switching stacks?  SP change: 0x6ffb8b8 --> 0x5533030
==126744==          to suppress, use: --max-stackframe=28084360 or greater
==126744== Warning: client switching stacks?  SP change: 0x5532f88 --> 0x6ffb8b8
==126744==          to suppress, use: --max-stackframe=28084528 or greater
==126744== Warning: client switching stacks?  SP change: 0x6ffb8b8 --> 0x5532f88
==126744==          to suppress, use: --max-stackframe=28084528 or greater
==126744==          further instances of this message will not be shown.
[0] tail.0: [1666509431.715223910, {"date"=>"Dec 14 06:41:08", "message"=>"Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
  at.hoge
  at.moge"}]
[2022/10/23 16:17:12] [ info] [input:tail:tail.0] inotify_fs_add(): inode=4725508 watch_fd=1 name=test.log
[1] tail.0: [1666509431.766079068, {"log"=>"New line"}]
^C[2022/10/23 16:17:15] [engine] caught signal (SIGINT)
[2022/10/23 16:17:15] [ warn] [engine] service will shutdown in max 5 seconds
[2022/10/23 16:17:15] [ info] [input] pausing tail.0
[2022/10/23 16:17:16] [ info] [engine] service has stopped (0 pending tasks)
[2022/10/23 16:17:16] [ info] [input] pausing tail.0
[2022/10/23 16:17:16] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=4725508 watch_fd=1
[2022/10/23 16:17:16] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2022/10/23 16:17:16] [ info] [output:stdout:stdout.0] thread worker #0 stopped
==126744== 
==126744== HEAP SUMMARY:
==126744==     in use at exit: 0 bytes in 0 blocks
==126744==   total heap usage: 2,491 allocs, 2,491 frees, 1,343,711 bytes allocated
==126744== 
==126744== All heap blocks were freed -- no leaks are possible
==126744== 
==126744== For lists of detected and suppressed errors, rerun with: -s
==126744== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by nokute78** [comment]
I updated test case.

**Comment by edsiper** [comment]
@nokute78 one question, what's the use case for this extension? 

I understand that the example aims to show multiline support with `/m` but we totally discourage that in our use case since multiple lines that belong to the same context might not come as part of the same buffer; we got many users trying to accomplish multiline with regex and never ended up well.

**Comment by nokute78** [comment]
@edsiper This patch is to get structured data from a concatenated input using named capture.
Not to concatenate.


e.g. filter_multiline -> **filter_parser (using this patch)** -> some outputs

input:
```
Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
  at.hoge
  at.moge
New line
```

structured data:
```
{"date"=>"Dec 14 06:41:08", "message"=>"Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
  at.hoge
  at.moge"}
```

> we totally discourage that in our use case since multiple lines that belong to the same context might not come as part of the same buffer

Hmm, is the issue that filter_multiline should solve ? I think this patch is not for it.

How do users use concatenated log ? Do they send it to S3 or some storages in non-structured format ?

**Comment by edsiper** [comment]
to concatenate logs they have to use the Multiline feature exposed on Tail or the filter:

- https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing

**Comment by nokute78** [comment]
> to concatenate logs they have to use the Multiline feature exposed on Tail or the filter:

I know it.
What I want to know is how to get structured data from concatenated log.

https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing#configuration-example
This example will output `"log":"<concatenated log>"`. It is not structured.

This example pipeline is 
1. in_tail reads log
2. in_tail concatenates log using multiline filter
3. out_stdout outputs concatenated log.

What I want to do is to add 2.5 "filter_parser parses concatenated log and get structured data using this patch".

**Comment by matschaffer-roblox** [comment]
Thanks for this @nokute78! 🧡 

It solves the problem I show in https://gist.github.com/matschaffer-roblox/d03b71ffbf6e8cfb034abc66e1c1166d#file-output-txt

If I build with this PR and switch my filter parser to `/^(?<time>\d+\/\d+\/\d+ \d+:\d+:\d+) (?<severity>\w+) (?<message>.*)/m` I'm able to pull captured groups from a multi-line log without losing the additional `message` lines like I do on v2.0.4

本当に助かる〜！＾_＾

@edsiper if you're able to demonstrate how to capture groups from mult-line logs _without_ this PR, I'd love to see it. Otherwise I think we might want to merge this 😉

**Comment by edsiper** [comment]
thanks both for the detailed explanation :) 

@nokute78 we will need a PR for docs to document the use case described by @matschaffer-roblox 

cc: @lecaros

**Comment by nokute78** [comment]
@matschaffer-roblox Thank you for testing!

@edsiper I sent a doc PR https://github.com/fluent/fluent-bit-docs/pull/983 .

**Pull request merged**
