### PR TITLE
Restart when config directory has changes

### PR DESCRIPTION
**Pull request by donbowman**
In Kubernetes there is a configmap used to give the main + parser configuration. If the change, the expectation is that fluent-bit will apply the changes.
Since there is no support for standard Unix 'HUP' behaviour of reloading config, the next best alternative is to exit and let the daemonset replication-controller restart. This should be seamless if the Tail plugin is used with DB & DB.Sync.

A new command-line flag (-C) and a new Service variable (Config_Watch: On|Off) are introduced to enable this behaviour.

This option may also be useful for systemd (which can restart on clean exit).

### CODE REVIEW

**Comment by kskewes** [comment]
Nice, this would be great for getting started with Fluent-bit and no doubt day 2+.

**Comment by donbowman** [comment]
is there anything more you need from me on this?

**Comment by edsiper** [comment]
I think this feature specifically added for "Kubernetes use case" and as a workaround for not having a config reload feature, should be placed in filter_kubernetes instead of the core it self. 

note: this PR do not reload the configuration, it just stop Fluent Bit if it detects a configuration change is found.

**Comment by donbowman** [comment]
> I think this feature specifically added for "Kubernetes use case" and as a workaround for not having a config reload feature, should be placed in filter_kubernetes instead of the core it self.
> 
> note: this PR do not reload the configuration, it just stop Fluent Bit if it detects a configuration change is found.

The concept of auto-applying config changes is not specific to kubernetes. It can apply to any automatic config environment. That's why i think it belongs in the core. Also its the 'core' that knows where the config directory is and is parsing it, i think it would be weird to share that w/ one of the input systems.
(e.g. one can use this in an upstart or systemd system... give a non-privleged user the ability to edit the config, leaving the privileged daemon to reload itself on change).

As for the reload... I don't believe the code supports reload(?) so this was the next best alternative. Is there another way?

**Comment by edsiper** [comment]
> The concept of auto-applying config changes is not specific to kubernetes. It can apply to any automatic config environment. That's why i think it belongs in the core. 

I agree, but this is not auto-applying config changes. It's a workaround to restart Fluent Bit when a configuration file changes in the monitored directory.

> Also its the 'core' that knows where the config directory is and is parsing it, i think it would be weird to share that w/ one of the input systems.
(e.g. one can use this in an upstart or systemd system... give a non-privleged user the ability to edit the config, leaving the privileged daemon to reload itself on change).

It should be in the core but if doing the right thing. In a non-containerized environment restarting the service should be enough upon changes. non-privileged users is not the thing that needs to be solved. 

> As for the reload... I don't believe the code supports reload(?) so this was the next best alternative. Is there another way?

Let me try something, I have some notes about this when the issue was more active (there some things to consider like dry-run mode to avoid broken configs, engine start time v/s plugins ready to run plus others...)

**Comment by donbowman** [comment]
ok.
I did the same thing as the HUP handler did, which is what typical unix program would do.

if there's a way to do a dynamic reload, that would be better. but this method is not that bad. The 'tail db' keeps the state. and, even if dynamic reload, i think it would have to delete and restart all the tail inputs so that would still have the same affect. the restart is sub second on kubernetes, it should be the same for docker or systemd as well (other environments where people would expect a reload concept).

**Comment by donbowman** [comment]
please let me know how i can help here. Either in this patch or an alternate approach.
its pretty critical to kubernetes use that configmap changes get applied.

**Comment by gprossliner** [comment]
Is there any progress on this? I have exactly the same problem. It's really annoying to delete the pods every time you change the config.

Also I have a new use-case which uses a partially gernerated lua Filter. So it would be nice to track changes to the lua file too.

**Comment by benjaminhuo** [comment]
@gprossliner You can use Fluent Bit Operator to solve this 
https://github.com/kubesphere/fluentbit-operator
```
To enable fluent-bit to pick up and use the latest config whenever the fluent-bit config changes, a wrapper called fluent-bit watcher is added to restart the fluent-bit process as soon as fluent-bit config changes are detected. This way the fluent-bit pod needn't be restarted to reload the new config. The fluent-bit config is reloaded in this way because there is no reload interface in fluent-bit itself, please refer to this known issue https://github.com/fluent/fluent-bit/issues/365 for more details.
```

**Pull request closed without merging**
