### PR TITLE
Add monitoring section.

### PR DESCRIPTION
**Pull request by naseemkullah**
Provide sample dashboard and sample alert to get users started with monitoring Fluent Bit.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ N/A] Example configuration file for the change
- [ N/A] Debug log output from testing the change

- [ N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [x] Documentation required for this feature

We will add something to docs to link here after this is merged.
----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by PettitWesley** [comment]
@naseemkullah @edsiper I feel like this is better placed in the docs repo?

**Comment by naseemkullah** [comment]
I was thinking of subsequently adding it to the docs, but it would be good to have the sample`dashboard.json and `alerts.yaml` files here. Do you want the `MONITORING.md` removed?

**Comment by PettitWesley** [comment]
@naseemkullah 

> but it would be good to have the sampledashboard.json and alerts.yaml files here

I think its best to have it all in one place, and the best place is the docs.

Instead of putting anything in this repo, how about we link to the section in the docs in this repos readme?

Ping @edsiper for comment.

**Comment by naseemkullah** [comment]
@PettitWesley 

> I think its best to have it all in one place, and the best place is the docs.

> Instead of putting anything in this repo, how about we link to the section in the docs in this repos readme?

It makes more sense to have the `dashboard.json` (and `alerts.yaml`) in this repo and link it from the docs to here imho. We could therefore move the contents of this PR's `MONITORING.md` to the docs.

Please see how other projects provide dashboards as such:

- https://github.com/oliver006/redis_exporter/blob/master/contrib/grafana_prometheus_redis_dashboard.json

- https://github.com/oliver006/redis_exporter/blob/master/contrib/grafana_prometheus_redis_dashboard.json

- https://github.com/jaegertracing/jaeger/blob/master/monitoring/jaeger-mixin/dashboard-for-grafana.json

and alerts:

- https://github.com/jaegertracing/jaeger/blob/master/monitoring/jaeger-mixin/prometheus_alerts.yml

**Comment by naseemkullah** [comment]
https://github.com/fluent/fluent-bit-docs/pull/294 opened @PettitWesley , this one may be closed.

**Comment by PettitWesley** [comment]
> fluent/fluent-bit-docs#294 

approved

**Pull request closed without merging**
