### PR TITLE
Add required dependencies for docker build

### PR DESCRIPTION
**Pull request by wfernandes**
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>

### CODE REVIEW

**Comment by wfernandes** [comment]
The force-push was to rebase onto current `master` for your convenience. 😉 👍

**Comment by edsiper** [comment]
thanks for the contribution.

Why libjemalloc-dev ?

**Comment by wfernandes** [comment]
@edsiper It was added as a dependency earlier on. We added it to the Dockerfile  because the docker image wouldn't build without it.

**Comment by wfernandes** [comment]
I see it being added as part of this commit 4641443a0e078ee87bbd0a502484f36aa29913e0 to the project.

**Comment by edsiper** [comment]
I troubleshoot the Jemalloc header issue, it was a problem of a directory context due to the new path of the stream processor, the fix has been pushed: 00dd804420e1c5aff2166fd32e8306ff4e457f28

On this case including libjemalloc-dev could generate issues since we bundle Jemalloc and likely headers can be different from the one provided in the build system v/s the bundled in Fluent Bit.

Please adjust the file Dockerfile change since it should be ok now.

**Comment by edsiper** [comment]
thanks. 

note: I've squashed and changed the commit subject to 

```
dockerfile: add required dependencies for docker build (#1271)
```

**Pull request merged**
