### PR TITLE
conf: add configuration file for out_flowcount

### PR DESCRIPTION
**Pull request by nokute78**
I added a configuration file to use out_flowcount.

Signed-off-by: Takahiro YAMASHITA <nokute78@gmail.com>

### CODE REVIEW

**Comment by edsiper** [comment]
please make the configuration examples in a logical order:

- service
- inputs
- outputs

**Comment by nokute78** [comment]
Well, I believe user who reads configure file wants to know how to write it.
In this case, the point is to explain how to configure "out_flowcount" clearly.
So, I wrote outputs section first.

How about this ?

**Comment by edsiper** [comment]
I understand what you mean, but I prefer to force the reader to a logic to avoid future bad configs. All current examples follow the proposed order/flow (service, input, output). The isolated config will be found in the documentation.

**Comment by edsiper** [comment]
thanks

**Comment by nokute78** [comment]
Thank you for merging.

>  I prefer to force the reader to a logic to avoid future bad configs.

Some user can write a non-logical configuration file (like me).
So, in the future, fluent-bit will not accept them, then user will report an issue why does it not work?

We should add a limitation or warning to notify user of limitation at least.

**Comment by edsiper** [comment]
sounds a good idea. Just wondering how to do it when the user set some options from the command line but also it uses a configuration file.

**Comment by nokute78** [comment]
> Just wondering how to do it when the user set some options from the command line but also it uses a configuration file.

Did you mean like this? 
` $ fluent-bit -i cpu -o stdout -c foobar.conf`

Hmm, it is difficult. Why do you think limitation is needed in the first place?

Simply we can use both settings like this.

* Configuration file to set statical settings (plugin, routing).
* Command line option to set unique settings (each node settings).

For example , refer to my old patch #122 , 
`$fluent-bit -c fluent-bit.conf -u hostname=$HOSTNAME`

**Comment by edsiper** [comment]
I think that adding a "Warning" message if the flow is different that INPUTs OUTPUTs would be enough

**Comment by nokute78** [comment]
Is it needless to take care of SERVICE ?

**Comment by edsiper** [comment]
hmm well, it have default values while input and outputs are optional

**Pull request merged**
