### PR TITLE
Add new option "User_Header"

### PR DESCRIPTION
**Pull request by nokute78**
I added a new option "User_Header" .
The option is only used by `in_head` and `fluent-bit binary` now.

## Use case

We can append 
* hostname
* uuid
* mac address

## Sample (with command line option)
We can set additional data with `-u` option.

This is a sample to append `hostname` with `-u hostname=$HOSTNAME`
```sh
$ bin/fluent-bit -i head -p file=/proc/uptime -o stdout -u hostname=$HOSTNAME
Fluent-Bit v0.9.0
Copyright (C) Treasure Data

[2016/10/28 22:13:34] [ info] [engine] started
[0] head.0: [1477660415, {"hostname"=>"localhost.localdomain", "head"=>"18394.48 17446.09
"}]
```

## Sample (in library mode)

We can also set like this in library mode.
```c
    flb_service_set(ctx, "User_Header", "hostname=localhost", NULL);
```

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for this contribution. 

At the moment I would not merge this because of the following reason:

v0.10 will introduce 'variables' for records, which means will exists 'global' and 'per instance as properties', this aims to allow the end-user to ingest specific values into their records. But this is done after data collection into the core instead of on each input plugin.

What I will do to avoid duplicate efforts is to create a detailed Roadmap for the next version so we can work more aligned.

Version v0.9 is right around the corner, just reviewing and doing minor fixes.

**Comment by nokute78** [comment]
@edsiper  I see.

> Roadmap

That's nice. Where will it be announced? Wiki on this repository?

**Comment by edsiper** [comment]
Github project sounds good, because I think it will need changes in multiples places.

**Comment by nokute78** [comment]
> Github project

O.K. I'm waiting it.
Thanks!

**Comment by nokute78** [comment]
@edsiper  Could you add 'variables' for records feature to github project ?

**Pull request closed without merging**
