### PR TITLE
lib: tutf8e: Updated API to support conversion of invalid input input

### PR DESCRIPTION
**Pull request by nigels-com**
As a follow-up for PR #1703 and PR #1757 and as an alternative to PR #2287.

Extend the "Tiny UTF-8 Encoder" library API to optionally handle invalid input characters.
A UTF-8 encoded string can be specified for substituting invalid input characters, rather than erroring.
If the _invalid_ parameter is NULL, invalid input characters will not be tolerated.

----

**Testing**

Valgrind of test harness is clean on Ubuntu 18.04.

**Documentation**

Documentation updates not required for this.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by bluebike** [comment]
Well.. seems to be working (tests in High Sierra macOS).
Invalid handling is different than in my (forgotten) PR.

Got rid of extra function layer.  Good.

One thing I don't really like at all is  **tutf8e_encoder** function. 
This using strcmp with every single encoding is not very efficient. 

We could live this just to get something done.. probably too late for 1.5 anyway.

**Comment by nigels-com** [comment]
Thanks for looking.

My time on this was a bit limited, tried to stick to the essentials.
The string-based encoder lookup is once-only, so not so performance critical?

**Comment by nigels-com** [comment]
@bluebike you'd like this merged to fluent-bit master branch, as is?  Any issues you came across in the course of #2420 ?

**Comment by bluebike** [comment]
@nigels-com  well... this is good enough.   Seems to be working.
I haven't seen any major problems with this...

**Comment by nigels-com** [comment]
@edsiper Could this be merged for the purposes of #2420  ?

**Comment by edsiper** [comment]
thanks!

**Pull request merged**
