### PR TITLE
in_cpu: fix compilation warning

### PR DESCRIPTION
**Pull request by yann-soubeyrand**
Signed-off-by: Yann Soubeyrand <ysoubeyrand@leadformance.com>

### CODE REVIEW

**Comment by edsiper** [comment]
which compiler triggers a warning ?

**Comment by yann-soubeyrand** [comment]
The compiler is g++ on Fedora 28 (g++ --version outputs "g++ (GCC) 8.1.1 20180712 (Red Hat 8.1.1-5)").

The warning in question is
```
[ 83%] Building C object plugins/in_cpu/CMakeFiles/flb-plugin-in_cpu.dir/in_cpu.c.o
/home/yann/fluent-bit/plugins/in_cpu/in_cpu.c: In function ‘snapshot_key_format’:
/home/yann/fluent-bit/plugins/in_cpu/in_cpu.c:43:5: warning: ‘strncpy’ output truncated before terminating nul copying 3 bytes from a string of the same length [-Wstringop-truncation]
     strncpy(snap->k_cpu.name, "cpu", 3);
```

**Comment by edsiper** [comment]
hmm I think the fix should be to use memcpy() instead of strncpy() including the null byte (just to avoid confusion when reading the number of bytes being copied)

**Comment by yann-soubeyrand** [comment]
Maybe this is a stupid question, but why not just using the strcpy function in this case?

**Comment by edsiper** [comment]
I prefer to have an explicit/visual NULL byte assignment than an implicit one.

**Comment by edsiper** [comment]
ping

**Comment by yann-soubeyrand** [comment]
> I prefer to have an explicit/visual NULL byte assignment than an implicit one.

Fair enough ;-) This effectively fixes the warning. I updated my PR accordingly.

**Comment by edsiper** [comment]
thanks!

**Pull request merged**
