### PR TITLE
build: Make to be buildable on macOS Big Sur intel chip

### PR DESCRIPTION
**Pull request by cosmo0920**
On macOS Big Sur (11.3), libbacktrace and LuaJIT cannot be built on current master code base.

Headers are missing on libbacktrace building due to lack of `-isysroot` argument in which contains required SDK headers.
This is caused by macOS Mojave SDK and later does not use `/usr/include` as headers place.

Also, Current master does not specify `MACOSX_DEPLOYMENT_TARGET` explicitly.
So, LuaJIT complains `MACOSX_DEPLOYMENT_TARGET` is missing on macOS build.

Maybe related to https://github.com/fluent/fluent-bit/issues/1082

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change
I confirmed that the very initial configurations:

## Configuration 1

```ini
[INPUT]
    Name          random
    Samples      -1
    Interval_Sec  1
    Interval_NSec 0

[OUTPUT]
    Name   stdout
    Match  *
```

## Configuration 2

```ini
[INPUT]
    Name   dummy

[FILTER]
    Name    lua
    Match   *
    script  test.lua
    call    append_tag

[OUTPUT]
    Name   stdout
    Match  *
```

```lua
function append_tag(tag, timestamp, record)
    new_record = record
    new_record["tag"] = tag
    return 1, timestamp, new_record
end
```

- [x] Debug log output from testing the change

With these cmake changes, fluent-bit is run-able on macOS Big Sur Intel chip.

## Configuration 1

```log
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/06/11 12:11:00] [ info] [engine] started (pid=85135)
[2021/06/11 12:11:00] [ info] [storage] version=1.1.1, initializing...
[2021/06/11 12:11:00] [ info] [storage] in-memory
[2021/06/11 12:11:00] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/06/11 12:11:00] [ info] [sp] stream processor started
[0] random.0: [1623381061.937653000, {"rand_value"=>18019043470212660025}]
[1] random.0: [1623381062.937777000, {"rand_value"=>18376424892230197732}]
[2] random.0: [1623381063.937661000, {"rand_value"=>11625871481651476948}]
[3] random.0: [1623381064.939597000, {"rand_value"=>3494948868897575260}]
```

## Configuration 2

```log
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/06/11 15:27:07] [ info] [engine] started (pid=96709)
[2021/06/11 15:27:07] [ info] [storage] version=1.1.1, initializing...
[2021/06/11 15:27:07] [ info] [storage] in-memory
[2021/06/11 15:27:07] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/06/11 15:27:07] [ info] [sp] stream processor started
[0] dummy.0: [1623392828.627598047, {"tag"=>"dummy.0", "message"=>"dummy"}]
[1] dummy.0: [1623392829.628926992, {"tag"=>"dummy.0", "message"=>"dummy"}]
[2] dummy.0: [1623392830.629914999, {"tag"=>"dummy.0", "message"=>"dummy"}]
[3] dummy.0: [1623392831.628725051, {"tag"=>"dummy.0", "message"=>"dummy"}]
[0] dummy.0: [1623392832.627249956, {"tag"=>"dummy.0", "message"=>"dummy"}]
[1] dummy.0: [1623392833.628317117, {"tag"=>"dummy.0", "message"=>"dummy"}]
[2] dummy.0: [1623392834.624963998, {"tag"=>"dummy.0", "message"=>"dummy"}]
[3] dummy.0: [1623392835.628189086, {"tag"=>"dummy.0", "message"=>"dummy"}]
[4] dummy.0: [1623392836.626735925, {"tag"=>"dummy.0", "message"=>"dummy"}]
```

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

Sadly, Valgrind does not work on macOS Big Sur for now...

----

**Additional context**

I don't have macOS Mojave, Catalina environments to build/develop fluent-bit.
So, any feedback is appreciated for LuaJIT cmake changes.

And I also executed `xcode-select` command to handle macOS SDK correctly as follows:

```console
$ sudo xcode-select --switch /Library/Developer/CommandLineTools 
```

**Documentation**

- [N/A] Documentation required for this feature

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by edsiper** [comment]
note: CI failed due to broken parsers interface, not related.

**Comment by cosmo0920** [comment]
Thanks!

**Comment by tomotvos** [comment]
Is there a how-to for building on Big Sur? I have the latest master but am still getting missing headers, and feel like there is some fundamental environment variables that I am missing. Any help would be greatly appreciated!

**Comment by cosmo0920** [comment]
I'd confirmed that the following steps:

Specify CommandlineTools path on xcode-select:

```console
$ sudo xcode-select --switch /Library/Developer/CommandLineTools 
$ clang --version
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
$ uname -a
Darwin Hiroshi-no-MacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
```

```console
$ cd /path/to/fluent-bit/build
$ git remote -v
upstream	git@github.com:fluent/fluent-bit.git (fetch)
upstream	git@github.com:fluent/fluent-bit.git (push)
$ git fetch upstream
$ git checkout 3a20a85bce201466194618891212c102cc675824 # or update the latest master.
$ cmake ..
$ make -j5
```

If you got building failure with this instruction, this should be another issue. 
I handled two building failure issues on macOS at #3622 and #3633.

**Comment by tomotvos** [comment]
Still failing on math.h and TargetConditionals.h missing.

**Comment by cosmo0920** [comment]
Sounds interesting. Could you file a new issue for your building failures?
I'm not psychic, sadly. 
You should share your building failure and `clang -v` or `xcode-select -p` results in the new issue.

**Pull request merged**
