### PR TITLE
in_tail: add Docker mode for recombining log lines split by Docker

### PR DESCRIPTION
**Pull request by gchbg**
An extension to in_tail that recombines JSON-encoded log lines split by
Docker's 16k log line limit. Just add "Docker_Mode on" to in_tail's
configuration.

### CODE REVIEW

**Comment by gchbg** [comment]
# Problem

Docker wraps log lines in the format:
```
{"log":"verylongmessage\n","stream":"stdout","time":"2018-08-06T10:33:50.916508402Z"}
```

When the message is longer than 16k, the line gets split into multiple parts:
```
{"log":"very","stream":"stdout","time":"2018-08-06T10:33:50.916508402Z"}
{"log":"long","stream":"stdout","time":"2018-08-06T10:33:50.916508403Z"}
{"log":"message\n","stream":"stdout","time":"2018-08-06T10:33:50.916508404Z"}
```

Unfinished lines have a log message which does not end in a newline. I would like to recombine these split lines within FluentBit.

# Solution

I have implemented a special-purpose "Docker mode" (dmode) within in_tail. In its most basic form, when enabled in the configuration, it does the following:

1. Intercept each incoming line in in_tail. Decode it as JSON, find a string value with the key "log", and unescape the string. If any of this fails (not JSON, value is not a string, etc.), process the line normally.
2. If the message is unfinished, append the message to a buffer (dmode_buf) and stop processing the line.
3. If the message is finished, prepend dmode_buf to the message in the line, reset dmode_buf.
4. Process the modified line as if without dmode, i.e. run it through the usual parser etc.

This has the effect that all fields other than "log" will have the values found within the last finished line. Note that multiline mode and dmode are mutually exclusive.

## Buffer flushing

In addition to the behavior above, dmode will flush a non-empty dmode_buf either when a following line cannot be parsed as a Docker line, or when a certain configurable time has passed without a fninished line becoming available. The default is 4 sec. For this to work, a copy of the last unfinished line is always kept in a preallocated buffer.

**Comment by edsiper** [comment]
hi @gchbg 

thanks for this contribution, the feature and patch looks really good.

would you please also submit a PR for the documentation ? 

https://github.com/fluent/fluent-bit-docs/blob/master/input/tail.md

**Comment by gchbg** [comment]
Hi @edsiper 
Thank you for reviewing the patch!
Here is the documentation PR: https://github.com/fluent/fluent-bit-docs/pull/106
I rebased and updated my patch to significantly reduce memory copies in the common case when lines are shorter than the Docker limit and not split.
As far as I can tell, the test failures are unrelated to my change.

**Comment by edsiper** [comment]
thanks!

**Pull request merged**
