### PR TITLE
Add temperature input plugin for Linux

### PR DESCRIPTION
**Pull request by nigels-com**
As previously mentioned in [Issue 308](https://github.com/fluent/fluent-bit/issues/308)

Along similar lines to in_cpu, an input that polls the Linux kernel thermal zones.

PC (Ubuntu 18.04):
```
$ bin/fluent-bit -i temp -p "interval_sec=5" -t my_temp -o stdout -m '*'
...
[0] my_temp: [1565762773.000146937, {"name"=>"thermal_zone0", "type"=>"x86_pkg_temp", "temp"=>48.000000}]
[0] my_temp: [1565762778.000252445, {"name"=>"thermal_zone0", "type"=>"x86_pkg_temp", "temp"=>53.000000}]
```

Raspberry Pi (Raspbian 9.8):
```
[0] my_temp: [1565762891.000612544, {"name"=>"thermal_zone0", "type"=>"cpu-thermal", "temp"=>55.306000}]
[0] my_temp: [1565762896.000601935, {"name"=>"thermal_zone0", "type"=>"cpu-thermal", "temp"=>54.768000}]
[0] my_temp: [1565762901.000605374, {"name"=>"thermal_zone0", "type"=>"cpu-thermal", "temp"=>54.768000}]
[0] my_temp: [1565762906.000607081, {"name"=>"thermal_zone0", "type"=>"cpu-thermal", "temp"=>54.768000}]
[0] my_temp: [1565762911.000593671, {"name"=>"thermal_zone0", "type"=>"cpu-thermal", "temp"=>55.306000}]
```

### CODE REVIEW

**Comment by nigels-com** [comment]
I'm thinking of renaming this plugin `in_thermal` rather than `in_temp` to avoid confusion with _temporary_ vs _temperature_.  Also to align with [colelctd thermal](https://collectd.org/wiki/index.php/Plugin:thermal).

**Comment by nigels-com** [comment]
Another machine that has multiple thermal zones:

```
[0] my_temp: [1565759542.001052911, {"name"=>"thermal_zone2", "type"=>"x86_pkg_temp", "temp"=>44.000000}]
[1] my_temp: [1565759542.001053749, {"name"=>"thermal_zone0", "type"=>"pch_skylake", "temp"=>48.500000}]
[2] my_temp: [1565759542.001054086, {"name"=>"thermal_zone1", "type"=>"iwlwifi", "temp"=>28.000000}]
[0] my_temp: [1565759602.001657622, {"name"=>"thermal_zone2", "type"=>"x86_pkg_temp", "temp"=>31.000000}]
[1] my_temp: [1565759602.001661061, {"name"=>"thermal_zone0", "type"=>"pch_skylake", "temp"=>48.500000}]
[2] my_temp: [1565759602.001662634, {"name"=>"thermal_zone1", "type"=>"iwlwifi", "temp"=>29.000000}]
```

**Comment by edsiper** [comment]
great contribution, thanks :)

please proceed with renaming, sounds good to me. In addition, can you add an option to specify the desired thermal zones (device) to lookup ? (if no one is set, just read all of them), what do u think ?

**Comment by nigels-com** [comment]
Yes, filtering the name and/or type makes sense, agreed.
Ad-hoc testing looks good also.
Screenshot from 2019-08-16 07-01-18

**Comment by edsiper** [comment]
note: to be merged once requested changes are ready

**Comment by nigels-com** [comment]
Renamed from `in_temp` to `in_thermal`.
Filtering the name and type upcoming.

**Comment by nigels-com** [comment]
I've implemented both the rename and filtering as discussed here.
I intend to do some further (broader) testing during the week.

**Comment by edsiper** [comment]
Testing the new changes I don't see any output, e.g:

```
$ bin/fluent-bit -i thermal -o stdout -f 1
Fluent Bit v1.3.0
Copyright (C) Treasure Data

[2019/08/20 16:15:30] [ info] [storage] initializing...
[2019/08/20 16:15:30] [ info] [storage] in-memory
[2019/08/20 16:15:30] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2019/08/20 16:15:30] [ info] [engine] started (pid=27740)
[2019/08/20 16:15:30] [ info] [sp] stream processor started
```

on ctrl-c,  it's crashing in the exit callback:

```
^C[engine] caught signal (SIGINT)
[2019/08/20 16:16:15] [ info] [input] pausing thermal.0
[engine] caught signal (SIGSEGV)
#0  0x55ad4e7bbec4      in  flb_regex_destroy() at src/flb_regex.c:214
#1  0x55ad4e7cae7b      in  in_thermal_exit() at plugins/in_thermal/in_thermal.c:269
#2  0x55ad4e79c41c      in  flb_input_instance_exit() at src/flb_input.c:428
#3  0x55ad4e79c483      in  flb_input_exit_all() at src/flb_input.c:448
#4  0x55ad4e7a6ae9      in  flb_engine_shutdown() at src/flb_engine.c:563
#5  0x55ad4e78df0d      in  flb_signal_handler() at src/fluent-bit.c:235
#6  0x7f866bd17f5f      in  ???() at ???:0
#7  0x7f866bdf1e3f      in  ???() at ???:0
#8  0x55ad4ea4327c      in  _mk_event_wait() at lib/monkey/mk_core/mk_event_epoll.c:345
#9  0x55ad4ea4356c      in  mk_event_wait() at lib/monkey/mk_core/mk_event.c:163
#10 0x55ad4e7a665a      in  flb_engine_start() at src/flb_engine.c:486
#11 0x55ad4e78f17f      in  main() at src/fluent-bit.c:853
#12 0x7f866bcfab6a      in  ???() at ???:0
#13 0x55ad4e78d369      in  ???() at ???:0
#14 0xffffffffffffffff  in  ???() at ???:0
Aborted
```

**Comment by nigels-com** [comment]
> ctrl-c, it's crashing in the exit callback

Yes, fixed.  I made a mistaken assumption there.

> I don't see any output

I set the default `Interval_Sec` to 60s since it's typically changing only slowly.

Can you try with ` -p "Interval_sec=1"`?

Better to default to 1s to align with the other input plugins, perhaps.

**Comment by edsiper** [comment]
@nigels-com thanks.

would you please switch back to one second ?, I prefer to have the default as 1 sec as done in other plugins, so we let the user decide to increase that value.

**Comment by nigels-com** [comment]
> would you please switch back to one second ?

Done!

**Comment by edsiper** [comment]
thanks.

Doing a test with -DFLB_PARSER=Off and -DFLB_REGEX_off I get the following failures:

```
[ 83%] Building C object plugins/in_thermal/CMakeFiles/flb-plugin-in_thermal.dir/in_thermal.c.o
/home/edsiper/coding/fluent-bit/plugins/in_thermal/in_thermal.c: In function ‘proc_temperature’:
/home/edsiper/coding/fluent-bit/plugins/in_thermal/in_thermal.c:79:16: error: ‘struct flb_in_thermal_config’ has no member named ‘name_regex’
         if (ctx->name_regex && !flb_regex_match(ctx->name_regex, (unsigned char *) e->d_name, strlen(e->d_name))) {
                ^~
/home/edsiper/coding/fluent-bit/plugins/in_thermal/in_thermal.c:79:33: warning: implicit declaration of function ‘flb_regex_match’ [-Wimplicit-function-declaration]
         if (ctx->name_regex && !flb_regex_match(ctx->name_regex, (unsigned char *) e->d_name, strlen(e->d_name))) {
                                 ^~~~~~~~~~~~~~~
/home/edsiper/coding/fluent-bit/plugins/in_thermal/in_thermal.c:79:52: error: ‘struct flb_in_thermal_config’ has no member named ‘name_regex’
         if (ctx->name_regex && !flb_regex_match(ctx->name_regex, (unsigned char *) e->d_name, strlen(e->d_name))) {
                                                    ^~
/home/edsiper/coding/fluent-bit/plugins/in_thermal/in_thermal.c:101:24: error: ‘struct flb_in_thermal_config’ has no member named ‘type_regex’
                 if (ctx->type_regex && !flb_regex_match(ctx->type_regex, (unsigned char *) info[i].type, strlen(info[i].type))) {
                        ^~
/home/edsiper/coding/fluent-bit/plugins/in_thermal/in_thermal.c:101:60: error: ‘struct flb_in_thermal_config’ has no member named ‘type_regex’
                 if (ctx->type_regex && !flb_regex_match(ctx->type_regex, (unsigned char *) info[i].type, strlen(info[i].type))) {
                                                            ^~
/home/edsiper/coding/fluent-bit/plugins/in_thermal/in_thermal.c: In function ‘in_thermal_exit’:
/home/edsiper/coding/fluent-bit/plugins/in_thermal/in_thermal.c:268:19: error: ‘struct flb_in_thermal_config’ has no member named ‘name_regex’
     if (ctx && ctx->name_regex) {
                   ^~
/home/edsiper/coding/fluent-bit/plugins/in_thermal/in_thermal.c:269:9: warning: implicit declaration of function ‘flb_regex_destroy’; did you mean ‘flb_pipe_destroy’? [-Wimplicit-function-declaration]
         flb_regex_destroy(ctx->name_regex);
         ^~~~~~~~~~~~~~~~~
         flb_pipe_destroy
/home/edsiper/coding/fluent-bit/plugins/in_thermal/in_thermal.c:269:30: error: ‘struct flb_in_thermal_config’ has no member named ‘name_regex’
         flb_regex_destroy(ctx->name_regex);
                              ^~
/home/edsiper/coding/fluent-bit/plugins/in_thermal/in_thermal.c:271:19: error: ‘struct flb_in_thermal_config’ has no member named ‘type_regex’
     if (ctx && ctx->type_regex) {
                   ^~
/home/edsiper/coding/fluent-bit/plugins/in_thermal/in_thermal.c:272:30: error: ‘struct flb_in_thermal_config’ has no member named ‘type_regex’
         flb_regex_destroy(ctx->type_regex);
```

**Comment by nigels-com** [comment]
> Doing a test with -DFLB_PARSER=Off and -DFLB_REGEX_off I get the following failures:

Ah indeed.  Fixed.

**Comment by edsiper** [comment]
thanks!, would you please submit a new documentation section on fluent/fluent-bit-docs ?

**Comment by nigels-com** [comment]
Yes, see: https://github.com/fluent/fluent-bit-docs/pull/203

**Pull request merged**
