### PR TITLE
parser_json: keep time key when parsing fails

### LINKED ISSUE #7322: `Time_Key` is dropped even when not parsed successfully in json parser
## Bug Report

**Describe the bug**
In the parser configuration docs: https://github.com/fluent/fluent-bit-docs/blob/4f06d31577aa476cf888d2829f94d84e6d1c323d/pipeline/parsers/configuring-parser.md#configuration-parameters 

The `Time_Keep` field documentation says the following:
```
By default when a time key is recognized and parsed, the parser will drop the original time field.
```
This implies to me that if the time value fails to parse, the key should not be dropped. This is not the case with the `json` parser. If a time value fails to parse, the `Time_Key` is dropped regardless.

**To Reproduce**
- Example log message if applicable:
```
{"time":"nonsense"}
```
- Steps to reproduce the problem:
1. Using the following parser:
```
[PARSER]
    Format      json
    Name        parse_json
    Time_Format %m-%dT%H:%M:%S.%L%Z
    Time_Key    time
```
Configured on a pipeline however you'd like, it's not really important. As long as it reads the example log line above and has a valid output you'll be able to see the result.

**Expected behavior**
`time` should still be present because it will fail to parse with the given `Time_Format`.

**Your Environment**

* Version used: Fluent Bit 2.0.12 and `master` branch

**Additional context**
It is possible that this is intended behaviour and that the docs are simply misleading and need an update, however I think it makes sense that the `Time_Key` would be kept if parsing fails.

### PR DESCRIPTION
**Pull request by braydonk**
This PR will cause the `json` parser to retain the time field if parsing the time key fails.

Resolves #7322 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Review by leonardo-albertovich — APPROVED** [review]

**Comment by leonardo-albertovich** [comment]
Thanks for the contribution @braydonk, do you want to backport this to 2.0 or would you rather have someone from the team do it?

**Comment by braydonk** [comment]
As long as this change is acceptable and merged in main, I can do the backport to 2.0!

**Comment by patrick-stephens** [comment]
Looks good to me, just the usual macOS flakes.

**Comment by leonardo-albertovich** [comment]
Thank you very much for the patch and for taking the time to backport it @braydonk.

**Comment by braydonk** [comment]
No problem! Glad we got this resolved.

**Pull request merged**
