### PR TITLE
log: fix memory leaks in the error case

### PR DESCRIPTION
**Pull request by takahasi**
Hi, I found small issues about initializing and try to fix them.
I added changes below;
- NULL checking for flb_log_init()
- free pointer if flb_worker_create() is failed

Could you review it?

### CODE REVIEW

**Comment by nokute78** [comment]
LGTM.

By the way, I found another leaking when I reviewed.

> NULL checking for flb_log_init()

In this point, `ctx->config` is already allocated. So, we should also release it.
Similarly, we should release it on other error cases.

**Comment by edsiper** [comment]
thanks for the report and review.

@takahasi  Please add the modification suggested by @nokute78 so we can merge the changes.

**Comment by takahasi** [comment]
Thank you for the review.

I modified according to your comments.
Could you check again?

**Comment by nokute78** [comment]
LGTM!

@edsiper  How about you?

**Comment by edsiper** [comment]
LGTM, thanks.

**Pull request merged**
