### PR TITLE
go: fix segfault on shutdown by separating exit and unregister

### PR DESCRIPTION
**Pull request by PettitWesley**
Previously the go plugin code attempted to free and unregister the plugin
    in the same code as the call to cb_exit on the plugin instance. This
    causes a segfault when there are multiple instances of the same go
    plugin configured.

https://github.com/aws/aws-for-fluent-bit/issues/613

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Run [local packaging test](./packaging/local-build-all.sh) showing all targets (including any new ones) build.
- [ ] Set `ok-package-test` label to test for all targets (requires maintainer to do).

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Review by Claych — APPROVED** [review]

**Comment by PettitWesley** [comment]
Looks like this is a slightly different version of this which is in master: https://github.com/fluent/fluent-bit/commit/7f4036721b0668a742c99e6b8a1c6b30d58b3320

https://github.com/fluent/fluent-bit/pull/6469

**Review by matthewfala — APPROVED** [review]

**Review by cosmo0920 — APPROVED** [review]
Looks good to me. 😃

**Comment by PettitWesley** [comment]
@cosmo0920 so technically we do not need this in master because of this PR: https://github.com/fluent/fluent-bit/pull/6469/files

Which I didn't find till after I wrote mine. I personally prefer my way of doing this because I think it fits the existing code better and it doesn't add a new callback type for the inputs and outputs (cb_destroy) which seems unnecessary.

**Comment by cosmo0920** [comment]
However, Fluent Bit 1.9 already has a mechanism to call `FLBPluginUnregister` callback at:

https://github.com/fluent/fluent-bit/blob/40be0af8ceb44bc51b8b60bd4c181dcb2fba1955/src/flb_plugin_proxy.c#L262-L276

It only differs how handle to call `FLBPluginUnregister` callback.

**Comment by PettitWesley** [comment]
@cosmo0920 I think the logic is fundamentally the same? In the other PR that was merged, the `FLBPluginUnregister` is called in `cb_destroy` which is the equivalent of my `flb_plugin_proxy_unregister` called on shutdown. We call `FLBPluginUnregister` as part of destroy basically. Not exit step.

**Comment by edsiper** [comment]
should I merge this for 1.9 ?

**Comment by PettitWesley** [comment]
@edsiper this is major bug which is not fixed in 1.9, so I think yes, we shouldn't leave 1.9 branch as closed when go plugins segfault on shutdown.

**Comment by cosmo0920** [comment]
> @cosmo0920 I think the logic is fundamentally the same? In the other PR that was merged, the `FLBPluginUnregister` is called in `cb_destroy` which is the equivalent of my `flb_plugin_proxy_unregister` called on shutdown. We call `FLBPluginUnregister` as part of destroy basically. Not exit step.

Fundamentally same but execution orders slightly different. Both of shutdown sequences should destroy and teardown loaded Golang plugins.

**Pull request merged**
