### PR TITLE
in_kmsg: add exit callback

### PR DESCRIPTION
**Pull request by nokute78**
I added exit callback to in_kmsg plugin to cleanup .

Signed-off-by: Takahiro YAMASHITA <nokute78@gmail.com>

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for the patch. Note that if fd == 0 you will be closing STDIN, so the condition should be > 2

**Comment by nokute78** [comment]
Thanks for reviewing.

> fd 0~2
Once they are closed, system may reuse them.

We make a library, so no such limitation makes fluentbit portable.

**Comment by edsiper** [comment]
I mean, in_kmsg aims to have a fd pointing to /dev/kmsg which should be > 2, otherwise if the input instance is turned down (for ex: from library mode) there is a chance FD=0, 1 or 2, so these FDS should not be touched.

**Comment by edsiper** [comment]
hmm looking at the code there is no way it could be something less < 2. It should be safe to merge.

**Comment by nokute78** [comment]
Thanks for merging.

> so these FDS should not be touched.

Yes it should be, but we can do that...

System reuses fd(=0) with this sample code. User may do like this.
``` c
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>

int main(void){
  int fd=-1;
  close(0);
  fd = open("/dev/kmsg",O_RDONLY);

  printf("fd=%d\n",fd);
  return 0;
}
```

``` sh
$ sudo ./a.out 
fd=0
```

How should we do? 
We can't choice number of fd without open(3).

Hmm should we try to open /dev/null until fd > 2 ?

**Comment by edsiper** [comment]
ahh I understand, for some reason I though the file descriptors assignation followed the PID number assignation algorithm, PID will be likely higher than previous ones, but for file descriptors is different. Thanks for pointing that :).

**Comment by nokute78** [comment]
> I think unused variables for file descriptors should set -1, otherwise try to close (fd != -1)

I think so.
It is better to set -1 unused or uninitialized fd.

**Pull request merged**
