### PR TITLE
ra: support flb_ra_update_kv_pair

### PR DESCRIPTION
**Pull request by nokute78**
I added an API to update key/value of map using record accessor.
It is useful for filter plugin to modify record using record accessor.
(I'll update filter_modify )
I also updated test code which shows how to use this API.

```c
int flb_ra_update_kv_pair(struct flb_record_accessor *ra, msgpack_object map,
                          void **out_map, size_t *out_size,
                          msgpack_object *in_key, msgpack_object *in_val)
```

|Arg|Description|
|----|-------------|
|ra| record accessor to indicate key/value pair|
|map| the original map to update |
|out_map| overwritten map. The value should be free via flb_free after using.|
|out_size| the size of out_map.|
|in_key| The key to overwrite. If NULL, the key will not be modified. |
|in_val| The val to overwrite. If NULL, the key will not be modified. |

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [N/A] Documentation required for this feature

## Debug output

```
$ bin/flb-it-record_accessor 
Test keys...                                    
=== test ===
type       : KEYMAP
key name   : aaa
 - subkey  : a

(snip)
Test update_key_val...                          [ OK ]
Test update_key...                              [ OK ]
Test update_val...                              [ OK ]

```

## Valgrind output 

The leaks are come from test framework not from my patch.
```
Test update_key_val...                          [ OK ]
==86629== 
==86629== HEAP SUMMARY:
==86629==     in use at exit: 144 bytes in 1 blocks
==86629==   total heap usage: 50 allocs, 49 frees, 45,908 bytes allocated
==86629== 
==86629== 144 bytes in 1 blocks are still reachable in loss record 1 of 1
==86629==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==86629==    by 0x11D8FA: main (acutest.h:1632)
==86629== 
==86629== LEAK SUMMARY:
==86629==    definitely lost: 0 bytes in 0 blocks
==86629==    indirectly lost: 0 bytes in 0 blocks
==86629==      possibly lost: 0 bytes in 0 blocks
==86629==    still reachable: 144 bytes in 1 blocks
==86629==         suppressed: 0 bytes in 0 blocks
==86629== 
==86629== For lists of detected and suppressed errors, rerun with: -s
==86629== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Test update_key...                              [ OK ]
==86630== 
==86630== HEAP SUMMARY:
==86630==     in use at exit: 144 bytes in 1 blocks
==86630==   total heap usage: 50 allocs, 49 frees, 45,908 bytes allocated
==86630== 
==86630== 144 bytes in 1 blocks are still reachable in loss record 1 of 1
==86630==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==86630==    by 0x11D8FA: main (acutest.h:1632)
==86630== 
==86630== LEAK SUMMARY:
==86630==    definitely lost: 0 bytes in 0 blocks
==86630==    indirectly lost: 0 bytes in 0 blocks
==86630==      possibly lost: 0 bytes in 0 blocks
==86630==    still reachable: 144 bytes in 1 blocks
==86630==         suppressed: 0 bytes in 0 blocks
==86630== 
==86630== For lists of detected and suppressed errors, rerun with: -s
==86630== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Test update_val...                              [ OK ]
==86631== 
==86631== HEAP SUMMARY:
==86631==     in use at exit: 144 bytes in 1 blocks
==86631==   total heap usage: 30 allocs, 29 frees, 45,121 bytes allocated
==86631== 
==86631== 144 bytes in 1 blocks are still reachable in loss record 1 of 1
==86631==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==86631==    by 0x11D8FA: main (acutest.h:1632)
==86631== 
==86631== LEAK SUMMARY:
==86631==    definitely lost: 0 bytes in 0 blocks
==86631==    indirectly lost: 0 bytes in 0 blocks
==86631==      possibly lost: 0 bytes in 0 blocks
==86631==    still reachable: 144 bytes in 1 blocks
==86631==         suppressed: 0 bytes in 0 blocks
==86631== 
==86631== For lists of detected and suppressed errors, rerun with: -s
==86631== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
SUCCESS: All unit tests have passed.
==86622== 
==86622== HEAP SUMMARY:
==86622==     in use at exit: 0 bytes in 0 blocks
==86622==   total heap usage: 2 allocs, 2 frees, 1,168 bytes allocated
==86622== 
==86622== All heap blocks were freed -- no leaks are possible
==86622== 
==86622== For lists of detected and suppressed errors, rerun with: -s
==86622== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by nokute78** [comment]
@edsiper Please take a look?
This patch is to add API `flb_ra_update_kv_pair` and test code.
The API is only called from test code. It will not be a breaking change.

Except below function.
`static struct flb_ra_parser* get_ra_parser(struct flb_record_accessor *ra)`

I created new function `get_ra_parser` for similar procedure.

**Comment by edsiper** [comment]
pls solve conflicts on tests (sorry for the delay)

**Comment by nokute78** [comment]
@edsiper  I fixed conflicts.

**Comment by nokute78** [comment]
@edsiper Ping.

**Comment by nokute78** [comment]
ping
I fixed conflicts and it was ready to review.

The new user request had come...
https://github.com/fluent/fluent-bit/issues/4651

**Comment by nokute78** [comment]
Fix conflict.

**Comment by nokute78** [comment]
Fix conflict.

**Comment by andrewnazarov** [comment]
@edsiper any chances to get this reviewed? It seems it would be a great help for those who want to modify k8s metadata, for example.

**Pull request merged**
