### PR TITLE
config_format: fluentbit: call stat again when resolve real path(#6281)

### PR DESCRIPTION
**Pull request by nokute78**
https://github.com/fluent/fluent-bit/blob/v2.0.0/src/config_format/flb_cf_fluentbit.c#L439
In this case, fluent-bit tries to resolve the real path.
However `st` will not be updated using new real path.
Then `st.st_ino` will be 0 and fluent-bit will abort.
https://github.com/fluent/fluent-bit/blob/v2.0.0/src/config_format/flb_cf_fluentbit.c#L453

This issue was caused by https://github.com/fluent/fluent-bit/pull/6213
It will happen using following command.
```
fluent-bit -c <absolute path to configuration file>
```

This patch is to fix it calling stat for new real path to get real inode.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [X] Example configuration file for the change
- [X] Debug log output from testing the change

- [X] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [N/A] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [N/A] Documentation required for this feature

**Backporting**

- [N/A] Backport to latest stable release.

## Configuration 

issue6281.conf:
```
@INCLUDE issue6281_input.conf
@INCLUDE issue6281_output.conf
```
issue6281_input.conf:
```
[INPUT]
    Name dummy
```

issue6281_output.conf:
```
[OUTPUT]
    Name stdout
```

## Debug/Valgrind output
```
$ valgrind --leak-check=full bin/fluent-bit -c ~/git/WORKTREE/fix_6281/tests/internal/data/config_format/classic/issue6281.conf 
==111408== Memcheck, a memory error detector
==111408== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==111408== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==111408== Command: bin/fluent-bit -c /home/taka/git/WORKTREE/fix_6281/tests/internal/data/config_format/classic/issue6281.conf
==111408== 
Fluent Bit v2.0.0
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/10/27 05:27:32] [ info] [fluent bit] version=2.0.0, commit=58b0214f02, pid=111408
[2022/10/27 05:27:32] [ info] [storage] ver=1.3.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/10/27 05:27:32] [ info] [cmetrics] version=0.5.3
[2022/10/27 05:27:32] [ info] [ctraces ] version=0.2.5
[2022/10/27 05:27:32] [ info] [input:dummy:dummy.0] initializing
[2022/10/27 05:27:32] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2022/10/27 05:27:33] [ info] [sp] stream processor started
[2022/10/27 05:27:33] [ info] [output:stdout:stdout.0] worker #0 started
[0] dummy.0: [1666816053.535887407, {"message"=>"dummy"}]
[0] dummy.0: [1666816054.510309454, {"message"=>"dummy"}]
^C[2022/10/27 05:27:35] [engine] caught signal (SIGINT)
[0] dummy.0: [1666816055.447874557, {"message"=>"dummy"}]
[2022/10/27 05:27:35] [ warn] [engine] service will shutdown in max 5 seconds
[2022/10/27 05:27:35] [ info] [input] pausing dummy.0
[2022/10/27 05:27:36] [ info] [engine] service has stopped (0 pending tasks)
[2022/10/27 05:27:36] [ info] [input] pausing dummy.0
[2022/10/27 05:27:36] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2022/10/27 05:27:36] [ info] [output:stdout:stdout.0] thread worker #0 stopped
==111408== 
==111408== HEAP SUMMARY:
==111408==     in use at exit: 0 bytes in 0 blocks
==111408==   total heap usage: 1,478 allocs, 1,478 frees, 1,275,432 bytes allocated
==111408== 
==111408== All heap blocks were freed -- no leaks are possible
==111408== 
==111408== For lists of detected and suppressed errors, rerun with: -s
==111408== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by nokute78** [comment]
@edsiper @niedbalski Could you review it ?
I think this is a critical bug. Sorry for it...

**Comment by drbugfinder-work** [comment]
@nokute78 I've tested your patch and it works like expected now. It does fix #6281.

**Review by drbugfinder-work — APPROVED** [review]

**Comment by nokute78** [comment]
@drbugfinder-work Thank you for testing patch.

**Comment by edsiper** [comment]
thanks!

**Pull request merged**
