### PR TITLE
TLS: using dot trimmed tcp_host/proxied_host for vhost

### LINKED ISSUE #7403: TCP&TLS output sends an invalid hostname if it's specified with a trailing dot
## Bug Report

**Describe the bug**
If TCP output is set to TLS and the `Host` field is filled with a host name with a dot at the end, the host name is sent as is, which causes the cert<->host validation to fail.

**To Reproduce**
```ini
[OUTPUT]
    Name                tcp
    Host                logstash.domain.com.
    Port                5044
    Format              json_lines
    json_date_key       @timestamp
    json_date_format    iso8601
    Match               *
    tls                 On
    tls.verify          On
    tls.ca_file         /fluent-bit/etc/tls/logstash-client-cert/ca.crt
    tls.crt_file        /fluent-bit/etc/tls/logstash-client-cert/tls.crt
    tls.key_file        /fluent-bit/etc/tls/logstash-client-cert/tls.key
```
As a result, the host check fails with the following error (in my case from Logstash):
```
null: closing due: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLProtocolException:
 Illegal server name, type=host_name(0), name=logstash.domain.com., value=.........
                                                                 ^
```
**Expected behavior**

Trailing dots should be trimmed after DNS resolution.

**Your Environment**
* Version used: Fluent Bit v2.1.2
* Configuration: N/A
* Environment name and version (e.g. Kubernetes? What version?): N/A
* Server type and version: Linux  5.15.90
* Operating System and version: Debian GNU/Linux 11 (bullseye)" 
* Filters and plugins: N/A

**Additional context**
Of course, just using hostnames without dots at the end solves this issue. But it goes against best practices when you run workloads inside k8s.
Link for Trailing Dots notation explanation: http://www.dns-sd.org/trailingdotsindomainnames.html

### PR DESCRIPTION
**Pull request by psmolkin**
* tls uses dot trimmed tcp_host/proxied_host for vhost
* new rtrim() function

Fixes #7403

**Testing**
Before we can approve your change; please submit the following in a comment:
- [x] Example configuration file for the change
    ```
    [SERVICE]
        Daemon Off
        Flush  1s
        Log_Level debug

    [INPUT]
        Name   dummy
        Tag    dummy.log
        Samples 2

    [OUTPUT]
        Name                tcp
        Host                logstash.redacted.com.
        Port                5059
        Format              json_lines
        json_date_key       @timestamp
        json_date_format    iso8601
        Match               *
        tls                 On
        tls.verify          On
        tls.ca_file         /tmp/ca.crt
        tls.crt_file        /tmp/tls.crt
        tls.key_file        /tmp/tls.key
        tls.debug           4

    [OUTPUT]
        Name   stdout
        Match  *
    ```
- [x] Debug log output from testing the change
    ```
    Fluent Bit v2.1.3
    * Copyright (C) 2015-2022 The Fluent Bit Authors
    * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
    * https://fluentbit.io

    [2023/05/17 05:18:48] [ info] Configuration:
    [2023/05/17 05:18:48] [ info]  flush time     | 1.000000 seconds
    [2023/05/17 05:18:48] [ info]  grace          | 5 seconds
    [2023/05/17 05:18:48] [ info]  daemon         | 0
    [2023/05/17 05:18:48] [ info] ___________
    [2023/05/17 05:18:48] [ info]  inputs:
    [2023/05/17 05:18:48] [ info]      dummy
    [2023/05/17 05:18:48] [ info] ___________
    [2023/05/17 05:18:48] [ info]  filters:
    [2023/05/17 05:18:48] [ info] ___________
    [2023/05/17 05:18:48] [ info]  outputs:
    [2023/05/17 05:18:48] [ info]      tcp.0
    [2023/05/17 05:18:48] [ info]      stdout.1
    [2023/05/17 05:18:48] [ info] ___________
    [2023/05/17 05:18:48] [ info]  collectors:
    [2023/05/17 05:18:48] [ info] [fluent bit] version=2.1.3, commit=14f4561474, pid=15503
    [2023/05/17 05:18:48] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
    [2023/05/17 05:18:48] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
    [2023/05/17 05:18:48] [ info] [cmetrics] version=0.6.1
    [2023/05/17 05:18:48] [ info] [ctraces ] version=0.3.0
    [2023/05/17 05:18:48] [ info] [input:dummy:dummy.0] initializing
    [2023/05/17 05:18:48] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
    [2023/05/17 05:18:48] [debug] [dummy:dummy.0] created event channels: read=22 write=23
    [2023/05/17 05:18:48] [debug] [tcp:tcp.0] created event channels: read=24 write=25
    [2023/05/17 05:18:49] [ info] [output:tcp:tcp.0] worker #0 started
    [2023/05/17 05:18:49] [debug] [stdout:stdout.1] created event channels: read=40 write=41
    [2023/05/17 05:18:49] [ info] [output:tcp:tcp.0] worker #1 started
    [2023/05/17 05:18:49] [debug] [router] match rule dummy.0:tcp.0
    [2023/05/17 05:18:49] [ info] [output:stdout:stdout.1] worker #0 started
    [2023/05/17 05:18:49] [debug] [router] match rule dummy.0:stdout.1
    [2023/05/17 05:18:49] [ info] [sp] stream processor started
    [2023/05/17 05:18:49] [debug] [input chunk] update output instances with new chunk size diff=36
    [2023/05/17 05:18:50] [debug] [task] created task=0x7faab8088510 id=0 OK
    [2023/05/17 05:18:50] [debug] [output:tcp:tcp.0] task_id=0 assigned to thread #0
    [2023/05/17 05:18:50] [debug] [output:stdout:stdout.1] task_id=0 assigned to thread #0
    [0] dummy.log: [[1684315129.222727729, {}], {"message"=>"dummy"}]
    [2023/05/17 05:18:50] [debug] [input chunk] update output instances with new chunk size diff=36
    [2023/05/17 05:18:50] [debug] [out flush] cb_destroy coro_id=0
    [2023/05/17 05:18:50] [debug] [upstream] KA connection #61 to logstash.redacted.com.:5059 is connected
    [2023/05/17 05:18:50] [debug] [upstream] KA connection #61 to logstash.redacted.com.:5059 is now available
    [2023/05/17 05:18:50] [debug] [out flush] cb_destroy coro_id=0
    [2023/05/17 05:18:50] [debug] [task] destroy task=0x7faab8088510 (task_id=0)
    [2023/05/17 05:18:51] [debug] [task] created task=0x7faab8088890 id=0 OK
    [0] dummy.log: [[1684315130.223515189, {}], {"message"=>"dummy"}]
    [2023/05/17 05:18:51] [debug] [output:tcp:tcp.0] task_id=0 assigned to thread #1
    [2023/05/17 05:18:51] [debug] [output:stdout:stdout.1] task_id=0 assigned to thread #0
    [2023/05/17 05:18:51] [debug] [out flush] cb_destroy coro_id=1
    [2023/05/17 05:18:51] [debug] [upstream] KA connection #62 to logstash.redacted.com.:5059 is connected
    [2023/05/17 05:18:51] [debug] [upstream] KA connection #62 to logstash.redacted.com.:5059 is now available
    [2023/05/17 05:18:51] [debug] [out flush] cb_destroy coro_id=0
    [2023/05/17 05:18:51] [debug] [task] destroy task=0x7faab8088890 (task_id=0)
    [2023/05/17 05:19:20] [debug] [upstream] drop keepalive connection #-1 to logstash.redacted.com.:5059 (keepalive idle timeout)
    ```
    
- [x] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found
    ```
    ==38345== 
    ==38345== HEAP SUMMARY:
    ==38345==     in use at exit: 291,064 bytes in 6,128 blocks
    ==38345==   total heap usage: 21,388 allocs, 15,260 frees, 7,468,915 bytes allocated
    ==38345== 
    ==38345== LEAK SUMMARY:
    ==38345==    definitely lost: 0 bytes in 0 blocks
    ==38345==    indirectly lost: 0 bytes in 0 blocks
    ==38345==      possibly lost: 0 bytes in 0 blocks
    ==38345==    still reachable: 291,064 bytes in 6,128 blocks
    ==38345==         suppressed: 0 bytes in 0 blocks
    ==38345== Rerun with --leak-check=full to see details of leaked memory
    ==38345== 
    ==38345== For lists of detected and suppressed errors, rerun with: -s
    ==38345== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
    ```

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [x] Run [local packaging test](./packaging/local-build-all.sh) showing all targets 
(including any new ones) build.\
   `[N/A]`
- [x] Set `ok-package-test` label to test for all targets (requires maintainer to do).\
  `[N/A]`

**Documentation**

- [x] Documentation required for this feature\
      `[N/A]` 

**Backporting**

- [x] Backport to latest stable release.\
  `[N/A]` 

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Review by leonardo-albertovich — CHANGES_REQUESTED** [review]
Please make those minor coding style changes and I'll merge this asap.

**Comment by leonardo-albertovich** [comment]
Thanks for coming through with this PR @psmolkin, we really appreciate it when users step up and contribute!

Once this is merged would you like to backport it to the 2.0 branch or would you rather have someone from the team do it?

**Review by leonardo-albertovich — APPROVED** [review]

**Comment by leonardo-albertovich** [comment]
Peachy, thanks a lot!

**Comment by psmolkin** [comment]
I assume correctly that the test errors are not caused by my change, right?

**Comment by leonardo-albertovich** [comment]
You are right.

**Comment by leonardo-albertovich** [comment]
Thank you very much for the contribution @psmolkin!

@Syn3rman is going to backport this improvement to fluent-bit 2.0.

**Pull request merged**
