### PR TITLE
update influxdb output help info

### PR DESCRIPTION
**Pull request by daixiang0**
In fact, there is not one reason to cause `bulk_body` emtpy:

1. no data from input module
1. all data exclude in filter module
1. data is tagged so no need to send
...

So update help info and change error to warn since it may be common and no need to highlight with error level.

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
@edsiper mind have a look?

**Comment by daixiang0** [comment]
@bluebike @edsiper mind have a look?

**Comment by daixiang0** [comment]
@edsiper mind have a look?

**Comment by daixiang0** [comment]
@edsiper mind have a look?

**Comment by edsiper** [comment]
Thanks, please fix the typos:

- aviliable
- all fields

**Comment by daixiang0** [comment]
@edsiper done.

**Comment by daixiang0** [comment]
@edsiper mind help me? I do not know how to fix it.

**Comment by edsiper** [comment]
conflicts resolved, merged.

thanks!

**Pull request merged**
