### PR TITLE
in_tail: use stricmp() to compare two paths

### PR DESCRIPTION
**Pull request by fujimotos**
Windows API is designed to be case insensitive. This means that the
following two paths refer to the same file:

    C:\Users\Alice\README.TXT
    C:\Users\Alice\readme.txt

This patch reflect this design and fixes flb_tail_file_name_cmp() to
use strnicmp() (= strcasecmp() in POSIX) to compare two file paths.

*This patch is intended to be merged after v1.1 release*

Part of #960

### CODE REVIEW

**Comment by fujimotos** [comment]
Sorry for a late reply. 

> do you not want to check platform rather than microsoft compiler?

I think this patch does not work for other build platforms like Cygwin
due to the use of _stricmp().

It's really a future task to support other build platforms than MSVC.
My current opinion (if we ever support them) is to follow what GIT does
- define FLB_WINDOWS_NATIVE to detect MSVC and MinGW and handle Cygwin
another way.

But anyway, as to whether/when/how to support alternetive build platforms,
we really need to ask @edsiper for his opinion; I'd like to follow his
decision and plan on this kind of general development issues.

**Comment by edsiper** [comment]
@fujimotos I think defining a FLB_WINDOWS_SOMETHING is the proper way, but for now we are focusing just on MSVC support-only

**Comment by donbowman** [comment]
> @fujimotos I think defining a FLB_WINDOWS_SOMETHING is the proper way, but for now we are focusing just on MSVC support-only

According to microsoft:

https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2017

_WIN32 :: means on the Windows platform

I would not use MSC_VER for this. 
a) it precludes the use of MSC for non windows platform
b) it precludes the use of non MSC compilers for the windows platform

So for a windows-specific change (e.g. case-insensitive paths) it should be _WIN32.
For a MSC specific change (e.g. location of some proprietary header) its appropriate to use MSC.

**Comment by edsiper** [comment]
so we should define a FLB_WINDOWS_OS IF _WIN32 and MSC Is set, comments ?

**Comment by donbowman** [comment]
If _WIN32 yes, not if MSC.

Microsoft C doesn't imply windows (e.g. you can target linux from it w/ cmake).
here you are using windows to imply case-insensitive paths.

**Comment by fujimotos** [comment]
@edsiper @donbowman

After re-reading CMake's documentation and the discussion in this ticket,
I think the changeset 62b85ed is probably what we want to do.

The key points are:

 * Cmake uses `CMAKE_SYSTEM_NAME` to declare the build target platform.
 
 * In most cases, it's equal to the host system where the build is
   taking place, but not always so.

 * For example, if we cross-compile a program for Windows on Linux,
   the variable should be set to "Windows", not "Linux".

 * Cygwin is considered to be a distinct platform and does not have
   "Windows" in its value.

So 62b85ed should work well for our needs, including the cross-compiling
case @donbowman suggests.

If you notice anything missing, please tell me!

Note: Cygwin is also case-insensitive, but [does not support stricmp()](https://trac.sagemath.org/ticket/17641)
(and other Windows-flavored functions in general). So I believe it's
sensible not to consider Cygwin as Windows here.

**Comment by fujimotos** [comment]
Update: Change the macro name from `FLB_WINDOWS_SYSTEM`
to `FLB_SYSTEM_WINDOWS`.

**Comment by fujimotos** [comment]
Submerged into the in_tail Windows support patch.

**Pull request closed without merging**
