### PR TITLE
workflow: allow equal and slash

### PR DESCRIPTION
**Pull request by nokute78**
This patch allows `=` and `/` for commit message.
e.g. 
- `=`
   -  `build: fix build failure with -DFLB_SHARED_LIB=OFF (#3042) ` [patch](https://github.com/fluent/fluent-bit/commit/f1ac53ed0e53ab48d54fb5d53bd7dbbcdf8b6a0e#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a)
-  `/`
   - `build: fix cpack rules and validate flex/bison` [patch](https://github.com/fluent/fluent-bit/commit/e6c9468df5bb709d52bd4ec7a155517c2d1903c5#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a)

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [X] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [N/A] Documentation required for this feature

## Debug output

equal case.
```ruby
irb(main):001:0> str = 'build: fix build failure with -DFLB_SHARED_LIB=OFF (#3042)'
irb(main):002:0> str.match /^[a-z0-9\-_]+\:[ ]{0,1}[a-z]+[a-zA-Z0-9 \-\.\:_\#\(\)=\/]+$/
=> #<MatchData "build: fix build failure with -DFLB_SHARED_LIB=OFF (#3042)">
```

slash case.
```ruby
irb(main):001:0> str = 'build: fix cpack rules and validate flex/bison'
irb(main):002:0> str.match /^[a-z0-9\-_]+\:[ ]{0,1}[a-z]+[a-zA-Z0-9 \-\.\:_\#\(\)=\/]+$/
=> #<MatchData "build: fix cpack rules and validate flex/bison">
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by fujimotos** [comment]
Hmm. The commit checker is evidently being too picky. This is the fourth PR
(after #3285, #3281 and #3270) that tries to amend the issue, but the bot
apparently needs a few more tweaks. Using this Python script:


```python3
import re
import sys 

pat = re.compile(r'^[a-z0-9\-_]+\:[ ]{0,1}[a-z]+[a-zA-Z0-9 \-\.\:_\#\(\)=\/]+$')
bad = 0 

for n, line in enumerate(sys.stdin):
    line = line.strip()
    if not pat.match(line):
        print("bad commit:", line)
        bad += 1

print("%i/%i rejected (%i%%)" % (bad, n, bad / n * 100))
```

I can confirm that the checking bot rejects ~1/4 of our historical commits:


```python3
$ git log --oneline  --no-merges --decorate=no | cut -d " " -f 2- | python3 a.py
...
bad commit: Core: initialization and 32 bit fixes.
1418/5933 rejected (23%)
```

Overall, the robot seems to be rejecting tons of valid commits, and actively
making contributors feel miserable.

**Review by fujimotos — APPROVED** [review]

**Comment by nokute78** [comment]
@fujimotos  nice script!

I modified script and this diff reports `92/6029 rejected (1%)`

```diff
--- /home/taka/a.py	2021-03-31 11:28:42.256176691 +0900
+++ /home/taka/b.py	2021-03-31 11:28:24.972003619 +0900
@@ -1,7 +1,7 @@
 import re
 import sys 
 
-pat = re.compile(r'^[a-z0-9\-_]+\:[ ]{0,1}[a-z]+[a-zA-Z0-9 \-\.\:_\#\(\)=\/]+$')
+pat = re.compile(r'^[a-z0-9A-Z\-_\s\,\.\/]+\:[ ]{0,1}[a-zA-Z]+[a-zA-Z0-9 \-\.\:_\#\(\)=\/\'\"\,><\+\[\]\!\*\\]+$')
 bad = 0 
 
 for n, line in enumerate(sys.stdin):

```

**Comment by fujimotos** [comment]
> I modified script and this diff reports 92/6029 rejected (1%)

@nokute78 Great. Can you submit that pattern as a PR with the
script report attached?

Looking over the new pattern, I'm basically fine with your proposal.

**Comment by nokute78** [comment]
I added commit to respect https://github.com/fluent/fluent-bit/pull/3306#issuecomment-810710912.

It is against this [document](https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md#commit-changes)
We may need to fix CONTRIBUTING.md.

e.g. `Your principal commit message (one line subject) must be prefixed with the core section name in lowercase plus a colon`
Refer to this, `SSL/TLS: add mbedtls encryption library`  is not allowed.

**Pull request merged**
