### PR TITLE
tests: fix the test ends before flushing

### PR DESCRIPTION
**Pull request by takahasi**
Hi, I found a small issue about test failure for out_file plugin.

The root cause was;
- sometimes the test ends before flushing

Could you review it?

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for catching this.

Note that when Fluent Bit is shutting down (stop), it have a graceful period of 5 seconds. Would you please check if you can reproduce the problem if you set the Flush time in the config for 1 second ?

**Comment by takahasi** [comment]
Thank you for your comment.

I checked it again and found the actual root cause.
It was "pause input plugin before happening collector events for input". 

Related the below commit.
commit: ea09c764ccce76cf7ce4d117f9dc0e50d505b335

In my opinion, this change was correct. flb_stop API must stop data as soon as possible.
So my test code should be waited until ends input collector.

How about your idea?

**Comment by takahasi** [comment]
Hi, do you have any comments?
I think this change is not so big impact, but the test which continues to fail is a bad thing for this project.

**Comment by edsiper** [comment]
merging for now, before final 0.12 release we will review for other similar cases.

thanks!

**Comment by takahasi** [comment]
thanks!

**Pull request merged**
