### PR TITLE
Debian build fixes

### PR DESCRIPTION
**Pull request by nickbroon**
- Flex, Bison are build dependencies to optional run time dependencies.
- Depend on linked libraries using ${shlibs}.
- Silence some Lintian warnings about statically linked vendored libraries.

### CODE REVIEW

**Comment by nickbroon** [comment]
Is this considerable for merging?

**Comment by edsiper** [comment]
@nickbroon since v1.3 we are using CMake (CPack specifically) to create the packages. Would you please how to move this improvement to the main CMakeLists.txt file ?

**Comment by nickbroon** [comment]
As far as I'm aware, cmake is still using these files from the debian directory, so these changes are valid there.

**Comment by sysword** [comment]
Hi , i want to know can i build locally and run the output fluent bit binary on other machine since the output binary is dynamically linked? i use the source code 1.3.3. will be appreciate if you can tip me .

**Comment by edsiper** [comment]
cmake is not using those files, only conffiles. 

can we make the changes available from cmakelists.txt ?

**Comment by nickbroon** [comment]
These changes are for the case where dpkg-buildpackge is used to build the .debs, not when cmake is used to build the .debs.

**Comment by edsiper** [comment]
got it, makes sense.

**Pull request merged**
