### PR TITLE
out_es: Add experimental support for Amazon ElasticSearch for 1.4

### PR DESCRIPTION
**Pull request by PettitWesley**
Addresses #1804 and #1807

### CODE REVIEW

**Comment by PettitWesley** [comment]
AWS credentials must be specified with environment variables, but it works.

Config:
```
[SERVICE]
    Log_Level debug

[INPUT]
    Name  cpu
    Tag   cpu

[OUTPUT]
    Name  es
    Match *
    Host  vpc-test-domain-ke7thhzoo7jawsrhmm6mb7ite7y.us-west-2.es.amazonaws.com
    Port  443
    Index my_index
    Type  my_type
    Aws_Auth On
    Aws_Region us-west-2
    tls     On
    tls.verify On
```

Output:
```
[2020/01/29 00:43:01] [debug] [task] created task=0x267aba0 id=0 OK
[2020/01/29 00:43:02] [debug] [out_es] Signing request with AWS Sigv4
[2020/01/29 00:43:02] [debug] [out_es] HTTP Status=200 URI=/_bulk
[2020/01/29 00:43:02] [debug] [out_es] Elasticsearch response
{"took":71,"errors":false,"items":[{"index":{"_index":"my_index","_type":"my_type","_id":"TijA7m8Bspwi5JFlXs4u","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":177,"_primary_term":1,"status":201}},{"index":{"_index":"my_index","_type":"my_type","_id":"TyjA7m8Bspwi5JFlXs4u","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":173,"_primary_term":1,"status":201}},{"index":{"_index":"my_index","_type":"my_type","_id":"UCjA7m8Bspwi5JFlXs4u","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":174,"_primary_term":1,"status":201}},{"index":{"_index":"my_index","_type":"my_type","_id":"USjA7m8Bspwi5JFlXs4u","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":171,"_primary_term":1,"status":201}}]}
[2020/01/29 00:43:02] [debug] [task] destroy task=0x267aba0 (task_id=0)
```

**Comment by PettitWesley** [comment]
I also built Fluent Bit with `-DFLB_SIGNV4=Off` and out_es works fine (and as expected AWS options in the config are then rejected)/

**Comment by PettitWesley** [comment]
Doc PR: https://github.com/fluent/fluent-bit-docs/pull/260

**Comment by edsiper** [comment]
thanks for this.

Would you please split the commits per components ? in two like :

1. out_es: ....
2. http_client: ...

**Comment by PettitWesley** [comment]
@edsiper updated

**Comment by edsiper** [comment]
thanks!

**Comment by jujugrrr** [comment]
> (by 1.5, we'll have full support for all credentials providers).

Thanks a lot for the work @edsiper !
Because of short lived credentials(STS session will be 1h), using environment variable is not really an option in a secured context. 

Once you support credentials provider could you include the Web identity provider? It's supported by all the latest AWS SDK versions, and is the go to solution, for a secure IAM/EKS role mapping.

https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

**Comment by PettitWesley** [comment]
@jujugrrr  

> include the Web identity provider?

We will. I'm working on a full set of providers including EKS:
- https://github.com/fluent/fluent-bit/pull/1852
- https://github.com/fluent/fluent-bit/pull/1854
- https://github.com/fluent/fluent-bit/pull/1855
- https://github.com/fluent/fluent-bit/pull/1857

> using environment variable is not really an option in a secured context.

Agreed. The Fluent Bit docs for this feature note that it's experimental and that it might not be suitable for production workloads. I probably won't enable this feature in [AWS for Fluent Bit](https://github.com/aws/aws-for-fluent-bit) either; instead we'll wait for the full set of providers to be completed.

**Comment by jujugrrr** [comment]
@PettitWesley Thanks! it looks like it's all coming. It seems much better than using proxy for the IAM signing.

I'll follow all of this closely. Let us know if we can helm with testing

**Comment by PettitWesley** [comment]
> Let us know if we can help with testing

@jujugrrr You can for sure; that would be awesome. The ECR image link noted below should be accessible from any AWS account. It includes all of the credential provider except for EC2 instance role.

 I'd be especially interested to know if you're an app mesh user- that's one test case I haven't covered yet- making sure the envoy proxy does not affect any of the calls Fluent Bit makes. (We've had some issues in the past where on startup calls will fail- though that was in ECS).

* `714124127858.dkr.ecr.us-west-2.amazonaws.com/fluent-bit-elastic-search-bug-bash:latest`

**Comment by jujugrrr** [comment]
No app-mesh here, probably Istio in the future though. I tried
https://github.com/fluent/fluent-bit/pull/1852, but when merging your
branch to fluent-bit master we were getting conflicts and some build issues
during the docker build.
Does the ECS image include the ENV changes only or all your other providers?

**Comment by PettitWesley** [comment]
> Does the ECR image include the ENV changes only or all your other providers?

Yup, as I noted, it has all of the credential providers besides EC2 instance role.

**Pull request merged**
