### PR TITLE
upstream: fix the stuck issue happened in Windows Server 2016 and 2019.

### PR DESCRIPTION
**Pull request by sudahang**
This patch fix the issue https://github.com/fluent/fluent-bit/issues/6163. It moves the close socket function from prepare_destroy_conn to destroy_conn function. In the old way, prepare_destroy_conn or flb_upstream_conn_timeouts will close or shutdown the socket, then call flb_tls_session_destroy to shutdown ssl, which causes failure of SSL_shutdown. And randomly fluent-bit is stuck at the second SSL_shutdown call in Windows Server 2016 or 2019. After this change, SSL_shutdown works correctly.

Signed-off-by: Richard Su <sudahang@hotmail.com>

https://github.com/fluent/fluent-bit/issues/6163
----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [ ] Example configuration file for the change
- [ ] Debug log output from testing the change

- [ ] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

If this is a change to packaging of containers or native binaries then please confirm it works for all targets.
- [ ] Attached [local packaging test](./packaging/local-build-all.sh) output showing all targets (including any new ones) build.

**Documentation**

- [ ] Documentation required for this feature

**Backporting**

- [ ] Backport to latest stable release.

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by edsiper** [comment]
assigned to @leonardo-albertovich

**Comment by leonardo-albertovich** [comment]
I will reproduce the bug in master and then apply the patch to validate the fix. 

Overall I agree with the rationale but I want to be completely sure of what's happening because even though it's wrong I would expect `Openssl_shutdown` to fail if the socket was closed (on either end) and I want to know if that's not happening or if there is a logic bug in our TLS layer.

Once I finish this process if everything still seems to be correct I'll approve this PR.

**Comment by leonardo-albertovich** [comment]
@sudahang, I've been trying to reproduce your issue with no luck so far. 
I know you mentioned it's not determinitic but would you mind sharing your configuration files and a bit of insight on the context? 
I also tried with multiple forward instances sending traffic and even with threading enabled which was not the default in 1.8 so I'm a bit lost here.
What I have not tried yet is explicitly setting keepalive or any other networking parameters.

About the openssl wrapper implementation I noticed that `SSL_shutdown` is being called twice in a row https://github.com/fluent/fluent-bit/blob/master/src/tls/openssl.c#L389 (but it's only called if there are no socket errors and I'm not sure of what would `flb_socket_error` return for a closed socket (I assume it should fail unless the file descriptor was reallocated before this code had a chance to run (1)))

Going back to the point, I noticed that instead of moving the `flb_tls_session_destroy` call to `prepare_destroy_conn` you moved the rest to `destroy_conn`. Please revert that, move the TLS session termination and socket closure to `prepare_destroy_conn` so it's executed immediately after removing the socket from the event loop and I'll approve the PR.

Could you also remove that repeated `SSL_shutdown` call please?

1 - Considering that you are running into this problem in windows I think is very unlikely that this is the case. In linux where you "can" liberally choose between using `recv`/`send` or `read`/`write` I could foresee this happening if :

1. A socket is created and a TLS session is established
2. The socket is closed but the TLS session is not terminated
3. A file is opened in read/write mode and the file descriptor is reused
4. `destroy_conn` -> `flb_tls_session_destroy` -> `tls_session_destroy` -> `SSL_shutdown` is called, writes to the file descriptor and blocks while waiting for the reply.


```
fluentd.conf

<source>
    @type forward
    port 24224
    bind 0.0.0.0

    <transport tls>
        cert_path /etc/fluentd/self_signed.crt
        private_key_path /etc/fluentd/self_signed.key
    </transport>
</source>

<match **>
    @type stdout
</match>
```

```
fluent-bit.conf

[SERVICE]
    flush 1
    log_level debug

[INPUT]
    name dummy
    rate 1000

[INPUT]
    name dummy
    rate 1000

[INPUT]
    name dummy
    rate 1000

[INPUT]
    name dummy
    rate 1000

[OUTPUT]
    name forward
    match *
    host 192.168.1.2
    port 24224
    tls.verify no
    tls on
    workers 0
```

**Comment by sudahang** [comment]
> 1 - Considering that you are running into this problem in windows I think is very unlikely that this is the case. In linux where you "can" liberally choose between using `recv`/`send` or `read`/`write` I could foresee this happening if :
> 
> 1. A socket is created and a TLS session is established
> 2. The socket is closed but the TLS session is not terminated
> 3. A file is opened in read/write mode and the file descriptor is reused
> 4. `destroy_conn` -> `flb_tls_session_destroy` -> `tls_session_destroy` -> `SSL_shutdown` is called, writes to the file descriptor and blocks while waiting for the reply.

Hi @leonardo-albertovich I agree with you. The step 3 is critical. If the fd is reused, it might go into this scenario. 
This issue is very difficult to reproduce in short time. But if you run it for long enough, most of the machine could be finally stuck. It may take days.
I also tried to comment out the second SSL_shutdown at the first time when I read the dump file, it could fix this issue. But appearently it is not a good way, so I eventuall found the root cause after more research.
I'll move the flb_tls_session_destroy call to prepare_destroy_conn and submit the change later today.

**Comment by sudahang** [comment]
Hi @leonardo-albertovich I have moved the flb_tls_session_destroy call to prepare_destroy_conn. I also have a PR https://github.com/fluent/fluent-bit/pull/6261 for branch 1.8, in which I made the same change.

**Comment by leonardo-albertovich** [comment]
There's a small error in there, you removed the `shutdown` call in the timeout handler but didn't put one before the `flb_socket_close` call which is just a macro that calls the appropriate `close` function so the code is not performing a shutdown now.

Could you add that back between the tls shutdown and socket close operations?

**Comment by sudahang** [comment]
Hi @leonardo-albertovich , I have added shutdown call between the tls shutdown and socket close.

**Comment by sudahang** [comment]
Hi @leonardo-albertovich , can you help to review this PR? Thank you.

**Review by leonardo-albertovich — APPROVED** [review]

**Pull request merged**
