### PR TITLE
out_flowcounter: don't discard return value of configure(#1624)

### LINKED ISSUE #1624: NULL dereference on memory allocation error (plugins / out_flowcounter)
## Bug Report

**Describe the bug**
NULL dereference (value returned by flb_malloc is not checked) after memory allocation error (flb_malloc is wrapper on malloc returning NULL on unsuccessful allocation).
In most cases this issue will lead to crash via segmentation fault.

Vulnerable code:
fluent-bit/plugins/out_flowcounter/out_flowcounter.c
97:    ctx->buf = (struct flb_out_fcount_buffer*)
98:        flb_malloc(sizeof(struct flb_out_fcount_buffer)*ctx->size);
99:
100:    for (i=0; i<ctx->size; i++) {
101:        ctx->buf[i].until = base + ctx->tick*i;
102:        count_initialized(&ctx->buf[i]);
103:    }

**To Reproduce**
Problem was identified by source code review.

**Expected behavior**
Memory allocation errors should be handled by checking value returned by flb_malloc().

**Your Environment**
* Version used:
Current "master" branch

**Additional context**
See following recommendations for details:
https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors

### PR DESCRIPTION
**Pull request by nokute78**
To fix #1624 .

The return value of configure is also thrown away.
My patch is to use it.

### CODE REVIEW

**Comment by nigels-com** [comment]
Looks good to me.  I'd just suggest "don't disregard return value" or "handle failure of configure step" as English phrasing.  (I was once a Nova teacher!)

**Comment by edsiper** [comment]
thanks

**Comment by nokute78** [comment]
@edsiper Oops, I found the PR is broken. It causes compilation error.
I will send a patch to fix it.

**Comment by edsiper** [comment]
ahh looks like it was my fault on fixing the conflict, sorry about that.

**Comment by nokute78** [comment]
@edsiper All right. Thank you.

**Pull request merged**
