### PR TITLE
tests: runtime: out_es: remove op_type to fix failing test

### PR DESCRIPTION
**Pull request by nokute78**
https://github.com/fluent/fluent-bit/pull/4361#issuecomment-997111614

out_es test failed on `flb_test_index_type` and `flb_test_logstash_format` since they expect `index` op_type .
Currently we use `create` op_type and it causes test failing.
https://github.com/fluent/fluent-bit/commit/7f0db9ef07a6dcb6fd9c1af58c68301356747529

I removed `index` op_type from expected output string.
We try to support other op_type on https://github.com/fluent/fluent-bit/pull/4079.
I think we should not take care op_type on such test cases.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
Before we can approve your change; please submit the following in a comment:
- [N/A] Example configuration file for the change
- [X] Debug log output from testing the change

- [N/A] Attached [Valgrind](https://valgrind.org/docs/manual/quick-start.html) output that shows no leaks or memory corruption was found

**Documentation**

- [N/A] Documentation required for this feature

## Debug output 

```
$ bin/flb-rt-out_elasticsearch 
Test div0_error...                              [2021/12/18 10:42:16] [ info] [engine] started (pid=32252)
[2021/12/18 10:42:16] [ info] [storage] version=1.1.5, initializing...
[2021/12/18 10:42:16] [ info] [storage] in-memory
[2021/12/18 10:42:16] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/18 10:42:16] [ info] [cmetrics] version=0.2.2
[2021/12/18 10:42:16] [ info] [sp] stream processor started
[2021/12/18 10:42:16] [ info] [task] cleanup test task
[2021/12/18 10:42:18] [ warn] [engine] service will shutdown in max 1 seconds
[2021/12/18 10:42:18] [ info] [engine] service has stopped (0 pending tasks)
[ OK ]
Test index_type...                              [2021/12/18 10:42:18] [ info] [engine] started (pid=32255)
[2021/12/18 10:42:18] [ info] [storage] version=1.1.5, initializing...
[2021/12/18 10:42:18] [ info] [storage] in-memory
[2021/12/18 10:42:18] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/18 10:42:18] [ info] [cmetrics] version=0.2.2
[2021/12/18 10:42:18] [ info] [sp] stream processor started
[2021/12/18 10:42:19] [ info] [task] cleanup test task
[2021/12/18 10:42:20] [ warn] [engine] service will shutdown in max 1 seconds
[2021/12/18 10:42:21] [ info] [engine] service has stopped (0 pending tasks)
[ OK ]
Test logstash_format...                         [2021/12/18 10:42:21] [ info] [engine] started (pid=32258)
[2021/12/18 10:42:21] [ info] [storage] version=1.1.5, initializing...
[2021/12/18 10:42:21] [ info] [storage] in-memory
[2021/12/18 10:42:21] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/18 10:42:21] [ info] [cmetrics] version=0.2.2
[2021/12/18 10:42:21] [ info] [sp] stream processor started
[2021/12/18 10:42:22] [ info] [task] cleanup test task
[2021/12/18 10:42:23] [ warn] [engine] service will shutdown in max 1 seconds
[2021/12/18 10:42:24] [ info] [engine] service has stopped (0 pending tasks)
[ OK ]
Test logstash_format_nanos...                   [2021/12/18 10:42:24] [ info] [engine] started (pid=32261)
[2021/12/18 10:42:24] [ info] [storage] version=1.1.5, initializing...
[2021/12/18 10:42:24] [ info] [storage] in-memory
[2021/12/18 10:42:24] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/18 10:42:24] [ info] [cmetrics] version=0.2.2
[2021/12/18 10:42:24] [ info] [sp] stream processor started
[2021/12/18 10:42:25] [ info] [task] cleanup test task
[2021/12/18 10:42:26] [ warn] [engine] service will shutdown in max 1 seconds
[2021/12/18 10:42:27] [ info] [engine] service has stopped (0 pending tasks)
[ OK ]
Test tag_key...                                 [2021/12/18 10:42:27] [ info] [engine] started (pid=32264)
[2021/12/18 10:42:27] [ info] [storage] version=1.1.5, initializing...
[2021/12/18 10:42:27] [ info] [storage] in-memory
[2021/12/18 10:42:27] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/18 10:42:27] [ info] [cmetrics] version=0.2.2
[2021/12/18 10:42:27] [ info] [sp] stream processor started
[2021/12/18 10:42:28] [ info] [task] cleanup test task
[2021/12/18 10:42:29] [ warn] [engine] service will shutdown in max 1 seconds
[2021/12/18 10:42:30] [ info] [engine] service has stopped (0 pending tasks)
[ OK ]
Test replace_dots...                            [2021/12/18 10:42:30] [ info] [engine] started (pid=32267)
[2021/12/18 10:42:30] [ info] [storage] version=1.1.5, initializing...
[2021/12/18 10:42:30] [ info] [storage] in-memory
[2021/12/18 10:42:30] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/18 10:42:30] [ info] [cmetrics] version=0.2.2
[2021/12/18 10:42:30] [ info] [sp] stream processor started
[2021/12/18 10:42:31] [ info] [task] cleanup test task
[2021/12/18 10:42:32] [ warn] [engine] service will shutdown in max 1 seconds
[2021/12/18 10:42:33] [ info] [engine] service has stopped (0 pending tasks)
[ OK ]
Test id_key...                                  [2021/12/18 10:42:33] [ info] [engine] started (pid=32270)
[2021/12/18 10:42:33] [ info] [storage] version=1.1.5, initializing...
[2021/12/18 10:42:33] [ info] [storage] in-memory
[2021/12/18 10:42:33] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/18 10:42:33] [ info] [cmetrics] version=0.2.2
[2021/12/18 10:42:33] [ info] [sp] stream processor started
[2021/12/18 10:42:34] [ info] [task] cleanup test task
[2021/12/18 10:42:35] [ warn] [engine] service will shutdown in max 1 seconds
[2021/12/18 10:42:36] [ info] [engine] service has stopped (0 pending tasks)
[ OK ]
SUCCESS: All unit tests have passed.
```

----

Fluent Bit is licensed under Apache 2.0, by submitting this pull request I understand that this code will be released under the terms of that license.

### CODE REVIEW

**Comment by nokute78** [comment]
If #4361 is merged, the issue https://github.com/fluent/fluent-bit/pull/4361#issuecomment-997111614 will be fixed without this PR.

**Comment by edsiper** [comment]
@nokute78  #4361 was just merged, thanks

**Comment by nokute78** [comment]
@edsiper Oops, I was wrong.

> If #4361 is merged, the issue #4361 (comment) will be fixed without this PR.

It should be https://github.com/fluent/fluent-bit/pull/4079.
I converted to draft PR to wait merging #4079.

**Comment by edsiper** [comment]
@nokute78 #4079 has been merged.

**Comment by nokute78** [comment]
@edsiper Thank you for information.
I close this PR since the out_es test of [master](https://github.com/fluent/fluent-bit/tree/52f638ee194eccdf40c1e7757cdf940b840375d2) works correctly.

**Pull request closed without merging**
