### PR TITLE
Updated k8s-nginx-ingress parser for NGINX Controller

### PR DESCRIPTION
**Pull request by arjun921**
Updated parser to support latest helm release 
Helm Version: `nginx-ingress-1.28.0`
App Version: `0.26.2 `

### CODE REVIEW

**Comment by arjun921** [comment]
@PettitWesley What can I do merge fix all checks?

**Comment by PettitWesley** [comment]
@arjun921 I think the travis failure is just a timeout issue, if you re-push your commit it should re-run and might be fine.

The App Veyor build can't be fixed to this is merged: https://github.com/fluent/fluent-bit/pull/1856

**Comment by PettitWesley** [comment]
Also, not certain (may be these repos get synced on a release?), but I think you should update the parser here too: https://github.com/fluent/fluent-bit-docker-image/tree/1.3

**Comment by edsiper** [comment]
@arjun921 would you please also attach a https://rubular.com short link with data sample and the regex ?, that would be useful for the record.

**Comment by arjun921** [comment]
> Also, not certain (may be these repos get synced on a release?), but I think you should update the parser here too: https://github.com/fluent/fluent-bit-docker-image/tree/1.3

I will update it for sure!

> @arjun921 would you please also attach a https://rubular.com short link with data sample and the regex ?, that would be useful for the record.

Here you go @edsiper 
https://rubular.com/r/P8zgLD5K73fp2n

I'll add it as a comment too in the parser for reference.

**Comment by arjun921** [comment]
@edsiper @PettitWesley Any chance we could merge this now 😅?

**Comment by edsiper** [comment]
thanks

**Comment by robberlang** [comment]
Hi, the new regular expression here is missing the `user` field.

**Comment by PettitWesley** [comment]
@robberlang Could you submit a pull request to add that field? Thanks!

**Comment by arjun921** [comment]
@robertlang Which version of Nginx Ingress Controller are you using? 
The parser was breaking for me with the latest version as of the time of raising this PR.

**Pull request merged**
